// Code generated by psgen. DO NOT EDIT.
// This is a generated environment config module.

module example.com/schemas/api/fixture-general

go 1.26.4

require (
	example.com/schemas/types/go/fixture-general v0.0.0-00010101000000-000000000000
	github.com/joho/godotenv v1.5.1
)

replace example.com/schemas/types/go/fixture-general => ../../types/go/fixture-general
