// Code generated by tsgen. DO NOT EDIT.

import {
  newValidationErrors,
  addFieldError,
  setFieldErrors,
} from 'superscalar/validation';
import type { ScalarValidationResult, ValidationResult } from 'superscalar/validation';
import { expectList, expectString } from '../primitives';
import { load as loadYaml } from 'js-yaml';
import { ParseError } from '../errors';
import type { Role } from '../../types';

import { validateIdentityUUIDRequired, validateIdentityUUID } from '../scalars/identity_uuid';

/**
 * Validates a Role object
 */
export function validateRole(value: Role | null | undefined): ValidationResult {
  const errors = newValidationErrors();

  if (value === null || value === undefined) {
    return true;
  }

  if (value.id !== null && value.id !== undefined) {
    const [valid, fieldErrors] = validateIdentityUUID(value.id);
    if (!valid && fieldErrors) {
      setFieldErrors(errors, "id", fieldErrors);
    }
  }

  if (value.name === null || value.name === undefined) {
    addFieldError(errors, "name", "required", "required field");
  }

  expectString(errors, "name", value.name);

  expectList(errors, "permissions", value.permissions);

  if (value.permissions === null || value.permissions === undefined) {
    addFieldError(errors, "permissions", "required", "required field");
  }

  if (Array.isArray(value.permissions)) {
    value.permissions.forEach((item, index) => expectString(errors, `permissions[${index}]`, item));
  }

  // A list element is never null: its one error is "required", in place of
  // whatever the element checks above made of it.
  if (Array.isArray(value.permissions)) {
    value.permissions.forEach((item, index) => {
      if (item === null || item === undefined) {
        setFieldErrors(errors, `permissions[${index}]`, [{ validator: "required", message: "required field" }]);
      }
    });
  }

  return Object.keys(errors).length > 0 ? errors : true;
}

export function validateRoleRequired(value: Role | null | undefined): ScalarValidationResult {
  if (value === null || value === undefined) {
    return [false, [{ validator: 'required', message: 'required field' }]];
  }

  const validationResult = validateRole(value);
  if (validationResult !== true) {
    return [false, [{ validator: 'object', message: JSON.stringify(validationResult) }]];
  }

  return [true, null];
}

const RoleKnownFields = new Set<string>([
  'id',
  'name',
  'permissions',
]);

type RoleTextParser = (value: string) => unknown;

function parseRoleInput(
  input: string | unknown,
  strict: boolean,
  sourceFormat: 'json' | 'yaml',
  parseText: RoleTextParser
): Role {
  let parsed: unknown = input;

  if (typeof input === 'string') {
    try {
      parsed = parseText(input);
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      throw new ParseError(
        `parseRole ${sourceFormat} parse failed: ${reason}`,
        `not valid ${sourceFormat === 'json' ? 'JSON' : 'YAML'}`
      );
    }
  }

  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new ParseError(`parseRole ${sourceFormat} expects an object input`, 'expected an object');
  }

  const candidate = parsed as Record<string, unknown>;

  // Apply @default values from the schema for keys absent from the payload.

  if (strict) {
    const unknownFields = Object.keys(candidate).filter(
      (fieldName) => !RoleKnownFields.has(fieldName)
    );
    if (unknownFields.length > 0) {
      const unknownErrors = newValidationErrors();
      for (const fieldName of unknownFields) {
        addFieldError(unknownErrors, fieldName, "unknown", "unknown field");
      }
      throw new ParseError(
        `parseRole ${sourceFormat} contains unknown fields: ${unknownFields.join(', ')}`,
        `unknown fields: ${unknownFields.join(', ')}`,
        unknownErrors
      );
    }
  }

  const typedCandidate = candidate as unknown as Role;
  const validationResult = validateRole(typedCandidate);
  if (validationResult !== true) {
    throw new ParseError(
      `parseRole ${sourceFormat} validation failed: ${JSON.stringify(validationResult)}`,
      'validation failed',
      validationResult
    );
  }

  return typedCandidate;
}

export function parseRoleJson(input: string | unknown): Role {
  return parseRoleInput(input, true, 'json', (value) => JSON.parse(value) as unknown);
}

export function parseRoleJsonNonStrict(input: string | unknown): Role {
  return parseRoleInput(input, false, 'json', (value) => JSON.parse(value) as unknown);
}

export function parseRoleYaml(input: string | unknown): Role {
  return parseRoleInput(input, true, 'yaml', (value) => loadYaml(value));
}

export function parseRoleYamlNonStrict(input: string | unknown): Role {
  return parseRoleInput(input, false, 'yaml', (value) => loadYaml(value));
}

/**
 * Parses a Role from JSON wire format into runtime types
 */

export function parseRoleFromJSON(input: unknown): Role {
  return input as Role;
}
