// Code generated by tsgen. DO NOT EDIT.

import type {
  RecipeSnapshotEntry,
  RecipeCommit,
} from '../../types';
import { maskSecretsRecipeCommit } from './recipecommit';

/**
 * Returns a copy of RecipeSnapshotEntry with fields marked @secret cleared.
 */
export function maskSecretsRecipeSnapshotEntry(value: RecipeSnapshotEntry): RecipeSnapshotEntry {
  return {
    id: value.id,
    commit: maskSecretsRecipeCommit(value.commit),
    entityKind: value.entityKind,
    entityKey: value.entityKey,
    entityId: value.entityId,
    entityVersion: value.entityVersion,
  };
}
