// Code generated by tsgen. DO NOT EDIT.

import type {
  RecipeCommit,
  Recipe,
  RecipeRef,
} from '../../types';
import { maskSecretsRecipe } from './recipe';
import { maskSecretsRecipeRef } from './reciperef';

/**
 * Returns a copy of RecipeCommit with fields marked @secret cleared.
 */
export function maskSecretsRecipeCommit(value: RecipeCommit): RecipeCommit {
  return {
    id: value.id,
    root: maskSecretsRecipe(value.root),
    ref: maskSecretsRecipeRef(value.ref),
    parentCommit: value.parentCommit !== null && value.parentCommit !== undefined ? maskSecretsRecipeCommit(value.parentCommit) : null,
    message: value.message !== undefined ? value.message : null,
    schemaEpoch: value.schemaEpoch,
    contentHash: value.contentHash,
    sequence: value.sequence,
    createdAt: value.createdAt,
    createdBy: value.createdBy,
  };
}
