package loader

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/parable-work/superschematic/internal/registry"
	ir "github.com/parable-work/superschematic/ir"
)

// userModelFixture is the JSON-authored service whose User and UserRole
// tables the generator goldens cover.
const userModelFixture = "tsreader/testdata/services/fixture-user-model-db"

// TestLoadUserModelAddsItsTables: a schema with a User and a UserRole table
// loads with Session, UserCredential and UserRoleGrant added, each of the
// identity origin, and every scalar their fields use hydrated from the
// catalog, the ones only they use included.
func TestLoadUserModelAddsItsTables(t *testing.T) {
	schema, err := LoadService(filepath.FromSlash(userModelFixture))
	if err != nil {
		t.Fatalf("LoadService: %v", err)
	}
	for _, name := range []string{ir.IdentitySessionTable, ir.IdentityCredentialTable, ir.IdentityRoleGrantTable} {
		td := schema.Types[name]
		if td == nil {
			t.Fatalf("the loader added no %s", name)
		}
		if td.Origin != ir.OriginIdentity {
			t.Errorf("%s has origin %q, want %q", name, td.Origin, ir.OriginIdentity)
		}
	}
	if user := schema.UserTable(); user == nil || user.Name != "User" || user.Origin != "" {
		t.Errorf("UserTable() = %+v, want the authored User table", user)
	}
	if role := schema.UserRoleTable(); role == nil || role.Name != "Role" {
		t.Errorf("UserRoleTable() = %+v, want Role", role)
	}
	for name, sql := range map[string]string{"Crypto.SHA256": "VARCHAR(64)", "Temporal.DateTime": "TIMESTAMPTZ", "Identity.UUID": "UUID", "Contact.Email": "CITEXT"} {
		def := schema.Scalars[name]
		if def == nil || def.Description == "" || def.TypeMappings["sql"] != sql {
			t.Errorf("%s was not hydrated from the catalog: %+v", name, def)
		}
	}
	// Hydration fills every member the catalog row has and leaves the rest
	// as the schema file wrote them; the row has none for case.
	if !schema.Scalars["Contact.Email"].CaseInsensitive {
		t.Error("Contact.Email lost the case-insensitive declaration its schema file makes")
	}
}

// TestLoadWithoutTheTraitsAddsNoTables: a schema without a User table loads
// with no identity tables and no scalar only they use.
func TestLoadWithoutTheTraitsAddsNoTables(t *testing.T) {
	schema, err := LoadService(filepath.FromSlash("tsreader/testdata/services/fixture-db"))
	if err != nil {
		t.Fatalf("LoadService: %v", err)
	}
	for name, td := range schema.Types {
		if td.Origin == ir.OriginIdentity {
			t.Errorf("the loader added %s to a schema without the traits", name)
		}
	}
	if schema.Scalars["Crypto.SHA256"] != nil {
		t.Error("the loader added Crypto.SHA256 to a schema without the traits")
	}
}

// userModelService writes a one-file DB service whose User table's login is
// email, typed by the given scalar entry.
func userModelService(t *testing.T, file, emailScalar string) string {
	t.Helper()
	files := map[string]string{"schema.config.json": `{"name": "temp-db", "kind": "DB", "outputs": {}}`}
	if strings.HasSuffix(file, ".yaml") {
		files[file] = `
scalars:
  Contact.Email: ` + emailScalar + `
  Identity.UUID: { name: Identity.UUID, languagePrimitive: string }
types:
  Account:
    name: Account
    role: DBTable
    user: { login: email }
    fields:
      - { name: id, typeRef: { name: Identity.UUID }, required: true, key: true, autoGenerated: true }
      - { name: email, typeRef: { name: Contact.Email }, required: true, unique: true }
`
	} else {
		files[file] = `{
  "scalars": {
    "Contact.Email": ` + emailScalar + `,
    "Identity.UUID": {"name": "Identity.UUID", "languagePrimitive": "string"}
  },
  "types": {
    "Account": {
      "name": "Account",
      "role": "DBTable",
      "user": {"login": "email"},
      "fields": [
        {"name": "id", "typeRef": {"name": "Identity.UUID"}, "required": true, "key": true, "autoGenerated": true},
        {"name": "email", "typeRef": {"name": "Contact.Email"}, "required": true, "unique": true}
      ]
    }
  }
}`
	}
	return writeService(t, files)
}

// TestLoadRefusesALoginTheCatalogDoesNotDeclare: in each data form, a login
// typed by a catalog scalar the schema file does not declare
// case-insensitive is refused, since the catalog carries no declaration of
// its own; declaring it loads.
func TestLoadRefusesALoginTheCatalogDoesNotDeclare(t *testing.T) {
	const want = "Account.email: the User trait's login must be typed by a scalar declared case-insensitive, and Contact.Email is not one"
	for _, tc := range []struct {
		file     string
		plain    string
		declared string
	}{
		{
			file:     "src/users.schema.json",
			plain:    `{"name": "Contact.Email", "languagePrimitive": "string"}`,
			declared: `{"name": "Contact.Email", "languagePrimitive": "string", "caseInsensitive": true}`,
		},
		{
			file:     "src/users.schema.yaml",
			plain:    `{ name: Contact.Email, languagePrimitive: string }`,
			declared: `{ name: Contact.Email, languagePrimitive: string, caseInsensitive: true }`,
		},
	} {
		t.Run(filepath.Ext(tc.file), func(t *testing.T) {
			_, err := LoadService(userModelService(t, tc.file, tc.plain))
			if err == nil || !strings.Contains(err.Error(), want) {
				t.Errorf("LoadService = %v, want an error containing %q", err, want)
			}
			schema, err := LoadService(userModelService(t, tc.file, tc.declared))
			if err != nil {
				t.Fatalf("LoadService with the declaration: %v", err)
			}
			if schema.Types[ir.IdentitySessionTable] == nil {
				t.Error("the loader added no Session table")
			}
		})
	}
}

// TestNoCatalogScalarIsCaseInsensitive records why a login typed by a
// catalog scalar alone is refused: the scalar package's metadata row has no
// member for case, so hydration gives every catalog scalar a ScalarDef
// whose CaseInsensitive is false, Contact.Email and Identity.Slug included.
// When superscalar exports the declaration, hydration takes it from the row
// and this test is rewritten to expect those scalars case-insensitive.
func TestNoCatalogScalarIsCaseInsensitive(t *testing.T) {
	catalog := registry.CoreScalars()
	schema := ir.NewSchema("temp-service", ir.SchemaKindGeneral)
	for _, name := range catalog.Names() {
		schema.Scalars[name] = &ir.ScalarDef{Name: name}
	}
	if err := HydrateScalars(schema, catalog); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"Contact.Email", "Identity.Slug"} {
		if schema.Scalars[name] == nil {
			t.Fatalf("the core catalog has no %s", name)
		}
	}
	for name, def := range schema.Scalars {
		if def.CaseInsensitive {
			t.Errorf("hydration declares %s case-insensitive; update the User login tests and the D50 status", name)
		}
	}
}
