package loader

import (
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/parable-work/superschematic/internal/registry"
	ir "github.com/parable-work/superschematic/ir"
)

// userModelFixture is the JSON-authored service whose User and UserRole
// tables the generator goldens cover.
const userModelFixture = "tsreader/testdata/services/fixture-user-model-db"

// TestLoadUserModelAddsItsTables: a schema with a User and a UserRole table
// loads with Session, UserCredential and UserRoleGrant added, each of the
// identity origin, and every scalar their fields use hydrated from the
// catalog, the ones only they use included.
func TestLoadUserModelAddsItsTables(t *testing.T) {
	schema, err := LoadService(filepath.FromSlash(userModelFixture))
	if err != nil {
		t.Fatalf("LoadService: %v", err)
	}
	for _, name := range []string{ir.IdentitySessionTable, ir.IdentityCredentialTable, ir.IdentityRoleGrantTable} {
		td := schema.Types[name]
		if td == nil {
			t.Fatalf("the loader added no %s", name)
		}
		if td.Origin != ir.OriginIdentity {
			t.Errorf("%s has origin %q, want %q", name, td.Origin, ir.OriginIdentity)
		}
	}
	if user := schema.UserTable(); user == nil || user.Name != "User" || user.Origin != "" {
		t.Errorf("UserTable() = %+v, want the authored User table", user)
	}
	if role := schema.UserRoleTable(); role == nil || role.Name != "Role" {
		t.Errorf("UserRoleTable() = %+v, want Role", role)
	}
	for name, sql := range map[string]string{"Crypto.SHA256": "VARCHAR(64)", "Temporal.DateTime": "TIMESTAMPTZ", "Identity.UUID": "UUID", "Contact.Email": "CITEXT"} {
		def := schema.Scalars[name]
		if def == nil || def.Description == "" || def.TypeMappings["sql"] != sql {
			t.Errorf("%s was not hydrated from the catalog: %+v", name, def)
		}
	}
	// Hydration fills every member the catalog row has and leaves the rest
	// as the schema file wrote them; the row has none for case.
	if !schema.Scalars["Contact.Email"].CaseInsensitive {
		t.Error("Contact.Email lost the case-insensitive declaration its schema file makes")
	}
}

// TestLoadWithoutTheTraitsAddsNoTables: a schema without a User table loads
// with no identity tables and no scalar only they use.
func TestLoadWithoutTheTraitsAddsNoTables(t *testing.T) {
	schema, err := LoadService(filepath.FromSlash("tsreader/testdata/services/fixture-db"))
	if err != nil {
		t.Fatalf("LoadService: %v", err)
	}
	for name, td := range schema.Types {
		if td.Origin == ir.OriginIdentity {
			t.Errorf("the loader added %s to a schema without the traits", name)
		}
	}
	if schema.Scalars["Crypto.SHA256"] != nil {
		t.Error("the loader added Crypto.SHA256 to a schema without the traits")
	}
}

// userModelService writes a one-file DB service whose User table's login is
// email, typed by scalar, which the schema file declares with entry.
func userModelService(t *testing.T, file, scalar, entry string) string {
	t.Helper()
	files := map[string]string{"schema.config.json": `{"name": "temp-db", "kind": "DB", "outputs": {}}`}
	if strings.HasSuffix(file, ".yaml") {
		files[file] = `
scalars:
  ` + scalar + `: ` + entry + `
  Identity.UUID: { name: Identity.UUID, languagePrimitive: string }
types:
  Account:
    name: Account
    role: DBTable
    user: { login: email }
    fields:
      - { name: id, typeRef: { name: Identity.UUID }, required: true, key: true, autoGenerated: true }
      - { name: email, typeRef: { name: ` + scalar + ` }, required: true, unique: true }
`
	} else {
		files[file] = `{
  "scalars": {
    "` + scalar + `": ` + entry + `,
    "Identity.UUID": {"name": "Identity.UUID", "languagePrimitive": "string"}
  },
  "types": {
    "Account": {
      "name": "Account",
      "role": "DBTable",
      "user": {"login": "email"},
      "fields": [
        {"name": "id", "typeRef": {"name": "Identity.UUID"}, "required": true, "key": true, "autoGenerated": true},
        {"name": "email", "typeRef": {"name": "` + scalar + `"}, "required": true, "unique": true}
      ]
    }
  }
}`
	}
	return writeService(t, files)
}

// TestLoadTakesALoginsCaseFromTheCatalog: in each data form, whether a
// login's scalar is case-insensitive is the catalog's to say. A login typed
// by Contact.Email loads, with no declaration in the schema file, and one
// typed by Identity.Name is refused though the file declares it
// case-insensitive, since hydration replaces the declaration with the
// catalog's.
func TestLoadTakesALoginsCaseFromTheCatalog(t *testing.T) {
	const refused = "Account.email: the User trait's login must be typed by a scalar declared case-insensitive, and Identity.Name is not one"
	for _, tc := range []struct {
		file  string
		email string
		name  string
	}{
		{
			file:  "src/users.schema.json",
			email: `{"name": "Contact.Email", "languagePrimitive": "string"}`,
			name:  `{"name": "Identity.Name", "languagePrimitive": "string", "caseInsensitive": true}`,
		},
		{
			file:  "src/users.schema.yaml",
			email: `{ name: Contact.Email, languagePrimitive: string }`,
			name:  `{ name: Identity.Name, languagePrimitive: string, caseInsensitive: true }`,
		},
	} {
		t.Run(filepath.Ext(tc.file), func(t *testing.T) {
			schema, err := LoadService(userModelService(t, tc.file, "Contact.Email", tc.email))
			if err != nil {
				t.Fatalf("LoadService with a Contact.Email login: %v", err)
			}
			if schema.Types[ir.IdentitySessionTable] == nil {
				t.Error("the loader added no Session table")
			}
			_, err = LoadService(userModelService(t, tc.file, "Identity.Name", tc.name))
			if err == nil || !strings.Contains(err.Error(), refused) {
				t.Errorf("LoadService = %v, want an error containing %q", err, refused)
			}
		})
	}
}

// TestCatalogCaseInsensitiveScalars: hydration takes each catalog scalar's
// case from the scalar package's row, so the core catalog's case-insensitive
// scalars are the ones superscalar declares, and a declaration a schema
// wrote is replaced by the catalog's.
func TestCatalogCaseInsensitiveScalars(t *testing.T) {
	catalog := registry.CoreScalars()
	schema := ir.NewSchema("temp-service", ir.SchemaKindGeneral)
	for _, name := range catalog.Names() {
		schema.Scalars[name] = &ir.ScalarDef{Name: name, CaseInsensitive: name == "Identity.Name"}
	}
	if err := HydrateScalars(schema, catalog); err != nil {
		t.Fatal(err)
	}
	want := []string{"AgentSkill.Name", "Contact.Email", "Identity.Slug", "Network.DnsLabel", "Network.DomainName", "Temporal.Quarter"}
	var got []string
	for _, name := range catalog.Names() {
		if schema.Scalars[name].CaseInsensitive {
			got = append(got, name)
		}
	}
	if !slices.Equal(got, want) {
		t.Errorf("case-insensitive catalog scalars = %v, want %v", got, want)
	}
}
