//! Code generated by superschematic topcoat. DO NOT EDIT.
//!
//! The fixture-views-api API in a Topcoat app. `RouterBuilderFixtureViewsApiExt::fixture_views_api`
//! mounts the JSON API at `/api` and keeps the implementations for the
//! in-process calls of `operations`, which pages, shards and procedures
//! make by each route's rules.
//! `records` mirrors each type an operation returns as a record a page
//! can hand the browser.
//! `procedures` lets browser code call each operation, its arguments and
//! result records; the app's `.discover()` registers them.
//! `views` renders each record as a description list and as a table.
//!
//! The app names this crate (`use`s an item of it), so the linker keeps
//! it.

pub mod operations;
pub mod procedures;
pub mod records;
mod wire;
pub mod views;

/// The service's API crate: its `Implementations`, `Args` structs and
/// `types`.
pub use schemas_fixture_views_api_api as api;

use api::{build_router, Implementations};
use topcoat::router::RouterBuilder;
use topcoat::router::tower::TowerRoute;

/// What `fixture_views_api` keeps in the app context for the in-process calls.
pub struct Setup {
    pub implementations: Implementations,
}

/// Adds the fixture-views-api API to a Topcoat app.
pub trait RouterBuilderFixtureViewsApiExt {
    /// Mounts the JSON API (`build_router`) at `/api/{*rest}` and keeps
    /// `implementations` for the in-process calls of
    /// `operations`.
    #[must_use]
    fn fixture_views_api(self, implementations: Implementations) -> Self;
}

impl RouterBuilderFixtureViewsApiExt for RouterBuilder {
    fn fixture_views_api(self, implementations: Implementations) -> Self {
        let api = build_router(implementations.clone());
        self.app_context(Setup {
            implementations,
        })
        .route(TowerRoute::any("/api/{*rest}", api))
    }
}
