//! Code generated by superschematic topcoat. DO NOT EDIT.
//!
//! Each operation of fixture-args-api, called in-process by its route's rules:
//! the caller admitted as the route admits it, the arguments checked as
//! the router checks them, then the implementation. A refusal is the
//! `ApiError` the route answers, and `?` carries it into a page's error.
//! A guard (`can_<operation>`) admits the caller alone, for a page that
//! shows or hides what the operation does. An operation without a call
//! still has its guard, whose doc says why.
//!
//! A call does not apply the route's traffic controls (@rateLimit,
//! @bodyLimit, @timeout): the page that makes it is a route of the app,
//! under the controls the app gives it.

#![allow(unused_imports)]

use crate::Setup;
use crate::api::operations;
use crate::api::runtime::{ApiError, Principal};
use crate::api::types;
use topcoat::context::{Cx, app_context};

/// order.listOrders (`GET /api/orders`): The orders that match every filter.
pub async fn order_list_orders(cx: &Cx, args: crate::api::OrderListOrdersArgs) -> Result<Vec<types::OrderView>, ApiError> {
    let caller = can_order_list_orders(cx).await?;
    args.check()?;
    let setup: &Setup = app_context(cx);
    setup
        .implementations
        .order
        .list_orders(operations::ORDER_LIST_ORDERS.context(caller), args)
        .await
}

/// order.getOrder (`GET /api/orders/{id}`): One order.
pub async fn order_get_order(cx: &Cx, args: crate::api::OrderGetOrderArgs) -> Result<types::OrderView, ApiError> {
    let caller = can_order_get_order(cx).await?;
    args.check()?;
    let setup: &Setup = app_context(cx);
    setup
        .implementations
        .order
        .get_order(operations::ORDER_GET_ORDER.context(caller), args)
        .await
}

/// order.cancelOrder (`POST /api/orders/{id}/cancel`): Cancels an order, recording why.
pub async fn order_cancel_order(cx: &Cx, args: crate::api::OrderCancelOrderArgs) -> Result<types::OrderView, ApiError> {
    let caller = can_order_cancel_order(cx).await?;
    args.check()?;
    let setup: &Setup = app_context(cx);
    setup
        .implementations
        .order
        .cancel_order(operations::ORDER_CANCEL_ORDER.context(caller), args)
        .await
}

/// order.tagOrder (`POST /api/orders/{id}/tags`): Tags an order; a form holds no map.
pub async fn order_tag_order(cx: &Cx, args: crate::api::OrderTagOrderArgs) -> Result<types::OrderView, ApiError> {
    let caller = can_order_tag_order(cx).await?;
    args.check()?;
    let setup: &Setup = app_context(cx);
    setup
        .implementations
        .order
        .tag_order(operations::ORDER_TAG_ORDER.context(caller), args)
        .await
}

/// product-reviews.writeReview (`POST /api/products/{productId}/reviews`): Writes a review of a product.
pub async fn product_reviews_write_review(cx: &Cx, args: crate::api::ProductReviewsWriteReviewArgs) -> Result<types::ReviewView, ApiError> {
    let caller = can_product_reviews_write_review(cx).await?;
    args.check()?;
    let setup: &Setup = app_context(cx);
    setup
        .implementations
        .product_reviews
        .write_review(operations::PRODUCT_REVIEWS_WRITE_REVIEW.context(caller), args)
        .await
}

/// Admits the caller of order.listOrders as its route does: it needs none, so
/// `Ok(None)`.
pub async fn can_order_list_orders(cx: &Cx) -> Result<Option<Principal>, ApiError> {
    let _ = cx;
    Ok(None)
}

/// Admits the caller of order.getOrder as its route does: it needs none, so
/// `Ok(None)`.
pub async fn can_order_get_order(cx: &Cx) -> Result<Option<Principal>, ApiError> {
    let _ = cx;
    Ok(None)
}

/// Admits the caller of order.cancelOrder as its route does: it needs none, so
/// `Ok(None)`.
pub async fn can_order_cancel_order(cx: &Cx) -> Result<Option<Principal>, ApiError> {
    let _ = cx;
    Ok(None)
}

/// Admits the caller of order.tagOrder as its route does: it needs none, so
/// `Ok(None)`.
pub async fn can_order_tag_order(cx: &Cx) -> Result<Option<Principal>, ApiError> {
    let _ = cx;
    Ok(None)
}

/// Admits the caller of product-reviews.writeReview as its route does: it needs none, so
/// `Ok(None)`.
pub async fn can_product_reviews_write_review(cx: &Cx) -> Result<Option<Principal>, ApiError> {
    let _ = cx;
    Ok(None)
}
