package validate

import (
	"fmt"
	"regexp"
	"strconv"
	"unicode/utf8"

	"github.com/parable-work/superschematic/ir"
)

// Validator interprets an IR Schema to validate data at runtime. It applies
// the same validation rules as code-generated validators: required checks,
// scalar constraints (length, pattern, min/max), custom scalar validation,
// enum membership, and recursive nested-type validation.
type Validator struct {
	schema   *ir.Schema
	registry *Registry
	patterns map[string]*regexp.Regexp
	// fieldPatterns caches compiled @validatePattern regexes keyed by the
	// pattern string. A key present with a nil value marks a pattern that
	// failed to compile: enforcement fails closed (emits a pattern error
	// for any present value), matching the TS and Python behavior.
	fieldPatterns  map[string]*regexp.Regexp
	strictRegistry bool
}

// Option configures a Validator during construction.
type Option func(*Validator)

// WithRegistry sets a custom scalar validator registry. If not provided,
// an empty registry is used (IR constraints still apply; custom validation
// functions are simply not called).
func WithRegistry(r *Registry) Option {
	return func(v *Validator) {
		v.registry = r
	}
}

// WithStrictRegistry makes New panic when the schema declares HasCustomValidate
// scalars that have no entry in the registry. Use this in tests or service
// startup to catch silent gaps where a schema scalar's custom validator was
// never wired up. The default (strict=false) lets New succeed regardless;
// callers that want to inspect the gap without panicking can call
// Registry.MissingValidators directly.
func WithStrictRegistry(strict bool) Option {
	return func(v *Validator) {
		v.strictRegistry = strict
	}
}

// New creates a Validator for the given schema. All scalar regex patterns
// are pre-compiled during construction for efficient reuse.
//
// If WithStrictRegistry(true) is set, New panics when the schema has
// HasCustomValidate scalars without a matching registry entry; the panic
// message lists the missing canonical scalar names.
func New(schema *ir.Schema, opts ...Option) *Validator {
	v := &Validator{
		schema:        schema,
		registry:      NewRegistry(),
		patterns:      make(map[string]*regexp.Regexp),
		fieldPatterns: make(map[string]*regexp.Regexp),
	}

	for _, opt := range opts {
		opt(v)
	}

	if v.strictRegistry {
		if missing := v.registry.MissingValidators(schema); len(missing) > 0 {
			panic(fmt.Sprintf(
				"validate: schema %q has HasCustomValidate scalars without registered validators: %v",
				schema.Name, missing,
			))
		}
	}

	for _, scalar := range schema.Scalars {
		if scalar.Pattern != "" {
			v.patterns[scalar.Pattern] = regexp.MustCompile(scalar.Pattern)
		}
	}

	for _, defs := range []map[string]*ir.TypeDef{schema.Types, schema.Inputs} {
		for _, td := range defs {
			for _, field := range td.Fields {
				if field.ValidatePattern == "" {
					continue
				}
				if _, seen := v.fieldPatterns[field.ValidatePattern]; seen {
					continue
				}
				// Compile, never MustCompile: a bad pattern must not panic,
				// and it must not be skipped either -- the nil entry makes
				// validateFieldStringConstraints emit a pattern error.
				re, err := regexp.Compile(field.ValidatePattern)
				if err != nil {
					v.fieldPatterns[field.ValidatePattern] = nil
					continue
				}
				v.fieldPatterns[field.ValidatePattern] = re
			}
		}
	}

	return v
}

// ValidateType validates a data map against a named object type definition.
// Returns an empty ValidationErrors if the type is not found.
func (v *Validator) ValidateType(typeName string, data map[string]any) ValidationErrors {
	td, ok := v.schema.Types[typeName]
	if !ok {
		return NewValidationErrors()
	}
	return v.validateTypeDef(td, data)
}

// ValidateInput validates a data map against a named input type definition.
// Returns an empty ValidationErrors if the input is not found.
func (v *Validator) ValidateInput(typeName string, data map[string]any) ValidationErrors {
	td, ok := v.schema.Inputs[typeName]
	if !ok {
		return NewValidationErrors()
	}
	return v.validateTypeDef(td, data)
}

// validateTypeDef validates all fields of a type definition against a data map.
func (v *Validator) validateTypeDef(td *ir.TypeDef, data map[string]any) ValidationErrors {
	errs := NewValidationErrors()
	for _, field := range td.Fields {
		v.validateField(field, data, errs)
	}
	return errs
}

// validateField validates a single field, dispatching to array or single-value logic.
func (v *Validator) validateField(field *ir.FieldDef, data map[string]any, errs ValidationErrors) {
	key := fieldKey(field)
	value, exists := data[key]
	isRequired := field.Required && !field.AutoGenerated

	if isRequired {
		if !exists || value == nil {
			errs.AddFieldError(key, "required", "required field")
			return
		}
		if field.TypeRef.IsArray {
			arr, ok := value.([]any)
			if !ok || len(arr) == 0 {
				errs.AddFieldError(key, "required", "required field")
				return
			}
		}
	}

	if !exists || value == nil {
		return
	}

	kind := v.resolveRefKind(field.TypeRef)

	if field.TypeRef.IsArray {
		v.validateArrayField(field, key, kind, isRequired, value, errs)
	} else {
		v.validateSingleField(field, key, kind, isRequired, value, errs)
	}
}

// validateSingleField validates a non-array field value based on its resolved kind.
func (v *Validator) validateSingleField(field *ir.FieldDef, key, kind string, required bool, value any, errs ValidationErrors) {
	switch kind {
	case "scalar":
		scalar := v.schema.Scalars[field.TypeRef.Name]
		var fieldErrs []ValidationError
		if required {
			fieldErrs = v.validateScalarRequired(scalar, value)
		} else {
			fieldErrs = v.validateScalarValue(scalar, value)
		}
		fieldErrs = append(fieldErrs, validateFieldNumericConstraints(field, value)...)
		fieldErrs = append(fieldErrs, v.validateFieldStringConstraints(field, value)...)
		errs.SetFieldErrors(key, fieldErrs)

	case "enum":
		enum := v.schema.Enums[field.TypeRef.Name]
		fieldErrs := v.validateEnumValue(enum, value)
		errs.SetFieldErrors(key, fieldErrs)

	case "type":
		td := v.schema.Types[field.TypeRef.Name]
		if m, ok := value.(map[string]any); ok {
			nested := v.validateTypeDef(td, m)
			if nested.HasErrors() {
				errs.AddNestedError(key, nested)
			}
		}

	case "input":
		td := v.schema.Inputs[field.TypeRef.Name]
		if m, ok := value.(map[string]any); ok {
			nested := v.validateTypeDef(td, m)
			if nested.HasErrors() {
				errs.AddNestedError(key, nested)
			}
		}

	case "builtin":
		if required && isBuiltinString(field.TypeRef.Name) {
			if s, ok := value.(string); ok && s == "" {
				errs.AddFieldError(key, "required", "required field")
			}
		}
		for _, fieldErr := range validateFieldNumericConstraints(field, value) {
			errs.AddFieldError(key, fieldErr.Validator, fieldErr.Message)
		}
		for _, fieldErr := range v.validateFieldStringConstraints(field, value) {
			errs.AddFieldError(key, fieldErr.Validator, fieldErr.Message)
		}
	}
}

// validateArrayField validates an array field, applying per-element
// validation at key[i]. For an array of arrays (T[][]) each element must be
// a list, never null, reported at key[i], and each inner element is
// validated at key[i][j].
func (v *Validator) validateArrayField(field *ir.FieldDef, key, kind string, required bool, value any, errs ValidationErrors) {
	arr, ok := value.([]any)
	if !ok {
		return
	}

	for i, elem := range arr {
		elemKey := fmt.Sprintf("%s[%d]", key, i)
		if !field.TypeRef.IsArrayOfArrays {
			v.validateArrayElem(field, elemKey, kind, required, elem, errs)
			continue
		}
		inner, isList := elem.([]any)
		if elem == nil || (isList && inner == nil) {
			errs.AddFieldError(elemKey, "required", "required field")
			continue
		}
		if !isList {
			errs.AddFieldError(elemKey, "type", "expected array value")
			continue
		}
		for j, innerElem := range inner {
			v.validateArrayElem(field, fmt.Sprintf("%s[%d]", elemKey, j), kind, required, innerElem, errs)
		}
	}
}

// validateArrayElem validates one element of an array field at elemKey.
func (v *Validator) validateArrayElem(field *ir.FieldDef, elemKey, kind string, required bool, elem any, errs ValidationErrors) {
	if elem == nil {
		if field.TypeRef.ElemNonNull {
			errs.AddFieldError(elemKey, "required", "required field")
		}
		return
	}

	switch kind {
	case "scalar":
		scalar := v.schema.Scalars[field.TypeRef.Name]
		var elemErrs []ValidationError
		if required {
			elemErrs = v.validateScalarRequired(scalar, elem)
		} else {
			elemErrs = v.validateScalarValue(scalar, elem)
		}
		elemErrs = append(elemErrs, validateFieldNumericConstraints(field, elem)...)
		elemErrs = append(elemErrs, v.validateFieldStringConstraints(field, elem)...)
		errs.SetFieldErrors(elemKey, elemErrs)

	case "enum":
		enum := v.schema.Enums[field.TypeRef.Name]
		elemErrs := v.validateEnumValue(enum, elem)
		errs.SetFieldErrors(elemKey, elemErrs)

	case "type":
		td := v.schema.Types[field.TypeRef.Name]
		if m, ok := elem.(map[string]any); ok {
			nested := v.validateTypeDef(td, m)
			if nested.HasErrors() {
				errs.AddNestedError(elemKey, nested)
			}
		}

	case "input":
		td := v.schema.Inputs[field.TypeRef.Name]
		if m, ok := elem.(map[string]any); ok {
			nested := v.validateTypeDef(td, m)
			if nested.HasErrors() {
				errs.AddNestedError(elemKey, nested)
			}
		}

	case "builtin":
		for _, elemErr := range validateFieldNumericConstraints(field, elem) {
			errs.AddFieldError(elemKey, elemErr.Validator, elemErr.Message)
		}
		for _, elemErr := range v.validateFieldStringConstraints(field, elem) {
			errs.AddFieldError(elemKey, elemErr.Validator, elemErr.Message)
		}
	}
}

func validateFieldNumericConstraints(field *ir.FieldDef, value any) []ValidationError {
	if field.ValidateMin == nil && field.ValidateMax == nil {
		return nil
	}
	numericValue, ok := toFloat64(value)
	if !ok {
		return nil
	}

	var errs []ValidationError
	if field.ValidateMin != nil && numericValue < *field.ValidateMin {
		errs = append(errs, ValidationError{
			Validator: "min",
			Message: "must be at least " +
				strconv.FormatFloat(*field.ValidateMin, 'f', -1, 64),
		})
	}
	if field.ValidateMax != nil && numericValue > *field.ValidateMax {
		errs = append(errs, ValidationError{
			Validator: "max",
			Message: "must be at most " +
				strconv.FormatFloat(*field.ValidateMax, 'f', -1, 64),
		})
	}
	return errs
}

// validateFieldStringConstraints enforces the field-level string constraint
// triple (@validateMinLength, @validateMaxLength, @validatePattern), mirroring
// the TS validateFieldLevelStringConstraints and Python semantics: absent/nil
// values are skipped by the caller, a present empty string IS checked, and an
// uncompilable pattern fails closed with a pattern error.
func (v *Validator) validateFieldStringConstraints(field *ir.FieldDef, value any) []ValidationError {
	if field.ValidateMinLength == nil && field.ValidateMaxLength == nil && field.ValidatePattern == "" {
		return nil
	}
	s, ok := value.(string)
	if !ok {
		return nil
	}

	var errs []ValidationError
	length := utf8.RuneCountInString(s)
	if field.ValidateMinLength != nil && length < *field.ValidateMinLength {
		errs = append(errs, ValidationError{
			Validator: "minLength",
			Message:   "must be at least " + strconv.Itoa(*field.ValidateMinLength) + " characters",
		})
	}
	if field.ValidateMaxLength != nil && length > *field.ValidateMaxLength {
		errs = append(errs, ValidationError{
			Validator: "maxLength",
			Message:   "must be at most " + strconv.Itoa(*field.ValidateMaxLength) + " characters",
		})
	}
	if field.ValidatePattern != "" {
		re := v.fieldPatterns[field.ValidatePattern]
		if re == nil || !re.MatchString(s) {
			errs = append(errs, ValidationError{Validator: "pattern", Message: "invalid format"})
		}
	}
	return errs
}

// validateEnumValue checks that a value matches one of the enum's allowed values.
func (v *Validator) validateEnumValue(enum *ir.EnumDef, value any) []ValidationError {
	s, ok := value.(string)
	if !ok {
		return []ValidationError{{Validator: "type", Message: "expected string value"}}
	}

	for _, ev := range enum.Values {
		match := ev.SerializedAs
		if match == "" {
			match = ev.Name
		}
		if s == match {
			return nil
		}
	}

	return []ValidationError{{Validator: "enum", Message: "must be one of the allowed values"}}
}

// resolveRefKind determines what category a TypeRef refers to within the schema.
// Returns "scalar", "enum", "type", "input", or "builtin".
func (v *Validator) resolveRefKind(ref ir.TypeRef) string {
	if _, ok := v.schema.Scalars[ref.Name]; ok {
		return "scalar"
	}
	if _, ok := v.schema.Enums[ref.Name]; ok {
		return "enum"
	}
	if _, ok := v.schema.Types[ref.Name]; ok {
		return "type"
	}
	if _, ok := v.schema.Inputs[ref.Name]; ok {
		return "input"
	}
	if ir.IsBuiltinScalar(ref.Name) {
		return "builtin"
	}
	return "builtin"
}

// fieldKey returns the JSON key used to look up a field value in a data map.
// Uses JSONTag if set, otherwise falls back to the field name.
func fieldKey(f *ir.FieldDef) string {
	if f.JSONTag != "" {
		return f.JSONTag
	}
	return f.Name
}

// isBuiltinString returns true for built-in scalar types that are string-based.
func isBuiltinString(name string) bool {
	return name == "String" || name == "ID"
}
