// Code generated by tsgen. DO NOT EDIT.

import type {
  SaveGridInput,
  Point,
} from '../../types';
import { maskSecretsPoint } from './point';

/**
 * Returns a copy of SaveGridInput with fields marked @secret cleared.
 */
export function maskSecretsSaveGridInput(value: SaveGridInput): SaveGridInput {
  return {
    labels: Array.isArray(value.labels) ? value.labels : [],
    shades: Array.isArray(value.shades) ? value.shades : [],
    polygons: Array.isArray(value.polygons) ? value.polygons.map((row: Point[]) => Array.isArray(row) ? row.map((item: Point) => maskSecretsPoint(item)) : row) : [],
    weights: Array.isArray(value.weights) ? value.weights : null,
  };
}
