// Code generated by rustgen. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::scalars::*;

/// Customer-facing projection of the Tenant table.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TenantView {
    pub id: IdentityUUID,
    pub name: IdentityName,
    #[serde(rename = "userCount")]
    pub user_count: f64,
    #[serde(rename = "internalDebugLabel")]
    pub internal_debug_label: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CreateTenantInput {
    pub name: IdentityName,
    pub slug: IdentitySlug,
}
