// Code generated by rustgen. DO NOT EDIT.

//! Validators for the JSON form of this crate's types.
//!
//! A validator checks a JSON value as the generated Go, TypeScript and
//! Python validators do (D14): presence, then the JSON type, then the
//! rules, with one error per failing value at its wire path (`field`,
//! `field[i]`, `field.key`). `parse_<type>` fills the type's defaults,
//! validates the value and decodes it.

#![allow(clippy::too_many_lines, clippy::needless_borrow)]

use serde_json::Value;
use superschematic_schema_runtime as rt;
#[allow(unused_imports)]
use rt::{ValidationError, ValidationErrors};

/// The scalar validators: `validate_<scalar>` passes a missing or null
/// value, `validate_<scalar>_required` refuses one.
pub mod scalars {
    #[allow(unused_imports)]
    use super::{rt, ValidationError, Value};

    static IDENTITY_SLUG_PATTERN: rt::Pattern = rt::Pattern::new("^[a-z0-9]+(?:[-_][a-z0-9]+)*$");

    static IDENTITY_UUID_PATTERN: rt::Pattern = rt::Pattern::new("^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$");

    /// Validates a `Generic.JSON` value.
    pub fn validate_generic_json(value: Option<&Value>) -> rt::ScalarResult {
        let value = match value {
            None | Some(Value::Null) => return Ok(()),
            Some(value) => value,
        };
        core_validates_json("Generic.JSON", value)
    }

    /// Validates a `Generic.JSON` value that must be present.
    pub fn validate_generic_json_required(value: Option<&Value>) -> rt::ScalarResult {
        match value {
            None | Some(Value::Null) => Err(vec![ValidationError::required()]),
            _ => validate_generic_json(value),
        }
    }

    /// Validates a `Identity.Name` value.
    pub fn validate_identity_name(value: Option<&Value>) -> rt::ScalarResult {
        let value = match value {
            None | Some(Value::Null) => return Ok(()),
            Some(value) => value,
        };
        let Some(text) = value.as_str() else {
            return Err(vec![ValidationError::new("type", "expected string value")]);
        };
        let mut errors = Vec::new();
        let length = rt::code_points(text);
        if length < 2 {
            errors.push(ValidationError::new("minLength", "must be at least 2 characters"));
        }
        if length > 80 {
            errors.push(ValidationError::new("maxLength", "must be at most 80 characters"));
        }
        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    /// Validates a `Identity.Name` value that must be present.
    pub fn validate_identity_name_required(value: Option<&Value>) -> rt::ScalarResult {
        match value {
            None | Some(Value::Null) => Err(vec![ValidationError::required()]),
            Some(Value::String(text)) if text.is_empty() => Err(vec![ValidationError::required()]),
            _ => validate_identity_name(value),
        }
    }

    /// Validates a `Identity.Slug` value.
    pub fn validate_identity_slug(value: Option<&Value>) -> rt::ScalarResult {
        let value = match value {
            None | Some(Value::Null) => return Ok(()),
            Some(value) => value,
        };
        let Some(text) = value.as_str() else {
            return Err(vec![ValidationError::new("type", "expected string value")]);
        };
        let mut errors = Vec::new();
        let length = rt::code_points(text);
        if length < 1 {
            errors.push(ValidationError::new("minLength", "must be at least 1 characters"));
        }
        if length > 255 {
            errors.push(ValidationError::new("maxLength", "must be at most 255 characters"));
        }
        if !IDENTITY_SLUG_PATTERN.is_match(text) {
            errors.push(ValidationError::new("pattern", "invalid format"));
        }
        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    /// Validates a `Identity.Slug` value that must be present.
    pub fn validate_identity_slug_required(value: Option<&Value>) -> rt::ScalarResult {
        match value {
            None | Some(Value::Null) => Err(vec![ValidationError::required()]),
            Some(Value::String(text)) if text.is_empty() => Err(vec![ValidationError::required()]),
            _ => validate_identity_slug(value),
        }
    }

    /// Validates a `Identity.UUID` value.
    pub fn validate_identity_uuid(value: Option<&Value>) -> rt::ScalarResult {
        let value = match value {
            None | Some(Value::Null) => return Ok(()),
            Some(value) => value,
        };
        let Some(text) = value.as_str() else {
            return Err(vec![ValidationError::new("type", "expected string value")]);
        };
        let mut errors = Vec::new();
        if !IDENTITY_UUID_PATTERN.is_match(text) {
            errors.push(ValidationError::new("pattern", "invalid format"));
        }
        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    /// Validates a `Identity.UUID` value that must be present.
    pub fn validate_identity_uuid_required(value: Option<&Value>) -> rt::ScalarResult {
        match value {
            None | Some(Value::Null) => Err(vec![ValidationError::required()]),
            Some(Value::String(text)) if text.is_empty() => Err(vec![ValidationError::required()]),
            _ => validate_identity_uuid(value),
        }
    }

    /// Validates a `Temporal.DateTime` value.
    pub fn validate_temporal_date_time(value: Option<&Value>) -> rt::ScalarResult {
        let value = match value {
            None | Some(Value::Null) => return Ok(()),
            Some(value) => value,
        };
        if !value.is_string() {
            return Err(vec![ValidationError::new("type", "expected a date-time string")]);
        }
        let _ = value;
        Ok(())
    }

    /// Validates a `Temporal.DateTime` value that must be present.
    pub fn validate_temporal_date_time_required(value: Option<&Value>) -> rt::ScalarResult {
        match value {
            None | Some(Value::Null) => Err(vec![ValidationError::required()]),
            _ => validate_temporal_date_time(value),
        }
    }

    /// The scalar core's verdict on an any-JSON value, read as its JSON
    /// text.
    fn core_validates_json(canonical: &str, value: &Value) -> rt::ScalarResult {
        let registry = superscalar::Registry::builtin();
        match registry.scalar(canonical) {
            Some(scalar) => scalar
                .validate(registry, &value.to_string())
                .map_err(|error| vec![ValidationError::new(error.kind.as_str(), error.message)]),
            None => Err(vec![ValidationError::new("enum", format!("unknown scalar: {canonical}"))]),
        }
    }
}

/// Validates a `TenantListStatus` value: a string the enum declares.
pub fn validate_tenant_list_status(value: Option<&Value>) -> rt::ScalarResult {
    let value = match value {
        None | Some(Value::Null) => return Ok(()),
        Some(value) => value,
    };
    let Some(text) = value.as_str() else {
        return Err(vec![ValidationError::new("type", "expected a string")]);
    };
    if crate::enums::TenantListStatus::ALL.iter().any(|member| member.as_str() == text) {
        Ok(())
    } else {
        Err(vec![ValidationError::new("enum", "must be a valid TenantListStatus value")])
    }
}

/// Validates a `TenantListStatus` value that must be present.
pub fn validate_tenant_list_status_required(value: Option<&Value>) -> rt::ScalarResult {
    match value {
        None | Some(Value::Null) => Err(vec![ValidationError::required()]),
        _ => validate_tenant_list_status(value),
    }
}

/// The fields `TenantView` declares, by their wire names.
pub const TENANT_VIEW_FIELDS: &[&str] = &["id", "name", "userCount", "internalDebugLabel"];

/// Validates a JSON value as `TenantView`. A null value passes; the errors
/// are empty when the value is valid.
pub fn validate_tenant_view(value: &Value) -> ValidationErrors {
    let mut errors = ValidationErrors::new();
    if value.is_null() {
        return errors;
    }
    {
        let field = value.get("id");
        errors.set_result("id", scalars::validate_identity_uuid_required(field));
    }
    {
        let field = value.get("name");
        errors.set_result("name", scalars::validate_identity_name_required(field));
    }
    {
        let field = value.get("userCount");
        if rt::is_absent(field) {
            errors.push("userCount", ValidationError::required());
        }
        rt::expect_number(&mut errors, "userCount", field);
    }
    {
        let field = value.get("internalDebugLabel");
        if rt::is_absent(field) {
            errors.push("internalDebugLabel", ValidationError::required());
        }
        rt::expect_string(&mut errors, "internalDebugLabel", field);
    }
    errors
}

/// Validates a `TenantView` object that must be present: its errors are one
/// `object` error.
pub fn validate_tenant_view_required(value: Option<&Value>) -> rt::ScalarResult {
    rt::require_object(value, validate_tenant_view)
}

/// Parses a JSON value as `TenantView`: fills its `@default` values, refuses
/// undeclared keys when asked, validates it and decodes it.
pub fn parse_tenant_view(value: Value, unknown_fields: rt::UnknownFields) -> Result<crate::types::TenantView, rt::ParseError> {
    let Value::Object(object) = value else {
        return Err(rt::ParseError::NotAnObject);
    };
    rt::check_unknown_fields(&object, TENANT_VIEW_FIELDS, unknown_fields)?;
    let value = Value::Object(object);
    let errors = validate_tenant_view(&value);
    if !errors.is_empty() {
        return Err(rt::ParseError::Invalid(errors));
    }
    serde_json::from_value(value).map_err(rt::ParseError::Decode)
}

/// The fields `CreateTenantInput` declares, by their wire names.
pub const CREATE_TENANT_INPUT_FIELDS: &[&str] = &["name", "slug"];

/// Validates a JSON value as `CreateTenantInput`. A null value passes; the errors
/// are empty when the value is valid.
pub fn validate_create_tenant_input(value: &Value) -> ValidationErrors {
    let mut errors = ValidationErrors::new();
    if value.is_null() {
        return errors;
    }
    {
        let field = value.get("name");
        errors.set_result("name", scalars::validate_identity_name_required(field));
    }
    {
        let field = value.get("slug");
        errors.set_result("slug", scalars::validate_identity_slug_required(field));
    }
    errors
}

/// Validates a `CreateTenantInput` object that must be present: its errors are one
/// `object` error.
pub fn validate_create_tenant_input_required(value: Option<&Value>) -> rt::ScalarResult {
    rt::require_object(value, validate_create_tenant_input)
}

/// Parses a JSON value as `CreateTenantInput`: fills its `@default` values, refuses
/// undeclared keys when asked, validates it and decodes it.
pub fn parse_create_tenant_input(value: Value, unknown_fields: rt::UnknownFields) -> Result<crate::types::CreateTenantInput, rt::ParseError> {
    let Value::Object(object) = value else {
        return Err(rt::ParseError::NotAnObject);
    };
    rt::check_unknown_fields(&object, CREATE_TENANT_INPUT_FIELDS, unknown_fields)?;
    let value = Value::Object(object);
    let errors = validate_create_tenant_input(&value);
    if !errors.is_empty() {
        return Err(rt::ParseError::Invalid(errors));
    }
    serde_json::from_value(value).map_err(rt::ParseError::Decode)
}
