[package]
name = "parable-fixture-api-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.89"
axum = { version = "0.8.9", features = ["json", "matched-path"] }
http = "1"
serde_json = "1.0.149"
tokio = { version = "1.52.2", features = ["macros", "rt-multi-thread"] }
psgen-http-runtime = { path = "../../../../utils/psgen/http-runtime/rust" }
parable-fixture-api-types = { path = "../../types/rust/fixture-api" }
