// Code generated by tsgen. DO NOT EDIT.

import type { ScalarValidationResult, ValidationError } from 'superscalar/validation';

import { parseIdentityUUID as parseIdentityUUIDFromLib } from 'superscalar/scalars';

const IdentityUUIDPattern = new RegExp("^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$");

/**
 * Validates a Identity.UUID value
 */
export function validateIdentityUUID(
  value: string | null | undefined
): ScalarValidationResult {
  const errors: ValidationError[] = [];

  if (value === null || value === undefined) {
    return [true, null];
  }

  const s = String(value);

  if (!IdentityUUIDPattern.test(s)) {
    errors.push({ validator: "pattern", message: "invalid format" });
  }

  return errors.length > 0 ? [false, errors] : [true, null];
}

/**
 * Validates a Identity.UUID value with required check
 */
export function validateIdentityUUIDRequired(
  value: string | null | undefined
): ScalarValidationResult {

  if (value === null || value === undefined || value === "") {
    return [false, [{ validator: "required", message: "required field" }]];
  }
  if (typeof value !== "string") {
    return [false, [{ validator: "type", message: "expected string value" }]];
  }

  return validateIdentityUUID(value);
}

/**
 * Parses a string and returns a Identity.UUID scalar
 */
export function parseIdentityUUID(value: string): string | null {
  return parseIdentityUUIDFromLib(value);
}
