# Code generated by pygen. DO NOT EDIT.

"""
parable_types_fixture_api - Generated Python types for fixture-api schema.

This package provides type-safe Python models generated from Parable Schema
definitions. All models use Pydantic v2 for validation and serialization.

Modules:
    - scalars: Custom scalar types with validation
    - types: Complex object types
    - validation_errors: Validation error classes

Usage:
    from parable_types_fixture_api import *

    # Use the generated types
    obj = SomeType.model_validate(data)
"""

__version__ = "1.0.0"

from .validation_errors import (
    ValidationError,
    FieldValidationError,
    RequiredFieldError,
    ValidationErrors,
)

from .scalars import (
    GenericJSON,
    IdentityName,
    IdentitySlug,
    IdentityUUID,
    TemporalDateTime
)

from .types import (
    CreateTenantInput,
    TenantView
)

__all__ = [
    "__version__",
    "ValidationError",
    "FieldValidationError",
    "RequiredFieldError",
    "ValidationErrors",
    # Scalars
    "GenericJSON",
    "IdentityName",
    "IdentitySlug",
    "IdentityUUID",
    "TemporalDateTime",

    # Types
    "CreateTenantInput",
    "TenantView",

]
