"""Scalar validator registry.

Maps canonical scalar names (e.g. ``Contact.Email``) to a function
``(value: str) -> list[ValidationError]``.
"""

from __future__ import annotations

from typing import Callable

from .. import errors as _errors
from .._generated_default_registry import DEFAULT_VALIDATE_FUNCTIONS
from .types import Schema


ScalarValidateFn = Callable[[str], list[_errors.ValidationError]]


class ScalarValidatorRegistry:
    """Registry mapping canonical scalar names to validator functions."""

    def __init__(self) -> None:
        self._validators: dict[str, ScalarValidateFn] = {}

    def register(self, name: str, fn: ScalarValidateFn) -> None:
        self._validators[name] = fn

    def unregister(self, name: str) -> bool:
        return self._validators.pop(name, None) is not None

    def get(self, name: str) -> ScalarValidateFn | None:
        return self._validators.get(name)

    def has(self, name: str) -> bool:
        return name in self._validators

    def names(self) -> list[str]:
        return sorted(self._validators)

    def __len__(self) -> int:
        return len(self._validators)


def create_default_scalar_validator_registry() -> ScalarValidatorRegistry:
    """Build a registry pre-populated with every scalar that ships a custom validator.

    Sources :data:`DEFAULT_VALIDATE_FUNCTIONS` from
    ``superschematic_schema_runtime._generated_default_registry`` (regenerated by
    scalar-lib codegen).
    """
    registry = ScalarValidatorRegistry()
    for canonical_name, fn in DEFAULT_VALIDATE_FUNCTIONS.items():
        registry.register(canonical_name, fn)
    return registry


def missing_validators(
    schema: Schema, registry: ScalarValidatorRegistry | None = None
) -> list[str]:
    """Return canonical scalar names declared with ``has_custom_validate=True``
    in ``schema`` that are not registered in ``registry`` (sorted).
    """
    reg = registry if registry is not None else create_default_scalar_validator_registry()
    missing = [
        name
        for name, scalar in schema.scalars.items()
        if scalar.has_custom_validate and not reg.has(name)
    ]
    return sorted(missing)


__all__ = [
    "ScalarValidateFn",
    "ScalarValidatorRegistry",
    "create_default_scalar_validator_registry",
    "missing_validators",
]
