// Code generated by tsrestgen. DO NOT EDIT.
//
// The Hono router of the object-lists-api schema. Every @rest operation is
// mounted under the same /api prefix the Go and Rust routers use; the
// operation table below is the schema's declaration of paths, parameters,
// strict body parsers, auth requirements, and the @bodyLimit, @rateLimit
// and @timeout directives, applied by @superschematic/http-runtime.

import { Hono, type Env } from 'hono';
import type { OperationSpec } from '@superschematic/http-runtime';
import {
  mountOperation,
  type RouterRuntimeOptions,
} from '@superschematic/http-runtime/hono';
import type {
  Point,
  Shade,
} from '@schemas/object-lists-api-types/types';
import {
  parsePointFromJSON,
  parsePointJson,
} from '@schemas/object-lists-api-types/validators';
import type { Implementations } from './interfaces';

export type OperationName =
  | 'saveOutline';

/** The operation table: what the schema declares about each route. */
export const operationSpecs = {
  saveOutline: {
    name: 'saveOutline',
    namespace: 'drawing',
    method: 'PUT',
    path: '/api/drawings/{id}/outline',
    pathParams: [{ name: 'id', kind: 'string', required: true }],
    queryParams: [],
    bodyParams: [{ name: 'points', kind: 'object', required: true, isArray: true, listMax: 4, parse: (value: unknown) => parsePointFromJSON(parsePointJson(value)) }, { name: 'markers', kind: 'object', required: false, isArray: true, parse: (value: unknown) => parsePointFromJSON(parsePointJson(value)) }, { name: 'shades', kind: 'enum', required: false, isArray: true, enumValues: ['light', 'dark'] }],
    auth: { public: false, required: false, permissions: [] },
    manual: false,
  },
} as const satisfies Record<OperationName, OperationSpec>;

export interface RouterOptions<E extends Env = Env> extends RouterRuntimeOptions {
  /** Per-operation JSON body caps in bytes; overrides the schema's @bodyLimit and bodyLimitBytes. */
  bodyLimits?: Partial<Record<OperationName, number>>;
  /** Per-operation requests per minute; overrides the schema's @rateLimit (0 disables). The store and key are `rateLimit`. */
  rateLimits?: Partial<Record<OperationName, number>>;
  /** Per-operation timeouts in seconds; overrides the schema's @timeout (0 disables). */
  timeouts?: Partial<Record<OperationName, number>>;
}

/** Mounts every operation of the schema on a new Hono router. Mount it at '/' of the application. */
export function buildRouter<E extends Env = Env>(implementations: Implementations, options: RouterOptions<E> = {}): Hono<E> {
  const router = new Hono<E>();
  mountOperation(
    router,
    operationSpecs.saveOutline,
    (ctx, request) =>
      implementations.drawing.saveOutline(
        {
          id: request.path['id'] as string,
          points: request.body['points'] as Point[],
          markers: request.body['markers'] as Point[] | undefined,
          shades: request.body['shades'] as Shade[] | undefined,
        },
        ctx
      ),
    options,
    {
      bodyLimitBytes: options.bodyLimits?.saveOutline,
      rateLimitPerMinute: options.rateLimits?.saveOutline,
      timeoutSeconds: options.timeouts?.saveOutline,
    }
  );
  return router;
}
