package apigen_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/parable-work/superschematic/internal/generator/apigen/sessionauth"
	"github.com/parable-work/superschematic/internal/generator/codegen"
	"github.com/parable-work/superschematic/internal/generator/sqlgen"
	"github.com/parable-work/superschematic/internal/loader"
	ir "github.com/parable-work/superschematic/ir"
)

// TestSessionStoreReportsARevokedSession compiles fixture-api with the
// session provider over a fixture-db whose Session table is soft-deletable,
// then runs sessionStoreTest in the generated module: the generated session
// store finds a revoked (soft-deleted) session with its DeletedAt set, and
// the check examples/acme-shop's auth middleware makes on the record
// refuses it. The store read soft-deleted rows and dropped their DeletedAt,
// so a revoked session authenticated. The in-memory half always runs; the
// Postgres half revokes the session with the generated ORM's soft delete
// when SUPERSCHEMATIC_ORMGEN_TEST_DATABASE_URL is set.
func TestSessionStoreReportsARevokedSession(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping compile check in -short mode")
	}
	dbSchema, err := loader.LoadService(filepath.Join(fixturesDir, "fixture-db"))
	if err != nil {
		t.Fatalf("load fixture-db: %v", err)
	}
	addSessionTables(dbSchema)
	ddl, err := sqlgen.Generate(dbSchema, sqlgen.Options{
		SchemaName: "fixture-db",
		Clock:      codegen.FixedClock(time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)),
	})
	if err != nil {
		t.Fatalf("generate fixture-db ddl: %v", err)
	}

	apiDir := buildFixtureAPIOver(t, sessionauth.Provider{}, dbSchema)
	if err := sqlgen.WriteDDL(ddl, filepath.Join(apiDir, "testdata")); err != nil {
		t.Fatalf("write fixture-db ddl: %v", err)
	}
	if err := os.WriteFile(filepath.Join(apiDir, "session_store_test.go"), []byte(sessionStoreTest), 0o644); err != nil {
		t.Fatalf("write session_store_test.go: %v", err)
	}
	var out []byte
	for _, args := range [][]string{{"mod", "tidy"}, {"vet", "./..."}, {"test", "-count=1", "-v", "./..."}} {
		cmd := exec.Command("go", args...)
		cmd.Dir = apiDir
		out, err = cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("go %s in the generated API module: %v\n%s", strings.Join(args, " "), err, out)
		}
	}
	t.Logf("generated API tests:\n%s", out)
	if !strings.Contains(string(out), "--- PASS: TestSessionStoreFindsARevokedSession ") {
		t.Fatal("the generated API module did not run TestSessionStoreFindsARevokedSession")
	}
}

// addSessionTables gives fixture-db the tables the session provider's
// stores read: User(id, name) and examples/acme-shop's Session(id, jti,
// user, expiresAt) with soft delete (deletedAt, deletedBy) added.
func addSessionTables(schema *ir.Schema) {
	uuid := ir.TypeRef{Name: "Identity.UUID"}
	dateTime := ir.TypeRef{Name: "Temporal.DateTime"}
	schema.Types["User"] = &ir.TypeDef{
		Name: "User",
		Role: ir.RoleDBTable,
		Fields: []*ir.FieldDef{
			{Name: "id", TypeRef: uuid, Required: true, Key: true, AutoGenerated: true},
			{Name: "name", TypeRef: ir.TypeRef{Name: "Identity.Name"}, Required: true},
		},
	}
	schema.Types["Session"] = &ir.TypeDef{
		Name: "Session",
		Role: ir.RoleDBTable,
		Fields: []*ir.FieldDef{
			{Name: "id", TypeRef: uuid, Required: true, Key: true, AutoGenerated: true},
			{Name: "jti", TypeRef: uuid, Required: true, Unique: true},
			{Name: "user", TypeRef: ir.TypeRef{Name: "User"}, Required: true, Relation: &ir.RelationDef{Type: "User", OnDelete: "CASCADE"}},
			{Name: "expiresAt", TypeRef: dateTime, Required: true},
			{Name: "deletedAt", TypeRef: dateTime},
			{Name: "deletedBy", TypeRef: uuid},
		},
	}
}

const sessionStoreTest = `package fixtureapi

import (
	"context"
	"errors"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	runtimesession "github.com/parable-work/superschematic/runtime/http/go/session"

	orm "example.com/schemas/orm/fixture-db"
	types "example.com/schemas/types/go/fixture-db"
)

const (
	liveJTI    = "00000000-0000-4000-8000-0000000000a1"
	revokedJTI = "00000000-0000-4000-8000-0000000000b1"
	unknownJTI = "00000000-0000-4000-8000-00000000dead"
)

// sessionEnded is the check examples/acme-shop's auth middleware makes on
// the record the session store returns: a revoked or expired session
// authenticates no one.
func sessionEnded(record SessionRecord, now time.Time) bool {
	return record.DeletedAt != nil || !record.ExpiresAt.After(now)
}

// checkRevokedSession resolves the three jtis through store: the live
// session authenticates; the revoked one is found, revoked between from and
// to, and authenticates no one; the unknown jti names no session.
func checkRevokedSession(t *testing.T, store runtimesession.Store, from, to time.Time) {
	t.Helper()
	ctx := context.Background()
	now := time.Now()

	live, err := store.FindByJTI(ctx, liveJTI)
	if err != nil {
		t.Fatalf("FindByJTI(live): %v", err)
	}
	if live.DeletedAt != nil || sessionEnded(live, now) {
		t.Fatalf("live session = %+v, want one that authenticates", live)
	}

	revoked, err := store.FindByJTI(ctx, revokedJTI)
	if err != nil {
		t.Fatalf("FindByJTI(revoked): %v, want the revoked session", err)
	}
	if !sessionEnded(revoked, now) {
		t.Fatalf("revoked session = %+v authenticates", revoked)
	}
	if revoked.DeletedAt == nil || revoked.DeletedAt.Before(from) || revoked.DeletedAt.After(to) {
		t.Fatalf("revoked DeletedAt = %v, want a time in [%v, %v]", revoked.DeletedAt, from, to)
	}

	if _, err := store.FindByJTI(ctx, unknownJTI); !errors.Is(err, runtimesession.ErrNotFound) {
		t.Fatalf("FindByJTI(unknown) = %v, want ErrNotFound", err)
	}
}

// sessionRows is a Session repository over rows in memory. FindOne leaves
// a soft-deleted row out unless the options set IncludeDeleted, as the
// generated ORM's does.
type sessionRows struct {
	orm.SessionRepositoryInterface
	rows []*types.Session
}

func (s sessionRows) FindOne(_ context.Context, filter *orm.SessionFilter, opts *orm.SessionFindOptions) (*types.Session, error) {
	for _, row := range s.rows {
		if row.Jti != *filter.Jti.Eq {
			continue
		}
		if row.DeletedAt != nil && (opts == nil || !opts.IncludeDeleted) {
			continue
		}
		return row, nil
	}
	return nil, orm.ErrNotFound
}

type sessionDatabase struct {
	orm.DatabaseInterface
	sessions sessionRows
}

func (d sessionDatabase) GetSessionRepository() orm.SessionRepositoryInterface {
	return d.sessions
}

func TestSessionStoreFindsARevokedSession(t *testing.T) {
	userID := mustUUID(t, "00000000-0000-4000-8000-0000000000c1")
	expiresAt := types.TemporalDateTime(time.Now().Add(time.Hour))
	revokedAt := time.Now().Add(-time.Minute)
	deletedAt := types.TemporalDateTime(revokedAt)
	row := func(id, jti string, deletedAt *types.TemporalDateTime) *types.Session {
		sessionID := mustUUID(t, id)
		return &types.Session{
			Id:        &sessionID,
			Jti:       mustUUID(t, jti),
			User:      types.User{Id: &userID},
			ExpiresAt: expiresAt,
			DeletedAt: deletedAt,
		}
	}
	db := sessionDatabase{sessions: sessionRows{rows: []*types.Session{
		row("00000000-0000-4000-8000-0000000000d1", liveJTI, nil),
		row("00000000-0000-4000-8000-0000000000d2", revokedJTI, &deletedAt),
	}}}
	checkRevokedSession(t, NewSessionStore(db), revokedAt, revokedAt)
}

func TestSessionStoreFindsARevokedSessionOnPostgres(t *testing.T) {
	dsn := os.Getenv("SUPERSCHEMATIC_ORMGEN_TEST_DATABASE_URL")
	if dsn == "" {
		t.Skip("set SUPERSCHEMATIC_ORMGEN_TEST_DATABASE_URL to run the session store against Postgres")
	}
	db := openSessionDatabase(t, dsn)
	ctx := orm.WithUserID(context.Background(), mustUUID(t, "00000000-0000-4000-8000-0000000000e1"))

	user, err := db.User.CreateOne(ctx, &types.User{Name: "Ada"})
	if err != nil {
		t.Fatalf("create user: %v", err)
	}
	expiresAt := types.TemporalDateTime(time.Now().Add(time.Hour))
	var revokedID types.IdentityUUID
	for _, jti := range []string{liveJTI, revokedJTI} {
		session, err := db.Session.CreateOne(ctx, &types.Session{
			Jti:       mustUUID(t, jti),
			User:      types.User{Id: user.Id},
			ExpiresAt: expiresAt,
		})
		if err != nil {
			t.Fatalf("create session %s: %v", jti, err)
		}
		revokedID = *session.Id
	}

	// Postgres keeps microseconds, so the stored time may fall just before
	// the nanosecond clock reading taken ahead of the delete.
	from := time.Now().Truncate(time.Microsecond)
	if err := db.Session.DeleteOne(ctx, revokedID); err != nil {
		t.Fatalf("revoke session: %v", err)
	}
	checkRevokedSession(t, NewSessionStore(db), from, time.Now())
}

func mustUUID(t *testing.T, raw string) types.IdentityUUID {
	t.Helper()
	id, err := types.ParseIdentityUUID(raw)
	if err != nil {
		t.Fatalf("parse uuid %q: %v", raw, err)
	}
	return id
}

// openSessionDatabase applies testdata/create.sql in a fresh schema and
// connects the generated ORM to it.
func openSessionDatabase(t *testing.T, dsn string) *orm.Database {
	t.Helper()
	createSQL, err := os.ReadFile("testdata/create.sql")
	if err != nil {
		t.Fatalf("read create.sql: %v", err)
	}
	ctx := context.Background()
	base, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatalf("connect: %v", err)
	}
	t.Cleanup(base.Close)
	schema := fmt.Sprintf("session_store_%d", time.Now().UnixNano())
	if _, err := base.Exec(ctx, "CREATE SCHEMA "+schema); err != nil {
		t.Fatalf("create schema: %v", err)
	}
	t.Cleanup(func() { _, _ = base.Exec(context.Background(), "DROP SCHEMA "+schema+" CASCADE") })

	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatalf("parse database URL: %v", err)
	}
	if cfg.ConnConfig.RuntimeParams == nil {
		cfg.ConnConfig.RuntimeParams = map[string]string{}
	}
	// Generated DDL can use extension types installed in public (citext).
	cfg.ConnConfig.RuntimeParams["search_path"] = schema + ",public"
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		t.Fatalf("connect schema pool: %v", err)
	}
	conn, err := pool.Acquire(ctx)
	if err != nil {
		pool.Close()
		t.Fatalf("acquire ddl connection: %v", err)
	}
	if _, err := conn.Conn().PgConn().Exec(ctx, string(createSQL)).ReadAll(); err != nil {
		conn.Release()
		pool.Close()
		t.Fatalf("apply create.sql: %v", err)
	}
	conn.Release()
	db, err := orm.ConnectWithPool(pool)
	if err != nil {
		pool.Close()
		t.Fatalf("connect generated orm: %v", err)
	}
	t.Cleanup(db.Close)
	return db
}
`
