package sqlgen

import (
	"fmt"

	"github.com/parable-work/superschematic/internal/generator/codegen"
	"github.com/parable-work/superschematic/internal/generator/sqlutil"
	ir "github.com/parable-work/superschematic/ir"
)

// A queue's table (docs/stack-model.md, section 8.8, D53). A DB service's
// `@queue` class is a message, not a table, and its queue is a table named
// after the class with ir.QueueTableSuffix: the message's ID, a column per
// message field, as a table's field becomes one, and the columns the queue
// keeps (ir.QueueColumns). A claim reads the messages that are ready and
// due, or claimed past their claim's expiry, so a partial index on each
// serves it. The table is a table like any other to the migration planner
// (D27), in every dialect the service lists: the SQLite model reads it from
// this output, as it reads every table.

// QueueTableName is the table of the queue whose class is name: the name
// in snake case, as a table's, and ir.QueueTableSuffix
// (`order_placed_queue`).
func QueueTableName(name string) string {
	return codegen.ToSnakeCase(name) + ir.QueueTableSuffix
}

// convertQueueToTable builds the table of the queue typeDef declares.
func convertQueueToTable(typeDef *ir.TypeDef, schema *ir.Schema, scalarMapping map[string]string, compositeDefaults map[string]*ir.CompositeDefaultDef) (Table, error) {
	message, err := convertTypeToTable(typeDef, schema, scalarMapping, compositeDefaults)
	if err != nil {
		return Table{}, err
	}
	if len(message.ForeignKeys) > 0 || message.PrimaryKey != "" || len(message.Unique) > 0 || len(message.SearchFields) > 0 || len(message.Indexes) > 0 {
		return Table{}, fmt.Errorf("queue %s: a message's fields are values, with no key, reference, unique field, search field or index", typeDef.Name)
	}
	name := QueueTableName(typeDef.Name)
	doc := message.Doc
	if doc == "" {
		doc = "Messages of the queue " + typeDef.Name + ", one row each."
	}
	column := func(name, typ string, nullable bool, def string) Column {
		return Column{Name: name, QuotedName: sqlutil.QuoteIdentifier(name), Type: typ, Nullable: nullable, DefaultValue: def}
	}
	id := column(ir.QueueColumnID, "UUID", false, "gen_random_uuid()")
	id.IsPrimaryKey, id.AutoGenerated = true, true
	columns := append([]Column{id}, message.Columns...)
	columns = append(columns,
		column(ir.QueueColumnState, "TEXT", false, "'"+ir.QueueStateReady+"'"),
		column(ir.QueueColumnAttempts, "INTEGER", false, "0"),
		column(ir.QueueColumnDueAt, "TIMESTAMPTZ", false, "CURRENT_TIMESTAMP"),
		column(ir.QueueColumnClaimExpiresAt, "TIMESTAMPTZ", true, ""),
		column(ir.QueueColumnClaimToken, "UUID", true, ""),
		column(ir.QueueColumnLastError, "TEXT", true, ""),
		column(ir.QueueColumnCreatedAt, "TIMESTAMPTZ", false, "CURRENT_TIMESTAMP"),
		column(ir.QueueColumnUpdatedAt, "TIMESTAMPTZ", false, "CURRENT_TIMESTAMP"),
	)
	seen := map[string]bool{}
	for _, c := range columns {
		if seen[c.Name] {
			return Table{}, fmt.Errorf("queue %s: column %s is both a field of the message and a column the queue keeps; rename the field", typeDef.Name, c.Name)
		}
		seen[c.Name] = true
	}
	// A claim reads the ready messages by when they are due, and the
	// claimed ones by when their claim expires.
	var indexes []Index
	for _, idx := range []struct{ column, state string }{
		{ir.QueueColumnDueAt, ir.QueueStateReady},
		{ir.QueueColumnClaimExpiresAt, ir.QueueStateClaimed},
	} {
		indexName, err := sqlutil.IndexName(name, []string{idx.column}, "", false)
		if err != nil {
			return Table{}, err
		}
		indexes = append(indexes, Index{
			Name:    indexName,
			Columns: []string{sqlutil.QuoteIdentifier(idx.column)},
			Type:    "BTREE",
			Where:   sqlutil.QuoteIdentifier(ir.QueueColumnState) + " = '" + idx.state + "'",
		})
	}
	return Table{
		Name:         name,
		QuotedName:   sqlutil.QuoteIdentifier(name),
		OriginalName: typeDef.Name,
		Doc:          doc,
		Columns:      columns,
		PrimaryKey:   id.QuotedName,
		Unique:       [][]string{},
		ForeignKeys:  []ForeignKey{},
		Indexes:      indexes,
	}, nil
}
