// Package sqlgen generates PostgreSQL DDL (create.sql / drop.sql) for a
// schema's database tables.
//
// This is the v2 port of the v1 sqlgen generator onto the refactored Schema
// IR: tables are selected by TypeDef.Role == DBTable (instead of treating
// every object type in a DB-kind schema as a table), base classes that other
// types extend are skipped because their fields arrive pre-flattened on the
// subclasses, table iteration is deterministic (sorted by type name), scalar
// SQL types come from ir.ScalarDef.TypeMappings via the shared codegen
// mapping, and v1's builtin-scalar special cases (UserID) are gone: foreign
// keys come exclusively from object-type references, @relation, @hasMany,
// and @manyToMany.
package sqlgen

import (
	"embed"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/parable-work/superschematic/internal/generator/codegen"
	"github.com/parable-work/superschematic/internal/generator/sqlutil"
	ir "github.com/parable-work/superschematic/ir"
)

//go:embed templates/*.tmpl
var templatesFS embed.FS

// postgresTypeExtensions maps PostgreSQL types to the extension they require.
var postgresTypeExtensions = map[string]string{
	"citext":    "citext",
	"ltree":     "ltree",
	"point":     "postgis",
	"geography": "postgis",
	"geometry":  "postgis",
}

// Table represents a database table.
type Table struct {
	Name         string
	QuotedName   string
	OriginalName string
	Doc          string
	Columns      []Column
	PrimaryKey   string
	Unique       [][]string
	ForeignKeys  []ForeignKey
	Indexes      []Index

	// SearchFields lists column names marked @searchField; they feed the
	// generated search_text column and its trigram index.
	SearchFields []string
}

// Index represents a database index.
type Index struct {
	Name    string
	Columns []string
	Type    string // BTREE, GIST, GIN, ...
	Unique  bool

	// Where is an optional partial-index predicate (without the WHERE
	// keyword), e.g. "deleted_at IS NULL" for unique indexes on
	// soft-deletable tables.
	Where string
}

// Column represents a table column.
type Column struct {
	Name          string
	QuotedName    string
	Type          string
	Nullable      bool
	Unique        bool
	IsPrimaryKey  bool
	AutoGenerated bool
	DefaultValue  string
}

// ForeignKey represents a foreign key constraint.
type ForeignKey struct {
	// ConstraintName is the identifier PostgreSQL will create, stamped by
	// assignForeignKeyNames once every pass has finished adding foreign keys.
	ConstraintName  string
	Column          string
	QuotedColumn    string
	RefTable        string
	QuotedRefTable  string
	RefColumn       string
	QuotedRefColumn string
	// OnDelete is the FK ON DELETE action. Empty is treated as CASCADE by the
	// template (the historical default).
	OnDelete string
}

// JoinTable represents a many-to-many join table.
type JoinTable struct {
	Name              string
	QuotedName        string
	LeftTable         string
	QuotedLeftTable   string
	LeftColumn        string
	QuotedLeftColumn  string
	LeftColumnType    string
	RightTable        string
	QuotedRightTable  string
	RightColumn       string
	QuotedRightColumn string
	RightColumnType   string

	// LeftConstraintName and RightConstraintName are the identifiers PostgreSQL
	// will create for the two join-table foreign keys.
	LeftConstraintName  string
	RightConstraintName string

	// OriginalField is the schema field that declared the relationship.
	OriginalField string
}

// HistoryTable represents the generated append-only history table and capture
// trigger metadata for a versioned source table.
type HistoryTable struct {
	Name                   string
	QuotedName             string
	SourceTableName        string
	QuotedSourceTableName  string
	KeyColumn              string
	QuotedKeyColumn        string
	KeyColumnType          string
	UniqueIndexName        string
	VersionIndexName       string
	RecordedIndexName      string
	RetentionIndexName     string
	FunctionName           string
	PruneFunctionName      string
	WriteTriggerName       string
	DeleteTriggerName      string
	RetentionDays          int
	PartitionBy            string
	DefaultPartitionName   string
	QuotedDefaultPartition string

	// PruneKeep adds one NOT EXISTS exclusion per entry to the generated prune
	// function, so externally referenced (key, _version) pairs survive.
	PruneKeep []PruneKeepRef
}

// PruneKeepRef is the quoted referencing-table metadata for one of the prune
// function's pinned-row exclusions.
type PruneKeepRef struct {
	// Alias disambiguates this exclusion's subquery from the others.
	Alias               string
	QuotedTable         string
	QuotedKeyColumn     string
	QuotedVersionColumn string
}

// DDLOutput contains all the generated DDL.
type DDLOutput struct {
	SchemaName      string
	Extensions      []string
	Tables          []Table
	JoinTables      []JoinTable
	HistoryTables   []HistoryTable
	Projections     []ProjectionView
	Timestamp       string
	HasUserTable    bool
	SystemUserUUID  string
	SystemUserName  string
	SystemUserEmail string

	// MetadataKeyPrefix prefixes the keys of the projection Arrow schemas'
	// metadata (Options.MetadataKeyPrefix).
	MetadataKeyPrefix string
}

// Options configures DDL generation.
type Options struct {
	// SchemaName is the service name (e.g. "web-db").
	SchemaName string

	// Dependencies contains declared service schemas used to resolve
	// platform defaults owned beside imported object types.
	Dependencies map[string]*ir.Schema

	// Clock stamps the generated output.
	Clock codegen.Clock

	// ViewOwner is the Postgres role the generated projection migrations
	// create their views as (SET ROLE around the DDL). Empty creates them as
	// the migration runner. It must be a plain lowercase identifier.
	ViewOwner string

	// MetadataKeyPrefix prefixes the keys of the projection Arrow schemas'
	// metadata (Naming.MetadataKeyPrefix). Empty means "superschematic.".
	MetadataKeyPrefix string
}

// viewOwnerPattern constrains Options.ViewOwner to a plain role name.
var viewOwnerPattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// DefaultMetadataKeyPrefix is the metadata key prefix when Options leaves it
// empty; it matches naming.Default().
const DefaultMetadataKeyPrefix = "superschematic."

// Generate generates PostgreSQL DDL from a v2 IR schema. Returns nil when
// the schema declares no database tables.
func Generate(schema *ir.Schema, opts Options) (*DDLOutput, error) {
	if opts.Clock == nil {
		opts.Clock = codegen.DefaultClock()
	}

	scalarMapping := buildSQLMapping(schema)
	compositeDefaults, err := collectCompositeDefaults(schema, opts.Dependencies)
	if err != nil {
		return nil, err
	}
	tableTypes := tableTypeDefs(schema)
	if len(tableTypes) == 0 {
		return nil, nil
	}

	tables := make([]Table, 0, len(tableTypes))
	usedScalars := make(map[string]bool)
	for _, typeDef := range tableTypes {
		table, err := convertTypeToTable(typeDef, schema, scalarMapping, compositeDefaults)
		if err != nil {
			return nil, fmt.Errorf("failed to convert type %s to table: %w", typeDef.Name, err)
		}
		tables = append(tables, table)
		for _, col := range table.Columns {
			usedScalars[col.Type] = true
		}
	}

	// Second pass: add FK columns on the "many" side of @hasMany.
	tableMap := make(map[string]*Table, len(tables))
	for i := range tables {
		tableMap[tables[i].OriginalName] = &tables[i]
	}

	for _, typeDef := range tableTypes {
		for _, field := range typeDef.Fields {
			if field.JsonField || field.TypeRef.IsMap || !field.TypeRef.IsArray {
				continue
			}
			if !field.HasMany || field.ManyToMany {
				continue
			}

			targetTable := tableMap[field.TypeRef.Name]
			if targetTable == nil {
				continue
			}

			parentTableName := codegen.ToSnakeCase(typeDef.Name)
			fkColumnName := parentTableName + "_id"

			columnExists := false
			for _, col := range targetTable.Columns {
				if col.Name == fkColumnName {
					columnExists = true
					break
				}
			}
			if columnExists {
				continue
			}

			targetTable.Columns = append(targetTable.Columns, Column{
				Name:       fkColumnName,
				QuotedName: sqlutil.QuoteIdentifier(fkColumnName),
				Type:       keyFieldType(typeDef, scalarMapping),
				Nullable:   !field.Required,
			})
			targetTable.ForeignKeys = append(targetTable.ForeignKeys, ForeignKey{
				Column:          fkColumnName,
				QuotedColumn:    sqlutil.QuoteIdentifier(fkColumnName),
				RefTable:        parentTableName,
				QuotedRefTable:  sqlutil.QuoteIdentifier(parentTableName),
				RefColumn:       "id",
				QuotedRefColumn: sqlutil.QuoteIdentifier("id"),
				// @hasMany back-ref: no RelationDef to read; stays CASCADE.
				OnDelete: "CASCADE",
			})
		}
	}

	// Collect join tables for @manyToMany relationships.
	var joinTables []JoinTable
	for _, typeDef := range tableTypes {
		for _, field := range typeDef.Fields {
			if field.JsonField || field.TypeRef.IsMap || !field.TypeRef.IsArray || !field.ManyToMany {
				continue
			}
			if tableMap[field.TypeRef.Name] == nil {
				continue
			}
			joinTables = append(joinTables, buildJoinTable(typeDef.Name, field, field.TypeRef.Name, schema, scalarMapping))
		}
	}

	// Stamp foreign key constraint names now that every pass has finished
	// adding them.
	for i := range tables {
		if err := assignForeignKeyNames(&tables[i]); err != nil {
			return nil, err
		}
	}
	for i := range joinTables {
		jt := &joinTables[i]
		jt.LeftConstraintName = serverConstraintName("fk_" + jt.Name + "_" + jt.LeftColumn)
		jt.RightConstraintName = serverConstraintName("fk_" + jt.Name + "_" + jt.RightColumn)
		if jt.LeftConstraintName == jt.RightConstraintName {
			return nil, fmt.Errorf(
				"join table %s: both foreign keys generate the constraint name %q; shorten one of the joined table names",
				jt.Name, jt.LeftConstraintName)
		}
	}

	// Ensure all tables have a primary key.
	for i := range tables {
		table := &tables[i]
		if table.PrimaryKey != "" {
			continue
		}
		idColumn := Column{
			Name:          "id",
			QuotedName:    sqlutil.QuoteIdentifier("id"),
			Type:          "UUID",
			Nullable:      false,
			IsPrimaryKey:  true,
			AutoGenerated: true,
			DefaultValue:  "gen_random_uuid()",
		}
		table.Columns = append([]Column{idColumn}, table.Columns...)
		table.PrimaryKey = idColumn.QuotedName
	}

	var historyTables []HistoryTable
	for _, typeDef := range tableTypes {
		if !typeDef.Versioned {
			continue
		}

		table := tableMap[typeDef.Name]
		if table == nil {
			continue
		}
		injectVersionColumn(table)
		historyTable, err := buildHistoryTable(*table, typeDef.VersionedConfig)
		if err != nil {
			return nil, fmt.Errorf("failed to build history table for %s: %w", typeDef.Name, err)
		}
		historyTables = append(historyTables, historyTable)
	}

	projections, err := buildProjections(schema, opts.Dependencies, tableMap, scalarMapping)
	if err != nil {
		return nil, err
	}
	if opts.ViewOwner != "" {
		if !viewOwnerPattern.MatchString(opts.ViewOwner) {
			return nil, fmt.Errorf("outputs.sql.viewOwner %q must be a lowercase Postgres role name", opts.ViewOwner)
		}
		for i := range projections {
			projections[i].ViewOwner = opts.ViewOwner
			projections[i].QuotedViewOwner = sqlutil.QuoteIdentifier(opts.ViewOwner)
		}
	}
	metadataKeyPrefix := opts.MetadataKeyPrefix
	if metadataKeyPrefix == "" {
		metadataKeyPrefix = DefaultMetadataKeyPrefix
	}

	hasUserTable := false
	for _, table := range tables {
		if table.OriginalName == "User" {
			hasUserTable = true
			break
		}
	}

	output := &DDLOutput{
		SchemaName:      opts.SchemaName,
		Extensions:      collectExtensions(tables, historyTables, usedScalars),
		Tables:          tables,
		JoinTables:      joinTables,
		HistoryTables:   historyTables,
		Projections:     projections,
		Timestamp:       opts.Clock.RFC3339(),
		HasUserTable:    hasUserTable,
		SystemUserUUID:  "00000000-0000-4000-8000-000000000000",
		SystemUserName:  "System",
		SystemUserEmail: "system@localhost",

		MetadataKeyPrefix: metadataKeyPrefix,
	}

	return output, nil
}

// buildSQLMapping returns the scalar-name -> SQL-type map. Scalars with an
// explicit TypeMappings["sql"] entry use it (via the shared codegen
// mapping); scalars without one are inferred from their semantic traits
// (UUID-like -> UUID, datetime-like -> TIMESTAMPTZ, ...) before bottoming
// out on the host-language primitive.
func buildSQLMapping(schema *ir.Schema) map[string]string {
	mapping := codegen.BuildScalarSQLMapping(schema)

	for _, scalarDef := range schema.Scalars {
		if _, ok := scalarDef.TypeMappings["sql"]; ok {
			continue
		}
		tokens := codegen.BuildScalarTokens(scalarDef.Name)
		traits := codegen.BuildScalarTraits(scalarDef, tokens, "")
		if inferred := sqlTypeFromTraits(traits); inferred != "" {
			mapping[scalarDef.Name] = inferred
		}
	}

	return mapping
}

// sqlTypeFromTraits infers a SQL type from scalar semantics. Returns "" when
// the traits carry no SQL-relevant signal.
func sqlTypeFromTraits(traits codegen.ScalarTraits) string {
	switch {
	case traits.IsUUIDLike:
		return "UUID"
	case traits.IsDateTimeLike:
		return "TIMESTAMPTZ"
	case traits.IsDateLike:
		return "DATE"
	case traits.IsTimeLike:
		return "TIME"
	case traits.IsDurationLike, traits.IsIntegerLike:
		return "BIGINT"
	case traits.IsFloatLike:
		return "DOUBLE PRECISION"
	case traits.IsJSONLike, traits.IsObjectLike:
		return "JSONB"
	}
	return ""
}

// tableTypeDefs returns the schema's table-backed type definitions sorted by
// name: Role == DBTable, not a @jsonField payload, and not a base class
// (base-class fields arrive pre-flattened on the subclasses).
func tableTypeDefs(schema *ir.Schema) []*ir.TypeDef {
	baseTypes := codegen.BaseTypeNames(schema)

	var defs []*ir.TypeDef
	for _, typeDef := range schema.Types {
		if typeDef.Role != ir.RoleDBTable || typeDef.JsonField || baseTypes[typeDef.Name] {
			continue
		}
		defs = append(defs, typeDef)
	}

	sort.Slice(defs, func(i, j int) bool { return defs[i].Name < defs[j].Name })
	return defs
}

// isRelationalTarget reports whether typeName names a table-backed type in
// this schema.
func isRelationalTarget(typeName string, schema *ir.Schema) bool {
	targetTypeDef := schema.Types[typeName]
	return targetTypeDef != nil && targetTypeDef.Role == ir.RoleDBTable && !targetTypeDef.JsonField
}

// convertTypeToTable converts an IR type to a database table.
func convertTypeToTable(
	typeDef *ir.TypeDef,
	schema *ir.Schema,
	scalarMapping map[string]string,
	compositeDefaults map[string]*ir.CompositeDefaultDef,
) (Table, error) {
	tableName := codegen.ToSnakeCase(typeDef.Name)
	table := Table{
		Name:         tableName,
		QuotedName:   sqlutil.QuoteIdentifier(tableName),
		OriginalName: typeDef.Name,
		Doc:          codegen.DocText(typeDef.Description, typeDef.Comment),
		Columns:      []Column{},
		Unique:       [][]string{},
		ForeignKeys:  []ForeignKey{},
		Indexes:      []Index{},
	}

	for _, field := range typeDef.Fields {
		relationalTarget := isRelationalTarget(field.TypeRef.Name, schema)

		// List relationship (one-to-many or many-to-many): no column here.
		if !field.JsonField && !field.TypeRef.IsMap && field.TypeRef.IsArray && relationalTarget {
			if !field.HasMany && !field.ManyToMany {
				return table, fmt.Errorf(
					"field %s.%s is a list of table type %s but lacks @hasMany or @manyToMany",
					typeDef.Name, field.Name, field.TypeRef.Name,
				)
			}
			continue
		}

		// Single object reference: FK column on this table.
		if !field.JsonField && !field.TypeRef.IsMap && !field.TypeRef.IsArray && relationalTarget {
			fkColumn, fkConstraint := buildForeignKey(field, schema, scalarMapping)

			if field.Unique && !field.Key {
				fkColumn.Unique = true
				table.Unique = append(table.Unique, []string{fkColumn.QuotedName})
			}

			table.Columns = append(table.Columns, fkColumn)
			table.ForeignKeys = append(table.ForeignKeys, fkConstraint)
			continue
		}

		// Regular column.
		columnName := codegen.ToSnakeCase(field.Name)
		irType := field.TypeRef.Name
		column := Column{
			Name:       columnName,
			QuotedName: sqlutil.QuoteIdentifier(columnName),
			Type:       columnType(field, scalarMapping),
			Nullable:   !field.Required,
		}

		if field.Key {
			column.IsPrimaryKey = true
			table.PrimaryKey = column.QuotedName
		}

		if field.SearchField {
			table.SearchFields = append(table.SearchFields, columnName)
		}

		if field.Unique && !field.Key {
			column.Unique = true
			table.Unique = append(table.Unique, []string{column.QuotedName})
		}

		if field.Key || field.AutoGenerated {
			if defaultVal := autoGeneratedDefault(column.Type, irType); defaultVal != "" {
				column.AutoGenerated = true
				column.DefaultValue = defaultVal
			}
		}

		if field.PlatformDefault != "" {
			def := compositeDefaults[field.PlatformDefault]
			if def == nil {
				return table, fmt.Errorf("field %s.%s references missing platform default %q", typeDef.Name, field.Name, field.PlatformDefault)
			}
			if column.Type != "JSONB" {
				return table, fmt.Errorf("field %s.%s uses platform default %q on non-JSONB column %s", typeDef.Name, field.Name, field.PlatformDefault, column.Type)
			}
			escaped := strings.ReplaceAll(def.CanonicalJSON, "'", "''")
			column.DefaultValue = "'" + escaped + "'::jsonb"
		}

		if !column.Nullable && !column.AutoGenerated && column.DefaultValue == "" {
			traits := codegen.GuessScalarTraits(irType)
			if column.Type == "TIMESTAMPTZ" || traits.IsDateTimeLike {
				column.DefaultValue = "CURRENT_TIMESTAMP"
			} else if column.Type == "DATE" || traits.IsDateLike {
				column.DefaultValue = "CURRENT_DATE"
			} else if column.Type == "TIME" || traits.IsTimeLike {
				column.DefaultValue = "CURRENT_TIME"
			}
		}

		if !column.Nullable && !column.AutoGenerated && column.DefaultValue == "" {
			if strings.HasSuffix(column.Type, "[]") {
				column.DefaultValue = "'{}'"
			}
		}

		// Explicit @relation: FK constraint on this scalar column.
		if !field.JsonField && !field.TypeRef.IsMap && field.Relation != nil {
			refTableName := codegen.ToSnakeCase(field.Relation.Type)
			onDelete := "CASCADE"
			if field.Relation.OnDelete != "" {
				onDelete = field.Relation.OnDelete
			}
			table.ForeignKeys = append(table.ForeignKeys, ForeignKey{
				Column:          columnName,
				QuotedColumn:    sqlutil.QuoteIdentifier(columnName),
				RefTable:        refTableName,
				QuotedRefTable:  sqlutil.QuoteIdentifier(refTableName),
				RefColumn:       "id",
				QuotedRefColumn: sqlutil.QuoteIdentifier("id"),
				OnDelete:        onDelete,
			})
		}

		table.Columns = append(table.Columns, column)
	}

	// Indexes from @index declarations.
	var pending []pendingIndex
	for _, idx := range typeDef.Indexes {
		if len(idx.Keys) == 0 {
			continue
		}

		indexColumns := make([]string, 0, len(idx.Keys))
		indexTypes := make([]string, 0, len(idx.Keys))
		indexKeys := make([]string, 0, len(idx.Keys))
		validIndex := true

		for _, key := range idx.Keys {
			indexCol := findIndexColumn(table.Columns, key)
			if indexCol == nil {
				validIndex = false
				break
			}
			indexColumns = append(indexColumns, indexCol.QuotedName)
			indexTypes = append(indexTypes, indexCol.Type)
			indexKeys = append(indexKeys, key)
		}
		if !validIndex {
			continue
		}

		pending = append(pending, pendingIndex{
			index: Index{
				Columns: indexColumns,
				Type:    determineIndexType(indexTypes),
				Unique:  idx.Unique,
				Where:   uniqueIndexPredicate(idx, table.Columns, indexColumns),
			},
			keys: indexKeys,
			name: idx.Name,
		})
	}
	indexes, err := assignIndexNames(table.Name, pending)
	if err != nil {
		return table, err
	}
	table.Indexes = indexes

	return table, nil
}

func collectCompositeDefaults(schema *ir.Schema, dependencies map[string]*ir.Schema) (map[string]*ir.CompositeDefaultDef, error) {
	defaults := make(map[string]*ir.CompositeDefaultDef)
	add := func(owner string, source *ir.Schema) error {
		if source == nil {
			return nil
		}
		for name, def := range source.CompositeDefaults {
			if existing, found := defaults[name]; found && existing != def {
				return fmt.Errorf("platform default %q is declared by more than one schema, including %s", name, owner)
			}
			defaults[name] = def
		}
		return nil
	}
	if err := add(schema.Name, schema); err != nil {
		return nil, err
	}
	names := make([]string, 0, len(dependencies))
	for name := range dependencies {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := add(name, dependencies[name]); err != nil {
			return nil, err
		}
	}
	return defaults, nil
}

// uniqueIndexPredicate returns the partial-index predicate for a unique
// index on a soft-deletable table (one with a deleted_at column):
// "deleted_at IS NULL", so soft-deleted tombstones do not permanently
// occupy the unique slot. Non-unique indexes, tables without
// deleted_at, and indexes that key on deleted_at itself get no predicate.
func uniqueIndexPredicate(idx ir.IndexDef, columns []Column, indexColumns []string) string {
	if !idx.Unique {
		return ""
	}

	deletedAtQuoted := ""
	for _, col := range columns {
		if col.Name == "deleted_at" {
			deletedAtQuoted = col.QuotedName
			break
		}
	}
	if deletedAtQuoted == "" {
		return ""
	}

	for _, quotedCol := range indexColumns {
		if quotedCol == deletedAtQuoted {
			return ""
		}
	}

	return "deleted_at IS NULL"
}

func injectVersionColumn(table *Table) {
	for _, col := range table.Columns {
		if col.Name == "_version" {
			return
		}
	}
	table.Columns = append(table.Columns, Column{
		Name:         "_version",
		QuotedName:   sqlutil.QuoteIdentifier("_version"),
		Type:         "BIGINT",
		Nullable:     false,
		DefaultValue: "1",
	})
}

func buildHistoryTable(table Table, cfg *ir.VersionedConfig) (HistoryTable, error) {
	keyColumn := primaryKeyColumn(table)
	if keyColumn == nil {
		return HistoryTable{}, fmt.Errorf("table %s has no primary key", table.Name)
	}

	historyName := table.Name + "_history"
	history := HistoryTable{
		Name:                   historyName,
		QuotedName:             sqlutil.QuoteIdentifier(historyName),
		SourceTableName:        table.Name,
		QuotedSourceTableName:  table.QuotedName,
		KeyColumn:              keyColumn.Name,
		QuotedKeyColumn:        keyColumn.QuotedName,
		KeyColumnType:          keyColumn.Type,
		UniqueIndexName:        "uq_" + historyName + "_" + keyColumn.Name + "_version",
		VersionIndexName:       "idx_" + historyName + "_" + keyColumn.Name + "_version",
		RecordedIndexName:      "idx_" + historyName + "_" + keyColumn.Name + "_recorded",
		RetentionIndexName:     "idx_" + historyName + "_recorded",
		FunctionName:           table.Name + "_capture_history",
		PruneFunctionName:      table.Name + "_prune_history",
		WriteTriggerName:       "trg_" + table.Name + "_capture_history_write",
		DeleteTriggerName:      "trg_" + table.Name + "_capture_history_delete",
		DefaultPartitionName:   historyName + "_default",
		QuotedDefaultPartition: sqlutil.QuoteIdentifier(historyName + "_default"),
	}
	if cfg != nil {
		if cfg.RetentionDays != nil {
			history.RetentionDays = *cfg.RetentionDays
		}
		history.PartitionBy = cfg.PartitionBy
		for i, pin := range cfg.PruneKeepReferencedBy {
			history.PruneKeep = append(history.PruneKeep, PruneKeepRef{
				Alias:               fmt.Sprintf("pin_%d", i+1),
				QuotedTable:         sqlutil.QuoteIdentifier(pin.Table),
				QuotedKeyColumn:     sqlutil.QuoteIdentifier(pin.KeyColumn),
				QuotedVersionColumn: sqlutil.QuoteIdentifier(pin.VersionColumn),
			})
		}
	}
	return history, nil
}

func primaryKeyColumn(table Table) *Column {
	for i := range table.Columns {
		if table.Columns[i].IsPrimaryKey {
			return &table.Columns[i]
		}
	}
	return nil
}

// keyFieldType returns the SQL type of a type's primary key field.
func keyFieldType(typeDef *ir.TypeDef, scalarMapping map[string]string) string {
	if typeDef == nil {
		return "UUID"
	}
	for _, field := range typeDef.Fields {
		if field.Key {
			return columnType(field, scalarMapping)
		}
	}
	for _, field := range typeDef.Fields {
		if field.Name == "id" {
			return columnType(field, scalarMapping)
		}
	}
	return "UUID"
}

// buildForeignKey generates a foreign key column and constraint for a field
// referencing another table type.
func buildForeignKey(field *ir.FieldDef, schema *ir.Schema, scalarMapping map[string]string) (Column, ForeignKey) {
	typeName := field.TypeRef.Name
	columnName := codegen.ToSnakeCase(field.Name) + "_id"
	refTableName := codegen.ToSnakeCase(typeName)

	column := Column{
		Name:       columnName,
		QuotedName: sqlutil.QuoteIdentifier(columnName),
		Type:       keyFieldType(schema.Types[typeName], scalarMapping),
		Nullable:   !field.Required,
	}

	onDelete := "CASCADE"
	if field.Relation != nil && field.Relation.OnDelete != "" {
		onDelete = field.Relation.OnDelete
	}
	fk := ForeignKey{
		Column:          columnName,
		QuotedColumn:    sqlutil.QuoteIdentifier(columnName),
		RefTable:        refTableName,
		QuotedRefTable:  sqlutil.QuoteIdentifier(refTableName),
		RefColumn:       "id",
		QuotedRefColumn: sqlutil.QuoteIdentifier("id"),
		OnDelete:        onDelete,
	}

	return column, fk
}

// buildJoinTable generates a join table for a many-to-many relationship.
func buildJoinTable(parentTypeName string, field *ir.FieldDef, targetTypeName string, schema *ir.Schema, scalarMapping map[string]string) JoinTable {
	parentTableName := codegen.ToSnakeCase(parentTypeName)
	targetTableName := codegen.ToSnakeCase(targetTypeName)
	joinTableName := parentTableName + "_" + targetTableName

	return JoinTable{
		Name:              joinTableName,
		QuotedName:        sqlutil.QuoteIdentifier(joinTableName),
		LeftTable:         parentTableName,
		QuotedLeftTable:   sqlutil.QuoteIdentifier(parentTableName),
		LeftColumn:        parentTableName + "_id",
		QuotedLeftColumn:  sqlutil.QuoteIdentifier(parentTableName + "_id"),
		LeftColumnType:    keyFieldType(schema.Types[parentTypeName], scalarMapping),
		RightTable:        targetTableName,
		QuotedRightTable:  sqlutil.QuoteIdentifier(targetTableName),
		RightColumn:       targetTableName + "_id",
		QuotedRightColumn: sqlutil.QuoteIdentifier(targetTableName + "_id"),
		RightColumnType:   keyFieldType(schema.Types[targetTypeName], scalarMapping),
		OriginalField:     field.Name,
	}
}

// columnType returns the PostgreSQL column type for an IR field.
func columnType(field *ir.FieldDef, scalarMapping map[string]string) string {
	if field.JsonField || field.TypeRef.IsMap {
		return "JSONB"
	}

	typeName := field.TypeRef.Name
	if field.TypeRef.IsArray {
		if sqlType, ok := scalarMapping[typeName]; ok {
			return sqlType + "[]"
		}
		return "TEXT[]"
	}

	if sqlType, ok := scalarMapping[typeName]; ok {
		return sqlType
	}

	return "TEXT"
}

// collectExtensions determines which PostgreSQL extensions the DDL requires.
func collectExtensions(tables []Table, historyTables []HistoryTable, usedScalars map[string]bool) []string {
	var extensions []string
	extensionSet := make(map[string]bool)
	add := func(ext string) {
		if !extensionSet[ext] {
			extensionSet[ext] = true
			extensions = append(extensions, ext)
		}
	}

	for _, table := range tables {
		for _, col := range table.Columns {
			if col.DefaultValue == "gen_random_uuid()" {
				add("pgcrypto")
				break
			}
		}
		if extensionSet["pgcrypto"] {
			break
		}
	}
	if len(historyTables) > 0 {
		add("pgcrypto")
	}

	scalarTypes := make([]string, 0, len(usedScalars))
	for pgType := range usedScalars {
		scalarTypes = append(scalarTypes, pgType)
	}
	sort.Strings(scalarTypes)
	for _, pgType := range scalarTypes {
		baseType := strings.ToLower(strings.TrimSuffix(pgType, "[]"))
		if ext, ok := postgresTypeExtensions[baseType]; ok {
			add(ext)
		}
	}

	for _, table := range tables {
		if len(table.SearchFields) > 0 {
			add("pg_trgm")
			break
		}
	}

	// btree_gist is needed when a GIST index includes a column whose type
	// has no default GIST operator class (uuid, integer, text, timestamp,
	// ...). The index type picks GIST as soon as one column is ltree/etc.,
	// so a composite GIST index that mixes a GIST-native column with a
	// btree-only column would otherwise fail at DDL time.
	for _, table := range tables {
		colTypeByQuoted := make(map[string]string, len(table.Columns))
		for _, col := range table.Columns {
			colTypeByQuoted[col.QuotedName] = col.Type
		}
		for _, idx := range table.Indexes {
			if idx.Type != "GIST" {
				continue
			}
			for _, quotedCol := range idx.Columns {
				if needsBtreeGist(colTypeByQuoted[quotedCol]) {
					add("btree_gist")
					break
				}
			}
			if extensionSet["btree_gist"] {
				break
			}
		}
		if extensionSet["btree_gist"] {
			break
		}
	}

	return extensions
}

// gistNativeTypes lists Postgres types that have a default GIST operator
// class without requiring the btree_gist extension. ltree comes from the
// ltree extension; the geometric and tsvector types are built-in. Anything
// else (uuid, text, integer, timestamps, ...) needs btree_gist to
// participate in a GIST index.
var gistNativeTypes = map[string]bool{
	"ltree":     true,
	"tsvector":  true,
	"box":       true,
	"circle":    true,
	"point":     true,
	"polygon":   true,
	"line":      true,
	"lseg":      true,
	"path":      true,
	"daterange": true,
	"int4range": true,
	"int8range": true,
	"numrange":  true,
	"tsrange":   true,
	"tstzrange": true,
	"geometry":  true,
	"geography": true,
}

// needsBtreeGist reports whether a column of the given SQL type requires the
// btree_gist extension to participate in a GIST index.
func needsBtreeGist(sqlType string) bool {
	if sqlType == "" {
		return false
	}
	base := strings.ToLower(strings.TrimSuffix(sqlType, "[]"))
	return !gistNativeTypes[base]
}

// determineIndexType picks the index access method based on column types.
func determineIndexType(columnTypes []string) string {
	for _, colType := range columnTypes {
		baseType := strings.ToLower(strings.TrimSuffix(colType, "[]"))

		// GIST for hierarchical data (ltree) and geometric types.
		if baseType == "ltree" || baseType == "point" || baseType == "geography" || baseType == "geometry" {
			return "GIST"
		}

		// GIN for JSONB, arrays, and full-text search.
		if baseType == "jsonb" || baseType == "tsvector" || strings.HasSuffix(colType, "[]") {
			return "GIN"
		}
	}
	return "BTREE"
}

func findIndexColumn(columns []Column, key string) *Column {
	keyFieldName := codegen.ToSnakeCase(key)
	for i := range columns {
		col := &columns[i]
		if col.Name == keyFieldName || col.Name == keyFieldName+"_id" {
			return col
		}
	}
	return nil
}

const postgresIdentifierLimit = 63

type pendingIndex struct {
	index Index
	keys  []string
	name  string
}

var indexPurposeName = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// indexName builds the identifier for one declared index. Without an explicit
// purpose the name stays idx_{table}_{columns}; with one it becomes
// {idx|uq}_{table}_{purpose}.
//
// PostgreSQL truncates identifiers past 63 bytes, which silently collapses two
// distinct indexes into one name. Rather than pack or hash a name to fit, an
// overlong result is a schema error: the author picks a purpose name, which
// reads better than any suffix the generator could derive.
func indexName(tableName string, p pendingIndex) (string, error) {
	if p.name == "" {
		parts := make([]string, 0, 2+len(p.keys))
		parts = append(parts, "idx", tableName)
		for _, key := range p.keys {
			parts = append(parts, codegen.ToSnakeCase(key))
		}
		name := strings.Join(parts, "_")
		if len(name) > postgresIdentifierLimit {
			return "", fmt.Errorf(
				"index on %s over %s generates %q (%d bytes), over PostgreSQL's %d-byte limit; give it a purpose name: @index([...], { name: 'purpose' })",
				tableName, strings.Join(p.keys, ", "), name, len(name), postgresIdentifierLimit)
		}
		return name, nil
	}

	if !indexPurposeName.MatchString(p.name) {
		return "", fmt.Errorf("index name %q on %s must be lowercase alphanumeric with underscores", p.name, tableName)
	}
	kind := "idx"
	if p.index.Unique {
		kind = "uq"
	}
	name := kind + "_" + tableName + "_" + p.name
	if len(name) > postgresIdentifierLimit {
		return "", fmt.Errorf(
			"index name %q on %s is %d bytes, over PostgreSQL's %d-byte limit; shorten the purpose name",
			name, tableName, len(name), postgresIdentifierLimit)
	}
	return name, nil
}

// serverConstraintName returns the identifier PostgreSQL will create for name.
// The server truncates anything past 63 bytes, so emitting the truncated form
// keeps the generated DDL honest about what ends up in the database instead of
// naming a constraint that never exists under that name.
//
// Unlike an index, a foreign key name is built from a table and a column the
// author already named, so there is no shorter name to offer them; the failure
// worth reporting is two constraints on one table collapsing into one, which
// assignForeignKeyNames catches.
func serverConstraintName(name string) string {
	if len(name) <= postgresIdentifierLimit {
		return name
	}
	// Mirror pg_mbcliplen: never cut a multi-byte character in half.
	end := postgresIdentifierLimit
	for end > 0 && !utf8.RuneStart(name[end]) {
		end--
	}
	return name[:end]
}

func assignForeignKeyNames(table *Table) error {
	seen := make(map[string]string, len(table.ForeignKeys))
	for i := range table.ForeignKeys {
		fk := &table.ForeignKeys[i]
		fk.ConstraintName = serverConstraintName("fk_" + table.Name + "_" + fk.Column)
		if prev, dup := seen[fk.ConstraintName]; dup {
			return fmt.Errorf(
				"foreign keys on %s over %s and %s both generate the constraint name %q; PostgreSQL truncates identifiers to %d bytes, so shorten one of the column names",
				table.Name, prev, fk.Column, fk.ConstraintName, postgresIdentifierLimit)
		}
		seen[fk.ConstraintName] = fk.Column
	}
	return nil
}

func assignIndexNames(tableName string, pending []pendingIndex) ([]Index, error) {
	if len(pending) == 0 {
		return nil, nil
	}
	out := make([]Index, len(pending))
	seen := make(map[string]int, len(pending))
	for i, p := range pending {
		name, err := indexName(tableName, p)
		if err != nil {
			return nil, err
		}
		if prev, dup := seen[name]; dup {
			return nil, fmt.Errorf(
				"indexes on %s over (%s) and (%s) both generate the name %q; give one a purpose name: @index([...], { name: 'purpose' })",
				tableName, strings.Join(pending[prev].keys, ", "), strings.Join(p.keys, ", "), name)
		}
		seen[name] = i
		p.index.Name = name
		out[i] = p.index
	}
	return out, nil
}

// autoGeneratedDefault returns the DEFAULT clause for auto-generated fields,
// or "" when the type cannot be auto-generated.
func autoGeneratedDefault(sqlType, irType string) string {
	traits := codegen.GuessScalarTraits(irType)

	if sqlType == "UUID" || traits.IsUUIDLike || traits.IsIDLike {
		return "gen_random_uuid()"
	}
	if sqlType == "TIMESTAMPTZ" || traits.IsDateTimeLike {
		return "CURRENT_TIMESTAMP"
	}
	if sqlType == "DATE" || traits.IsDateLike {
		return "CURRENT_DATE"
	}
	if sqlType == "TIME" || traits.IsTimeLike {
		return "CURRENT_TIME"
	}
	return ""
}
