// Code generated by rustgen. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::scalars::*;
use crate::enums::*;

/// Base class providing audit fields to every table.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Auditable {
    #[serde(rename = "createdAt")]
    pub created_at: TemporalDateTime,
    #[serde(default, rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<TemporalDateTime>,
}

fn default_tenant_status() -> TenantStatus {
    TenantStatus::Active
}

fn default_tenant_is_active() -> bool {
    true
}

fn default_tenant_seat_count() -> f64 {
    5_f64
}

/// A tenant of the platform.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tenant {
    #[serde(rename = "createdAt")]
    pub created_at: TemporalDateTime,
    #[serde(default, rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<TemporalDateTime>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    /// Display name shown across the product.
    pub name: IdentityName,
    pub slug: IdentitySlug,
    pub email: String,
    #[serde(default = "default_tenant_status")]
    pub status: TenantStatus,
    #[serde(default = "default_tenant_is_active", rename = "isActive")]
    pub is_active: bool,
    #[serde(default = "default_tenant_seat_count", rename = "seatCount")]
    pub seat_count: f64,
    pub metadata: GenericJSON,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<TenantUser>>,
}

/// A soft-deletable tenant membership.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TenantUser {
    #[serde(rename = "createdAt")]
    pub created_at: TemporalDateTime,
    #[serde(default, rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<TemporalDateTime>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Tenant>,
    #[serde(default, rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(default, rename = "deletedAt", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<TemporalDateTime>,
    #[serde(default, rename = "deletedBy", skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<IdentityUUID>,
}
