// Code generated by superschematic. DO NOT EDIT.
//
// The module of worker shop-orders-fulfil-orders of stack shop-cloud-stack. It requires each
// generated module, runtime module and implementation module the worker
// builds from, and a replace points each at its directory. superschematic
// writes no go.sum, so build with -mod=mod, which fills it:
//
//	go build -mod=mod .
//
// go mod tidy also resolves the imports of the implementations' tests,
// which this go.mod does not replace.

module example.com/schemas/server/shop-cloud-stack/shop-orders-fulfil-orders

go 1.26.4

require (
	cloud.google.com/go/cloudsqlconn v1.25.3
	example.com/schemas/api/shop-orders v0.0.0-00010101000000-000000000000
	example.com/schemas/implementation/shop-orders v0.0.0-00010101000000-000000000000
	example.com/schemas/orm/shop-db v0.0.0-00010101000000-000000000000
	example.com/schemas/sdk/go/shop-api v0.0.0-00010101000000-000000000000
	github.com/jackc/pgx/v5 v5.11.0
	github.com/parable-work/superschematic/runtime/http/go v0.0.0-00010101000000-000000000000
	go.uber.org/zap v1.28.0
)

require (
	example.com/schemas/types/go/shop-api v0.0.0-00010101000000-000000000000 // indirect
	example.com/schemas/types/go/shop-db v0.0.0-00010101000000-000000000000 // indirect
	example.com/schemas/types/go/shop-orders v0.0.0-00010101000000-000000000000 // indirect
	github.com/parable-work/superscalar/go v1.0.0 // indirect
	github.com/parable-work/superschematic/ir v0.0.0-00010101000000-000000000000 // indirect
	github.com/parable-work/superschematic/runtime/schema/go v0.0.0-00010101000000-000000000000 // indirect
)

replace (
	example.com/schemas/api/shop-orders => ../../../api/shop-orders
	example.com/schemas/implementation/shop-orders => ../../../../../go/shop-orders
	example.com/schemas/orm/shop-db => ../../../orm/shop-db
	example.com/schemas/sdk/go/shop-api => ../../../sdk/go/shop-api
	example.com/schemas/types/go/shop-api => ../../../types/go/shop-api
	example.com/schemas/types/go/shop-db => ../../../types/go/shop-db
	example.com/schemas/types/go/shop-orders => ../../../types/go/shop-orders
	github.com/parable-work/superscalar/go => ../../../../../third_party/superscalar/go
	github.com/parable-work/superschematic/ir => ../../../../../ir
	github.com/parable-work/superschematic/runtime/http/go => ../../../../../runtime/http/go
	github.com/parable-work/superschematic/runtime/schema/go => ../../../../../runtime/schema/go
)
