# Code generated by pygen. DO NOT EDIT.

"""
Enum types for fixture-api schema.

This module defines enumeration types using Python's Enum class.
"""

from enum import Enum
from pydantic_core import core_schema

class TenantListStatus(str, Enum):
    """
    Status filter for listTenants: an enum array query parameter.
    """

    Active = "active"

    Suspended = "suspended"

    @classmethod
    def __get_pydantic_core_schema__(cls, source_type, handler):
        return core_schema.no_info_before_validator_function(
            cls,
            handler(source_type),
        )

    def __str__(self) -> str:
        """Return the string value of the enum."""
        return self.value
