[package]
name = "acme-fixture-version-graph-db-types"
version = "0.1.0"
edition = "2021"
rust-version = "1.99.0"
description = "Generated Rust types for fixture-version-graph-db schema"
license = "UNLICENSED"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
acme-scalars-core = "0.1.0"
serde_json = { version = "1.0" }
acme-schema-runtime = { path = "../../../vendor/acme-schema-runtime" }
acme-versiongraph-engine = { path = "../../../vendor/acme-versiongraph-engine" }
