// Code generated by superschematic ormgen. DO NOT EDIT.

package orm

import (
	"context"
	"fmt"
	"strings"
	"time"

	types "example.com/schemas/types/go/fixture-optimistic-db"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// ShelfRepository provides database operations for Shelf
type ShelfRepository struct {
	db   *Database // Set when using Database directly
	tx   pgx.Tx    // Set when using Transaction
	txDB *Database // Parent database for transaction (enables accessing other repos)
}

// Allowed fields for Shelf (for validation and ordering)
var ShelfAllowedFields = map[string]bool{
	"id":         true,
	"label":      true,
	"created_at": true,
	"created_by": true,
	"updated_at": true,
	"updated_by": true,
	"deleted_at": true,
	"deleted_by": true,
	"_version":   true,
}

// Quoted field names for Shelf (for SQL generation)
var ShelfQuotedFields = map[string]string{
	"id":         `id`,
	"label":      `label`,
	"created_at": `created_at`,
	"created_by": `created_by`,
	"updated_at": `updated_at`,
	"updated_by": `updated_by`,
	"deleted_at": `deleted_at`,
	"deleted_by": `deleted_by`,
	"_version":   `_version`,
}

// buildShelfOrderByClause builds an ORDER BY clause for Shelf
func buildShelfOrderByClause(orderBy []ShelfOrderBy, tableName string) string {
	if len(orderBy) == 0 {
		return ""
	}

	var clauses []string
	for _, order := range orderBy {
		fieldStr := string(order.Field)
		direction := "ASC"
		if order.Desc {
			direction = "DESC"
		}
		// Use pre-computed quoted field name
		quotedField, ok := ShelfQuotedFields[fieldStr]
		if !ok {
			quotedField = fieldStr // Fallback to unquoted if not found
		}
		clauses = append(clauses, fmt.Sprintf("%s.%s %s", tableName, quotedField, direction))
	}

	if len(clauses) == 0 {
		return ""
	}

	return " ORDER BY " + strings.Join(clauses, ", ")
}

func shelfUUIDValue(value any) (types.IdentityUUID, bool) {
	switch v := value.(type) {
	case types.IdentityUUID:
		return v, true
	case *types.IdentityUUID:
		if v == nil {
			var zero types.IdentityUUID
			return zero, false
		}
		return *v, true
	default:
		var zero types.IdentityUUID
		return zero, false
	}
}

func shelfUUIDPtr(value types.IdentityUUID) *types.IdentityUUID {
	return &value
}

// GetOne retrieves a single Shelf by ID
func (r *ShelfRepository) GetOne(ctx context.Context, id types.IdentityUUID, opts *ShelfGetOptions) (*types.Shelf, error) {
	// Determine if we're using partial field selection
	var fieldStrings []string
	usePartialFields := opts != nil && !opts.Fields.IsZero()

	// Build query - if no fields specified, select all in scan order
	var query string
	if usePartialFields {
		// Build selected fields in OrderedMembers order so FK columns match scan order.
		if opts.Fields.Id {
			fieldStrings = append(fieldStrings, "id")
		}
		if opts.Fields.Label {
			fieldStrings = append(fieldStrings, "label")
		}
		if opts.Fields.CreatedAt {
			fieldStrings = append(fieldStrings, "created_at")
		}
		if opts.Fields.CreatedBy {
			fieldStrings = append(fieldStrings, "created_by")
		}
		if opts.Fields.UpdatedAt {
			fieldStrings = append(fieldStrings, "updated_at")
		}
		if opts.Fields.UpdatedBy {
			fieldStrings = append(fieldStrings, "updated_by")
		}
		if opts.Fields.DeletedAt {
			fieldStrings = append(fieldStrings, "deleted_at")
		}
		if opts.Fields.DeletedBy {
			fieldStrings = append(fieldStrings, "deleted_by")
		}
		if opts.Fields.Version {
			fieldStrings = append(fieldStrings, "_version")
		}
		// Validate fields
		if err := validateFields(fieldStrings, ShelfAllowedFields); err != nil {
			return nil, err
		}
		selectFields := buildSelectFieldsTyped(fieldStrings, "shelf")
		query = fmt.Sprintf(`SELECT %s FROM shelf WHERE id = $1`, selectFields)
	} else {
		// Select all fields in explicit order matching scan order (using OrderedMembers for schema order)
		query = `SELECT "id", "label", "created_at", "created_by", "updated_at", "updated_by", "deleted_at", "deleted_by", "_version" FROM shelf WHERE id = $1`
	}
	query += " AND deleted_at IS NULL"

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, id.ToUUID())
	} else {
		row = r.db.pool.QueryRow(ctx, query, id.ToUUID())
	}

	// Scan result - when selecting all fields, scan directly into struct
	result := &types.Shelf{}
	// Create temporary variables for nullable fields that need pointer scanning

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)

	var err error
	if usePartialFields {
		// Dynamic scanning for partial field selection
		// Track whether special fields were selected so we can post-process after Scan.

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "label":
				scanDest[i] = &result.Label
			case "created_at":
				scanDest[i] = &result.CreatedAt
			case "created_by":
				scanDest[i] = &result.CreatedBy
			case "updated_at":
				scanDest[i] = &result.UpdatedAt
			case "updated_by":
				scanDest[i] = &result.UpdatedBy
			case "deleted_at":
				scanDest[i] = &result.DeletedAt
			case "deleted_by":
				scanDest[i] = &result.DeletedBy
			case "_version":
				scanDest[i] = &result.Version
			default:
				return nil, fmt.Errorf("unexpected field %q for Shelf.GetOne", fieldName)
			}
		}

		err = row.Scan(scanDest...)
		if err == nil {
			// Copy nullable fields when present
			var jsonFieldDecodeErr error

			if jsonFieldDecodeErr != nil {
				return nil, jsonFieldDecodeErr
			}
		}
	} else {

		// Scan all fields in schema order (matches DDL column order)
		err = row.Scan(

			&result.Id,

			&result.Label,

			&result.CreatedAt,

			&result.CreatedBy,

			&result.UpdatedAt,

			&result.UpdatedBy,

			&result.DeletedAt,

			&result.DeletedBy,

			&result.Version,
		)

		if err == nil {
			// Copy nullable fields when present

		}
	}

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan row: %w", err)
	}

	// Hydrate relationship foreign keys into nested objects from typed field selections.

	return result, nil
}

// GetManyByIDs retrieves multiple Shelf records by their IDs in a single query
func (r *ShelfRepository) GetManyByIDs(ctx context.Context, ids []types.IdentityUUID) (map[types.IdentityUUID]*types.Shelf, error) {
	if len(ids) == 0 {
		return map[types.IdentityUUID]*types.Shelf{}, nil
	}

	// Dedupe IDs
	seen := make(map[types.IdentityUUID]bool)
	uniqueIDs := make([]types.IdentityUUID, 0, len(ids))
	for _, id := range ids {
		if !seen[id] {
			seen[id] = true
			uniqueIDs = append(uniqueIDs, id)
		}
	}

	// Build WHERE id IN (...) clause
	placeholders := make([]string, len(uniqueIDs))
	args := make([]interface{}, len(uniqueIDs))
	for i, id := range uniqueIDs {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
		args[i] = id.ToUUID()
	}

	// Build query with explicit column order
	query := fmt.Sprintf(`SELECT "id", "label", "created_at", "created_by", "updated_at", "updated_by", "deleted_at", "deleted_by", "_version" FROM shelf WHERE id IN (%s)`, strings.Join(placeholders, ", "))
	query += " AND deleted_at IS NULL"

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, args...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, args...)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to execute query: %w", err)
	}
	defer rows.Close()

	// Scan results into map
	resultMap := make(map[types.IdentityUUID]*types.Shelf, len(uniqueIDs))
	for rows.Next() {
		entity := &types.Shelf{}

		// Create temporary variables for nullable fields that need pointer scanning

		// Create temporary variables for relationship foreign keys (we don't store these in the struct)

		// Scan all fields in schema order (matches DDL column order)
		err := rows.Scan(

			&entity.Id,

			&entity.Label,

			&entity.CreatedAt,

			&entity.CreatedBy,

			&entity.UpdatedAt,

			&entity.UpdatedBy,

			&entity.DeletedAt,

			&entity.DeletedBy,

			&entity.Version,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan row: %w", err)
		}

		// Copy nullable fields when present

		// Set relationship IDs from scanned FK values

		entityID, ok := shelfUUIDValue(entity.Id)
		if !ok {
			continue
		}
		resultMap[entityID] = entity
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating rows: %w", err)
	}

	return resultMap, nil
}

// FindOne retrieves the first Shelf matching the filter
func (r *ShelfRepository) FindOne(ctx context.Context, filter *ShelfFilter, opts *ShelfFindOptions) (*types.Shelf, error) {
	// Determine if we're using partial field selection
	var fieldStrings []string
	var selectFields string
	usePartialFields := opts != nil && !opts.Fields.IsZero()

	if usePartialFields {
		// Build selected fields in OrderedMembers order so FK columns match scan order.
		if opts.Fields.Id {
			fieldStrings = append(fieldStrings, "id")
		}
		if opts.Fields.Label {
			fieldStrings = append(fieldStrings, "label")
		}
		if opts.Fields.CreatedAt {
			fieldStrings = append(fieldStrings, "created_at")
		}
		if opts.Fields.CreatedBy {
			fieldStrings = append(fieldStrings, "created_by")
		}
		if opts.Fields.UpdatedAt {
			fieldStrings = append(fieldStrings, "updated_at")
		}
		if opts.Fields.UpdatedBy {
			fieldStrings = append(fieldStrings, "updated_by")
		}
		if opts.Fields.DeletedAt {
			fieldStrings = append(fieldStrings, "deleted_at")
		}
		if opts.Fields.DeletedBy {
			fieldStrings = append(fieldStrings, "deleted_by")
		}
		if opts.Fields.Version {
			fieldStrings = append(fieldStrings, "_version")
		}
		// Validate fields
		if err := validateFields(fieldStrings, ShelfAllowedFields); err != nil {
			return nil, err
		}
		selectFields = buildSelectFieldsTyped(fieldStrings, "shelf")
	} else {
		// Select all fields in explicit order matching scan order (using OrderedMembers for schema order)
		selectFields = `"id", "label", "created_at", "created_by", "updated_at", "updated_by", "deleted_at", "deleted_by", "_version"`
		if opts == nil {
			opts = &ShelfFindOptions{}
		}
	}

	// Build WHERE clause
	var args []interface{}
	whereClause := filter.buildWhereClause(&args, 0)
	// Apply soft-delete filter unless IncludeDeleted is set
	if !opts.IncludeDeleted {
		if whereClause == "" {
			whereClause = " WHERE deleted_at IS NULL"
		} else {
			whereClause += " AND deleted_at IS NULL"
		}
	}

	// Build ORDER BY clause
	orderByClause := buildShelfOrderByClause(opts.OrderBy, "shelf")

	// Build query
	query := fmt.Sprintf(`SELECT %s FROM shelf%s%s LIMIT 1`, selectFields, whereClause, orderByClause)

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, args...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, args...)
	}

	// Scan result
	result := &types.Shelf{}
	// Create temporary variables for nullable fields that need pointer scanning

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)

	var err error
	if usePartialFields {
		// Dynamic scanning for partial field selection
		// Track whether special fields were selected so we can post-process after Scan.

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "label":
				scanDest[i] = &result.Label
			case "created_at":
				scanDest[i] = &result.CreatedAt
			case "created_by":
				scanDest[i] = &result.CreatedBy
			case "updated_at":
				scanDest[i] = &result.UpdatedAt
			case "updated_by":
				scanDest[i] = &result.UpdatedBy
			case "deleted_at":
				scanDest[i] = &result.DeletedAt
			case "deleted_by":
				scanDest[i] = &result.DeletedBy
			case "_version":
				scanDest[i] = &result.Version
			default:
				return nil, fmt.Errorf("unexpected field %q for Shelf.FindOne", fieldName)
			}
		}

		err = row.Scan(scanDest...)
		if err == nil {
			// Copy nullable fields when present
			var jsonFieldDecodeErr error

			if jsonFieldDecodeErr != nil {
				return nil, jsonFieldDecodeErr
			}

			// Set relationship IDs from scanned FK values
		}
	} else {
		// Scan all fields in schema order (matches DDL column order)
		err = row.Scan(

			&result.Id,

			&result.Label,

			&result.CreatedAt,

			&result.CreatedBy,

			&result.UpdatedAt,

			&result.UpdatedBy,

			&result.DeletedAt,

			&result.DeletedBy,

			&result.Version,
		)

		if err == nil {
			// Copy nullable fields when present

		}
	}

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan row: %w", err)
	}

	// Hydrate relationship foreign keys into nested objects from typed field selections.

	return result, nil
}

// FindMany retrieves multiple Shelf records matching the filter
func (r *ShelfRepository) FindMany(ctx context.Context, filter *ShelfFilter, opts *ShelfFindOptions) ([]*types.Shelf, int, error) {
	if opts == nil || opts.Fields.IsZero() {
		return nil, 0, fmt.Errorf("fields must be specified in FindOptions for performance")
	}

	// Build selected fields in OrderedMembers order so FK columns match scan order.
	var fieldStrings []string
	if opts.Fields.Id {
		fieldStrings = append(fieldStrings, "id")
	}
	if opts.Fields.Label {
		fieldStrings = append(fieldStrings, "label")
	}
	if opts.Fields.CreatedAt {
		fieldStrings = append(fieldStrings, "created_at")
	}
	if opts.Fields.CreatedBy {
		fieldStrings = append(fieldStrings, "created_by")
	}
	if opts.Fields.UpdatedAt {
		fieldStrings = append(fieldStrings, "updated_at")
	}
	if opts.Fields.UpdatedBy {
		fieldStrings = append(fieldStrings, "updated_by")
	}
	if opts.Fields.DeletedAt {
		fieldStrings = append(fieldStrings, "deleted_at")
	}
	if opts.Fields.DeletedBy {
		fieldStrings = append(fieldStrings, "deleted_by")
	}
	if opts.Fields.Version {
		fieldStrings = append(fieldStrings, "_version")
	}

	// Validate fields
	if err := validateFields(fieldStrings, ShelfAllowedFields); err != nil {
		return nil, 0, err
	}

	// Build SELECT clause
	selectFields := buildSelectFieldsTyped(fieldStrings, "shelf")
	if selectFields == "" {
		return nil, 0, fmt.Errorf("no valid fields specified")
	}

	// Build WHERE clause
	var args []interface{}
	whereClause := filter.buildWhereClause(&args, 0)
	// Apply soft-delete filter unless IncludeDeleted is set
	if !opts.IncludeDeleted {
		if whereClause == "" {
			whereClause = " WHERE deleted_at IS NULL"
		} else {
			whereClause += " AND deleted_at IS NULL"
		}
	}

	// Build ORDER BY clause
	orderByClause := buildShelfOrderByClause(opts.OrderBy, "shelf")

	// Build LIMIT/OFFSET clause
	limitOffsetClause := buildLimitOffsetClauseTyped(opts.Limit, opts.Offset)

	// Build query
	query := fmt.Sprintf(`SELECT %s FROM shelf%s%s%s`, selectFields, whereClause, orderByClause, limitOffsetClause)

	// Get total count
	countQuery := fmt.Sprintf(`SELECT COUNT(*) FROM shelf%s`, whereClause)

	var totalCount int
	var countRow pgx.Row
	if r.tx != nil {
		countRow = r.tx.QueryRow(ctx, countQuery, args...)
	} else {
		countRow = r.db.pool.QueryRow(ctx, countQuery, args...)
	}
	if err := countRow.Scan(&totalCount); err != nil {
		return nil, 0, fmt.Errorf("failed to get count: %w", err)
	}

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, args...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, args...)
	}
	if err != nil {
		return nil, 0, fmt.Errorf("failed to execute query: %w", err)
	}
	defer rows.Close()

	// Scan results
	results := []*types.Shelf{}
	for rows.Next() {
		result := &types.Shelf{}

		// Create temporary variables for nullable fields that need pointer scanning (per-row)

		// Create temporary variables for relationship foreign keys (we don't store these directly on the struct)

		// Track whether special fields were selected so we can post-process after Scan.

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "label":
				scanDest[i] = &result.Label
			case "created_at":
				scanDest[i] = &result.CreatedAt
			case "created_by":
				scanDest[i] = &result.CreatedBy
			case "updated_at":
				scanDest[i] = &result.UpdatedAt
			case "updated_by":
				scanDest[i] = &result.UpdatedBy
			case "deleted_at":
				scanDest[i] = &result.DeletedAt
			case "deleted_by":
				scanDest[i] = &result.DeletedBy
			case "_version":
				scanDest[i] = &result.Version
			default:
				return nil, 0, fmt.Errorf("unexpected field %q for Shelf.FindMany", fieldName)
			}
		}

		if err := rows.Scan(scanDest...); err != nil {
			return nil, 0, fmt.Errorf("failed to scan row: %w", err)
		}

		// Copy nullable fields when present
		var jsonFieldDecodeErr error

		if jsonFieldDecodeErr != nil {
			return nil, 0, jsonFieldDecodeErr
		}

		// Set relationship IDs from scanned FK values (hydration happens after loop)

		results = append(results, result)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("error iterating rows: %w", err)
	}

	// Batch hydrate relationships (outside the row loop for efficiency)

	return results, totalCount, nil
}

// CreateOne inserts a new Shelf record
func (r *ShelfRepository) CreateOne(ctx context.Context, input *types.Shelf) (*types.Shelf, error) {
	// Set audit fields
	if !HasUserID(ctx) {
		return nil, ErrNoUserInContext
	}
	input.CreatedBy = GetUserID(ctx)
	input.UpdatedBy = GetUserID(ctx)

	// Build INSERT query
	var fields []string
	var placeholders []string
	var values []interface{}
	paramNum := 0
	// Schema-owned identities may supply a stable UUID. A zero value keeps the
	// database-generated default used by ordinary creates.
	{
		var zeroPrimaryKey types.IdentityUUID
		if primaryKey, ok := shelfUUIDValue(input.Id); ok && primaryKey != zeroPrimaryKey {
			fields = append(fields, `id`)
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, primaryKey.ToUUID())
		}
	}
	// Required field: label
	fields = append(fields, `label`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Label)
	// Required field: createdBy
	fields = append(fields, `created_by`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.CreatedBy.ToUUID())
	// Required field: updatedBy
	fields = append(fields, `updated_by`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.UpdatedBy.ToUUID())
	// Optional field: deletedAt - only add if set
	{
		if input.DeletedAt != nil {
			fields = append(fields, `deleted_at`)
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, time.Time(*input.DeletedAt))
		}
	}
	// Optional field: deletedBy - only add if set
	{
		if input.DeletedBy != nil {
			fields = append(fields, `deleted_by`)
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, input.DeletedBy.ToUUID())
		}
	}

	// Handle relationship foreign key columns

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	returningClause := `"id", "label", "created_at", "created_by", "updated_at", "updated_by", "deleted_at", "deleted_by", "_version"`
	query := fmt.Sprintf(
		`INSERT INTO shelf (%s) VALUES (%s) RETURNING %s`,
		strings.Join(fields, ", "),
		strings.Join(placeholders, ", "),
		returningClause,
	)

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, values...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, values...)
	}

	// Scan result
	result := &types.Shelf{}
	// Create temporary variables for nullable fields that need pointer scanning

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)

	// Scan all fields in schema order (matches DDL column order)
	if err := row.Scan(

		&result.Id,

		&result.Label,

		&result.CreatedAt,

		&result.CreatedBy,

		&result.UpdatedAt,

		&result.UpdatedBy,

		&result.DeletedAt,

		&result.DeletedBy,

		&result.Version,
	); err != nil {
		return nil, fmt.Errorf("failed to scan result: %w", err)
	}

	// Copy nullable fields when present

	// Set relationship IDs from scanned FK values

	return result, nil
}

// CreateMany inserts multiple Shelf records in a single statement
func (r *ShelfRepository) CreateMany(ctx context.Context, inputs []*types.Shelf) ([]*types.Shelf, error) {
	if len(inputs) == 0 {
		return []*types.Shelf{}, nil
	}

	// Set audit fields
	if !HasUserID(ctx) {
		return nil, ErrNoUserInContext
	}
	for _, input := range inputs {
		input.CreatedBy = GetUserID(ctx)
	}
	for _, input := range inputs {
		input.UpdatedBy = GetUserID(ctx)
	}

	// Build batch INSERT query - collect field names from first input
	var fieldNames []string
	// Schema-owned identities may supply stable UUIDs, matching CreateOne. One
	// INSERT has one column set, so a batch must supply ids for every row or
	// none; mixing is refused rather than silently dropping the supplied ids.
	explicitPrimaryKey := false
	{
		var zeroPrimaryKey types.IdentityUUID
		if primaryKey, ok := shelfUUIDValue(inputs[0].Id); ok && primaryKey != zeroPrimaryKey {
			explicitPrimaryKey = true
		}
		for _, input := range inputs {
			primaryKey, ok := shelfUUIDValue(input.Id)
			if (ok && primaryKey != zeroPrimaryKey) != explicitPrimaryKey {
				return nil, fmt.Errorf("inputs mix explicit and default primary keys; a batch must supply ids for every row or none")
			}
		}
	}
	if explicitPrimaryKey {
		fieldNames = append(fieldNames, `id`)
	}
	fieldNames = append(fieldNames, `label`)
	fieldNames = append(fieldNames, `created_by`)
	fieldNames = append(fieldNames, `updated_by`)

	// Add optional/auto-generated fields that are set in first input
	{
		if inputs[0].DeletedAt != nil {
			fieldNames = append(fieldNames, `deleted_at`)
		}
	}
	{
		if inputs[0].DeletedBy != nil {
			fieldNames = append(fieldNames, `deleted_by`)
		}
	}

	// Add relationship foreign key columns present in first input (matches CreateOne's column set)

	var valuePlaceholders []string
	var values []interface{}
	paramNum := 0

	for _, input := range inputs {
		var placeholders []string
		if explicitPrimaryKey {
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			primaryKey, _ := shelfUUIDValue(input.Id)
			values = append(values, primaryKey.ToUUID())
		}
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Label)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.CreatedBy.ToUUID())
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.UpdatedBy.ToUUID())
		{
			if input.DeletedAt != nil {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, time.Time(*input.DeletedAt))
			}
		}
		{
			if input.DeletedBy != nil {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, input.DeletedBy.ToUUID())
			}
		}

		// Handle relationship foreign key columns (per-row, matches CreateOne)
		valuePlaceholders = append(valuePlaceholders, "("+strings.Join(placeholders, ", ")+")")
	}

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	returningClauseMany := `"id", "label", "created_at", "created_by", "updated_at", "updated_by", "deleted_at", "deleted_by", "_version"`
	query := fmt.Sprintf(
		`INSERT INTO shelf (%s) VALUES %s RETURNING %s`,
		strings.Join(fieldNames, ", "),
		strings.Join(valuePlaceholders, ", "),
		returningClauseMany,
	)

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, values...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, values...)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to execute batch insert: %w", err)
	}
	defer rows.Close()

	// Scan results
	results := []*types.Shelf{}
	for rows.Next() {
		result := &types.Shelf{}
		// Create temporary variables for nullable fields that need pointer scanning

		// Create temporary variables for relationship foreign keys (we don't store these in the struct)

		// Scan all fields in schema order (matches DDL column order)
		err := rows.Scan(

			&result.Id,

			&result.Label,

			&result.CreatedAt,

			&result.CreatedBy,

			&result.UpdatedAt,

			&result.UpdatedBy,

			&result.DeletedAt,

			&result.DeletedBy,

			&result.Version,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan result: %w", err)
		}

		// Copy nullable fields when present

		// Set relationship IDs from scanned FK values
		results = append(results, result)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating results: %w", err)
	}

	return results, nil
}

// UpdateOne updates a single Shelf record by ID
func (r *ShelfRepository) UpdateOne(ctx context.Context, id types.IdentityUUID, update *ShelfUpdate) (*types.Shelf, error) {
	return r.updateOne(ctx, id, update, nil)
}

// UpdateOneIfVersion updates a single Shelf only if its current _version matches expectedVersion.
// It returns ErrVersionConflict when the row exists at another version and
// ErrNotFound when it does not exist.
func (r *ShelfRepository) UpdateOneIfVersion(ctx context.Context, id types.IdentityUUID, expectedVersion int64, update *ShelfUpdate) (*types.Shelf, error) {
	return r.updateOne(ctx, id, update, &expectedVersion)
}

// versionMiss tells apart why a write fenced on _version matched no row:
// ErrVersionConflict when the row exists at another version, ErrNotFound when
// it does not exist or is soft-deleted.
func (r *ShelfRepository) versionMiss(ctx context.Context, id types.IdentityUUID) error {
	query := `SELECT _version FROM shelf WHERE id = $1 AND deleted_at IS NULL`

	var version int64
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, id.ToUUID())
	} else {
		row = r.db.pool.QueryRow(ctx, query, id.ToUUID())
	}
	if err := row.Scan(&version); err != nil {
		if err == pgx.ErrNoRows {
			return ErrNotFound
		}
		return fmt.Errorf("failed to read Shelf version: %w", err)
	}
	return ErrVersionConflict
}

func (r *ShelfRepository) updateOne(ctx context.Context, id types.IdentityUUID, update *ShelfUpdate, expectedVersion *int64) (*types.Shelf, error) {
	// Build UPDATE query
	var setClauses []string
	var values []interface{}
	paramNum := 0
	if update.Label != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`label = $%d`, paramNum))
		values = append(values, *update.Label)
	}

	// Set updated_at
	paramNum++
	setClauses = append(setClauses, fmt.Sprintf("updated_at = $%d", paramNum))
	values = append(values, time.Now())

	// Set updated_by
	if update.UpdatedBy != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("updated_by = $%d", paramNum))
		values = append(values, *update.UpdatedBy)
	} else if HasUserID(ctx) {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("updated_by = $%d", paramNum))
		values = append(values, GetUserID(ctx))
	}

	if len(setClauses) == 0 {
		return nil, fmt.Errorf("no fields to update")
	}

	paramNum++
	values = append(values, id.ToUUID())

	query := fmt.Sprintf(
		`UPDATE shelf SET %s WHERE id = $%d`,
		strings.Join(setClauses, ", "),
		paramNum,
	)
	if expectedVersion != nil {
		paramNum++
		values = append(values, *expectedVersion)
		query += fmt.Sprintf(" AND _version = $%d", paramNum)
	}
	query += " AND deleted_at IS NULL"

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	query += ` RETURNING "id", "label", "created_at", "created_by", "updated_at", "updated_by", "deleted_at", "deleted_by", "_version"`

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, values...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, values...)
	}

	// Scan result
	result := &types.Shelf{}
	// Create temporary variables for nullable fields that need pointer scanning

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)

	// Scan all fields in schema order (matches DDL column order)
	if err := row.Scan(

		&result.Id,

		&result.Label,

		&result.CreatedAt,

		&result.CreatedBy,

		&result.UpdatedAt,

		&result.UpdatedBy,

		&result.DeletedAt,

		&result.DeletedBy,

		&result.Version,
	); err != nil {
		if err == pgx.ErrNoRows {
			if expectedVersion != nil {
				return nil, r.versionMiss(ctx, id)
			}
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan result: %w", err)
	}

	// Copy nullable fields when present

	// Set relationship IDs from scanned FK values

	return result, nil
}

// UpdateMany updates multiple Shelf records matching the filter
func (r *ShelfRepository) UpdateMany(ctx context.Context, filter *ShelfFilter, update *ShelfUpdate) (int, error) {
	// Build UPDATE query
	var setClauses []string
	var values []interface{}
	paramNum := 0
	if update.Label != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`label = $%d`, paramNum))
		values = append(values, *update.Label)
	}

	// Set updated_at
	paramNum++
	setClauses = append(setClauses, fmt.Sprintf("updated_at = $%d", paramNum))
	values = append(values, time.Now())

	// Set updated_by
	if update.UpdatedBy != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("updated_by = $%d", paramNum))
		values = append(values, *update.UpdatedBy)
	} else if HasUserID(ctx) {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("updated_by = $%d", paramNum))
		values = append(values, GetUserID(ctx))
	}

	if len(setClauses) == 0 {
		return 0, fmt.Errorf("no fields to update")
	}

	// Build WHERE clause
	whereClause := filter.buildWhereClause(&values, paramNum)
	if whereClause == "" {
		whereClause = " WHERE deleted_at IS NULL"
	} else {
		whereClause += " AND deleted_at IS NULL"
	}

	query := fmt.Sprintf(
		`UPDATE shelf SET %s%s`,
		strings.Join(setClauses, ", "),
		whereClause,
	)

	// Execute query
	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, values...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, values...)
	}
	if err != nil {
		return 0, fmt.Errorf("failed to execute update: %w", err)
	}

	return int(result.RowsAffected()), nil
}

// DeleteOne soft deletes a single Shelf record by ID
func (r *ShelfRepository) DeleteOne(ctx context.Context, id types.IdentityUUID) error {
	if !HasUserID(ctx) {
		return ErrNoUserInContext
	}
	query := `UPDATE shelf SET deleted_at = $1, deleted_by = $2 WHERE id = $3 AND deleted_at IS NULL`
	queryArgs := []interface{}{time.Now(), GetUserID(ctx), id.ToUUID()}

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, queryArgs...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, queryArgs...)
	}
	if err != nil {
		return fmt.Errorf("failed to delete record: %w", err)
	}

	if result.RowsAffected() == 0 {
		return ErrNotFound
	}

	return nil
}

// DeleteOneIfVersion soft deletes a single Shelf only if its current
// _version matches expectedVersion. It returns ErrVersionConflict when the row
// exists at another version and ErrNotFound when it does not exist.
func (r *ShelfRepository) DeleteOneIfVersion(ctx context.Context, id types.IdentityUUID, expectedVersion int64) error {
	if !HasUserID(ctx) {
		return ErrNoUserInContext
	}
	query := `UPDATE shelf SET deleted_at = $1, deleted_by = $2 WHERE id = $3 AND _version = $4 AND deleted_at IS NULL`
	queryArgs := []interface{}{time.Now(), GetUserID(ctx), id.ToUUID(), expectedVersion}

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, queryArgs...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, queryArgs...)
	}
	if err != nil {
		return fmt.Errorf("failed to delete record: %w", err)
	}

	if result.RowsAffected() == 0 {
		return r.versionMiss(ctx, id)
	}

	return nil
}

// DeleteMany soft deletes multiple Shelf records matching the filter
func (r *ShelfRepository) DeleteMany(ctx context.Context, filter *ShelfFilter) (int, error) {
	if !HasUserID(ctx) {
		return 0, ErrNoUserInContext
	}

	// Build WHERE clause
	values := []interface{}{time.Now(), GetUserID(ctx)}
	whereClause := filter.buildWhereClause(&values, 2)

	if whereClause == "" {
		whereClause = " WHERE deleted_at IS NULL"
	} else {
		whereClause += " AND deleted_at IS NULL"
	}
	query := fmt.Sprintf(`UPDATE shelf SET deleted_at = $1, deleted_by = $2%s`, whereClause)

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, values...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, values...)
	}
	if err != nil {
		return 0, fmt.Errorf("failed to delete records: %w", err)
	}

	return int(result.RowsAffected()), nil
}

// HardDeleteOne permanently deletes a single Shelf record by ID
func (r *ShelfRepository) HardDeleteOne(ctx context.Context, id types.IdentityUUID) error {
	query := `DELETE FROM shelf WHERE id = $1`
	queryArgs := []interface{}{id.ToUUID()}

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, queryArgs...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, queryArgs...)
	}
	if err != nil {
		return fmt.Errorf("failed to delete record: %w", err)
	}

	if result.RowsAffected() == 0 {
		return ErrNotFound
	}

	return nil
}
