// Code generated by superschematic apigen. DO NOT EDIT.

package fixtureapi

import (
	"net/http"

	types "example.com/schemas/types/go/fixture-api"
	chimiddleware "github.com/go-chi/chi/v5/middleware"
	"github.com/parable-work/superschematic/runtime/http/go/bodyargs"
	runtimeresponse "github.com/parable-work/superschematic/runtime/http/go/response"
)

// RespondJSON sends a bare JSON response (used for non-enveloped endpoints like health checks).
func RespondJSON(w http.ResponseWriter, status int, data interface{}) {
	runtimeresponse.JSON(w, status, data)
}

// RespondError sends a logged error response with the given status and message.
func RespondError(w http.ResponseWriter, r *http.Request, status int, message string) {
	runtimeresponse.LoggedError(w, r, status, message)
}

// RespondValidationErrors sends a logged validation errors response, with
// the bad_request code every generated server sends for a request its
// validation refuses.
func RespondValidationErrors(w http.ResponseWriter, r *http.Request, errors types.ValidationErrors) {
	runtimeresponse.LoggedValidationErrors(w, r, errors)
}

// RespondInputRefusal sends the logged 400 of a refused input body, the
// problem every generated server sends: its detail, and for a body the
// input type refuses details {location: "body", reason} and the field
// errors in errors.
func RespondInputRefusal(w http.ResponseWriter, r *http.Request, refusal *bodyargs.InputRefusal) {
	runtimeresponse.LoggedInputRefusal(w, r, refusal)
}

// RespondCreated sends a 201 Created response.
func RespondCreated(w http.ResponseWriter, data interface{}) {
	runtimeresponse.Created(w, data)
}

// RespondNoContent sends a 204 No Content response.
func RespondNoContent(w http.ResponseWriter) {
	runtimeresponse.NoContent(w)
}

// RespondJSONEnvelope sends a JSON response wrapped in the success envelope format.
func RespondJSONEnvelope(w http.ResponseWriter, status int, data interface{}, r *http.Request) {
	runtimeresponse.JSONEnvelope(w, status, data, requestMeta(r), nil)
}

// RespondCollectionEnvelope sends a collection JSON response ensuring nil slices serialize as [].
func RespondCollectionEnvelope(w http.ResponseWriter, status int, data interface{}, r *http.Request) {
	runtimeresponse.CollectionEnvelope(w, status, data, requestMeta(r), nil)
}

func requestMeta(r *http.Request) *runtimeresponse.Meta {
	return &runtimeresponse.Meta{
		RequestID: chimiddleware.GetReqID(r.Context()),
	}
}
