// Code generated by superschematic ormgen. DO NOT EDIT.

package orm

import (
	"context"
	"fmt"

	types "example.com/schemas/types/go/fixture-user-model-db"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// contextKey is a custom type for context keys to avoid collisions
type contextKey string

const (
	// userContextKey is the context key for storing user information
	userContextKey contextKey = "orm_user_id"
)

// Database represents the ORM database connection
type Database struct {
	pool           *pgxpool.Pool
	Role           *RoleRepository
	Session        *SessionRepository
	User           *UserRepository
	UserCredential *UserCredentialRepository
	UserRoleGrant  *UserRoleGrantRepository
}

// Tx represents a database transaction with repositories
type Tx struct {
	tx             pgx.Tx
	Role           *RoleRepository
	Session        *SessionRepository
	User           *UserRepository
	UserCredential *UserCredentialRepository
	UserRoleGrant  *UserRoleGrantRepository
}

// Config holds database configuration
type Config struct {
	Host     string
	Port     int
	User     string
	Password string
	Database string
	SSLMode  string
}

// Connect creates a new database connection
func Connect(ctx context.Context, connString string) (*Database, error) {
	pool, err := pgxpool.New(ctx, connString)
	if err != nil {
		return nil, fmt.Errorf("failed to create connection pool: %w", err)
	}

	// Test the connection
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	db := &Database{pool: pool}

	// Initialize repositories
	db.Role = &RoleRepository{db: db}
	db.Session = &SessionRepository{db: db}
	db.User = &UserRepository{db: db}
	db.UserCredential = &UserCredentialRepository{db: db}
	db.UserRoleGrant = &UserRoleGrantRepository{db: db}

	return db, nil
}

// ConnectWithConfig creates a new database connection using Config
func ConnectWithConfig(ctx context.Context, cfg *Config) (*Database, error) {
	connString := fmt.Sprintf(
		"host=%s port=%d user=%s password=%s dbname=%s sslmode=%s",
		cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.Database, cfg.SSLMode,
	)
	return Connect(ctx, connString)
}

// ConnectWithPool creates a Database using an existing pgxpool.Pool.
// Use this when you need custom pool configuration not supported by Connect.
func ConnectWithPool(pool *pgxpool.Pool) (*Database, error) {
	db := &Database{pool: pool}

	// Initialize repositories
	db.Role = &RoleRepository{db: db}
	db.Session = &SessionRepository{db: db}
	db.User = &UserRepository{db: db}
	db.UserCredential = &UserCredentialRepository{db: db}
	db.UserRoleGrant = &UserRoleGrantRepository{db: db}

	return db, nil
}

// Close closes the database connection
func (db *Database) Close() {
	db.pool.Close()
}

// GetRoleRepository returns the Role repository interface.
func (db *Database) GetRoleRepository() RoleRepositoryInterface {
	return db.Role
}

// GetSessionRepository returns the Session repository interface.
func (db *Database) GetSessionRepository() SessionRepositoryInterface {
	return db.Session
}

// GetUserRepository returns the User repository interface.
func (db *Database) GetUserRepository() UserRepositoryInterface {
	return db.User
}

// GetUserCredentialRepository returns the UserCredential repository interface.
func (db *Database) GetUserCredentialRepository() UserCredentialRepositoryInterface {
	return db.UserCredential
}

// GetUserRoleGrantRepository returns the UserRoleGrant repository interface.
func (db *Database) GetUserRoleGrantRepository() UserRoleGrantRepositoryInterface {
	return db.UserRoleGrant
}

// GetRoleRepository returns the Role transaction repository interface.
func (tx *Tx) GetRoleRepository() RoleRepositoryInterface {
	return tx.Role
}

// GetSessionRepository returns the Session transaction repository interface.
func (tx *Tx) GetSessionRepository() SessionRepositoryInterface {
	return tx.Session
}

// GetUserRepository returns the User transaction repository interface.
func (tx *Tx) GetUserRepository() UserRepositoryInterface {
	return tx.User
}

// GetUserCredentialRepository returns the UserCredential transaction repository interface.
func (tx *Tx) GetUserCredentialRepository() UserCredentialRepositoryInterface {
	return tx.UserCredential
}

// GetUserRoleGrantRepository returns the UserRoleGrant transaction repository interface.
func (tx *Tx) GetUserRoleGrantRepository() UserRoleGrantRepositoryInterface {
	return tx.UserRoleGrant
}

// Transaction executes a function within a database transaction
func (db *Database) Transaction(ctx context.Context, fn func(TxInterface) error) error {
	tx, err := db.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}

	txWrapper := &Tx{tx: tx}

	// Initialize transaction repositories with parent database reference
	txWrapper.Role = &RoleRepository{tx: tx, txDB: db}
	txWrapper.Session = &SessionRepository{tx: tx, txDB: db}
	txWrapper.User = &UserRepository{tx: tx, txDB: db}
	txWrapper.UserCredential = &UserCredentialRepository{tx: tx, txDB: db}
	txWrapper.UserRoleGrant = &UserRoleGrantRepository{tx: tx, txDB: db}

	defer func() {
		if p := recover(); p != nil {
			_ = tx.Rollback(ctx)
			panic(p)
		}
	}()

	if err := fn(txWrapper); err != nil {
		if rbErr := tx.Rollback(ctx); rbErr != nil {
			return fmt.Errorf("failed to rollback transaction: %w (original error: %v)", rbErr, err)
		}
		return err
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("failed to commit transaction: %w", err)
	}

	return nil
}

// Exec runs raw SQL within the open transaction. Prefer generated repository
// methods when they exist; use this only for operations the ORM does not
// expose (e.g. clearing soft-delete columns that UpdateOne blocks).
func (tx *Tx) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	return tx.tx.Exec(ctx, sql, arguments...)
}

// Query runs a raw read within the open transaction. Prefer generated
// repository methods when they exist; use this only for reads the ORM does not
// express, such as a keyset-paged join across tables. The caller closes the
// returned rows.
func (tx *Tx) Query(ctx context.Context, sql string, arguments ...any) (pgx.Rows, error) {
	return tx.tx.Query(ctx, sql, arguments...)
}

// WithUserID returns a new context with the user ID set
func WithUserID(ctx context.Context, userID types.IdentityUUID) context.Context {
	return context.WithValue(ctx, userContextKey, userID)
}

// GetUserID retrieves the user ID from context, returns zero value if not set
func GetUserID(ctx context.Context) types.IdentityUUID {
	if userID, ok := ctx.Value(userContextKey).(types.IdentityUUID); ok {
		return userID
	}
	var zero types.IdentityUUID
	return zero
}

// HasUserID checks if a user ID is set in the context
func HasUserID(ctx context.Context) bool {
	_, ok := ctx.Value(userContextKey).(types.IdentityUUID)
	return ok
}

// Ping checks if the database connection is alive
func (db *Database) Ping(ctx context.Context) error {
	return db.pool.Ping(ctx)
}

// Stats returns database connection pool statistics
func (db *Database) Stats() *pgxpool.Stat {
	return db.pool.Stat()
}

// Common errors
var (
	ErrNotFound        = fmt.Errorf("record not found")
	ErrAlreadyDeleted  = fmt.Errorf("record already deleted")
	ErrNoUserInContext = fmt.Errorf("no user ID in context")
)
