// Code generated by superschematic sentinel. DO NOT EDIT.
import { service, SchemaKind } from "@superschematic/schema-config";
export const Notes = service({ name: "notes", kind: SchemaKind.General });
