// Code generated by psgen sentinel. DO NOT EDIT.
import { service, SchemaKind } from "@psgen/schema-config";
export const BrokenRelationOndelete = service({ name: "broken-relation-ondelete", kind: SchemaKind.DB });
