package sqlmigrate

import (
	"testing"

	"github.com/parable-work/superschematic/internal/generator/sqlgen"
	ir "github.com/parable-work/superschematic/ir"
)

// The SQLite plan cases: every plan case whose change SQLite supports,
// planned for SQLite, and the cases that exercise the copy-table rebuild.
// Both versions of a case drop what SQLite refuses from the shop first: the
// projection and the search field (sqliteShop).

// sqliteShop removes from a version of the shop what the SQLite dialect
// refuses: projections and search fields.
func sqliteShop(s *ir.Schema) {
	for name, td := range s.Types {
		if td.Role == ir.RoleProjection {
			delete(s.Types, name)
		}
	}
	for _, td := range s.Types {
		for _, f := range td.Fields {
			f.SearchField = false
		}
	}
}

// andThen runs change, when there is one, then next.
func andThen(change, next func(*ir.Schema)) func(*ir.Schema) {
	return func(s *ir.Schema) {
		if change != nil {
			change(s)
		}
		next(s)
	}
}

// forSQLite is pc planned for SQLite, on the shop without what SQLite
// refuses. The golden is <name>.sqlite.json.
func forSQLite(pc planCase) planCase {
	pc.dialect = SQLite
	pc.before = andThen(pc.before, sqliteShop)
	pc.after = andThen(pc.after, sqliteShop)
	return pc
}

// sqliteOnlyCases exercise what only SQLite plans: the rebuild of a table
// its ALTER TABLE cannot change, and a column ADD COLUMN cannot add.
var sqliteOnlyCases = []planCase{
	// A type change: INTEGER to REAL, cast in the copy.
	{name: "rebuild-retype", after: func(s *ir.Schema) {
		fieldNamed(s, "OrderLine", "quantity").TypeRef = ir.TypeRef{Name: "number"}
	}},
	// A collation change: CITEXT's TEXT COLLATE NOCASE to TEXT, under a
	// unique index.
	{name: "rebuild-collation", after: func(s *ir.Schema) {
		fieldNamed(s, "Label", "name").TypeRef = stringRef
	}},
	// A default set in expand and one dropped in contract.
	{name: "rebuild-set-default", after: func(s *ir.Schema) {
		fieldNamed(s, "Customer", "referrerId").AutoGenerated = true
	}},
	{name: "rebuild-drop-default",
		before: func(s *ir.Schema) { fieldNamed(s, "Customer", "referrerId").AutoGenerated = true }},
	// A NOT NULL column whose default is not a constant: ADD COLUMN cannot
	// add it, and the copy fills each row from the default.
	{name: "rebuild-add-column-volatile-default", after: func(s *ir.Schema) {
		addField(s, "Order", &ir.FieldDef{Name: "shippedAt", TypeRef: ir.TypeRef{Name: "Temporal.DateTime"}, Required: true})
	}},
	// A nullable column with a default that is not a constant.
	{name: "rebuild-add-uuid-column", after: func(s *ir.Schema) {
		addField(s, "OrderLine", &ir.FieldDef{Name: "batch", TypeRef: uuidRef, AutoGenerated: true})
	}},
	// Several changes to one table in each phase: one rebuild per phase,
	// which also adds the column and the index the expand phase adds.
	{name: "rebuild-batched", after: func(s *ir.Schema) {
		fieldNamed(s, "Order", "total").TypeRef = ir.TypeRef{Name: "number"}
		fieldNamed(s, "Order", "placedAt").Required = false
		addField(s, "Order", &ir.FieldDef{Name: "shippedAt", TypeRef: ir.TypeRef{Name: "Temporal.DateTime"}, Required: true})
		addField(s, "Order", &ir.FieldDef{Name: "discount", TypeRef: int64Ref})
		typeNamed(s, "Order").Indexes = append(typeNamed(s, "Order").Indexes, ir.IndexDef{Keys: []string{"reference"}})
		fieldNamed(s, "Order", "note").Required = true
		dropField(s, "Order", "code")
	}},
	// A table that other tables reference, renamed and rebuilt: order
	// references it with ON DELETE RESTRICT, which dropping the old table
	// would refuse with foreign keys on.
	{name: "rebuild-renamed-referenced-table",
		after: func(s *ir.Schema) {
			renameType(s, "Customer", "Buyer")
			fieldNamed(s, "Buyer", "createdAt").Required = false
		},
		renames: []Rename{{From: "customer", To: "buyer"}}},
	// A JSON field becomes text: each value keeps its JSON text, as
	// Postgres's cast keeps it, through a rebuild that casts nothing.
	{name: "rebuild-json-to-text",
		before: func(s *ir.Schema) { addField(s, "Order", &ir.FieldDef{Name: "details", TypeRef: jsonRef(s)}) },
		after:  func(s *ir.Schema) { addField(s, "Order", &ir.FieldDef{Name: "details", TypeRef: stringRef}) }},
	// A foreign key added over a column a table has, and a relation added
	// as a column with its foreign key, in one plan.
	{name: "rebuild-foreign-keys", after: func(s *ir.Schema) {
		fieldNamed(s, "Customer", "referrerId").Relation = &ir.RelationDef{Type: "Customer", OnDelete: "SET NULL"}
		addField(s, "OrderLine", &ir.FieldDef{Name: "product", TypeRef: ir.TypeRef{Name: "Product"}, Relation: &ir.RelationDef{Type: "Product", OnDelete: "SET NULL"}})
	}},

	// A list's element changes: the rebuild converts each element in
	// order, and a NULL list and an empty one stay as they are.
	{name: "list-element-text-to-integer", before: productItems(stringRef), after: productItems(int64Ref),
		lists: lists(
			[2]string{`'["7","-2","1.9","x",""]'`, `'[7,-2,1,0,0]'`},
			[2]string{`'["10","9","8","7","6","5","4","3","2","1","0","11"]'`, `'[10,9,8,7,6,5,4,3,2,1,0,11]'`},
		)},
	{name: "list-element-integer-to-text", before: productItems(int64Ref), after: productItems(stringRef),
		lists: lists([2]string{`'[7,-2,0,9007199254740993]'`, `'["7","-2","0","9007199254740993"]'`})},
	{name: "list-element-integer-to-real", before: productItems(int64Ref), after: productItems(numberRef),
		lists: lists([2]string{`'[7,-2,9007199254740993]'`, `'[7.0,-2.0,9007199254740992.0]'`})},
	// Into a boolean list, as JSON's true and false, and out of one.
	{name: "list-element-integer-to-boolean", before: productItems(int64Ref), after: productItems(booleanRef),
		lists: lists([2]string{`'[1,0,7,-2]'`, `'[true,false,true,true]'`})},
	{name: "list-element-boolean-to-text", before: productItems(booleanRef), after: productItems(stringRef),
		lists: lists([2]string{`'[true,false,true]'`, `'["true","false","true"]'`})},
	// UUIDs and text are both strings in the JSON array: no step.
	{name: "list-element-uuid-to-text", before: productItems(uuidRef), after: productItems(stringRef),
		lists: lists([2]string{`'["0b6a2c1e-5d3f-4a7b-9c8d-1e2f3a4b5c6d"]'`, `'["0b6a2c1e-5d3f-4a7b-9c8d-1e2f3a4b5c6d"]'`})},
	// An element change beside a drop in contract: the model between the
	// phases holds the converted list.
	{name: "list-element-and-drop-column", before: productItems(stringRef),
		after: andThen(productItems(int64Ref), func(s *ir.Schema) { dropField(s, "Product", "price") }),
		lists: lists([2]string{`'["7","x"]'`, `'[7,0]'`})},

	// Rebuilds with foreign keys on (D27, amended). A rebuilt table that
	// tables reference with each ON DELETE action, and a grandchild under a
	// CASCADE: the step copies them all, and every seeded row survives.
	{name: "rebuild-referenced-table", before: addCustomerChildren,
		after: andThen(addCustomerChildren, func(s *ir.Schema) { fieldNamed(s, "Customer", "createdAt").Required = false })},
	// Tables that reference themselves, with rows that reference one
	// another and rows that reference themselves: customer through a
	// RESTRICT key and a NO ACTION key, category through a NOT NULL
	// RESTRICT key. Each rebuild drops the old table with its rows, whose
	// keys SQLite checks at the commit.
	{name: "rebuild-self-referencing-table", before: addSelfReferences,
		after: andThen(addSelfReferences, func(s *ir.Schema) {
			fieldNamed(s, "Customer", "createdAt").Required = false
			fieldNamed(s, "Category", "name").Required = false
		}),
		rows: selfReferences},
	// A rebuilt table whose referencing tables change in the same phase:
	// order is retyped, and order_line gains a column ADD COLUMN could add.
	// One step makes every change.
	{name: "rebuild-with-referencing-changes", after: func(s *ir.Schema) {
		fieldNamed(s, "Customer", "createdAt").Required = false
		fieldNamed(s, "Order", "total").TypeRef = numberRef
		addField(s, "OrderLine", &ir.FieldDef{Name: "note", TypeRef: stringRef})
	}},
	// A table contract drops references a table rebuilt in each phase:
	// expand copies it as it is, and contract's rebuild drops it.
	{name: "rebuild-and-drop-referencing-table",
		before: func(s *ir.Schema) {
			addReviews(s)
			fieldNamed(s, "Customer", "referrerId").AutoGenerated = true
		},
		after: func(s *ir.Schema) { fieldNamed(s, "Customer", "createdAt").Required = false }},
	// Tables that reference each other ON DELETE RESTRICT, one key NOT NULL,
	// and one of them itself too, with rows that do: SQLite checks the keys
	// at the commit, when the step has dropped both tables.
	{name: "drop-tables-in-restrict-cycle", before: addRestrictedSupplierAndWarehouse, rows: supplierWarehouseCycle},
}

// addCustomerChildren adds tables that reference customer, beside order's
// RESTRICT: a review (CASCADE) with its replies (CASCADE), a visit (SET
// NULL) and an invoice (NO ACTION).
func addCustomerChildren(s *ir.Schema) {
	addReviews(s)
	s.Types["ReviewReply"] = &ir.TypeDef{Name: "ReviewReply", Role: ir.RoleDBTable, Fields: []*ir.FieldDef{
		{Name: "id", TypeRef: uuidRef, Required: true, Key: true, AutoGenerated: true},
		{Name: "review", TypeRef: ir.TypeRef{Name: "Review"}, Required: true, Relation: &ir.RelationDef{Type: "Review", OnDelete: "CASCADE"}},
	}}
	s.Types["Visit"] = &ir.TypeDef{Name: "Visit", Role: ir.RoleDBTable, Fields: []*ir.FieldDef{
		{Name: "id", TypeRef: uuidRef, Required: true, Key: true, AutoGenerated: true},
		{Name: "customer", TypeRef: ir.TypeRef{Name: "Customer"}, Relation: &ir.RelationDef{Type: "Customer", OnDelete: "SET NULL"}},
	}}
	s.Types["Invoice"] = &ir.TypeDef{Name: "Invoice", Role: ir.RoleDBTable, Fields: []*ir.FieldDef{
		{Name: "id", TypeRef: uuidRef, Required: true, Key: true, AutoGenerated: true},
		{Name: "customer", TypeRef: ir.TypeRef{Name: "Customer"}, Required: true, Relation: &ir.RelationDef{Type: "Customer", OnDelete: "NO ACTION"}},
	}}
}

// addReviews adds a review of a customer, deleted with it.
func addReviews(s *ir.Schema) {
	s.Types["Review"] = &ir.TypeDef{Name: "Review", Role: ir.RoleDBTable, Fields: []*ir.FieldDef{
		{Name: "id", TypeRef: uuidRef, Required: true, Key: true, AutoGenerated: true},
		{Name: "customer", TypeRef: ir.TypeRef{Name: "Customer"}, Required: true, Relation: &ir.RelationDef{Type: "Customer", OnDelete: "CASCADE"}},
		{Name: "body", TypeRef: stringRef, Required: true},
	}}
}

// addSelfReferences makes a customer's referrer a RESTRICT key and adds a
// mentor, a NO ACTION key, both to customer itself, and adds a category
// whose parent, another category or itself, is a NOT NULL RESTRICT key.
func addSelfReferences(s *ir.Schema) {
	fieldNamed(s, "Customer", "referrerId").Relation = &ir.RelationDef{Type: "Customer", OnDelete: "RESTRICT"}
	addField(s, "Customer", &ir.FieldDef{Name: "mentor", TypeRef: ir.TypeRef{Name: "Customer"}, Relation: &ir.RelationDef{Type: "Customer", OnDelete: "NO ACTION"}})
	s.Types["Category"] = &ir.TypeDef{Name: "Category", Role: ir.RoleDBTable, Fields: []*ir.FieldDef{
		{Name: "id", TypeRef: uuidRef, Required: true, Key: true, AutoGenerated: true},
		{Name: "name", TypeRef: stringRef, Required: true},
		{Name: "parent", TypeRef: ir.TypeRef{Name: "Category"}, Required: true, Relation: &ir.RelationDef{Type: "Category", OnDelete: "RESTRICT"}},
	}}
}

// selfReferences are customers who refer one another in a cycle, one her
// own mentor, and a tree of categories whose root is its own parent.
var selfReferences = extraRows{
	seed: []string{
		`INSERT INTO "customer" ("id", "name", "email", "created_at") VALUES ('c-2', 'two', 'two@example.com', 't')`,
		`INSERT INTO "customer" ("id", "name", "email", "created_at", "referrer_id", "mentor_id") VALUES ('c-3', 'three', 'three@example.com', 't', 'c-2', 'c-3')`,
		`INSERT INTO "customer" ("id", "name", "email", "created_at", "referrer_id", "mentor_id") VALUES ('c-4', 'four', 'four@example.com', 't', 'c-3', 'c-2')`,
		`UPDATE "customer" SET "referrer_id" = 'c-4' WHERE "id" = 'c-2'`,
		`INSERT INTO "category" ("id", "name", "parent_id") VALUES ('k-1', 'root', 'k-1')`,
		`INSERT INTO "category" ("id", "name", "parent_id") VALUES ('k-2', 'branch', 'k-1')`,
		`INSERT INTO "category" ("id", "name", "parent_id") VALUES ('k-3', 'leaf', 'k-2')`,
	},
	checks: []seedCheck{
		{Name: "c-2 keeps its referrer", SQL: `SELECT count(*) = 1 FROM "customer" WHERE "id" = 'c-2' AND "referrer_id" IS 'c-4' AND "mentor_id" IS NULL`},
		{Name: "c-3 keeps its referrer and mentor", SQL: `SELECT count(*) = 1 FROM "customer" WHERE "id" = 'c-3' AND "referrer_id" IS 'c-2' AND "mentor_id" IS 'c-3'`},
		{Name: "c-4 keeps its referrer and mentor", SQL: `SELECT count(*) = 1 FROM "customer" WHERE "id" = 'c-4' AND "referrer_id" IS 'c-3' AND "mentor_id" IS 'c-2'`},
		{Name: "the categories keep their parents", SQL: `SELECT count(*) = 3 FROM "category" WHERE ("id", "parent_id") IN (VALUES ('k-1', 'k-1'), ('k-2', 'k-1'), ('k-3', 'k-2'))`},
	},
}

// addRestrictedSupplierAndWarehouse is addSupplierAndWarehouse with RESTRICT
// keys, a warehouse's supplier required, and a warehouse's backup, another
// warehouse or itself.
func addRestrictedSupplierAndWarehouse(s *ir.Schema) {
	addSupplierAndWarehouse(s)
	fieldNamed(s, "Supplier", "mainWarehouse").Relation.OnDelete = "RESTRICT"
	fieldNamed(s, "Warehouse", "supplier").Relation.OnDelete = "RESTRICT"
	fieldNamed(s, "Warehouse", "supplier").Required = true
	addField(s, "Warehouse", &ir.FieldDef{Name: "backup", TypeRef: ir.TypeRef{Name: "Warehouse"}, Relation: &ir.RelationDef{Type: "Warehouse", OnDelete: "RESTRICT"}})
}

// supplierWarehouseCycle makes the seeded supplier and warehouse reference
// each other, adds a warehouse whose backup is the seeded one, and makes
// that one its own backup.
var supplierWarehouseCycle = extraRows{
	seed: []string{
		`UPDATE "supplier" SET "main_warehouse_id" = (SELECT "id" FROM "warehouse")`,
		`INSERT INTO "warehouse" ("id", "city", "supplier_id", "backup_id") SELECT 'w-2', 'two', "supplier_id", "id" FROM "warehouse"`,
		`UPDATE "warehouse" SET "backup_id" = "id" WHERE "id" <> 'w-2'`,
	},
}

// extraRows are rows a SQLite case seeds after seedRows' one row per table:
// statements, run in order, and checks that hold after the plan.
type extraRows struct {
	seed   []string
	checks []seedCheck
}

var (
	numberRef  = ir.TypeRef{Name: "number"}
	booleanRef = ir.TypeRef{Name: "boolean"}
)

// productItems gives Product an optional list, items, of element ref.
func productItems(ref ir.TypeRef) func(*ir.Schema) {
	return func(s *ir.Schema) {
		ref.IsArray = true
		addField(s, "Product", &ir.FieldDef{Name: "items", TypeRef: ref})
	}
}

// listRows are rows a SQLite case seeds into product besides seedRows' one
// row per table, each a literal of its list in items before the plan and
// the JSON text the list holds after it. A check compares the text, so
// each element's place and JSON type count.
type listRows [][2]string

// lists is the rows given, then an empty list and a NULL one, which every
// plan keeps.
func lists(rows ...[2]string) listRows {
	return append(rows, [2]string{"'[]'", "'[]'"}, [2]string{"NULL", "NULL"})
}

// jsonRef declares a JSON scalar in s, which sqlgen stores as JSONB, and
// returns a reference to it.
func jsonRef(s *ir.Schema) ir.TypeRef {
	s.Scalars["T.JSON"] = &ir.ScalarDef{Name: "T.JSON", LanguagePrimitive: ir.LanguageString, TypeMappings: map[string]string{"sql": "JSONB"}}
	return ir.TypeRef{Name: "T.JSON"}
}

// jsonRef declares a JSON scalar in s, which sqlgen stores as JSONB, and
// returns a reference to it.
func jsonRef(s *ir.Schema) ir.TypeRef {
	s.Scalars["T.JSON"] = &ir.ScalarDef{Name: "T.JSON", LanguagePrimitive: ir.LanguageString, TypeMappings: map[string]string{"sql": "JSONB"}}
	return ir.TypeRef{Name: "T.JSON"}
}

// sqlitePlanCases are the SQLite plan goldens: the plan cases SQLite
// supports, then sqliteOnlyCases.
func sqlitePlanCases() []planCase {
	var cases []planCase
	for _, pc := range planCases {
		if pc.noSQLite == "" {
			cases = append(cases, forSQLite(pc))
		}
	}
	for _, pc := range sqliteOnlyCases {
		cases = append(cases, forSQLite(pc))
	}
	return cases
}

// sqliteTypesSchema has a column of every type the SQLite dialect stores,
// with the defaults sqlgen gives them.
func sqliteTypesSchema() *ir.Schema {
	s := ir.NewSchema("types-db", ir.SchemaKindDB)
	scalar := func(name, sql string) ir.TypeRef {
		s.Scalars[name] = &ir.ScalarDef{Name: name, LanguagePrimitive: ir.LanguageString, TypeMappings: map[string]string{"sql": sql}}
		return ir.TypeRef{Name: name}
	}
	field := func(name string, ref ir.TypeRef, required bool) *ir.FieldDef {
		return &ir.FieldDef{Name: name, TypeRef: ref, Required: required}
	}
	list := func(ref ir.TypeRef) ir.TypeRef {
		ref.IsArray = true
		return ref
	}
	s.Types["Sample"] = &ir.TypeDef{Name: "Sample", Role: ir.RoleDBTable, Fields: []*ir.FieldDef{
		{Name: "id", TypeRef: scalar("T.UUID", "UUID"), Required: true, Key: true, AutoGenerated: true},
		field("text", scalar("T.Text", "TEXT"), true),
		field("short", scalar("T.Short", "VARCHAR(80)"), false),
		field("folded", scalar("T.Folded", "CITEXT"), false),
		field("day", scalar("T.Date", "DATE"), true),
		field("clock", scalar("T.Time", "TIME"), true),
		field("at", scalar("T.Timestamp", "TIMESTAMPTZ"), true),
		field("span", scalar("T.Interval", "INTERVAL"), false),
		field("address", scalar("T.Inet", "INET"), false),
		field("small", scalar("T.Small", "SMALLINT"), false),
		field("count", scalar("T.Count", "BIGINT"), true),
		field("flag", ir.TypeRef{Name: "boolean"}, true),
		field("ratio", ir.TypeRef{Name: "number"}, false),
		field("amount", scalar("T.Money", "NUMERIC(12,2)"), false),
		field("doc", scalar("T.JSON", "JSONB"), false),
		field("tags", list(ir.TypeRef{Name: "string"}), true),
		field("bytes", scalar("T.Bytes", "BYTEA"), false),
		{Name: "stamp", TypeRef: scalar("T.Stamp", "TIMESTAMPTZ"), AutoGenerated: true},
	}}
	return s
}

// sqliteModelFixtures are the services whose SQLite models have goldens,
// by name: the sqlgen fixtures SQLite supports, the shop without what
// SQLite refuses, and sqliteTypesSchema.
func sqliteModelFixtures(t *testing.T) map[string]*ir.Schema {
	t.Helper()
	fixtures := map[string]*ir.Schema{"types-db": sqliteTypesSchema()}
	for _, name := range []string{"fixture-list-defaults-db", "fixture-nested-arrays-db"} {
		fixtures[name] = planCase{base: sqlgenFixtures + "/" + name}.load(t, nil)
	}
	fixtures["shop-db"] = planCase{}.load(t, sqliteShop)
	return fixtures
}

// sqliteModel builds a schema's SQLite model.
func sqliteModel(t *testing.T, name string, schema *ir.Schema) *Model {
	t.Helper()
	model, err := BuildModel(schema, sqlgen.Options{SchemaName: name}, SQLite)
	if err != nil {
		t.Fatalf("%s: %v", name, err)
	}
	return model
}
