package sqlmigrate

import (
	"testing"

	"github.com/parable-work/superschematic/internal/generator/sqlgen"
	ir "github.com/parable-work/superschematic/ir"
)

// The SQLite plan cases: every plan case whose change SQLite supports,
// planned for SQLite, and the cases that exercise the copy-table rebuild.
// Both versions of a case drop what SQLite refuses from the shop first: the
// projection and the search field (sqliteShop).

// sqliteShop removes from a version of the shop what the SQLite dialect
// refuses: projections and search fields.
func sqliteShop(s *ir.Schema) {
	for name, td := range s.Types {
		if td.Role == ir.RoleProjection {
			delete(s.Types, name)
		}
	}
	for _, td := range s.Types {
		for _, f := range td.Fields {
			f.SearchField = false
		}
	}
}

// andThen runs change, when there is one, then next.
func andThen(change, next func(*ir.Schema)) func(*ir.Schema) {
	return func(s *ir.Schema) {
		if change != nil {
			change(s)
		}
		next(s)
	}
}

// forSQLite is pc planned for SQLite, on the shop without what SQLite
// refuses. The golden is <name>.sqlite.json.
func forSQLite(pc planCase) planCase {
	pc.dialect = SQLite
	pc.before = andThen(pc.before, sqliteShop)
	pc.after = andThen(pc.after, sqliteShop)
	return pc
}

// sqliteOnlyCases exercise what only SQLite plans: the rebuild of a table
// its ALTER TABLE cannot change, and a column ADD COLUMN cannot add.
var sqliteOnlyCases = []planCase{
	// A type change: INTEGER to REAL, cast in the copy.
	{name: "rebuild-retype", after: func(s *ir.Schema) {
		fieldNamed(s, "OrderLine", "quantity").TypeRef = ir.TypeRef{Name: "number"}
	}},
	// A collation change: CITEXT's TEXT COLLATE NOCASE to TEXT, under a
	// unique index.
	{name: "rebuild-collation", after: func(s *ir.Schema) {
		fieldNamed(s, "Label", "name").TypeRef = stringRef
	}},
	// A default set in expand and one dropped in contract.
	{name: "rebuild-set-default", after: func(s *ir.Schema) {
		fieldNamed(s, "Customer", "referrerId").AutoGenerated = true
	}},
	{name: "rebuild-drop-default",
		before: func(s *ir.Schema) { fieldNamed(s, "Customer", "referrerId").AutoGenerated = true }},
	// A NOT NULL column whose default is not a constant: ADD COLUMN cannot
	// add it, and the copy fills each row from the default.
	{name: "rebuild-add-column-volatile-default", after: func(s *ir.Schema) {
		addField(s, "Order", &ir.FieldDef{Name: "shippedAt", TypeRef: ir.TypeRef{Name: "Temporal.DateTime"}, Required: true})
	}},
	// A nullable column with a default that is not a constant.
	{name: "rebuild-add-uuid-column", after: func(s *ir.Schema) {
		addField(s, "OrderLine", &ir.FieldDef{Name: "batch", TypeRef: uuidRef, AutoGenerated: true})
	}},
	// Several changes to one table in each phase: one rebuild per phase,
	// which also adds the column and the index the expand phase adds.
	{name: "rebuild-batched", after: func(s *ir.Schema) {
		fieldNamed(s, "Order", "total").TypeRef = ir.TypeRef{Name: "number"}
		fieldNamed(s, "Order", "placedAt").Required = false
		addField(s, "Order", &ir.FieldDef{Name: "shippedAt", TypeRef: ir.TypeRef{Name: "Temporal.DateTime"}, Required: true})
		addField(s, "Order", &ir.FieldDef{Name: "discount", TypeRef: int64Ref})
		typeNamed(s, "Order").Indexes = append(typeNamed(s, "Order").Indexes, ir.IndexDef{Keys: []string{"reference"}})
		fieldNamed(s, "Order", "note").Required = true
		dropField(s, "Order", "code")
	}},
	// A table that other tables reference, renamed and rebuilt: order
	// references it with ON DELETE RESTRICT, which dropping the old table
	// would refuse with foreign keys on.
	{name: "rebuild-renamed-referenced-table",
		after: func(s *ir.Schema) {
			renameType(s, "Customer", "Buyer")
			fieldNamed(s, "Buyer", "createdAt").Required = false
		},
		renames: []Rename{{From: "customer", To: "buyer"}}},
	// A JSON field becomes text: each value keeps its JSON text, as
	// Postgres's cast keeps it, through a rebuild that casts nothing.
	{name: "rebuild-json-to-text",
		before: func(s *ir.Schema) { addField(s, "Order", &ir.FieldDef{Name: "details", TypeRef: jsonRef(s)}) },
		after:  func(s *ir.Schema) { addField(s, "Order", &ir.FieldDef{Name: "details", TypeRef: stringRef}) }},
	// A foreign key added over a column a table has, and a relation added
	// as a column with its foreign key, in one plan.
	{name: "rebuild-foreign-keys", after: func(s *ir.Schema) {
		fieldNamed(s, "Customer", "referrerId").Relation = &ir.RelationDef{Type: "Customer", OnDelete: "SET NULL"}
		addField(s, "OrderLine", &ir.FieldDef{Name: "product", TypeRef: ir.TypeRef{Name: "Product"}, Relation: &ir.RelationDef{Type: "Product", OnDelete: "SET NULL"}})
	}},
}

// jsonRef declares a JSON scalar in s, which sqlgen stores as JSONB, and
// returns a reference to it.
func jsonRef(s *ir.Schema) ir.TypeRef {
	s.Scalars["T.JSON"] = &ir.ScalarDef{Name: "T.JSON", LanguagePrimitive: ir.LanguageString, TypeMappings: map[string]string{"sql": "JSONB"}}
	return ir.TypeRef{Name: "T.JSON"}
}

// sqlitePlanCases are the SQLite plan goldens: the plan cases SQLite
// supports, then sqliteOnlyCases.
func sqlitePlanCases() []planCase {
	var cases []planCase
	for _, pc := range planCases {
		if pc.noSQLite == "" {
			cases = append(cases, forSQLite(pc))
		}
	}
	for _, pc := range sqliteOnlyCases {
		cases = append(cases, forSQLite(pc))
	}
	return cases
}

// sqliteTypesSchema has a column of every type the SQLite dialect stores,
// with the defaults sqlgen gives them.
func sqliteTypesSchema() *ir.Schema {
	s := ir.NewSchema("types-db", ir.SchemaKindDB)
	scalar := func(name, sql string) ir.TypeRef {
		s.Scalars[name] = &ir.ScalarDef{Name: name, LanguagePrimitive: ir.LanguageString, TypeMappings: map[string]string{"sql": sql}}
		return ir.TypeRef{Name: name}
	}
	field := func(name string, ref ir.TypeRef, required bool) *ir.FieldDef {
		return &ir.FieldDef{Name: name, TypeRef: ref, Required: required}
	}
	list := func(ref ir.TypeRef) ir.TypeRef {
		ref.IsArray = true
		return ref
	}
	s.Types["Sample"] = &ir.TypeDef{Name: "Sample", Role: ir.RoleDBTable, Fields: []*ir.FieldDef{
		{Name: "id", TypeRef: scalar("T.UUID", "UUID"), Required: true, Key: true, AutoGenerated: true},
		field("text", scalar("T.Text", "TEXT"), true),
		field("short", scalar("T.Short", "VARCHAR(80)"), false),
		field("folded", scalar("T.Folded", "CITEXT"), false),
		field("day", scalar("T.Date", "DATE"), true),
		field("clock", scalar("T.Time", "TIME"), true),
		field("at", scalar("T.Timestamp", "TIMESTAMPTZ"), true),
		field("span", scalar("T.Interval", "INTERVAL"), false),
		field("address", scalar("T.Inet", "INET"), false),
		field("small", scalar("T.Small", "SMALLINT"), false),
		field("count", scalar("T.Count", "BIGINT"), true),
		field("flag", ir.TypeRef{Name: "boolean"}, true),
		field("ratio", ir.TypeRef{Name: "number"}, false),
		field("amount", scalar("T.Money", "NUMERIC(12,2)"), false),
		field("doc", scalar("T.JSON", "JSONB"), false),
		field("tags", list(ir.TypeRef{Name: "string"}), true),
		field("bytes", scalar("T.Bytes", "BYTEA"), false),
		{Name: "stamp", TypeRef: scalar("T.Stamp", "TIMESTAMPTZ"), AutoGenerated: true},
	}}
	return s
}

// sqliteModelFixtures are the services whose SQLite models have goldens,
// by name: the sqlgen fixtures SQLite supports, the shop without what
// SQLite refuses, and sqliteTypesSchema.
func sqliteModelFixtures(t *testing.T) map[string]*ir.Schema {
	t.Helper()
	fixtures := map[string]*ir.Schema{"types-db": sqliteTypesSchema()}
	for _, name := range []string{"fixture-list-defaults-db", "fixture-nested-arrays-db"} {
		fixtures[name] = planCase{base: sqlgenFixtures + "/" + name}.load(t, nil)
	}
	fixtures["shop-db"] = planCase{}.load(t, sqliteShop)
	return fixtures
}

// sqliteModel builds a schema's SQLite model.
func sqliteModel(t *testing.T, name string, schema *ir.Schema) *Model {
	t.Helper()
	model, err := BuildModel(schema, sqlgen.Options{SchemaName: name}, SQLite)
	if err != nil {
		t.Fatalf("%s: %v", name, err)
	}
	return model
}
