// Code generated by superschematic typegen. DO NOT EDIT.

package types

import scalars "github.com/parable-work/superscalar/go"

// =============================================================================
// Scalar Type Aliases
// =============================================================================
// All scalar types are aliases to the scalar library.
// This enables zero-cast interoperability between different type libraries.

// Network.Url - Valid HTTP/HTTPS URL
type NetworkUrl = scalars.NetworkUrl

// NetworkUrlPattern is the validation pattern for Network.Url.
var NetworkUrlPattern = scalars.NetworkUrlPattern

// ParseNetworkUrl parses a string and returns a Network.Url scalar.
func ParseNetworkUrl(s string) (NetworkUrl, error) {
	parsed, err := scalars.ParseNetworkUrl(s)
	if err != nil {
		var zero NetworkUrl
		return zero, err
	}
	return NetworkUrl(parsed), nil
}

// =============================================================================
// ValidationErrors Aliases
// =============================================================================

// ValidationError represents a single validation error.
type ValidationError = scalars.ValidationError

// ValidationErrors represents validation errors for fields.
type ValidationErrors = scalars.ValidationErrors

// NewValidationErrors creates a new ValidationErrors instance.
var NewValidationErrors = scalars.NewValidationErrors

// NewUUID generates a new random UUID scalar.
var NewUUID = scalars.NewUUID
