// Code generated by superschematic sentinel. DO NOT EDIT.
import { service, SchemaKind } from "@superschematic/schema-config";
export const Tickets = service({ name: "tickets", kind: SchemaKind.General });
