// Code generated by superschematic ormgen. DO NOT EDIT.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"

	types "example.com/schemas/types/go/fixture-version-graph-db"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// RecipeCommitRepository provides database operations for RecipeCommit
type RecipeCommitRepository struct {
	db   *Database // Set when using Database directly
	tx   pgx.Tx    // Set when using Transaction
	txDB *Database // Parent database for transaction (enables accessing other repos)
}

// Allowed fields for RecipeCommit (for validation and ordering)
var RecipeCommitAllowedFields = map[string]bool{
	"id":               true,
	"message":          true,
	"schema_epoch":     true,
	"content_hash":     true,
	"sequence":         true,
	"created_at":       true,
	"created_by":       true,
	"root_id":          true,
	"ref_id":           true,
	"parent_commit_id": true,
}

// Quoted field names for RecipeCommit (for SQL generation)
var RecipeCommitQuotedFields = map[string]string{
	"id":               `id`,
	"message":          `message`,
	"schema_epoch":     `schema_epoch`,
	"content_hash":     `content_hash`,
	"sequence":         `"sequence"`,
	"created_at":       `created_at`,
	"created_by":       `created_by`,
	"root_id":          `root_id`,
	"ref_id":           `ref_id`,
	"parent_commit_id": `parent_commit_id`,
}

// buildRecipeCommitOrderByClause builds an ORDER BY clause for RecipeCommit
func buildRecipeCommitOrderByClause(orderBy []RecipeCommitOrderBy, tableName string) string {
	if len(orderBy) == 0 {
		return ""
	}

	var clauses []string
	for _, order := range orderBy {
		fieldStr := string(order.Field)
		direction := "ASC"
		if order.Desc {
			direction = "DESC"
		}
		// Use pre-computed quoted field name
		quotedField, ok := RecipeCommitQuotedFields[fieldStr]
		if !ok {
			quotedField = fieldStr // Fallback to unquoted if not found
		}
		clauses = append(clauses, fmt.Sprintf("%s.%s %s", tableName, quotedField, direction))
	}

	if len(clauses) == 0 {
		return ""
	}

	return " ORDER BY " + strings.Join(clauses, ", ")
}

func recipeCommitUUIDValue(value any) (types.IdentityUUID, bool) {
	switch v := value.(type) {
	case types.IdentityUUID:
		return v, true
	case *types.IdentityUUID:
		if v == nil {
			var zero types.IdentityUUID
			return zero, false
		}
		return *v, true
	default:
		var zero types.IdentityUUID
		return zero, false
	}
}

func recipeCommitUUIDPtr(value types.IdentityUUID) *types.IdentityUUID {
	return &value
}

// batchRootByIDs fetches multiple Recipe records by their IDs using a single query.
//
// This is the recursion point: the FindMany below hydrates Recipe's own
// relations, which lands back here for each of them. enterRelationHydration is
// what bounds that -- see the guard's contract in utils.go. defaultSelection
// says whether the caller named a nested selection or fell back to
// RecipeFields{}.All(); only the fallback is pruned.
//
// A refusal returns no rows rather than an error, because the caller's miss
// path already writes the id-only stub that a refused expansion should produce.
func (r *RecipeCommitRepository) batchRootByIDs(ctx context.Context, ids []types.IdentityUUID, opts *RecipeFindOptions, defaultSelection bool) (map[types.IdentityUUID]*types.Recipe, error) {
	if len(ids) == 0 {
		return map[types.IdentityUUID]*types.Recipe{}, nil
	}

	ctx, allowed := enterRelationHydration(ctx, "RecipeCommit", "root", "Recipe", defaultSelection)
	if !allowed {
		return map[types.IdentityUUID]*types.Recipe{}, nil
	}

	// Get repository for related type
	var repo *RecipeRepository
	if r.tx != nil {
		txDB := r.txDB
		if txDB == nil {
			txDB = r.db
		}
		repo = &RecipeRepository{tx: r.tx, txDB: txDB}
	} else if r.db != nil {
		repo = r.db.Recipe
	} else if r.txDB != nil {
		repo = r.txDB.Recipe
	} else {
		return nil, fmt.Errorf("no database connection available for batch fetch")
	}

	findOpts := opts
	if findOpts == nil || findOpts.Fields.IsZero() {
		findOpts = &RecipeFindOptions{
			Fields: (RecipeFields{}).All(),
		}
	} else {
		optsCopy := *findOpts
		findOpts = &optsCopy
	}

	if findOpts.Limit <= 0 || findOpts.Limit < len(ids) {
		findOpts.Limit = len(ids)
	}

	relatedRecords, _, err := repo.FindMany(
		ctx,
		&RecipeFilter{
			Id: &UUIDFilter{
				In: ids,
			},
		},
		findOpts,
	)
	if err != nil {
		return nil, err
	}

	relatedByID := make(map[types.IdentityUUID]*types.Recipe, len(relatedRecords))
	for _, related := range relatedRecords {
		if related == nil {
			continue
		}
		relatedID, ok := recipeCommitUUIDValue(related.Id)
		if !ok {
			continue
		}
		relatedByID[relatedID] = related
	}

	return relatedByID, nil
}

// batchRefByIDs fetches multiple RecipeRef records by their IDs using a single query.
//
// This is the recursion point: the FindMany below hydrates RecipeRef's own
// relations, which lands back here for each of them. enterRelationHydration is
// what bounds that -- see the guard's contract in utils.go. defaultSelection
// says whether the caller named a nested selection or fell back to
// RecipeRefFields{}.All(); only the fallback is pruned.
//
// A refusal returns no rows rather than an error, because the caller's miss
// path already writes the id-only stub that a refused expansion should produce.
func (r *RecipeCommitRepository) batchRefByIDs(ctx context.Context, ids []types.IdentityUUID, opts *RecipeRefFindOptions, defaultSelection bool) (map[types.IdentityUUID]*types.RecipeRef, error) {
	if len(ids) == 0 {
		return map[types.IdentityUUID]*types.RecipeRef{}, nil
	}

	ctx, allowed := enterRelationHydration(ctx, "RecipeCommit", "ref", "RecipeRef", defaultSelection)
	if !allowed {
		return map[types.IdentityUUID]*types.RecipeRef{}, nil
	}

	// Get repository for related type
	var repo *RecipeRefRepository
	if r.tx != nil {
		txDB := r.txDB
		if txDB == nil {
			txDB = r.db
		}
		repo = &RecipeRefRepository{tx: r.tx, txDB: txDB}
	} else if r.db != nil {
		repo = r.db.RecipeRef
	} else if r.txDB != nil {
		repo = r.txDB.RecipeRef
	} else {
		return nil, fmt.Errorf("no database connection available for batch fetch")
	}

	findOpts := opts
	if findOpts == nil || findOpts.Fields.IsZero() {
		findOpts = &RecipeRefFindOptions{
			Fields: (RecipeRefFields{}).All(),
		}
	} else {
		optsCopy := *findOpts
		findOpts = &optsCopy
	}

	if findOpts.Limit <= 0 || findOpts.Limit < len(ids) {
		findOpts.Limit = len(ids)
	}

	relatedRecords, _, err := repo.FindMany(
		ctx,
		&RecipeRefFilter{
			Id: &UUIDFilter{
				In: ids,
			},
		},
		findOpts,
	)
	if err != nil {
		return nil, err
	}

	relatedByID := make(map[types.IdentityUUID]*types.RecipeRef, len(relatedRecords))
	for _, related := range relatedRecords {
		if related == nil {
			continue
		}
		relatedID, ok := recipeCommitUUIDValue(related.Id)
		if !ok {
			continue
		}
		relatedByID[relatedID] = related
	}

	return relatedByID, nil
}

// batchParentCommitByIDs fetches multiple RecipeCommit records by their IDs using a single query.
//
// This is the recursion point: the FindMany below hydrates RecipeCommit's own
// relations, which lands back here for each of them. enterRelationHydration is
// what bounds that -- see the guard's contract in utils.go. defaultSelection
// says whether the caller named a nested selection or fell back to
// RecipeCommitFields{}.All(); only the fallback is pruned.
//
// A refusal returns no rows rather than an error, because the caller's miss
// path already writes the id-only stub that a refused expansion should produce.
func (r *RecipeCommitRepository) batchParentCommitByIDs(ctx context.Context, ids []types.IdentityUUID, opts *RecipeCommitFindOptions, defaultSelection bool) (map[types.IdentityUUID]*types.RecipeCommit, error) {
	if len(ids) == 0 {
		return map[types.IdentityUUID]*types.RecipeCommit{}, nil
	}

	ctx, allowed := enterRelationHydration(ctx, "RecipeCommit", "parentCommit", "RecipeCommit", defaultSelection)
	if !allowed {
		return map[types.IdentityUUID]*types.RecipeCommit{}, nil
	}

	// Get repository for related type
	var repo *RecipeCommitRepository
	if r.tx != nil {
		txDB := r.txDB
		if txDB == nil {
			txDB = r.db
		}
		repo = &RecipeCommitRepository{tx: r.tx, txDB: txDB}
	} else if r.db != nil {
		repo = r.db.RecipeCommit
	} else if r.txDB != nil {
		repo = r.txDB.RecipeCommit
	} else {
		return nil, fmt.Errorf("no database connection available for batch fetch")
	}

	findOpts := opts
	if findOpts == nil || findOpts.Fields.IsZero() {
		findOpts = &RecipeCommitFindOptions{
			Fields: (RecipeCommitFields{}).All(),
		}
	} else {
		optsCopy := *findOpts
		findOpts = &optsCopy
	}

	if findOpts.Limit <= 0 || findOpts.Limit < len(ids) {
		findOpts.Limit = len(ids)
	}

	relatedRecords, _, err := repo.FindMany(
		ctx,
		&RecipeCommitFilter{
			Id: &UUIDFilter{
				In: ids,
			},
		},
		findOpts,
	)
	if err != nil {
		return nil, err
	}

	relatedByID := make(map[types.IdentityUUID]*types.RecipeCommit, len(relatedRecords))
	for _, related := range relatedRecords {
		if related == nil {
			continue
		}
		relatedID, ok := recipeCommitUUIDValue(related.Id)
		if !ok {
			continue
		}
		relatedByID[relatedID] = related
	}

	return relatedByID, nil
}

// GetOne retrieves a single RecipeCommit by ID
func (r *RecipeCommitRepository) GetOne(ctx context.Context, id types.IdentityUUID, opts *RecipeCommitGetOptions) (*types.RecipeCommit, error) {
	// Determine if we're using partial field selection
	var fieldStrings []string
	usePartialFields := opts != nil && !opts.Fields.IsZero()

	// Build query - if no fields specified, select all in scan order
	var query string
	if usePartialFields {
		// Build selected fields in OrderedMembers order so FK columns match scan order.
		if opts.Fields.Id {
			fieldStrings = append(fieldStrings, "id")
		}
		if opts.Fields.Root || !opts.Fields.RootNested.IsZero() {
			fieldStrings = append(fieldStrings, "root_id")
		}
		if opts.Fields.Ref || (opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero()) {
			fieldStrings = append(fieldStrings, "ref_id")
		}
		if opts.Fields.ParentCommit || (opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero()) {
			fieldStrings = append(fieldStrings, "parent_commit_id")
		}
		if opts.Fields.Message {
			fieldStrings = append(fieldStrings, "message")
		}
		if opts.Fields.SchemaEpoch {
			fieldStrings = append(fieldStrings, "schema_epoch")
		}
		if opts.Fields.ContentHash {
			fieldStrings = append(fieldStrings, "content_hash")
		}
		if opts.Fields.Sequence {
			fieldStrings = append(fieldStrings, "sequence")
		}
		if opts.Fields.CreatedAt {
			fieldStrings = append(fieldStrings, "created_at")
		}
		if opts.Fields.CreatedBy {
			fieldStrings = append(fieldStrings, "created_by")
		}
		// Validate fields
		if err := validateFields(fieldStrings, RecipeCommitAllowedFields); err != nil {
			return nil, err
		}
		selectFields := buildSelectFieldsTyped(fieldStrings, "recipe_commit")
		query = fmt.Sprintf(`SELECT %s FROM recipe_commit WHERE id = $1`, selectFields)
	} else {
		// Select all fields in explicit order matching scan order (using OrderedMembers for schema order)
		query = `SELECT "id", "root_id", "ref_id", "parent_commit_id", "message", "schema_epoch", "content_hash", "sequence", "created_at", "created_by" FROM recipe_commit WHERE id = $1`
	}

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, id.ToUUID())
	} else {
		row = r.db.pool.QueryRow(ctx, query, id.ToUUID())
	}

	// Scan result - when selecting all fields, scan directly into struct
	result := &types.RecipeCommit{}
	// Create temporary variables for nullable fields that need pointer scanning

	var tempMessage sql.NullString
	var tempSequence *types.GenericInt64

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)
	var tempRelRoot *types.IdentityUUID
	var tempRelRef *types.IdentityUUID
	var tempRelParentCommit *types.IdentityUUID
	var selectedRelRoot bool
	var selectedRelRef bool
	var selectedRelParentCommit bool

	var err error
	if usePartialFields {
		// Dynamic scanning for partial field selection
		// Track whether special fields were selected so we can post-process after Scan.

		var selectedMessage bool
		var selectedSequence bool

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "message":
				scanDest[i] = &tempMessage
				selectedMessage = true
			case "schema_epoch":
				scanDest[i] = &result.SchemaEpoch
			case "content_hash":
				scanDest[i] = &result.ContentHash
			case "sequence":
				scanDest[i] = &tempSequence
				selectedSequence = true
			case "created_at":
				scanDest[i] = &result.CreatedAt
			case "created_by":
				scanDest[i] = &result.CreatedBy
			case "root_id":
				scanDest[i] = &tempRelRoot
				selectedRelRoot = true
			case "ref_id":
				scanDest[i] = &tempRelRef
				selectedRelRef = true
			case "parent_commit_id":
				scanDest[i] = &tempRelParentCommit
				selectedRelParentCommit = true
			default:
				return nil, fmt.Errorf("unexpected field %q for RecipeCommit.GetOne", fieldName)
			}
		}

		err = row.Scan(scanDest...)
		if err == nil {
			// Copy nullable fields when present
			var jsonFieldDecodeErr error

			if selectedMessage && tempMessage.Valid {
				result.Message = tempMessage.String
			}
			if selectedSequence && tempSequence != nil {
				// Value type (primitive): dereference pointer temp to value
				result.Sequence = *tempSequence
			}
			if jsonFieldDecodeErr != nil {
				return nil, jsonFieldDecodeErr
			}
		}
	} else {
		selectedRelRoot = true
		selectedRelRef = true
		selectedRelParentCommit = true

		// Scan all fields in schema order (matches DDL column order)
		err = row.Scan(

			&result.Id,

			&tempRelRoot,

			&tempRelRef,

			&tempRelParentCommit,

			&tempMessage,

			&result.SchemaEpoch,

			&result.ContentHash,

			&tempSequence,

			&result.CreatedAt,

			&result.CreatedBy,
		)

		if err == nil {
			// Copy nullable fields when present

			if tempMessage.Valid {
				result.Message = tempMessage.String
			}
			if tempSequence != nil {
				// Value type (primitive): dereference pointer temp to value
				result.Sequence = *tempSequence
			}
		}
	}

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan row: %w", err)
	}

	// Hydrate relationship foreign keys into nested objects from typed field selections.
	if selectedRelRoot && tempRelRoot != nil {
		relRequested := opts != nil && (opts.Fields.Root || !opts.Fields.RootNested.IsZero())
		if relRequested {
			childFields := (RecipeFields{}).All()
			childFieldsAreDefault := true
			if !opts.Fields.RootNested.IsZero() {
				childFields = opts.Fields.RootNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchRootByIDs(ctx, []types.IdentityUUID{*tempRelRoot}, &RecipeFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch root: %w", err)
			}
			if rel, ok := relMap[*tempRelRoot]; ok {
				result.Root = *rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
			}
		} else {
			// Just set the ID when not including full entity
			result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
		}
	}
	if selectedRelRef && tempRelRef != nil {
		relRequested := opts != nil && (opts.Fields.Ref || (opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero()))
		if relRequested {
			childFields := (RecipeRefFields{}).All()
			childFieldsAreDefault := true
			if opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero() {
				childFields = *opts.Fields.RefNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchRefByIDs(ctx, []types.IdentityUUID{*tempRelRef}, &RecipeRefFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch ref: %w", err)
			}
			if rel, ok := relMap[*tempRelRef]; ok {
				result.Ref = *rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
			}
		} else {
			// Just set the ID when not including full entity
			result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
		}
	}
	if selectedRelParentCommit && tempRelParentCommit != nil {
		relRequested := opts != nil && (opts.Fields.ParentCommit || (opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero()))
		if relRequested {
			childFields := (RecipeCommitFields{}).All()
			childFieldsAreDefault := true
			if opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero() {
				childFields = *opts.Fields.ParentCommitNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchParentCommitByIDs(ctx, []types.IdentityUUID{*tempRelParentCommit}, &RecipeCommitFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch parentCommit: %w", err)
			}
			if rel, ok := relMap[*tempRelParentCommit]; ok {
				result.ParentCommit = rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
			}
		} else {
			// Just set the ID when not including full entity
			// Initialize pointer for optional relationship before setting ID
			result.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
		}
	}

	return result, nil
}

// GetManyByIDs retrieves multiple RecipeCommit records by their IDs in a single query
func (r *RecipeCommitRepository) GetManyByIDs(ctx context.Context, ids []types.IdentityUUID) (map[types.IdentityUUID]*types.RecipeCommit, error) {
	if len(ids) == 0 {
		return map[types.IdentityUUID]*types.RecipeCommit{}, nil
	}

	// Dedupe IDs
	seen := make(map[types.IdentityUUID]bool)
	uniqueIDs := make([]types.IdentityUUID, 0, len(ids))
	for _, id := range ids {
		if !seen[id] {
			seen[id] = true
			uniqueIDs = append(uniqueIDs, id)
		}
	}

	// Build WHERE id IN (...) clause
	placeholders := make([]string, len(uniqueIDs))
	args := make([]interface{}, len(uniqueIDs))
	for i, id := range uniqueIDs {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
		args[i] = id.ToUUID()
	}

	// Build query with explicit column order
	query := fmt.Sprintf(`SELECT "id", "root_id", "ref_id", "parent_commit_id", "message", "schema_epoch", "content_hash", "sequence", "created_at", "created_by" FROM recipe_commit WHERE id IN (%s)`, strings.Join(placeholders, ", "))

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, args...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, args...)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to execute query: %w", err)
	}
	defer rows.Close()

	// Scan results into map
	resultMap := make(map[types.IdentityUUID]*types.RecipeCommit, len(uniqueIDs))
	for rows.Next() {
		entity := &types.RecipeCommit{}

		// Create temporary variables for nullable fields that need pointer scanning

		var tempMessage sql.NullString
		var tempSequence *types.GenericInt64

		// Create temporary variables for relationship foreign keys (we don't store these in the struct)
		var tempRelRoot *types.IdentityUUID
		var tempRelRef *types.IdentityUUID
		var tempRelParentCommit *types.IdentityUUID

		// Scan all fields in schema order (matches DDL column order)
		err := rows.Scan(

			&entity.Id,

			&tempRelRoot,

			&tempRelRef,

			&tempRelParentCommit,

			&tempMessage,

			&entity.SchemaEpoch,

			&entity.ContentHash,

			&tempSequence,

			&entity.CreatedAt,

			&entity.CreatedBy,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan row: %w", err)
		}

		// Copy nullable fields when present

		if tempMessage.Valid {
			entity.Message = tempMessage.String
		}
		if tempSequence != nil {
			entity.Sequence = *tempSequence
		}

		// Set relationship IDs from scanned FK values
		if tempRelRoot != nil {
			entity.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
		}
		if tempRelRef != nil {
			entity.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
		}
		if tempRelParentCommit != nil {
			// Initialize pointer for optional relationship before setting ID
			entity.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
		}

		entityID, ok := recipeCommitUUIDValue(entity.Id)
		if !ok {
			continue
		}
		resultMap[entityID] = entity
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating rows: %w", err)
	}

	return resultMap, nil
}

// FindOne retrieves the first RecipeCommit matching the filter
func (r *RecipeCommitRepository) FindOne(ctx context.Context, filter *RecipeCommitFilter, opts *RecipeCommitFindOptions) (*types.RecipeCommit, error) {
	// Determine if we're using partial field selection
	var fieldStrings []string
	var selectFields string
	usePartialFields := opts != nil && !opts.Fields.IsZero()

	if usePartialFields {
		// Build selected fields in OrderedMembers order so FK columns match scan order.
		if opts.Fields.Id {
			fieldStrings = append(fieldStrings, "id")
		}
		if opts.Fields.Root || !opts.Fields.RootNested.IsZero() {
			fieldStrings = append(fieldStrings, "root_id")
		}
		if opts.Fields.Ref || (opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero()) {
			fieldStrings = append(fieldStrings, "ref_id")
		}
		if opts.Fields.ParentCommit || (opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero()) {
			fieldStrings = append(fieldStrings, "parent_commit_id")
		}
		if opts.Fields.Message {
			fieldStrings = append(fieldStrings, "message")
		}
		if opts.Fields.SchemaEpoch {
			fieldStrings = append(fieldStrings, "schema_epoch")
		}
		if opts.Fields.ContentHash {
			fieldStrings = append(fieldStrings, "content_hash")
		}
		if opts.Fields.Sequence {
			fieldStrings = append(fieldStrings, "sequence")
		}
		if opts.Fields.CreatedAt {
			fieldStrings = append(fieldStrings, "created_at")
		}
		if opts.Fields.CreatedBy {
			fieldStrings = append(fieldStrings, "created_by")
		}
		// Validate fields
		if err := validateFields(fieldStrings, RecipeCommitAllowedFields); err != nil {
			return nil, err
		}
		selectFields = buildSelectFieldsTyped(fieldStrings, "recipe_commit")
	} else {
		// Select all fields in explicit order matching scan order (using OrderedMembers for schema order)
		selectFields = `"id", "root_id", "ref_id", "parent_commit_id", "message", "schema_epoch", "content_hash", "sequence", "created_at", "created_by"`
		if opts == nil {
			opts = &RecipeCommitFindOptions{}
		}
	}

	// Build WHERE clause
	var args []interface{}
	whereClause := filter.buildWhereClause(&args, 0)

	// Build ORDER BY clause
	orderByClause := buildRecipeCommitOrderByClause(opts.OrderBy, "recipe_commit")

	// Build query
	query := fmt.Sprintf(`SELECT %s FROM recipe_commit%s%s LIMIT 1`, selectFields, whereClause, orderByClause)

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, args...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, args...)
	}

	// Scan result
	result := &types.RecipeCommit{}
	// Create temporary variables for nullable fields that need pointer scanning

	var tempMessage sql.NullString
	var tempSequence *types.GenericInt64

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)
	var tempRelRoot *types.IdentityUUID
	var tempRelRef *types.IdentityUUID
	var tempRelParentCommit *types.IdentityUUID

	var err error
	if usePartialFields {
		// Dynamic scanning for partial field selection
		// Track whether special fields were selected so we can post-process after Scan.

		var selectedMessage bool
		var selectedSequence bool
		var selectedRelRoot bool
		var selectedRelRef bool
		var selectedRelParentCommit bool

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "message":
				scanDest[i] = &tempMessage
				selectedMessage = true
			case "schema_epoch":
				scanDest[i] = &result.SchemaEpoch
			case "content_hash":
				scanDest[i] = &result.ContentHash
			case "sequence":
				scanDest[i] = &tempSequence
				selectedSequence = true
			case "created_at":
				scanDest[i] = &result.CreatedAt
			case "created_by":
				scanDest[i] = &result.CreatedBy
			case "root_id":
				scanDest[i] = &tempRelRoot
				selectedRelRoot = true
			case "ref_id":
				scanDest[i] = &tempRelRef
				selectedRelRef = true
			case "parent_commit_id":
				scanDest[i] = &tempRelParentCommit
				selectedRelParentCommit = true
			default:
				return nil, fmt.Errorf("unexpected field %q for RecipeCommit.FindOne", fieldName)
			}
		}

		err = row.Scan(scanDest...)
		if err == nil {
			// Copy nullable fields when present
			var jsonFieldDecodeErr error

			if selectedMessage && tempMessage.Valid {
				result.Message = tempMessage.String
			}
			if selectedSequence && tempSequence != nil {
				// Value type (primitive): dereference pointer temp to value
				result.Sequence = *tempSequence
			}
			if jsonFieldDecodeErr != nil {
				return nil, jsonFieldDecodeErr
			}

			// Set relationship IDs from scanned FK values
			if selectedRelRoot && tempRelRoot != nil {
				result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
			}
			if selectedRelRef && tempRelRef != nil {
				result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
			}
			if selectedRelParentCommit && tempRelParentCommit != nil {
				// Initialize pointer for optional relationship before setting ID
				if result.ParentCommit == nil {
					result.ParentCommit = &types.RecipeCommit{}
				}
				result.ParentCommit.Id = recipeCommitUUIDPtr(*tempRelParentCommit)
			}
		}
	} else {
		// Scan all fields in schema order (matches DDL column order)
		err = row.Scan(

			&result.Id,

			&tempRelRoot,

			&tempRelRef,

			&tempRelParentCommit,

			&tempMessage,

			&result.SchemaEpoch,

			&result.ContentHash,

			&tempSequence,

			&result.CreatedAt,

			&result.CreatedBy,
		)

		if err == nil {
			// Copy nullable fields when present

			if tempMessage.Valid {
				result.Message = tempMessage.String
			}
			if tempSequence != nil {
				// Value type (primitive): dereference pointer temp to value
				result.Sequence = *tempSequence
			}
		}
	}

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan row: %w", err)
	}

	// Hydrate relationship foreign keys into nested objects from typed field selections.
	if tempRelRoot != nil {
		relRequested := opts != nil && (opts.Fields.Root || !opts.Fields.RootNested.IsZero())
		if relRequested {
			childFields := (RecipeFields{}).All()
			childFieldsAreDefault := true
			if !opts.Fields.RootNested.IsZero() {
				childFields = opts.Fields.RootNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchRootByIDs(ctx, []types.IdentityUUID{*tempRelRoot}, &RecipeFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch root: %w", err)
			}
			if rel, ok := relMap[*tempRelRoot]; ok {
				result.Root = *rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
			}
		} else {
			// Just set the ID when not including full entity
			result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
		}
	}
	if tempRelRef != nil {
		relRequested := opts != nil && (opts.Fields.Ref || (opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero()))
		if relRequested {
			childFields := (RecipeRefFields{}).All()
			childFieldsAreDefault := true
			if opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero() {
				childFields = *opts.Fields.RefNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchRefByIDs(ctx, []types.IdentityUUID{*tempRelRef}, &RecipeRefFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch ref: %w", err)
			}
			if rel, ok := relMap[*tempRelRef]; ok {
				result.Ref = *rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
			}
		} else {
			// Just set the ID when not including full entity
			result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
		}
	}
	if tempRelParentCommit != nil {
		relRequested := opts != nil && (opts.Fields.ParentCommit || (opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero()))
		if relRequested {
			childFields := (RecipeCommitFields{}).All()
			childFieldsAreDefault := true
			if opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero() {
				childFields = *opts.Fields.ParentCommitNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchParentCommitByIDs(ctx, []types.IdentityUUID{*tempRelParentCommit}, &RecipeCommitFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch parentCommit: %w", err)
			}
			if rel, ok := relMap[*tempRelParentCommit]; ok {
				result.ParentCommit = rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
			}
		} else {
			// Just set the ID when not including full entity
			// Initialize pointer for optional relationship before setting ID
			result.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
		}
	}

	return result, nil
}

// FindMany retrieves multiple RecipeCommit records matching the filter
func (r *RecipeCommitRepository) FindMany(ctx context.Context, filter *RecipeCommitFilter, opts *RecipeCommitFindOptions) ([]*types.RecipeCommit, int, error) {
	if opts == nil || opts.Fields.IsZero() {
		return nil, 0, fmt.Errorf("fields must be specified in FindOptions for performance")
	}

	// Build selected fields in OrderedMembers order so FK columns match scan order.
	var fieldStrings []string
	if opts.Fields.Id {
		fieldStrings = append(fieldStrings, "id")
	}
	if opts.Fields.Root || !opts.Fields.RootNested.IsZero() {
		fieldStrings = append(fieldStrings, "root_id")
	}
	if opts.Fields.Ref || (opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero()) {
		fieldStrings = append(fieldStrings, "ref_id")
	}
	if opts.Fields.ParentCommit || (opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero()) {
		fieldStrings = append(fieldStrings, "parent_commit_id")
	}
	if opts.Fields.Message {
		fieldStrings = append(fieldStrings, "message")
	}
	if opts.Fields.SchemaEpoch {
		fieldStrings = append(fieldStrings, "schema_epoch")
	}
	if opts.Fields.ContentHash {
		fieldStrings = append(fieldStrings, "content_hash")
	}
	if opts.Fields.Sequence {
		fieldStrings = append(fieldStrings, "sequence")
	}
	if opts.Fields.CreatedAt {
		fieldStrings = append(fieldStrings, "created_at")
	}
	if opts.Fields.CreatedBy {
		fieldStrings = append(fieldStrings, "created_by")
	}

	// Validate fields
	if err := validateFields(fieldStrings, RecipeCommitAllowedFields); err != nil {
		return nil, 0, err
	}

	// Build SELECT clause
	selectFields := buildSelectFieldsTyped(fieldStrings, "recipe_commit")
	if selectFields == "" {
		return nil, 0, fmt.Errorf("no valid fields specified")
	}

	// Build WHERE clause
	var args []interface{}
	whereClause := filter.buildWhereClause(&args, 0)

	// Build ORDER BY clause
	orderByClause := buildRecipeCommitOrderByClause(opts.OrderBy, "recipe_commit")

	// Build LIMIT/OFFSET clause
	limitOffsetClause := buildLimitOffsetClauseTyped(opts.Limit, opts.Offset)

	// Build query
	query := fmt.Sprintf(`SELECT %s FROM recipe_commit%s%s%s`, selectFields, whereClause, orderByClause, limitOffsetClause)

	// Get total count
	countQuery := fmt.Sprintf(`SELECT COUNT(*) FROM recipe_commit%s`, whereClause)

	var totalCount int
	var countRow pgx.Row
	if r.tx != nil {
		countRow = r.tx.QueryRow(ctx, countQuery, args...)
	} else {
		countRow = r.db.pool.QueryRow(ctx, countQuery, args...)
	}
	if err := countRow.Scan(&totalCount); err != nil {
		return nil, 0, fmt.Errorf("failed to get count: %w", err)
	}

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, args...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, args...)
	}
	if err != nil {
		return nil, 0, fmt.Errorf("failed to execute query: %w", err)
	}
	defer rows.Close()

	// Scan results
	results := []*types.RecipeCommit{}
	for rows.Next() {
		result := &types.RecipeCommit{}

		// Create temporary variables for nullable fields that need pointer scanning (per-row)

		var tempMessage sql.NullString
		var tempSequence *types.GenericInt64

		// Create temporary variables for relationship foreign keys (we don't store these directly on the struct)
		var tempRelRoot *types.IdentityUUID
		var tempRelRef *types.IdentityUUID
		var tempRelParentCommit *types.IdentityUUID

		// Track whether special fields were selected so we can post-process after Scan.

		var selectedMessage bool
		var selectedSequence bool
		var selectedRelRoot bool
		var selectedRelRef bool
		var selectedRelParentCommit bool

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "message":
				scanDest[i] = &tempMessage
				selectedMessage = true
			case "schema_epoch":
				scanDest[i] = &result.SchemaEpoch
			case "content_hash":
				scanDest[i] = &result.ContentHash
			case "sequence":
				scanDest[i] = &tempSequence
				selectedSequence = true
			case "created_at":
				scanDest[i] = &result.CreatedAt
			case "created_by":
				scanDest[i] = &result.CreatedBy
			case "root_id":
				scanDest[i] = &tempRelRoot
				selectedRelRoot = true
			case "ref_id":
				scanDest[i] = &tempRelRef
				selectedRelRef = true
			case "parent_commit_id":
				scanDest[i] = &tempRelParentCommit
				selectedRelParentCommit = true
			default:
				return nil, 0, fmt.Errorf("unexpected field %q for RecipeCommit.FindMany", fieldName)
			}
		}

		if err := rows.Scan(scanDest...); err != nil {
			return nil, 0, fmt.Errorf("failed to scan row: %w", err)
		}

		// Copy nullable fields when present
		var jsonFieldDecodeErr error

		if selectedMessage && tempMessage.Valid {
			result.Message = tempMessage.String
		}
		if selectedSequence && tempSequence != nil {
			// Value type (primitive): dereference pointer temp to value
			result.Sequence = *tempSequence
		}
		if jsonFieldDecodeErr != nil {
			return nil, 0, jsonFieldDecodeErr
		}

		// Set relationship IDs from scanned FK values (hydration happens after loop)
		if selectedRelRoot && tempRelRoot != nil {
			result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
		}
		if selectedRelRef && tempRelRef != nil {
			result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
		}
		if selectedRelParentCommit && tempRelParentCommit != nil {
			// Initialize pointer for optional relationship before setting ID
			result.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
		}

		results = append(results, result)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("error iterating rows: %w", err)
	}

	// Batch hydrate relationships (outside the row loop for efficiency)
	if opts.Fields.Root || !opts.Fields.RootNested.IsZero() {
		// Collect unique FK IDs from results (dedupe during collection)
		rootIDSet := make(map[types.IdentityUUID]bool)
		var rootIDs []types.IdentityUUID
		for _, result := range results {
			var zeroID types.IdentityUUID
			rootID, ok := recipeCommitUUIDValue(result.Root.Id)
			if ok && rootID != zeroID && !rootIDSet[rootID] {
				rootIDSet[rootID] = true
				rootIDs = append(rootIDs, rootID)
			}
		}

		// Batch fetch related entities with typed child field options.
		childFields := (RecipeFields{}).All()
		childFieldsAreDefault := true
		if !opts.Fields.RootNested.IsZero() {
			childFields = opts.Fields.RootNested
			childFieldsAreDefault = false
		}

		rootMap, err := r.batchRootByIDs(ctx, rootIDs, &RecipeFindOptions{
			Fields: childFields,
			Limit:  len(rootIDs),
		}, childFieldsAreDefault)
		if err != nil {
			return nil, 0, fmt.Errorf("failed to batch fetch root: %w", err)
		}

		// Hydrate results from map
		for _, result := range results {
			rootID, ok := recipeCommitUUIDValue(result.Root.Id)
			if ok {
				if rel, ok := rootMap[rootID]; ok {
					result.Root = *rel
				}
			}
		}
	}
	if opts.Fields.Ref || (opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero()) {
		// Collect unique FK IDs from results (dedupe during collection)
		refIDSet := make(map[types.IdentityUUID]bool)
		var refIDs []types.IdentityUUID
		for _, result := range results {
			var zeroID types.IdentityUUID
			refID, ok := recipeCommitUUIDValue(result.Ref.Id)
			if ok && refID != zeroID && !refIDSet[refID] {
				refIDSet[refID] = true
				refIDs = append(refIDs, refID)
			}
		}

		// Batch fetch related entities with typed child field options.
		childFields := (RecipeRefFields{}).All()
		childFieldsAreDefault := true
		if opts.Fields.RefNested != nil && !opts.Fields.RefNested.IsZero() {
			childFields = *opts.Fields.RefNested
			childFieldsAreDefault = false
		}

		refMap, err := r.batchRefByIDs(ctx, refIDs, &RecipeRefFindOptions{
			Fields: childFields,
			Limit:  len(refIDs),
		}, childFieldsAreDefault)
		if err != nil {
			return nil, 0, fmt.Errorf("failed to batch fetch ref: %w", err)
		}

		// Hydrate results from map
		for _, result := range results {
			refID, ok := recipeCommitUUIDValue(result.Ref.Id)
			if ok {
				if rel, ok := refMap[refID]; ok {
					result.Ref = *rel
				}
			}
		}
	}
	if opts.Fields.ParentCommit || (opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero()) {
		// Collect unique FK IDs from results (dedupe during collection)
		parentCommitIDSet := make(map[types.IdentityUUID]bool)
		var parentCommitIDs []types.IdentityUUID
		for _, result := range results {
			var zeroID types.IdentityUUID
			// Check if optional relationship pointer is not nil before accessing Id
			if result.ParentCommit != nil {
				parentCommitID, ok := recipeCommitUUIDValue(result.ParentCommit.Id)
				if ok && parentCommitID != zeroID && !parentCommitIDSet[parentCommitID] {
					parentCommitIDSet[parentCommitID] = true
					parentCommitIDs = append(parentCommitIDs, parentCommitID)
				}
			}
		}

		// Batch fetch related entities with typed child field options.
		childFields := (RecipeCommitFields{}).All()
		childFieldsAreDefault := true
		if opts.Fields.ParentCommitNested != nil && !opts.Fields.ParentCommitNested.IsZero() {
			childFields = *opts.Fields.ParentCommitNested
			childFieldsAreDefault = false
		}

		parentCommitMap, err := r.batchParentCommitByIDs(ctx, parentCommitIDs, &RecipeCommitFindOptions{
			Fields: childFields,
			Limit:  len(parentCommitIDs),
		}, childFieldsAreDefault)
		if err != nil {
			return nil, 0, fmt.Errorf("failed to batch fetch parentCommit: %w", err)
		}

		// Hydrate results from map
		for _, result := range results {
			// Check if optional relationship pointer is not nil before accessing Id
			if result.ParentCommit != nil {
				parentCommitID, ok := recipeCommitUUIDValue(result.ParentCommit.Id)
				if ok {
					if rel, ok := parentCommitMap[parentCommitID]; ok {
						result.ParentCommit = rel
					}
				}
			}
		}
	}

	return results, totalCount, nil
}

// CreateOne inserts a new RecipeCommit record
func (r *RecipeCommitRepository) CreateOne(ctx context.Context, input *types.RecipeCommit) (*types.RecipeCommit, error) {
	// Set audit fields
	if !HasUserID(ctx) {
		return nil, ErrNoUserInContext
	}
	input.CreatedBy = GetUserID(ctx)

	// Build INSERT query
	var fields []string
	var placeholders []string
	var values []interface{}
	paramNum := 0
	// Schema-owned identities may supply a stable UUID. A zero value keeps the
	// database-generated default used by ordinary creates.
	{
		var zeroPrimaryKey types.IdentityUUID
		if primaryKey, ok := recipeCommitUUIDValue(input.Id); ok && primaryKey != zeroPrimaryKey {
			fields = append(fields, `id`)
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, primaryKey.ToUUID())
		}
	}
	// Optional field: message - only add if set
	{
		if !reflect.ValueOf(input.Message).IsZero() {
			fields = append(fields, `message`)
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, input.Message)
		}
	}
	// Required field: schemaEpoch
	fields = append(fields, `schema_epoch`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.SchemaEpoch)
	// Required field: contentHash
	fields = append(fields, `content_hash`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.ContentHash)
	// Optional field: sequence - only add if set
	{
		if !reflect.ValueOf(input.Sequence).IsZero() {
			fields = append(fields, `"sequence"`)
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, input.Sequence)
		}
	}
	// Required field: createdBy
	fields = append(fields, `created_by`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.CreatedBy.ToUUID())

	// Handle relationship foreign key columns
	// Relationship: root (FK: root_id)
	{
		var zeroId types.IdentityUUID
		if relID, ok := recipeCommitUUIDValue(input.Root.Id); ok && relID != zeroId {
			fields = append(fields, "root_id")
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, relID.ToUUID())
		}
	}
	// Relationship: ref (FK: ref_id)
	{
		var zeroId types.IdentityUUID
		if relID, ok := recipeCommitUUIDValue(input.Ref.Id); ok && relID != zeroId {
			fields = append(fields, "ref_id")
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, relID.ToUUID())
		}
	}
	// Relationship: parentCommit (FK: parent_commit_id)
	{
		var zeroId types.IdentityUUID
		if input.ParentCommit != nil {
			if relID, ok := recipeCommitUUIDValue(input.ParentCommit.Id); ok && relID != zeroId {
				fields = append(fields, "parent_commit_id")
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, relID.ToUUID())
			}
		}
	}

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	returningClause := `"id", "root_id", "ref_id", "parent_commit_id", "message", "schema_epoch", "content_hash", "sequence", "created_at", "created_by"`
	query := fmt.Sprintf(
		`INSERT INTO recipe_commit (%s) VALUES (%s) RETURNING %s`,
		strings.Join(fields, ", "),
		strings.Join(placeholders, ", "),
		returningClause,
	)

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, values...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, values...)
	}

	// Scan result
	result := &types.RecipeCommit{}
	// Create temporary variables for nullable fields that need pointer scanning

	var tempMessage sql.NullString
	var tempSequence *types.GenericInt64

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)
	var tempRelRoot *types.IdentityUUID
	var tempRelRef *types.IdentityUUID
	var tempRelParentCommit *types.IdentityUUID

	// Scan all fields in schema order (matches DDL column order)
	if err := row.Scan(

		&result.Id,

		&tempRelRoot,

		&tempRelRef,

		&tempRelParentCommit,

		&tempMessage,

		&result.SchemaEpoch,

		&result.ContentHash,

		&tempSequence,

		&result.CreatedAt,

		&result.CreatedBy,
	); err != nil {
		return nil, fmt.Errorf("failed to scan result: %w", err)
	}

	// Copy nullable fields when present

	if tempMessage.Valid {
		result.Message = tempMessage.String
	}
	if tempSequence != nil {
		// Value type (primitive): dereference pointer temp to value
		result.Sequence = *tempSequence
	}

	// Set relationship IDs from scanned FK values
	if tempRelRoot != nil {
		result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
	}
	if tempRelRef != nil {
		result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
	}
	if tempRelParentCommit != nil {
		// Initialize pointer for optional relationship before setting ID
		result.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
	}

	return result, nil
}

// CreateMany inserts multiple RecipeCommit records in a single statement
func (r *RecipeCommitRepository) CreateMany(ctx context.Context, inputs []*types.RecipeCommit) ([]*types.RecipeCommit, error) {
	if len(inputs) == 0 {
		return []*types.RecipeCommit{}, nil
	}

	// Set audit fields
	if !HasUserID(ctx) {
		return nil, ErrNoUserInContext
	}
	for _, input := range inputs {
		input.CreatedBy = GetUserID(ctx)
	}

	// Build batch INSERT query - collect field names from first input
	var fieldNames []string
	// Schema-owned identities may supply stable UUIDs, matching CreateOne. One
	// INSERT has one column set, so a batch must supply ids for every row or
	// none; mixing is refused rather than silently dropping the supplied ids.
	explicitPrimaryKey := false
	{
		var zeroPrimaryKey types.IdentityUUID
		if primaryKey, ok := recipeCommitUUIDValue(inputs[0].Id); ok && primaryKey != zeroPrimaryKey {
			explicitPrimaryKey = true
		}
		for _, input := range inputs {
			primaryKey, ok := recipeCommitUUIDValue(input.Id)
			if (ok && primaryKey != zeroPrimaryKey) != explicitPrimaryKey {
				return nil, fmt.Errorf("inputs mix explicit and default primary keys; a batch must supply ids for every row or none")
			}
		}
	}
	if explicitPrimaryKey {
		fieldNames = append(fieldNames, `id`)
	}
	fieldNames = append(fieldNames, `schema_epoch`)
	fieldNames = append(fieldNames, `content_hash`)
	fieldNames = append(fieldNames, `created_by`)

	// Add optional/auto-generated fields that are set in first input
	{
		if !reflect.ValueOf(inputs[0].Message).IsZero() {
			fieldNames = append(fieldNames, `message`)
		}
	}
	{
		if !reflect.ValueOf(inputs[0].Sequence).IsZero() {
			fieldNames = append(fieldNames, `"sequence"`)
		}
	}

	// Add relationship foreign key columns present in first input (matches CreateOne's column set)
	// Relationship: root (FK: root_id)
	{
		var zeroId types.IdentityUUID
		if relID, ok := recipeCommitUUIDValue(inputs[0].Root.Id); ok && relID != zeroId {
			fieldNames = append(fieldNames, "root_id")
		}
	}
	// Relationship: ref (FK: ref_id)
	{
		var zeroId types.IdentityUUID
		if relID, ok := recipeCommitUUIDValue(inputs[0].Ref.Id); ok && relID != zeroId {
			fieldNames = append(fieldNames, "ref_id")
		}
	}
	// Relationship: parentCommit (FK: parent_commit_id)
	{
		var zeroId types.IdentityUUID
		if inputs[0].ParentCommit != nil {
			if relID, ok := recipeCommitUUIDValue(inputs[0].ParentCommit.Id); ok && relID != zeroId {
				fieldNames = append(fieldNames, "parent_commit_id")
			}
		}
	}

	var valuePlaceholders []string
	var values []interface{}
	paramNum := 0

	for _, input := range inputs {
		var placeholders []string
		if explicitPrimaryKey {
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			primaryKey, _ := recipeCommitUUIDValue(input.Id)
			values = append(values, primaryKey.ToUUID())
		}
		{
			if !reflect.ValueOf(input.Message).IsZero() {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, input.Message)
			}
		}
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.SchemaEpoch)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.ContentHash)
		{
			if !reflect.ValueOf(input.Sequence).IsZero() {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, input.Sequence)
			}
		}
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.CreatedBy.ToUUID())

		// Handle relationship foreign key columns (per-row, matches CreateOne)
		// Relationship: root (FK: root_id)
		{
			var zeroId types.IdentityUUID
			if relID, ok := recipeCommitUUIDValue(input.Root.Id); ok && relID != zeroId {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, relID.ToUUID())
			}
		}
		// Relationship: ref (FK: ref_id)
		{
			var zeroId types.IdentityUUID
			if relID, ok := recipeCommitUUIDValue(input.Ref.Id); ok && relID != zeroId {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, relID.ToUUID())
			}
		}
		// Relationship: parentCommit (FK: parent_commit_id)
		{
			var zeroId types.IdentityUUID
			if input.ParentCommit != nil {
				if relID, ok := recipeCommitUUIDValue(input.ParentCommit.Id); ok && relID != zeroId {
					paramNum++
					placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
					values = append(values, relID.ToUUID())
				}
			}
		}
		valuePlaceholders = append(valuePlaceholders, "("+strings.Join(placeholders, ", ")+")")
	}

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	returningClauseMany := `"id", "root_id", "ref_id", "parent_commit_id", "message", "schema_epoch", "content_hash", "sequence", "created_at", "created_by"`
	query := fmt.Sprintf(
		`INSERT INTO recipe_commit (%s) VALUES %s RETURNING %s`,
		strings.Join(fieldNames, ", "),
		strings.Join(valuePlaceholders, ", "),
		returningClauseMany,
	)

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, values...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, values...)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to execute batch insert: %w", err)
	}
	defer rows.Close()

	// Scan results
	results := []*types.RecipeCommit{}
	for rows.Next() {
		result := &types.RecipeCommit{}
		// Create temporary variables for nullable fields that need pointer scanning

		var tempMessage sql.NullString
		var tempSequence *types.GenericInt64

		// Create temporary variables for relationship foreign keys (we don't store these in the struct)
		var tempRelRoot *types.IdentityUUID
		var tempRelRef *types.IdentityUUID
		var tempRelParentCommit *types.IdentityUUID

		// Scan all fields in schema order (matches DDL column order)
		err := rows.Scan(

			&result.Id,

			&tempRelRoot,

			&tempRelRef,

			&tempRelParentCommit,

			&tempMessage,

			&result.SchemaEpoch,

			&result.ContentHash,

			&tempSequence,

			&result.CreatedAt,

			&result.CreatedBy,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan result: %w", err)
		}

		// Copy nullable fields when present

		if tempMessage.Valid {
			result.Message = tempMessage.String
		}
		if tempSequence != nil {
			// Value type (primitive): dereference pointer temp to value
			result.Sequence = *tempSequence
		}

		// Set relationship IDs from scanned FK values
		if tempRelRoot != nil {
			result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
		}
		if tempRelRef != nil {
			result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
		}
		if tempRelParentCommit != nil {
			// Initialize pointer for optional relationship before setting ID
			result.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
		}
		results = append(results, result)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating results: %w", err)
	}

	return results, nil
}

// UpdateOne updates a single RecipeCommit record by ID
func (r *RecipeCommitRepository) UpdateOne(ctx context.Context, id types.IdentityUUID, update *RecipeCommitUpdate) (*types.RecipeCommit, error) {
	// Build UPDATE query
	var setClauses []string
	var values []interface{}
	paramNum := 0
	if update.Message != nil && update.MessageSetNull {
		return nil, fmt.Errorf("message cannot be updated with both value and null assignment")
	}
	if update.MessageSetNull {
		setClauses = append(setClauses, `message = NULL`)
	} else if update.Message != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`message = $%d`, paramNum))
		values = append(values, *update.Message)
	}
	if update.SchemaEpoch != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`schema_epoch = $%d`, paramNum))
		values = append(values, *update.SchemaEpoch)
	}
	if update.ContentHash != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`content_hash = $%d`, paramNum))
		values = append(values, *update.ContentHash)
	}
	if update.Sequence != nil && update.SequenceSetNull {
		return nil, fmt.Errorf("sequence cannot be updated with both value and null assignment")
	}
	if update.SequenceSetNull {
		setClauses = append(setClauses, `"sequence" = NULL`)
	} else if update.Sequence != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`"sequence" = $%d`, paramNum))
		values = append(values, *update.Sequence)
	}
	// Handle relationship foreign key: root
	if update.RootID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("root_id = $%d", paramNum))
		values = append(values, update.RootID.ToUUID())
	}
	// Handle relationship foreign key: ref
	if update.RefID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("ref_id = $%d", paramNum))
		values = append(values, update.RefID.ToUUID())
	}
	// Handle relationship foreign key: parentCommit
	if update.ParentCommitID != nil && update.ParentCommitIDSetNull {
		return nil, fmt.Errorf("parent_commit_id cannot be updated with both value and null assignment")
	}
	if update.ParentCommitIDSetNull {
		setClauses = append(setClauses, "parent_commit_id = NULL")
	} else if update.ParentCommitID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("parent_commit_id = $%d", paramNum))
		values = append(values, update.ParentCommitID.ToUUID())
	}

	// Set updated_at

	// Set updated_by

	if len(setClauses) == 0 {
		return nil, fmt.Errorf("no fields to update")
	}

	paramNum++
	values = append(values, id.ToUUID())

	query := fmt.Sprintf(
		`UPDATE recipe_commit SET %s WHERE id = $%d`,
		strings.Join(setClauses, ", "),
		paramNum,
	)

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	query += ` RETURNING "id", "root_id", "ref_id", "parent_commit_id", "message", "schema_epoch", "content_hash", "sequence", "created_at", "created_by"`

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, values...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, values...)
	}

	// Scan result
	result := &types.RecipeCommit{}
	// Create temporary variables for nullable fields that need pointer scanning

	var tempMessage sql.NullString
	var tempSequence *types.GenericInt64

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)
	var tempRelRoot *types.IdentityUUID
	var tempRelRef *types.IdentityUUID
	var tempRelParentCommit *types.IdentityUUID

	// Scan all fields in schema order (matches DDL column order)
	if err := row.Scan(

		&result.Id,

		&tempRelRoot,

		&tempRelRef,

		&tempRelParentCommit,

		&tempMessage,

		&result.SchemaEpoch,

		&result.ContentHash,

		&tempSequence,

		&result.CreatedAt,

		&result.CreatedBy,
	); err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan result: %w", err)
	}

	// Copy nullable fields when present

	if tempMessage.Valid {
		result.Message = tempMessage.String
	}
	if tempSequence != nil {
		// Value type (primitive): dereference pointer temp to value
		result.Sequence = *tempSequence
	}

	// Set relationship IDs from scanned FK values
	if tempRelRoot != nil {
		result.Root.Id = recipeCommitUUIDPtr(*tempRelRoot)
	}
	if tempRelRef != nil {
		result.Ref.Id = recipeCommitUUIDPtr(*tempRelRef)
	}
	if tempRelParentCommit != nil {
		// Initialize pointer for optional relationship before setting ID
		result.ParentCommit = &types.RecipeCommit{Id: recipeCommitUUIDPtr(*tempRelParentCommit)}
	}

	return result, nil
}

// UpdateMany updates multiple RecipeCommit records matching the filter
func (r *RecipeCommitRepository) UpdateMany(ctx context.Context, filter *RecipeCommitFilter, update *RecipeCommitUpdate) (int, error) {
	// Build UPDATE query
	var setClauses []string
	var values []interface{}
	paramNum := 0
	if update.Message != nil && update.MessageSetNull {
		return 0, fmt.Errorf("message cannot be updated with both value and null assignment")
	}
	if update.MessageSetNull {
		setClauses = append(setClauses, `message = NULL`)
	} else if update.Message != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`message = $%d`, paramNum))
		values = append(values, *update.Message)
	}
	if update.SchemaEpoch != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`schema_epoch = $%d`, paramNum))
		values = append(values, *update.SchemaEpoch)
	}
	if update.ContentHash != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`content_hash = $%d`, paramNum))
		values = append(values, *update.ContentHash)
	}
	if update.Sequence != nil && update.SequenceSetNull {
		return 0, fmt.Errorf("sequence cannot be updated with both value and null assignment")
	}
	if update.SequenceSetNull {
		setClauses = append(setClauses, `"sequence" = NULL`)
	} else if update.Sequence != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`"sequence" = $%d`, paramNum))
		values = append(values, *update.Sequence)
	}
	// Handle relationship foreign key: root
	if update.RootID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("root_id = $%d", paramNum))
		values = append(values, update.RootID.ToUUID())
	}
	// Handle relationship foreign key: ref
	if update.RefID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("ref_id = $%d", paramNum))
		values = append(values, update.RefID.ToUUID())
	}
	// Handle relationship foreign key: parentCommit
	if update.ParentCommitID != nil && update.ParentCommitIDSetNull {
		return 0, fmt.Errorf("parent_commit_id cannot be updated with both value and null assignment")
	}
	if update.ParentCommitIDSetNull {
		setClauses = append(setClauses, "parent_commit_id = NULL")
	} else if update.ParentCommitID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("parent_commit_id = $%d", paramNum))
		values = append(values, update.ParentCommitID.ToUUID())
	}

	// Set updated_at

	// Set updated_by

	if len(setClauses) == 0 {
		return 0, fmt.Errorf("no fields to update")
	}

	// Build WHERE clause
	whereClause := filter.buildWhereClause(&values, paramNum)

	query := fmt.Sprintf(
		`UPDATE recipe_commit SET %s%s`,
		strings.Join(setClauses, ", "),
		whereClause,
	)

	// Execute query
	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, values...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, values...)
	}
	if err != nil {
		return 0, fmt.Errorf("failed to execute update: %w", err)
	}

	return int(result.RowsAffected()), nil
}

// DeleteOne permanently deletes a single RecipeCommit record by ID
func (r *RecipeCommitRepository) DeleteOne(ctx context.Context, id types.IdentityUUID) error {
	query := `DELETE FROM recipe_commit WHERE id = $1`

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, id.ToUUID())
	} else {
		result, err = r.db.pool.Exec(ctx, query, id.ToUUID())
	}
	if err != nil {
		return fmt.Errorf("failed to delete record: %w", err)
	}

	if result.RowsAffected() == 0 {
		return ErrNotFound
	}

	return nil
}

// DeleteMany permanently deletes multiple RecipeCommit records matching the filter
func (r *RecipeCommitRepository) DeleteMany(ctx context.Context, filter *RecipeCommitFilter) (int, error) {
	// Build WHERE clause
	var values []interface{}
	whereClause := filter.buildWhereClause(&values, 0)

	query := fmt.Sprintf(`DELETE FROM recipe_commit%s`, whereClause)

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, values...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, values...)
	}
	if err != nil {
		return 0, fmt.Errorf("failed to delete records: %w", err)
	}

	return int(result.RowsAffected()), nil
}
