// Code generated by superschematic ormgen. DO NOT EDIT.

package orm

import (
	"context"
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"time"

	types "example.com/schemas/types/go/fixture-version-graph-db"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

func decodeTastingHistoryData(raw []byte) (*types.Tasting, error) {
	var values map[string]json.RawMessage
	if err := json.Unmarshal(raw, &values); err != nil {
		return nil, fmt.Errorf("failed to decode Tasting history data: %w", err)
	}

	result := &types.Tasting{}
	if rawValue, ok := values["id"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Id); err != nil {
			return nil, fmt.Errorf("failed to decode history field id: %w", err)
		}
	}
	if rawValue, ok := values["taster"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Taster); err != nil {
			return nil, fmt.Errorf("failed to decode history field taster: %w", err)
		}
	}
	if rawValue, ok := values["salty"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Salty); err != nil {
			return nil, fmt.Errorf("failed to decode history field salty: %w", err)
		}
	}
	if rawValue, ok := values["score"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Score); err != nil {
			return nil, fmt.Errorf("failed to decode history field score: %w", err)
		}
	}
	if rawValue, ok := values["servings"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Servings); err != nil {
			return nil, fmt.Errorf("failed to decode history field servings: %w", err)
		}
	}
	if rawValue, ok := values["tasted_on"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.TastedOn); err != nil {
			return nil, fmt.Errorf("failed to decode history field tasted_on: %w", err)
		}
	}
	if rawValue, ok := values["tasted_at"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.TastedAt); err != nil {
			return nil, fmt.Errorf("failed to decode history field tasted_at: %w", err)
		}
	}
	if rawValue, ok := values["served_at"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.ServedAt); err != nil {
			return nil, fmt.Errorf("failed to decode history field served_at: %w", err)
		}
	}
	if rawValue, ok := values["rested"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Rested); err != nil {
			return nil, fmt.Errorf("failed to decode history field rested: %w", err)
		}
	}
	if rawValue, ok := values["verdict"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Verdict); err != nil {
			return nil, fmt.Errorf("failed to decode history field verdict: %w", err)
		}
	}
	if rawValue, ok := values["remarks"]; ok && len(rawValue) > 0 {
		if err := unmarshalGenericJSONFieldValue(rawValue, &result.Remarks); err != nil {
			return nil, fmt.Errorf("failed to decode history field remarks: %w", err)
		}
	}
	if rawValue, ok := values["tags"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Tags); err != nil {
			return nil, fmt.Errorf("failed to decode history field tags: %w", err)
		}
	}
	if rawValue, ok := values["helpers"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Helpers); err != nil {
			return nil, fmt.Errorf("failed to decode history field helpers: %w", err)
		}
	}
	if rawValue, ok := values["bites"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := unmarshalJSONListFieldValue(rawValue, &result.Bites, "bites", 2); err != nil {
			return nil, fmt.Errorf("failed to decode history field bites: %w", err)
		}
	}
	if rawValue, ok := values["entity_key"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.EntityKey); err != nil {
			return nil, fmt.Errorf("failed to decode history field entity_key: %w", err)
		}
	}
	if rawValue, ok := values["deleted_on_ref"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.DeletedOnRef); err != nil {
			return nil, fmt.Errorf("failed to decode history field deleted_on_ref: %w", err)
		}
	}
	if rawValue, ok := values["_version"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		if err := json.Unmarshal(rawValue, &result.Version); err != nil {
			return nil, fmt.Errorf("failed to decode history field _version: %w", err)
		}
	}
	if rawValue, ok := values["recipe_id"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		var relID types.IdentityUUID
		if err := json.Unmarshal(rawValue, &relID); err != nil {
			return nil, fmt.Errorf("failed to decode history field recipe_id: %w", err)
		}
		result.Recipe.Id = tastingUUIDPtr(relID)
	}
	if rawValue, ok := values["ref_id"]; ok && len(rawValue) > 0 && string(rawValue) != "null" {
		var relID types.IdentityUUID
		if err := json.Unmarshal(rawValue, &relID); err != nil {
			return nil, fmt.Errorf("failed to decode history field ref_id: %w", err)
		}
		result.Ref.Id = tastingUUIDPtr(relID)
	}

	return result, nil
}

// TastingRepository provides database operations for Tasting
type TastingRepository struct {
	db   *Database // Set when using Database directly
	tx   pgx.Tx    // Set when using Transaction
	txDB *Database // Parent database for transaction (enables accessing other repos)
}

// Allowed fields for Tasting (for validation and ordering)
var TastingAllowedFields = map[string]bool{
	"id":             true,
	"taster":         true,
	"salty":          true,
	"score":          true,
	"servings":       true,
	"tasted_on":      true,
	"tasted_at":      true,
	"served_at":      true,
	"rested":         true,
	"verdict":        true,
	"remarks":        true,
	"tags":           true,
	"helpers":        true,
	"bites":          true,
	"entity_key":     true,
	"deleted_on_ref": true,
	"_version":       true,
	"recipe_id":      true,
	"ref_id":         true,
}

// Quoted field names for Tasting (for SQL generation)
var TastingQuotedFields = map[string]string{
	"id":             `id`,
	"taster":         `taster`,
	"salty":          `salty`,
	"score":          `score`,
	"servings":       `servings`,
	"tasted_on":      `tasted_on`,
	"tasted_at":      `tasted_at`,
	"served_at":      `served_at`,
	"rested":         `rested`,
	"verdict":        `verdict`,
	"remarks":        `remarks`,
	"tags":           `tags`,
	"helpers":        `helpers`,
	"bites":          `bites`,
	"entity_key":     `entity_key`,
	"deleted_on_ref": `deleted_on_ref`,
	"_version":       `_version`,
	"recipe_id":      `recipe_id`,
	"ref_id":         `ref_id`,
}

// buildTastingOrderByClause builds an ORDER BY clause for Tasting
func buildTastingOrderByClause(orderBy []TastingOrderBy, tableName string) string {
	if len(orderBy) == 0 {
		return ""
	}

	var clauses []string
	for _, order := range orderBy {
		fieldStr := string(order.Field)
		direction := "ASC"
		if order.Desc {
			direction = "DESC"
		}
		// Use pre-computed quoted field name
		quotedField, ok := TastingQuotedFields[fieldStr]
		if !ok {
			quotedField = fieldStr // Fallback to unquoted if not found
		}
		clauses = append(clauses, fmt.Sprintf("%s.%s %s", tableName, quotedField, direction))
	}

	if len(clauses) == 0 {
		return ""
	}

	return " ORDER BY " + strings.Join(clauses, ", ")
}

func tastingUUIDValue(value any) (types.IdentityUUID, bool) {
	switch v := value.(type) {
	case types.IdentityUUID:
		return v, true
	case *types.IdentityUUID:
		if v == nil {
			var zero types.IdentityUUID
			return zero, false
		}
		return *v, true
	default:
		var zero types.IdentityUUID
		return zero, false
	}
}

func tastingUUIDPtr(value types.IdentityUUID) *types.IdentityUUID {
	return &value
}

// GetVersion retrieves a historical Tasting value by version. A delete
// tombstone's version is not a value of the row, so it reads as ErrNotFound.
func (r *TastingRepository) GetVersion(ctx context.Context, id types.IdentityUUID, version int64) (*types.Tasting, error) {
	query := `SELECT data FROM tasting_history WHERE id = $1 AND _version = $2 AND operation <> 'DELETE'`

	var data []byte
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, id.ToUUID(), version)
	} else {
		row = r.db.pool.QueryRow(ctx, query, id.ToUUID(), version)
	}

	if err := row.Scan(&data); err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan Tasting history version: %w", err)
	}

	result, err := decodeTastingHistoryData(data)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ListVersions retrieves historical Tasting values ordered by version.
func (r *TastingRepository) ListVersions(ctx context.Context, id types.IdentityUUID, opts *TastingHistoryOptions) ([]types.HistoryRecord[*types.Tasting], error) {
	if opts == nil {
		opts = &TastingHistoryOptions{}
	}
	query := `SELECT _version, operation, recorded_at, data FROM tasting_history WHERE id = $1 ORDER BY _version ASC`
	query += buildLimitOffsetClauseTyped(opts.Limit, opts.Offset)

	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, id.ToUUID())
	} else {
		rows, err = r.db.pool.Query(ctx, query, id.ToUUID())
	}
	if err != nil {
		return nil, fmt.Errorf("failed to query Tasting history versions: %w", err)
	}
	defer rows.Close()

	records := []types.HistoryRecord[*types.Tasting]{}
	for rows.Next() {
		var record types.HistoryRecord[*types.Tasting]
		var data []byte
		if err := rows.Scan(&record.Version, &record.Operation, &record.RecordedAt, &data); err != nil {
			return nil, fmt.Errorf("failed to scan Tasting history version: %w", err)
		}
		value, err := decodeTastingHistoryData(data)
		if err != nil {
			return nil, err
		}
		record.Value = value
		records = append(records, record)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating Tasting history versions: %w", err)
	}

	return records, nil
}

// GetAsOf retrieves the latest historical Tasting value at or before ts.
// It returns ErrNotFound when the row did not exist then: no history row at
// or before ts, or the latest one is a delete tombstone.
func (r *TastingRepository) GetAsOf(ctx context.Context, id types.IdentityUUID, ts time.Time) (*types.Tasting, error) {
	query := `SELECT data
FROM (
  SELECT operation, data
  FROM tasting_history
  WHERE id = $1 AND recorded_at <= $2
  ORDER BY recorded_at DESC, _version DESC
  LIMIT 1
) latest
WHERE operation <> 'DELETE'`

	var data []byte
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, id.ToUUID(), ts)
	} else {
		row = r.db.pool.QueryRow(ctx, query, id.ToUUID(), ts)
	}

	if err := row.Scan(&data); err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan Tasting history as-of value: %w", err)
	}

	result, err := decodeTastingHistoryData(data)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ListAsOfByRecipeID retrieves the latest historical Tasting values for recipe at or before ts.
// A row whose latest history row at ts is a delete tombstone is left out.
func (r *TastingRepository) ListAsOfByRecipeID(ctx context.Context, recipeID types.IdentityUUID, ts time.Time, opts *TastingHistoryOptions) ([]types.HistoryRecord[*types.Tasting], error) {
	if opts == nil {
		opts = &TastingHistoryOptions{}
	}
	query := `WITH latest AS (
  SELECT DISTINCT ON (id) _version, operation, recorded_at, data
  FROM tasting_history
  WHERE recorded_at <= $1
  ORDER BY id, recorded_at DESC, _version DESC
)
SELECT _version, operation, recorded_at, data
FROM latest
WHERE operation <> 'DELETE' AND data->>'recipe_id' = $2
ORDER BY recorded_at ASC, _version ASC`
	query += buildLimitOffsetClauseTyped(opts.Limit, opts.Offset)

	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, ts, recipeID.ToUUID().String())
	} else {
		rows, err = r.db.pool.Query(ctx, query, ts, recipeID.ToUUID().String())
	}
	if err != nil {
		return nil, fmt.Errorf("failed to query Tasting history as-of values by recipe_id: %w", err)
	}
	defer rows.Close()

	records := []types.HistoryRecord[*types.Tasting]{}
	for rows.Next() {
		var record types.HistoryRecord[*types.Tasting]
		var data []byte
		if err := rows.Scan(&record.Version, &record.Operation, &record.RecordedAt, &data); err != nil {
			return nil, fmt.Errorf("failed to scan Tasting history as-of value by recipe_id: %w", err)
		}
		value, err := decodeTastingHistoryData(data)
		if err != nil {
			return nil, err
		}
		record.Value = value
		records = append(records, record)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating Tasting history as-of values by recipe_id: %w", err)
	}

	return records, nil
}

// ListAsOfByRefID retrieves the latest historical Tasting values for ref at or before ts.
// A row whose latest history row at ts is a delete tombstone is left out.
func (r *TastingRepository) ListAsOfByRefID(ctx context.Context, refID types.IdentityUUID, ts time.Time, opts *TastingHistoryOptions) ([]types.HistoryRecord[*types.Tasting], error) {
	if opts == nil {
		opts = &TastingHistoryOptions{}
	}
	query := `WITH latest AS (
  SELECT DISTINCT ON (id) _version, operation, recorded_at, data
  FROM tasting_history
  WHERE recorded_at <= $1
  ORDER BY id, recorded_at DESC, _version DESC
)
SELECT _version, operation, recorded_at, data
FROM latest
WHERE operation <> 'DELETE' AND data->>'ref_id' = $2
ORDER BY recorded_at ASC, _version ASC`
	query += buildLimitOffsetClauseTyped(opts.Limit, opts.Offset)

	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, ts, refID.ToUUID().String())
	} else {
		rows, err = r.db.pool.Query(ctx, query, ts, refID.ToUUID().String())
	}
	if err != nil {
		return nil, fmt.Errorf("failed to query Tasting history as-of values by ref_id: %w", err)
	}
	defer rows.Close()

	records := []types.HistoryRecord[*types.Tasting]{}
	for rows.Next() {
		var record types.HistoryRecord[*types.Tasting]
		var data []byte
		if err := rows.Scan(&record.Version, &record.Operation, &record.RecordedAt, &data); err != nil {
			return nil, fmt.Errorf("failed to scan Tasting history as-of value by ref_id: %w", err)
		}
		value, err := decodeTastingHistoryData(data)
		if err != nil {
			return nil, err
		}
		record.Value = value
		records = append(records, record)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating Tasting history as-of values by ref_id: %w", err)
	}

	return records, nil
}

// batchRecipeByIDs fetches multiple Recipe records by their IDs using a single query.
//
// This is the recursion point: the FindMany below hydrates Recipe's own
// relations, which lands back here for each of them. enterRelationHydration is
// what bounds that -- see the guard's contract in utils.go. defaultSelection
// says whether the caller named a nested selection or fell back to
// RecipeFields{}.All(); only the fallback is pruned.
//
// A refusal returns no rows rather than an error, because the caller's miss
// path already writes the id-only stub that a refused expansion should produce.
func (r *TastingRepository) batchRecipeByIDs(ctx context.Context, ids []types.IdentityUUID, opts *RecipeFindOptions, defaultSelection bool) (map[types.IdentityUUID]*types.Recipe, error) {
	if len(ids) == 0 {
		return map[types.IdentityUUID]*types.Recipe{}, nil
	}

	ctx, allowed := enterRelationHydration(ctx, "Tasting", "recipe", "Recipe", defaultSelection)
	if !allowed {
		return map[types.IdentityUUID]*types.Recipe{}, nil
	}

	// Get repository for related type
	var repo *RecipeRepository
	if r.tx != nil {
		txDB := r.txDB
		if txDB == nil {
			txDB = r.db
		}
		repo = &RecipeRepository{tx: r.tx, txDB: txDB}
	} else if r.db != nil {
		repo = r.db.Recipe
	} else if r.txDB != nil {
		repo = r.txDB.Recipe
	} else {
		return nil, fmt.Errorf("no database connection available for batch fetch")
	}

	findOpts := opts
	if findOpts == nil || findOpts.Fields.IsZero() {
		findOpts = &RecipeFindOptions{
			Fields: (RecipeFields{}).All(),
		}
	} else {
		optsCopy := *findOpts
		findOpts = &optsCopy
	}

	if findOpts.Limit <= 0 || findOpts.Limit < len(ids) {
		findOpts.Limit = len(ids)
	}

	relatedRecords, _, err := repo.FindMany(
		ctx,
		&RecipeFilter{
			Id: &UUIDFilter{
				In: ids,
			},
		},
		findOpts,
	)
	if err != nil {
		return nil, err
	}

	relatedByID := make(map[types.IdentityUUID]*types.Recipe, len(relatedRecords))
	for _, related := range relatedRecords {
		if related == nil {
			continue
		}
		relatedID, ok := tastingUUIDValue(related.Id)
		if !ok {
			continue
		}
		relatedByID[relatedID] = related
	}

	return relatedByID, nil
}

// batchRefByIDs fetches multiple RecipeRef records by their IDs using a single query.
//
// This is the recursion point: the FindMany below hydrates RecipeRef's own
// relations, which lands back here for each of them. enterRelationHydration is
// what bounds that -- see the guard's contract in utils.go. defaultSelection
// says whether the caller named a nested selection or fell back to
// RecipeRefFields{}.All(); only the fallback is pruned.
//
// A refusal returns no rows rather than an error, because the caller's miss
// path already writes the id-only stub that a refused expansion should produce.
func (r *TastingRepository) batchRefByIDs(ctx context.Context, ids []types.IdentityUUID, opts *RecipeRefFindOptions, defaultSelection bool) (map[types.IdentityUUID]*types.RecipeRef, error) {
	if len(ids) == 0 {
		return map[types.IdentityUUID]*types.RecipeRef{}, nil
	}

	ctx, allowed := enterRelationHydration(ctx, "Tasting", "ref", "RecipeRef", defaultSelection)
	if !allowed {
		return map[types.IdentityUUID]*types.RecipeRef{}, nil
	}

	// Get repository for related type
	var repo *RecipeRefRepository
	if r.tx != nil {
		txDB := r.txDB
		if txDB == nil {
			txDB = r.db
		}
		repo = &RecipeRefRepository{tx: r.tx, txDB: txDB}
	} else if r.db != nil {
		repo = r.db.RecipeRef
	} else if r.txDB != nil {
		repo = r.txDB.RecipeRef
	} else {
		return nil, fmt.Errorf("no database connection available for batch fetch")
	}

	findOpts := opts
	if findOpts == nil || findOpts.Fields.IsZero() {
		findOpts = &RecipeRefFindOptions{
			Fields: (RecipeRefFields{}).All(),
		}
	} else {
		optsCopy := *findOpts
		findOpts = &optsCopy
	}

	if findOpts.Limit <= 0 || findOpts.Limit < len(ids) {
		findOpts.Limit = len(ids)
	}

	relatedRecords, _, err := repo.FindMany(
		ctx,
		&RecipeRefFilter{
			Id: &UUIDFilter{
				In: ids,
			},
		},
		findOpts,
	)
	if err != nil {
		return nil, err
	}

	relatedByID := make(map[types.IdentityUUID]*types.RecipeRef, len(relatedRecords))
	for _, related := range relatedRecords {
		if related == nil {
			continue
		}
		relatedID, ok := tastingUUIDValue(related.Id)
		if !ok {
			continue
		}
		relatedByID[relatedID] = related
	}

	return relatedByID, nil
}

// GetOne retrieves a single Tasting by ID
func (r *TastingRepository) GetOne(ctx context.Context, id types.IdentityUUID, opts *TastingGetOptions) (*types.Tasting, error) {
	// Determine if we're using partial field selection
	var fieldStrings []string
	usePartialFields := opts != nil && !opts.Fields.IsZero()

	// Build query - if no fields specified, select all in scan order
	var query string
	if usePartialFields {
		// Build selected fields in OrderedMembers order so FK columns match scan order.
		if opts.Fields.Id {
			fieldStrings = append(fieldStrings, "id")
		}
		if opts.Fields.Recipe || !opts.Fields.RecipeNested.IsZero() {
			fieldStrings = append(fieldStrings, "recipe_id")
		}
		if opts.Fields.Taster {
			fieldStrings = append(fieldStrings, "taster")
		}
		if opts.Fields.Salty {
			fieldStrings = append(fieldStrings, "salty")
		}
		if opts.Fields.Score {
			fieldStrings = append(fieldStrings, "score")
		}
		if opts.Fields.Servings {
			fieldStrings = append(fieldStrings, "servings")
		}
		if opts.Fields.TastedOn {
			fieldStrings = append(fieldStrings, "tasted_on")
		}
		if opts.Fields.TastedAt {
			fieldStrings = append(fieldStrings, "tasted_at")
		}
		if opts.Fields.ServedAt {
			fieldStrings = append(fieldStrings, "served_at")
		}
		if opts.Fields.Rested {
			fieldStrings = append(fieldStrings, "rested")
		}
		if opts.Fields.Verdict {
			fieldStrings = append(fieldStrings, "verdict")
		}
		if opts.Fields.Remarks {
			fieldStrings = append(fieldStrings, "remarks")
		}
		if opts.Fields.Tags {
			fieldStrings = append(fieldStrings, "tags")
		}
		if opts.Fields.Helpers {
			fieldStrings = append(fieldStrings, "helpers")
		}
		if opts.Fields.Bites {
			fieldStrings = append(fieldStrings, "bites")
		}
		if opts.Fields.EntityKey {
			fieldStrings = append(fieldStrings, "entity_key")
		}
		if opts.Fields.Ref || !opts.Fields.RefNested.IsZero() {
			fieldStrings = append(fieldStrings, "ref_id")
		}
		if opts.Fields.DeletedOnRef {
			fieldStrings = append(fieldStrings, "deleted_on_ref")
		}
		if opts.Fields.Version {
			fieldStrings = append(fieldStrings, "_version")
		}
		// Validate fields
		if err := validateFields(fieldStrings, TastingAllowedFields); err != nil {
			return nil, err
		}
		selectFields := buildSelectFieldsTyped(fieldStrings, "tasting")
		query = fmt.Sprintf(`SELECT %s FROM tasting WHERE id = $1`, selectFields)
	} else {
		// Select all fields in explicit order matching scan order (using OrderedMembers for schema order)
		query = `SELECT "id", "recipe_id", "taster", "salty", "score", "servings", "tasted_on", "tasted_at", "served_at", "rested", "verdict", "remarks", "tags", "helpers", "bites", "entity_key", "ref_id", "deleted_on_ref", "_version" FROM tasting WHERE id = $1`
	}

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, id.ToUUID())
	} else {
		row = r.db.pool.QueryRow(ctx, query, id.ToUUID())
	}

	// Scan result - when selecting all fields, scan directly into struct
	result := &types.Tasting{}
	// Create temporary variables for nullable fields that need pointer scanning

	var tempTastedOn pgtype.Date
	var tempRemarks []byte
	var tempBites []byte

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)
	var tempRelRecipe *types.IdentityUUID
	var tempRelRef *types.IdentityUUID
	var selectedRelRecipe bool
	var selectedRelRef bool

	var err error
	if usePartialFields {
		// Dynamic scanning for partial field selection
		// Track whether special fields were selected so we can post-process after Scan.

		var selectedTastedOn bool

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "taster":
				scanDest[i] = &result.Taster
			case "salty":
				scanDest[i] = &result.Salty
			case "score":
				scanDest[i] = &result.Score
			case "servings":
				scanDest[i] = &result.Servings
			case "tasted_on":
				scanDest[i] = &tempTastedOn
				selectedTastedOn = true
			case "tasted_at":
				scanDest[i] = &result.TastedAt
			case "served_at":
				scanDest[i] = &result.ServedAt
			case "rested":
				scanDest[i] = &result.Rested
			case "verdict":
				scanDest[i] = &result.Verdict
			case "remarks":
				scanDest[i] = &tempRemarks
			case "tags":
				scanDest[i] = &result.Tags
			case "helpers":
				scanDest[i] = &result.Helpers
			case "bites":
				scanDest[i] = &tempBites
			case "entity_key":
				scanDest[i] = &result.EntityKey
			case "deleted_on_ref":
				scanDest[i] = &result.DeletedOnRef
			case "_version":
				scanDest[i] = &result.Version
			case "recipe_id":
				scanDest[i] = &tempRelRecipe
				selectedRelRecipe = true
			case "ref_id":
				scanDest[i] = &tempRelRef
				selectedRelRef = true
			default:
				return nil, fmt.Errorf("unexpected field %q for Tasting.GetOne", fieldName)
			}
		}

		err = row.Scan(scanDest...)
		if err == nil {
			// Copy nullable fields when present
			var jsonFieldDecodeErr error

			if selectedTastedOn && tempTastedOn.Valid {
				result.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
			}
			if len(tempRemarks) > 0 {
				if err := unmarshalGenericJSONFieldValue(tempRemarks, &result.Remarks); err != nil {
					jsonFieldDecodeErr = fmt.Errorf("failed to decode JSON field remarks: %w", err)
				}
			}
			if len(tempBites) > 0 {
				if err := unmarshalJSONListFieldValue(tempBites, &result.Bites, "bites", 2); err != nil {
					jsonFieldDecodeErr = fmt.Errorf("failed to decode JSON field bites: %w", err)
				}
			}
			if jsonFieldDecodeErr != nil {
				return nil, jsonFieldDecodeErr
			}
		}
	} else {
		selectedRelRecipe = true
		selectedRelRef = true

		// Scan all fields in schema order (matches DDL column order)
		err = row.Scan(

			&result.Id,

			&tempRelRecipe,

			&result.Taster,

			&result.Salty,

			&result.Score,

			&result.Servings,

			&tempTastedOn,

			&result.TastedAt,

			&result.ServedAt,

			&result.Rested,

			&result.Verdict,

			&tempRemarks,

			&result.Tags,

			&result.Helpers,

			&tempBites,

			&result.EntityKey,

			&tempRelRef,

			&result.DeletedOnRef,

			&result.Version,
		)

		if err == nil {
			// Copy nullable fields when present

			if tempTastedOn.Valid {
				result.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
			}
			if len(tempRemarks) > 0 {
				if err := unmarshalGenericJSONFieldValue(tempRemarks, &result.Remarks); err != nil {
					return nil, fmt.Errorf("failed to decode JSON field remarks: %w", err)
				}
			}
			if len(tempBites) > 0 {
				if err := unmarshalJSONListFieldValue(tempBites, &result.Bites, "bites", 2); err != nil {
					return nil, fmt.Errorf("failed to decode JSON field bites: %w", err)
				}
			}
		}
	}

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan row: %w", err)
	}

	// Hydrate relationship foreign keys into nested objects from typed field selections.
	if selectedRelRecipe && tempRelRecipe != nil {
		relRequested := opts != nil && (opts.Fields.Recipe || !opts.Fields.RecipeNested.IsZero())
		if relRequested {
			childFields := (RecipeFields{}).All()
			childFieldsAreDefault := true
			if !opts.Fields.RecipeNested.IsZero() {
				childFields = opts.Fields.RecipeNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchRecipeByIDs(ctx, []types.IdentityUUID{*tempRelRecipe}, &RecipeFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch recipe: %w", err)
			}
			if rel, ok := relMap[*tempRelRecipe]; ok {
				result.Recipe = *rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
			}
		} else {
			// Just set the ID when not including full entity
			result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
		}
	}
	if selectedRelRef && tempRelRef != nil {
		relRequested := opts != nil && (opts.Fields.Ref || !opts.Fields.RefNested.IsZero())
		if relRequested {
			childFields := (RecipeRefFields{}).All()
			childFieldsAreDefault := true
			if !opts.Fields.RefNested.IsZero() {
				childFields = opts.Fields.RefNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchRefByIDs(ctx, []types.IdentityUUID{*tempRelRef}, &RecipeRefFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch ref: %w", err)
			}
			if rel, ok := relMap[*tempRelRef]; ok {
				result.Ref = *rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.Ref.Id = tastingUUIDPtr(*tempRelRef)
			}
		} else {
			// Just set the ID when not including full entity
			result.Ref.Id = tastingUUIDPtr(*tempRelRef)
		}
	}

	return result, nil
}

// GetManyByIDs retrieves multiple Tasting records by their IDs in a single query
func (r *TastingRepository) GetManyByIDs(ctx context.Context, ids []types.IdentityUUID) (map[types.IdentityUUID]*types.Tasting, error) {
	if len(ids) == 0 {
		return map[types.IdentityUUID]*types.Tasting{}, nil
	}

	// Dedupe IDs
	seen := make(map[types.IdentityUUID]bool)
	uniqueIDs := make([]types.IdentityUUID, 0, len(ids))
	for _, id := range ids {
		if !seen[id] {
			seen[id] = true
			uniqueIDs = append(uniqueIDs, id)
		}
	}

	// Build WHERE id IN (...) clause
	placeholders := make([]string, len(uniqueIDs))
	args := make([]interface{}, len(uniqueIDs))
	for i, id := range uniqueIDs {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
		args[i] = id.ToUUID()
	}

	// Build query with explicit column order
	query := fmt.Sprintf(`SELECT "id", "recipe_id", "taster", "salty", "score", "servings", "tasted_on", "tasted_at", "served_at", "rested", "verdict", "remarks", "tags", "helpers", "bites", "entity_key", "ref_id", "deleted_on_ref", "_version" FROM tasting WHERE id IN (%s)`, strings.Join(placeholders, ", "))

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, args...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, args...)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to execute query: %w", err)
	}
	defer rows.Close()

	// Scan results into map
	resultMap := make(map[types.IdentityUUID]*types.Tasting, len(uniqueIDs))
	for rows.Next() {
		entity := &types.Tasting{}

		// Create temporary variables for nullable fields that need pointer scanning

		var tempTastedOn pgtype.Date
		var tempRemarks []byte
		var tempBites []byte

		// Create temporary variables for relationship foreign keys (we don't store these in the struct)
		var tempRelRecipe *types.IdentityUUID
		var tempRelRef *types.IdentityUUID

		// Scan all fields in schema order (matches DDL column order)
		err := rows.Scan(

			&entity.Id,

			&tempRelRecipe,

			&entity.Taster,

			&entity.Salty,

			&entity.Score,

			&entity.Servings,

			&tempTastedOn,

			&entity.TastedAt,

			&entity.ServedAt,

			&entity.Rested,

			&entity.Verdict,

			&tempRemarks,

			&entity.Tags,

			&entity.Helpers,

			&tempBites,

			&entity.EntityKey,

			&tempRelRef,

			&entity.DeletedOnRef,

			&entity.Version,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan row: %w", err)
		}

		// Copy nullable fields when present

		if tempTastedOn.Valid {
			entity.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
		}
		if len(tempRemarks) > 0 {
			if err := unmarshalGenericJSONFieldValue(tempRemarks, &entity.Remarks); err != nil {
				return nil, fmt.Errorf("failed to decode JSON field remarks: %w", err)
			}
		}
		if len(tempBites) > 0 {
			if err := unmarshalJSONListFieldValue(tempBites, &entity.Bites, "bites", 2); err != nil {
				return nil, fmt.Errorf("failed to decode JSON field bites: %w", err)
			}
		}

		// Set relationship IDs from scanned FK values
		if tempRelRecipe != nil {
			entity.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
		}
		if tempRelRef != nil {
			entity.Ref.Id = tastingUUIDPtr(*tempRelRef)
		}

		entityID, ok := tastingUUIDValue(entity.Id)
		if !ok {
			continue
		}
		resultMap[entityID] = entity
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating rows: %w", err)
	}

	return resultMap, nil
}

// FindOne retrieves the first Tasting matching the filter
func (r *TastingRepository) FindOne(ctx context.Context, filter *TastingFilter, opts *TastingFindOptions) (*types.Tasting, error) {
	// Determine if we're using partial field selection
	var fieldStrings []string
	var selectFields string
	usePartialFields := opts != nil && !opts.Fields.IsZero()

	if usePartialFields {
		// Build selected fields in OrderedMembers order so FK columns match scan order.
		if opts.Fields.Id {
			fieldStrings = append(fieldStrings, "id")
		}
		if opts.Fields.Recipe || !opts.Fields.RecipeNested.IsZero() {
			fieldStrings = append(fieldStrings, "recipe_id")
		}
		if opts.Fields.Taster {
			fieldStrings = append(fieldStrings, "taster")
		}
		if opts.Fields.Salty {
			fieldStrings = append(fieldStrings, "salty")
		}
		if opts.Fields.Score {
			fieldStrings = append(fieldStrings, "score")
		}
		if opts.Fields.Servings {
			fieldStrings = append(fieldStrings, "servings")
		}
		if opts.Fields.TastedOn {
			fieldStrings = append(fieldStrings, "tasted_on")
		}
		if opts.Fields.TastedAt {
			fieldStrings = append(fieldStrings, "tasted_at")
		}
		if opts.Fields.ServedAt {
			fieldStrings = append(fieldStrings, "served_at")
		}
		if opts.Fields.Rested {
			fieldStrings = append(fieldStrings, "rested")
		}
		if opts.Fields.Verdict {
			fieldStrings = append(fieldStrings, "verdict")
		}
		if opts.Fields.Remarks {
			fieldStrings = append(fieldStrings, "remarks")
		}
		if opts.Fields.Tags {
			fieldStrings = append(fieldStrings, "tags")
		}
		if opts.Fields.Helpers {
			fieldStrings = append(fieldStrings, "helpers")
		}
		if opts.Fields.Bites {
			fieldStrings = append(fieldStrings, "bites")
		}
		if opts.Fields.EntityKey {
			fieldStrings = append(fieldStrings, "entity_key")
		}
		if opts.Fields.Ref || !opts.Fields.RefNested.IsZero() {
			fieldStrings = append(fieldStrings, "ref_id")
		}
		if opts.Fields.DeletedOnRef {
			fieldStrings = append(fieldStrings, "deleted_on_ref")
		}
		if opts.Fields.Version {
			fieldStrings = append(fieldStrings, "_version")
		}
		// Validate fields
		if err := validateFields(fieldStrings, TastingAllowedFields); err != nil {
			return nil, err
		}
		selectFields = buildSelectFieldsTyped(fieldStrings, "tasting")
	} else {
		// Select all fields in explicit order matching scan order (using OrderedMembers for schema order)
		selectFields = `"id", "recipe_id", "taster", "salty", "score", "servings", "tasted_on", "tasted_at", "served_at", "rested", "verdict", "remarks", "tags", "helpers", "bites", "entity_key", "ref_id", "deleted_on_ref", "_version"`
		if opts == nil {
			opts = &TastingFindOptions{}
		}
	}

	// Build WHERE clause
	var args []interface{}
	whereClause := filter.buildWhereClause(&args, 0)

	// Build ORDER BY clause
	orderByClause := buildTastingOrderByClause(opts.OrderBy, "tasting")

	// Build query
	query := fmt.Sprintf(`SELECT %s FROM tasting%s%s LIMIT 1`, selectFields, whereClause, orderByClause)

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, args...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, args...)
	}

	// Scan result
	result := &types.Tasting{}
	// Create temporary variables for nullable fields that need pointer scanning

	var tempTastedOn pgtype.Date
	var tempRemarks []byte
	var tempBites []byte

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)
	var tempRelRecipe *types.IdentityUUID
	var tempRelRef *types.IdentityUUID

	var err error
	if usePartialFields {
		// Dynamic scanning for partial field selection
		// Track whether special fields were selected so we can post-process after Scan.

		var selectedTastedOn bool
		var selectedRelRecipe bool
		var selectedRelRef bool

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "taster":
				scanDest[i] = &result.Taster
			case "salty":
				scanDest[i] = &result.Salty
			case "score":
				scanDest[i] = &result.Score
			case "servings":
				scanDest[i] = &result.Servings
			case "tasted_on":
				scanDest[i] = &tempTastedOn
				selectedTastedOn = true
			case "tasted_at":
				scanDest[i] = &result.TastedAt
			case "served_at":
				scanDest[i] = &result.ServedAt
			case "rested":
				scanDest[i] = &result.Rested
			case "verdict":
				scanDest[i] = &result.Verdict
			case "remarks":
				scanDest[i] = &tempRemarks
			case "tags":
				scanDest[i] = &result.Tags
			case "helpers":
				scanDest[i] = &result.Helpers
			case "bites":
				scanDest[i] = &tempBites
			case "entity_key":
				scanDest[i] = &result.EntityKey
			case "deleted_on_ref":
				scanDest[i] = &result.DeletedOnRef
			case "_version":
				scanDest[i] = &result.Version
			case "recipe_id":
				scanDest[i] = &tempRelRecipe
				selectedRelRecipe = true
			case "ref_id":
				scanDest[i] = &tempRelRef
				selectedRelRef = true
			default:
				return nil, fmt.Errorf("unexpected field %q for Tasting.FindOne", fieldName)
			}
		}

		err = row.Scan(scanDest...)
		if err == nil {
			// Copy nullable fields when present
			var jsonFieldDecodeErr error

			if selectedTastedOn && tempTastedOn.Valid {
				result.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
			}
			if len(tempRemarks) > 0 {
				if err := unmarshalGenericJSONFieldValue(tempRemarks, &result.Remarks); err != nil {
					jsonFieldDecodeErr = fmt.Errorf("failed to decode JSON field remarks: %w", err)
				}
			}
			if len(tempBites) > 0 {
				if err := unmarshalJSONListFieldValue(tempBites, &result.Bites, "bites", 2); err != nil {
					jsonFieldDecodeErr = fmt.Errorf("failed to decode JSON field bites: %w", err)
				}
			}
			if jsonFieldDecodeErr != nil {
				return nil, jsonFieldDecodeErr
			}

			// Set relationship IDs from scanned FK values
			if selectedRelRecipe && tempRelRecipe != nil {
				result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
			}
			if selectedRelRef && tempRelRef != nil {
				result.Ref.Id = tastingUUIDPtr(*tempRelRef)
			}
		}
	} else {
		// Scan all fields in schema order (matches DDL column order)
		err = row.Scan(

			&result.Id,

			&tempRelRecipe,

			&result.Taster,

			&result.Salty,

			&result.Score,

			&result.Servings,

			&tempTastedOn,

			&result.TastedAt,

			&result.ServedAt,

			&result.Rested,

			&result.Verdict,

			&tempRemarks,

			&result.Tags,

			&result.Helpers,

			&tempBites,

			&result.EntityKey,

			&tempRelRef,

			&result.DeletedOnRef,

			&result.Version,
		)

		if err == nil {
			// Copy nullable fields when present

			if tempTastedOn.Valid {
				result.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
			}
			if len(tempRemarks) > 0 {
				if err := unmarshalGenericJSONFieldValue(tempRemarks, &result.Remarks); err != nil {
					return nil, fmt.Errorf("failed to decode JSON field remarks: %w", err)
				}
			}
			if len(tempBites) > 0 {
				if err := unmarshalJSONListFieldValue(tempBites, &result.Bites, "bites", 2); err != nil {
					return nil, fmt.Errorf("failed to decode JSON field bites: %w", err)
				}
			}
		}
	}

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan row: %w", err)
	}

	// Hydrate relationship foreign keys into nested objects from typed field selections.
	if tempRelRecipe != nil {
		relRequested := opts != nil && (opts.Fields.Recipe || !opts.Fields.RecipeNested.IsZero())
		if relRequested {
			childFields := (RecipeFields{}).All()
			childFieldsAreDefault := true
			if !opts.Fields.RecipeNested.IsZero() {
				childFields = opts.Fields.RecipeNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchRecipeByIDs(ctx, []types.IdentityUUID{*tempRelRecipe}, &RecipeFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch recipe: %w", err)
			}
			if rel, ok := relMap[*tempRelRecipe]; ok {
				result.Recipe = *rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
			}
		} else {
			// Just set the ID when not including full entity
			result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
		}
	}
	if tempRelRef != nil {
		relRequested := opts != nil && (opts.Fields.Ref || !opts.Fields.RefNested.IsZero())
		if relRequested {
			childFields := (RecipeRefFields{}).All()
			childFieldsAreDefault := true
			if !opts.Fields.RefNested.IsZero() {
				childFields = opts.Fields.RefNested
				childFieldsAreDefault = false
			}

			relMap, err := r.batchRefByIDs(ctx, []types.IdentityUUID{*tempRelRef}, &RecipeRefFindOptions{
				Fields: childFields,
				Limit:  1,
			}, childFieldsAreDefault)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch ref: %w", err)
			}
			if rel, ok := relMap[*tempRelRef]; ok {
				result.Ref = *rel
			} else {
				// Preserve FK ID even when entity not found (e.g. soft-deleted)
				result.Ref.Id = tastingUUIDPtr(*tempRelRef)
			}
		} else {
			// Just set the ID when not including full entity
			result.Ref.Id = tastingUUIDPtr(*tempRelRef)
		}
	}

	return result, nil
}

// FindMany retrieves multiple Tasting records matching the filter
func (r *TastingRepository) FindMany(ctx context.Context, filter *TastingFilter, opts *TastingFindOptions) ([]*types.Tasting, int, error) {
	if opts == nil || opts.Fields.IsZero() {
		return nil, 0, fmt.Errorf("fields must be specified in FindOptions for performance")
	}

	// Build selected fields in OrderedMembers order so FK columns match scan order.
	var fieldStrings []string
	if opts.Fields.Id {
		fieldStrings = append(fieldStrings, "id")
	}
	if opts.Fields.Recipe || !opts.Fields.RecipeNested.IsZero() {
		fieldStrings = append(fieldStrings, "recipe_id")
	}
	if opts.Fields.Taster {
		fieldStrings = append(fieldStrings, "taster")
	}
	if opts.Fields.Salty {
		fieldStrings = append(fieldStrings, "salty")
	}
	if opts.Fields.Score {
		fieldStrings = append(fieldStrings, "score")
	}
	if opts.Fields.Servings {
		fieldStrings = append(fieldStrings, "servings")
	}
	if opts.Fields.TastedOn {
		fieldStrings = append(fieldStrings, "tasted_on")
	}
	if opts.Fields.TastedAt {
		fieldStrings = append(fieldStrings, "tasted_at")
	}
	if opts.Fields.ServedAt {
		fieldStrings = append(fieldStrings, "served_at")
	}
	if opts.Fields.Rested {
		fieldStrings = append(fieldStrings, "rested")
	}
	if opts.Fields.Verdict {
		fieldStrings = append(fieldStrings, "verdict")
	}
	if opts.Fields.Remarks {
		fieldStrings = append(fieldStrings, "remarks")
	}
	if opts.Fields.Tags {
		fieldStrings = append(fieldStrings, "tags")
	}
	if opts.Fields.Helpers {
		fieldStrings = append(fieldStrings, "helpers")
	}
	if opts.Fields.Bites {
		fieldStrings = append(fieldStrings, "bites")
	}
	if opts.Fields.EntityKey {
		fieldStrings = append(fieldStrings, "entity_key")
	}
	if opts.Fields.Ref || !opts.Fields.RefNested.IsZero() {
		fieldStrings = append(fieldStrings, "ref_id")
	}
	if opts.Fields.DeletedOnRef {
		fieldStrings = append(fieldStrings, "deleted_on_ref")
	}
	if opts.Fields.Version {
		fieldStrings = append(fieldStrings, "_version")
	}

	// Validate fields
	if err := validateFields(fieldStrings, TastingAllowedFields); err != nil {
		return nil, 0, err
	}

	// Build SELECT clause
	selectFields := buildSelectFieldsTyped(fieldStrings, "tasting")
	if selectFields == "" {
		return nil, 0, fmt.Errorf("no valid fields specified")
	}

	// Build WHERE clause
	var args []interface{}
	whereClause := filter.buildWhereClause(&args, 0)

	// Build ORDER BY clause
	orderByClause := buildTastingOrderByClause(opts.OrderBy, "tasting")

	// Build LIMIT/OFFSET clause
	limitOffsetClause := buildLimitOffsetClauseTyped(opts.Limit, opts.Offset)

	// Build query
	query := fmt.Sprintf(`SELECT %s FROM tasting%s%s%s`, selectFields, whereClause, orderByClause, limitOffsetClause)

	// Get total count
	countQuery := fmt.Sprintf(`SELECT COUNT(*) FROM tasting%s`, whereClause)

	var totalCount int
	var countRow pgx.Row
	if r.tx != nil {
		countRow = r.tx.QueryRow(ctx, countQuery, args...)
	} else {
		countRow = r.db.pool.QueryRow(ctx, countQuery, args...)
	}
	if err := countRow.Scan(&totalCount); err != nil {
		return nil, 0, fmt.Errorf("failed to get count: %w", err)
	}

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, args...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, args...)
	}
	if err != nil {
		return nil, 0, fmt.Errorf("failed to execute query: %w", err)
	}
	defer rows.Close()

	// Scan results
	results := []*types.Tasting{}
	for rows.Next() {
		result := &types.Tasting{}

		// Create temporary variables for nullable fields that need pointer scanning (per-row)

		var tempTastedOn pgtype.Date
		var tempRemarks []byte
		var tempBites []byte

		// Create temporary variables for relationship foreign keys (we don't store these directly on the struct)
		var tempRelRecipe *types.IdentityUUID
		var tempRelRef *types.IdentityUUID

		// Track whether special fields were selected so we can post-process after Scan.

		var selectedTastedOn bool
		var selectedRelRecipe bool
		var selectedRelRef bool

		scanDest := make([]any, len(fieldStrings))
		for i, fieldName := range fieldStrings {
			switch fieldName {
			case "id":
				scanDest[i] = &result.Id
			case "taster":
				scanDest[i] = &result.Taster
			case "salty":
				scanDest[i] = &result.Salty
			case "score":
				scanDest[i] = &result.Score
			case "servings":
				scanDest[i] = &result.Servings
			case "tasted_on":
				scanDest[i] = &tempTastedOn
				selectedTastedOn = true
			case "tasted_at":
				scanDest[i] = &result.TastedAt
			case "served_at":
				scanDest[i] = &result.ServedAt
			case "rested":
				scanDest[i] = &result.Rested
			case "verdict":
				scanDest[i] = &result.Verdict
			case "remarks":
				scanDest[i] = &tempRemarks
			case "tags":
				scanDest[i] = &result.Tags
			case "helpers":
				scanDest[i] = &result.Helpers
			case "bites":
				scanDest[i] = &tempBites
			case "entity_key":
				scanDest[i] = &result.EntityKey
			case "deleted_on_ref":
				scanDest[i] = &result.DeletedOnRef
			case "_version":
				scanDest[i] = &result.Version
			case "recipe_id":
				scanDest[i] = &tempRelRecipe
				selectedRelRecipe = true
			case "ref_id":
				scanDest[i] = &tempRelRef
				selectedRelRef = true
			default:
				return nil, 0, fmt.Errorf("unexpected field %q for Tasting.FindMany", fieldName)
			}
		}

		if err := rows.Scan(scanDest...); err != nil {
			return nil, 0, fmt.Errorf("failed to scan row: %w", err)
		}

		// Copy nullable fields when present
		var jsonFieldDecodeErr error

		if selectedTastedOn && tempTastedOn.Valid {
			result.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
		}
		if len(tempRemarks) > 0 {
			if err := unmarshalGenericJSONFieldValue(tempRemarks, &result.Remarks); err != nil {
				jsonFieldDecodeErr = fmt.Errorf("failed to decode JSON field remarks: %w", err)
			}
		}
		if len(tempBites) > 0 {
			if err := unmarshalJSONListFieldValue(tempBites, &result.Bites, "bites", 2); err != nil {
				jsonFieldDecodeErr = fmt.Errorf("failed to decode JSON field bites: %w", err)
			}
		}
		if jsonFieldDecodeErr != nil {
			return nil, 0, jsonFieldDecodeErr
		}

		// Set relationship IDs from scanned FK values (hydration happens after loop)
		if selectedRelRecipe && tempRelRecipe != nil {
			result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
		}
		if selectedRelRef && tempRelRef != nil {
			result.Ref.Id = tastingUUIDPtr(*tempRelRef)
		}

		results = append(results, result)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("error iterating rows: %w", err)
	}

	// Batch hydrate relationships (outside the row loop for efficiency)
	if opts.Fields.Recipe || !opts.Fields.RecipeNested.IsZero() {
		// Collect unique FK IDs from results (dedupe during collection)
		recipeIDSet := make(map[types.IdentityUUID]bool)
		var recipeIDs []types.IdentityUUID
		for _, result := range results {
			var zeroID types.IdentityUUID
			recipeID, ok := tastingUUIDValue(result.Recipe.Id)
			if ok && recipeID != zeroID && !recipeIDSet[recipeID] {
				recipeIDSet[recipeID] = true
				recipeIDs = append(recipeIDs, recipeID)
			}
		}

		// Batch fetch related entities with typed child field options.
		childFields := (RecipeFields{}).All()
		childFieldsAreDefault := true
		if !opts.Fields.RecipeNested.IsZero() {
			childFields = opts.Fields.RecipeNested
			childFieldsAreDefault = false
		}

		recipeMap, err := r.batchRecipeByIDs(ctx, recipeIDs, &RecipeFindOptions{
			Fields: childFields,
			Limit:  len(recipeIDs),
		}, childFieldsAreDefault)
		if err != nil {
			return nil, 0, fmt.Errorf("failed to batch fetch recipe: %w", err)
		}

		// Hydrate results from map
		for _, result := range results {
			recipeID, ok := tastingUUIDValue(result.Recipe.Id)
			if ok {
				if rel, ok := recipeMap[recipeID]; ok {
					result.Recipe = *rel
				}
			}
		}
	}
	if opts.Fields.Ref || !opts.Fields.RefNested.IsZero() {
		// Collect unique FK IDs from results (dedupe during collection)
		refIDSet := make(map[types.IdentityUUID]bool)
		var refIDs []types.IdentityUUID
		for _, result := range results {
			var zeroID types.IdentityUUID
			refID, ok := tastingUUIDValue(result.Ref.Id)
			if ok && refID != zeroID && !refIDSet[refID] {
				refIDSet[refID] = true
				refIDs = append(refIDs, refID)
			}
		}

		// Batch fetch related entities with typed child field options.
		childFields := (RecipeRefFields{}).All()
		childFieldsAreDefault := true
		if !opts.Fields.RefNested.IsZero() {
			childFields = opts.Fields.RefNested
			childFieldsAreDefault = false
		}

		refMap, err := r.batchRefByIDs(ctx, refIDs, &RecipeRefFindOptions{
			Fields: childFields,
			Limit:  len(refIDs),
		}, childFieldsAreDefault)
		if err != nil {
			return nil, 0, fmt.Errorf("failed to batch fetch ref: %w", err)
		}

		// Hydrate results from map
		for _, result := range results {
			refID, ok := tastingUUIDValue(result.Ref.Id)
			if ok {
				if rel, ok := refMap[refID]; ok {
					result.Ref = *rel
				}
			}
		}
	}

	return results, totalCount, nil
}

// CreateOne inserts a new Tasting record
func (r *TastingRepository) CreateOne(ctx context.Context, input *types.Tasting) (*types.Tasting, error) {
	// Set audit fields

	// Build INSERT query
	var fields []string
	var placeholders []string
	var values []interface{}
	paramNum := 0
	// Schema-owned identities may supply a stable UUID. A zero value keeps the
	// database-generated default used by ordinary creates.
	{
		var zeroPrimaryKey types.IdentityUUID
		if primaryKey, ok := tastingUUIDValue(input.Id); ok && primaryKey != zeroPrimaryKey {
			fields = append(fields, `id`)
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, primaryKey.ToUUID())
		}
	}
	// Required field: taster
	fields = append(fields, `taster`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Taster.ToUUID())
	// Required field: salty
	fields = append(fields, `salty`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Salty)
	// Required field: score
	fields = append(fields, `score`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Score)
	// Required field: servings
	fields = append(fields, `servings`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Servings)
	// Required field: tastedOn
	fields = append(fields, `tasted_on`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.TastedOn)
	// Required field: tastedAt
	fields = append(fields, `tasted_at`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, time.Time(input.TastedAt))
	// Required field: servedAt
	fields = append(fields, `served_at`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.ServedAt)
	// Required field: rested
	fields = append(fields, `rested`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Rested)
	// Required field: verdict
	fields = append(fields, `verdict`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Verdict)
	// Required field: remarks
	fields = append(fields, `remarks`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	jsonValueRemarks, err := marshalJSONFieldValue(input.Remarks)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal JSON field remarks: %w", err)
	}
	values = append(values, jsonValueRemarks)
	// Required field: tags
	fields = append(fields, `tags`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Tags)
	// Required field: helpers
	fields = append(fields, `helpers`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.Helpers)
	// Required field: bites
	fields = append(fields, `bites`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	jsonValueBites, err := marshalArrayOfArraysFieldValue(input.Bites)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal JSON field bites: %w", err)
	}
	values = append(values, jsonValueBites)
	// Auto-generated field: entityKey - only add if set
	{
		if !reflect.ValueOf(input.EntityKey).IsZero() {
			fields = append(fields, `entity_key`)
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, input.EntityKey.ToUUID())
		}
	}
	// Required field: deletedOnRef
	fields = append(fields, `deleted_on_ref`)
	paramNum++
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
	values = append(values, input.DeletedOnRef)

	// Handle relationship foreign key columns
	// Relationship: recipe (FK: recipe_id)
	{
		var zeroId types.IdentityUUID
		if relID, ok := tastingUUIDValue(input.Recipe.Id); ok && relID != zeroId {
			fields = append(fields, "recipe_id")
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, relID.ToUUID())
		}
	}
	// Relationship: ref (FK: ref_id)
	{
		var zeroId types.IdentityUUID
		if relID, ok := tastingUUIDValue(input.Ref.Id); ok && relID != zeroId {
			fields = append(fields, "ref_id")
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			values = append(values, relID.ToUUID())
		}
	}

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	returningClause := `"id", "recipe_id", "taster", "salty", "score", "servings", "tasted_on", "tasted_at", "served_at", "rested", "verdict", "remarks", "tags", "helpers", "bites", "entity_key", "ref_id", "deleted_on_ref", "_version"`
	query := fmt.Sprintf(
		`INSERT INTO tasting (%s) VALUES (%s) RETURNING %s`,
		strings.Join(fields, ", "),
		strings.Join(placeholders, ", "),
		returningClause,
	)

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, values...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, values...)
	}

	// Scan result
	result := &types.Tasting{}
	// Create temporary variables for nullable fields that need pointer scanning

	var tempTastedOn pgtype.Date
	var tempRemarks []byte
	var tempBites []byte

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)
	var tempRelRecipe *types.IdentityUUID
	var tempRelRef *types.IdentityUUID

	// Scan all fields in schema order (matches DDL column order)
	if err := row.Scan(

		&result.Id,

		&tempRelRecipe,

		&result.Taster,

		&result.Salty,

		&result.Score,

		&result.Servings,

		&tempTastedOn,

		&result.TastedAt,

		&result.ServedAt,

		&result.Rested,

		&result.Verdict,

		&tempRemarks,

		&result.Tags,

		&result.Helpers,

		&tempBites,

		&result.EntityKey,

		&tempRelRef,

		&result.DeletedOnRef,

		&result.Version,
	); err != nil {
		return nil, fmt.Errorf("failed to scan result: %w", err)
	}

	// Copy nullable fields when present

	if tempTastedOn.Valid {
		result.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
	}
	if len(tempRemarks) > 0 {
		if err := unmarshalGenericJSONFieldValue(tempRemarks, &result.Remarks); err != nil {
			return nil, fmt.Errorf("failed to decode JSON field remarks: %w", err)
		}
	}
	if len(tempBites) > 0 {
		if err := unmarshalJSONListFieldValue(tempBites, &result.Bites, "bites", 2); err != nil {
			return nil, fmt.Errorf("failed to decode JSON field bites: %w", err)
		}
	}

	// Set relationship IDs from scanned FK values
	if tempRelRecipe != nil {
		result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
	}
	if tempRelRef != nil {
		result.Ref.Id = tastingUUIDPtr(*tempRelRef)
	}

	return result, nil
}

// CreateMany inserts multiple Tasting records in a single statement
func (r *TastingRepository) CreateMany(ctx context.Context, inputs []*types.Tasting) ([]*types.Tasting, error) {
	if len(inputs) == 0 {
		return []*types.Tasting{}, nil
	}

	// Set audit fields

	// Build batch INSERT query - collect field names from first input
	var fieldNames []string
	// Schema-owned identities may supply stable UUIDs, matching CreateOne. One
	// INSERT has one column set, so a batch must supply ids for every row or
	// none; mixing is refused rather than silently dropping the supplied ids.
	explicitPrimaryKey := false
	{
		var zeroPrimaryKey types.IdentityUUID
		if primaryKey, ok := tastingUUIDValue(inputs[0].Id); ok && primaryKey != zeroPrimaryKey {
			explicitPrimaryKey = true
		}
		for _, input := range inputs {
			primaryKey, ok := tastingUUIDValue(input.Id)
			if (ok && primaryKey != zeroPrimaryKey) != explicitPrimaryKey {
				return nil, fmt.Errorf("inputs mix explicit and default primary keys; a batch must supply ids for every row or none")
			}
		}
	}
	if explicitPrimaryKey {
		fieldNames = append(fieldNames, `id`)
	}
	fieldNames = append(fieldNames, `taster`)
	fieldNames = append(fieldNames, `salty`)
	fieldNames = append(fieldNames, `score`)
	fieldNames = append(fieldNames, `servings`)
	fieldNames = append(fieldNames, `tasted_on`)
	fieldNames = append(fieldNames, `tasted_at`)
	fieldNames = append(fieldNames, `served_at`)
	fieldNames = append(fieldNames, `rested`)
	fieldNames = append(fieldNames, `verdict`)
	fieldNames = append(fieldNames, `remarks`)
	fieldNames = append(fieldNames, `tags`)
	fieldNames = append(fieldNames, `helpers`)
	fieldNames = append(fieldNames, `bites`)
	fieldNames = append(fieldNames, `deleted_on_ref`)

	// Add optional/auto-generated fields that are set in first input
	{
		if !reflect.ValueOf(inputs[0].EntityKey).IsZero() {
			fieldNames = append(fieldNames, `entity_key`)
		}
	}

	// Add relationship foreign key columns present in first input (matches CreateOne's column set)
	// Relationship: recipe (FK: recipe_id)
	{
		var zeroId types.IdentityUUID
		if relID, ok := tastingUUIDValue(inputs[0].Recipe.Id); ok && relID != zeroId {
			fieldNames = append(fieldNames, "recipe_id")
		}
	}
	// Relationship: ref (FK: ref_id)
	{
		var zeroId types.IdentityUUID
		if relID, ok := tastingUUIDValue(inputs[0].Ref.Id); ok && relID != zeroId {
			fieldNames = append(fieldNames, "ref_id")
		}
	}

	var valuePlaceholders []string
	var values []interface{}
	paramNum := 0

	for _, input := range inputs {
		var placeholders []string
		if explicitPrimaryKey {
			paramNum++
			placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
			primaryKey, _ := tastingUUIDValue(input.Id)
			values = append(values, primaryKey.ToUUID())
		}
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Taster.ToUUID())
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Salty)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Score)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Servings)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.TastedOn)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, time.Time(input.TastedAt))
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.ServedAt)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Rested)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Verdict)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		jsonValueRemarks, err := marshalJSONFieldValue(input.Remarks)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal JSON field remarks: %w", err)
		}
		values = append(values, jsonValueRemarks)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Tags)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.Helpers)
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		jsonValueBites, err := marshalArrayOfArraysFieldValue(input.Bites)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal JSON field bites: %w", err)
		}
		values = append(values, jsonValueBites)
		{
			if !reflect.ValueOf(input.EntityKey).IsZero() {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, input.EntityKey.ToUUID())
			}
		}
		paramNum++
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
		values = append(values, input.DeletedOnRef)

		// Handle relationship foreign key columns (per-row, matches CreateOne)
		// Relationship: recipe (FK: recipe_id)
		{
			var zeroId types.IdentityUUID
			if relID, ok := tastingUUIDValue(input.Recipe.Id); ok && relID != zeroId {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, relID.ToUUID())
			}
		}
		// Relationship: ref (FK: ref_id)
		{
			var zeroId types.IdentityUUID
			if relID, ok := tastingUUIDValue(input.Ref.Id); ok && relID != zeroId {
				paramNum++
				placeholders = append(placeholders, fmt.Sprintf("$%d", paramNum))
				values = append(values, relID.ToUUID())
			}
		}
		valuePlaceholders = append(valuePlaceholders, "("+strings.Join(placeholders, ", ")+")")
	}

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	returningClauseMany := `"id", "recipe_id", "taster", "salty", "score", "servings", "tasted_on", "tasted_at", "served_at", "rested", "verdict", "remarks", "tags", "helpers", "bites", "entity_key", "ref_id", "deleted_on_ref", "_version"`
	query := fmt.Sprintf(
		`INSERT INTO tasting (%s) VALUES %s RETURNING %s`,
		strings.Join(fieldNames, ", "),
		strings.Join(valuePlaceholders, ", "),
		returningClauseMany,
	)

	// Execute query
	var rows pgx.Rows
	var err error
	if r.tx != nil {
		rows, err = r.tx.Query(ctx, query, values...)
	} else {
		rows, err = r.db.pool.Query(ctx, query, values...)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to execute batch insert: %w", err)
	}
	defer rows.Close()

	// Scan results
	results := []*types.Tasting{}
	for rows.Next() {
		result := &types.Tasting{}
		// Create temporary variables for nullable fields that need pointer scanning

		var tempTastedOn pgtype.Date
		var tempRemarks []byte
		var tempBites []byte

		// Create temporary variables for relationship foreign keys (we don't store these in the struct)
		var tempRelRecipe *types.IdentityUUID
		var tempRelRef *types.IdentityUUID

		// Scan all fields in schema order (matches DDL column order)
		err := rows.Scan(

			&result.Id,

			&tempRelRecipe,

			&result.Taster,

			&result.Salty,

			&result.Score,

			&result.Servings,

			&tempTastedOn,

			&result.TastedAt,

			&result.ServedAt,

			&result.Rested,

			&result.Verdict,

			&tempRemarks,

			&result.Tags,

			&result.Helpers,

			&tempBites,

			&result.EntityKey,

			&tempRelRef,

			&result.DeletedOnRef,

			&result.Version,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan result: %w", err)
		}

		// Copy nullable fields when present

		if tempTastedOn.Valid {
			result.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
		}
		if len(tempRemarks) > 0 {
			if err := unmarshalGenericJSONFieldValue(tempRemarks, &result.Remarks); err != nil {
				return nil, fmt.Errorf("failed to decode JSON field remarks: %w", err)
			}
		}
		if len(tempBites) > 0 {
			if err := unmarshalJSONListFieldValue(tempBites, &result.Bites, "bites", 2); err != nil {
				return nil, fmt.Errorf("failed to decode JSON field bites: %w", err)
			}
		}

		// Set relationship IDs from scanned FK values
		if tempRelRecipe != nil {
			result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
		}
		if tempRelRef != nil {
			result.Ref.Id = tastingUUIDPtr(*tempRelRef)
		}
		results = append(results, result)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating results: %w", err)
	}

	return results, nil
}

// UpdateOne updates a single Tasting record by ID
func (r *TastingRepository) UpdateOne(ctx context.Context, id types.IdentityUUID, update *TastingUpdate) (*types.Tasting, error) {
	return r.updateOne(ctx, id, update, nil)
}

// UpdateOneIfVersion updates a single Tasting only if its current _version matches expectedVersion.
// It returns ErrVersionConflict when the row exists at another version and
// ErrNotFound when it does not exist.
func (r *TastingRepository) UpdateOneIfVersion(ctx context.Context, id types.IdentityUUID, expectedVersion int64, update *TastingUpdate) (*types.Tasting, error) {
	return r.updateOne(ctx, id, update, &expectedVersion)
}

// versionMiss tells apart why a write fenced on _version matched no row:
// ErrVersionConflict when the row exists at another version, ErrNotFound when
// it does not exist.
func (r *TastingRepository) versionMiss(ctx context.Context, id types.IdentityUUID) error {
	query := `SELECT _version FROM tasting WHERE id = $1`

	var version int64
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, id.ToUUID())
	} else {
		row = r.db.pool.QueryRow(ctx, query, id.ToUUID())
	}
	if err := row.Scan(&version); err != nil {
		if err == pgx.ErrNoRows {
			return ErrNotFound
		}
		return fmt.Errorf("failed to read Tasting version: %w", err)
	}
	return ErrVersionConflict
}

func (r *TastingRepository) updateOne(ctx context.Context, id types.IdentityUUID, update *TastingUpdate, expectedVersion *int64) (*types.Tasting, error) {
	// Build UPDATE query
	var setClauses []string
	var values []interface{}
	paramNum := 0
	if update.Taster != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`taster = $%d`, paramNum))
		values = append(values, (*update.Taster).ToUUID())
	}
	if update.Salty != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`salty = $%d`, paramNum))
		values = append(values, *update.Salty)
	}
	if update.Score != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`score = $%d`, paramNum))
		values = append(values, *update.Score)
	}
	if update.Servings != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`servings = $%d`, paramNum))
		values = append(values, *update.Servings)
	}
	if update.TastedOn != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`tasted_on = $%d`, paramNum))
		values = append(values, *update.TastedOn)
	}
	if update.TastedAt != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`tasted_at = $%d`, paramNum))
		values = append(values, time.Time(*update.TastedAt))
	}
	if update.ServedAt != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`served_at = $%d`, paramNum))
		values = append(values, *update.ServedAt)
	}
	if update.Rested != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`rested = $%d`, paramNum))
		values = append(values, *update.Rested)
	}
	if update.Verdict != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`verdict = $%d`, paramNum))
		values = append(values, *update.Verdict)
	}
	if update.Remarks != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`remarks = $%d`, paramNum))
		jsonValueRemarks, err := marshalJSONFieldValue(*update.Remarks)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal JSON field remarks: %w", err)
		}
		values = append(values, jsonValueRemarks)
	}
	if update.Tags != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`tags = $%d`, paramNum))
		values = append(values, *update.Tags)
	}
	if update.Helpers != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`helpers = $%d`, paramNum))
		values = append(values, *update.Helpers)
	}
	if update.Bites != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`bites = $%d`, paramNum))
		jsonValueBites, err := marshalArrayOfArraysFieldValue(*update.Bites)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal JSON field bites: %w", err)
		}
		values = append(values, jsonValueBites)
	}
	if update.EntityKey != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`entity_key = $%d`, paramNum))
		values = append(values, (*update.EntityKey).ToUUID())
	}
	if update.DeletedOnRef != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`deleted_on_ref = $%d`, paramNum))
		values = append(values, *update.DeletedOnRef)
	}
	// Handle relationship foreign key: recipe
	if update.RecipeID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("recipe_id = $%d", paramNum))
		values = append(values, update.RecipeID.ToUUID())
	}
	// Handle relationship foreign key: ref
	if update.RefID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("ref_id = $%d", paramNum))
		values = append(values, update.RefID.ToUUID())
	}

	// Set updated_at

	// Set updated_by

	if len(setClauses) == 0 {
		return nil, fmt.Errorf("no fields to update")
	}

	paramNum++
	values = append(values, id.ToUUID())

	query := fmt.Sprintf(
		`UPDATE tasting SET %s WHERE id = $%d`,
		strings.Join(setClauses, ", "),
		paramNum,
	)
	if expectedVersion != nil {
		paramNum++
		values = append(values, *expectedVersion)
		query += fmt.Sprintf(" AND _version = $%d", paramNum)
	}

	// Build RETURNING clause with explicit column order matching scan order (using OrderedMembers for schema order)
	query += ` RETURNING "id", "recipe_id", "taster", "salty", "score", "servings", "tasted_on", "tasted_at", "served_at", "rested", "verdict", "remarks", "tags", "helpers", "bites", "entity_key", "ref_id", "deleted_on_ref", "_version"`

	// Execute query
	var row pgx.Row
	if r.tx != nil {
		row = r.tx.QueryRow(ctx, query, values...)
	} else {
		row = r.db.pool.QueryRow(ctx, query, values...)
	}

	// Scan result
	result := &types.Tasting{}
	// Create temporary variables for nullable fields that need pointer scanning

	var tempTastedOn pgtype.Date
	var tempRemarks []byte
	var tempBites []byte

	// Create temporary variables for relationship foreign keys (we don't store these in the struct)
	var tempRelRecipe *types.IdentityUUID
	var tempRelRef *types.IdentityUUID

	// Scan all fields in schema order (matches DDL column order)
	if err := row.Scan(

		&result.Id,

		&tempRelRecipe,

		&result.Taster,

		&result.Salty,

		&result.Score,

		&result.Servings,

		&tempTastedOn,

		&result.TastedAt,

		&result.ServedAt,

		&result.Rested,

		&result.Verdict,

		&tempRemarks,

		&result.Tags,

		&result.Helpers,

		&tempBites,

		&result.EntityKey,

		&tempRelRef,

		&result.DeletedOnRef,

		&result.Version,
	); err != nil {
		if err == pgx.ErrNoRows {
			if expectedVersion != nil {
				return nil, r.versionMiss(ctx, id)
			}
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to scan result: %w", err)
	}

	// Copy nullable fields when present

	if tempTastedOn.Valid {
		result.TastedOn = types.TemporalDate(tempTastedOn.Time.Format("2006-01-02"))
	}
	if len(tempRemarks) > 0 {
		if err := unmarshalGenericJSONFieldValue(tempRemarks, &result.Remarks); err != nil {
			return nil, fmt.Errorf("failed to decode JSON field remarks: %w", err)
		}
	}
	if len(tempBites) > 0 {
		if err := unmarshalJSONListFieldValue(tempBites, &result.Bites, "bites", 2); err != nil {
			return nil, fmt.Errorf("failed to decode JSON field bites: %w", err)
		}
	}

	// Set relationship IDs from scanned FK values
	if tempRelRecipe != nil {
		result.Recipe.Id = tastingUUIDPtr(*tempRelRecipe)
	}
	if tempRelRef != nil {
		result.Ref.Id = tastingUUIDPtr(*tempRelRef)
	}

	return result, nil
}

// UpdateMany updates multiple Tasting records matching the filter
func (r *TastingRepository) UpdateMany(ctx context.Context, filter *TastingFilter, update *TastingUpdate) (int, error) {
	// Build UPDATE query
	var setClauses []string
	var values []interface{}
	paramNum := 0
	if update.Taster != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`taster = $%d`, paramNum))
		values = append(values, (*update.Taster).ToUUID())
	}
	if update.Salty != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`salty = $%d`, paramNum))
		values = append(values, *update.Salty)
	}
	if update.Score != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`score = $%d`, paramNum))
		values = append(values, *update.Score)
	}
	if update.Servings != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`servings = $%d`, paramNum))
		values = append(values, *update.Servings)
	}
	if update.TastedOn != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`tasted_on = $%d`, paramNum))
		values = append(values, *update.TastedOn)
	}
	if update.TastedAt != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`tasted_at = $%d`, paramNum))
		values = append(values, time.Time(*update.TastedAt))
	}
	if update.ServedAt != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`served_at = $%d`, paramNum))
		values = append(values, *update.ServedAt)
	}
	if update.Rested != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`rested = $%d`, paramNum))
		values = append(values, *update.Rested)
	}
	if update.Verdict != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`verdict = $%d`, paramNum))
		values = append(values, *update.Verdict)
	}
	if update.Remarks != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`remarks = $%d`, paramNum))
		jsonValueRemarks, err := marshalJSONFieldValue(*update.Remarks)
		if err != nil {
			return 0, fmt.Errorf("failed to marshal JSON field remarks: %w", err)
		}
		values = append(values, jsonValueRemarks)
	}
	if update.Tags != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`tags = $%d`, paramNum))
		values = append(values, *update.Tags)
	}
	if update.Helpers != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`helpers = $%d`, paramNum))
		values = append(values, *update.Helpers)
	}
	if update.Bites != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`bites = $%d`, paramNum))
		jsonValueBites, err := marshalArrayOfArraysFieldValue(*update.Bites)
		if err != nil {
			return 0, fmt.Errorf("failed to marshal JSON field bites: %w", err)
		}
		values = append(values, jsonValueBites)
	}
	if update.EntityKey != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`entity_key = $%d`, paramNum))
		values = append(values, (*update.EntityKey).ToUUID())
	}
	if update.DeletedOnRef != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf(`deleted_on_ref = $%d`, paramNum))
		values = append(values, *update.DeletedOnRef)
	}
	// Handle relationship foreign key: recipe
	if update.RecipeID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("recipe_id = $%d", paramNum))
		values = append(values, update.RecipeID.ToUUID())
	}
	// Handle relationship foreign key: ref
	if update.RefID != nil {
		paramNum++
		setClauses = append(setClauses, fmt.Sprintf("ref_id = $%d", paramNum))
		values = append(values, update.RefID.ToUUID())
	}

	// Set updated_at

	// Set updated_by

	if len(setClauses) == 0 {
		return 0, fmt.Errorf("no fields to update")
	}

	// Build WHERE clause
	whereClause := filter.buildWhereClause(&values, paramNum)

	query := fmt.Sprintf(
		`UPDATE tasting SET %s%s`,
		strings.Join(setClauses, ", "),
		whereClause,
	)

	// Execute query
	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, values...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, values...)
	}
	if err != nil {
		return 0, fmt.Errorf("failed to execute update: %w", err)
	}

	return int(result.RowsAffected()), nil
}

// DeleteOne permanently deletes a single Tasting record by ID
func (r *TastingRepository) DeleteOne(ctx context.Context, id types.IdentityUUID) error {
	query := `DELETE FROM tasting WHERE id = $1`

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, id.ToUUID())
	} else {
		result, err = r.db.pool.Exec(ctx, query, id.ToUUID())
	}
	if err != nil {
		return fmt.Errorf("failed to delete record: %w", err)
	}

	if result.RowsAffected() == 0 {
		return ErrNotFound
	}

	return nil
}

// DeleteOneIfVersion permanently deletes a single Tasting only if its
// current _version matches expectedVersion. It returns ErrVersionConflict when
// the row exists at another version and ErrNotFound when it does not exist.
func (r *TastingRepository) DeleteOneIfVersion(ctx context.Context, id types.IdentityUUID, expectedVersion int64) error {
	query := `DELETE FROM tasting WHERE id = $1 AND _version = $2`
	queryArgs := []interface{}{id.ToUUID(), expectedVersion}

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, queryArgs...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, queryArgs...)
	}
	if err != nil {
		return fmt.Errorf("failed to delete record: %w", err)
	}

	if result.RowsAffected() == 0 {
		return r.versionMiss(ctx, id)
	}

	return nil
}

// DeleteMany permanently deletes multiple Tasting records matching the filter
func (r *TastingRepository) DeleteMany(ctx context.Context, filter *TastingFilter) (int, error) {
	// Build WHERE clause
	var values []interface{}
	whereClause := filter.buildWhereClause(&values, 0)

	query := fmt.Sprintf(`DELETE FROM tasting%s`, whereClause)

	var result pgconn.CommandTag
	var err error
	if r.tx != nil {
		result, err = r.tx.Exec(ctx, query, values...)
	} else {
		result, err = r.db.pool.Exec(ctx, query, values...)
	}
	if err != nil {
		return 0, fmt.Errorf("failed to delete records: %w", err)
	}

	return int(result.RowsAffected()), nil
}
