//! Code generated by superschematic topcoat. DO NOT EDIT.
//!
//! A form per input type an in-process call of fixture-forms-api takes. Its
//! struct holds each field as the browser sends it, so a form that is
//! refused re-renders as it was sent; `parse` reads it into the input by
//! the input type's rules (D14); and its component renders the fields with
//! the attributes those rules give them. A browser checks those attributes
//! before it sends the form, and `parse` checks every rule again.
//!
//! A control is named by its field's path in the input: `email`, a nested
//! object's field `guest.name`, a row's `rooms[0].adults`, a list of
//! values' `tags[0]`. A form decodes from the pairs a browser posts
//! (`Form<...Form>`, or `from_pairs`) into its struct, rows in the order of
//! their indexes, and its errors are keyed by the same names, so each
//! message renders at its control. A list's rows are added and removed by
//! submit buttons named `_action` (`add:rooms`, `remove:rooms[1]`), which
//! `apply_action` applies without JavaScript.

use std::collections::BTreeMap;

use crate::api::runtime::ApiError;
use crate::api::runtime::schema::{ParseError, UnknownFields};
use crate::api::types;
use serde::{Deserialize, Deserializer};
use serde_json::{Map, Value};
use topcoat::view::{View, component, view};

/// Why a form was refused: each control's messages, and the form's own.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct FormErrors {
    /// Each control's messages, by its name in the form: `email`,
    /// `guest.name`, `rooms[0].adults`.
    pub fields: Vec<(String, Vec<String>)>,
    /// Messages about the form as a whole.
    pub form: Vec<String>,
}

impl FormErrors {
    pub fn is_empty(&self) -> bool {
        self.fields.is_empty() && self.form.is_empty()
    }

    /// The control's messages.
    pub fn of(&self, field: &str) -> Vec<String> {
        self.fields
            .iter()
            .filter(|(name, _)| name == field)
            .flat_map(|(_, messages)| messages.iter().cloned())
            .collect()
    }

    /// The messages of a control and of the values under it, each of
    /// those after its place: a JSON value's member (`vip: expected a
    /// string`), a group's item.
    pub fn under(&self, field: &str) -> Vec<String> {
        let mut out = Vec::new();
        for (name, messages) in &self.fields {
            if name == field {
                out.extend(messages.iter().cloned());
            } else if let Some(place) = place_under(name, field) {
                out.extend(messages.iter().map(|message| format!("{place}: {message}")));
            }
        }
        out
    }

    /// A control's `aria-invalid`: "true" when it, or a value under it, has
    /// a message.
    pub fn invalid(&self, field: &str) -> Option<&'static str> {
        self.fields
            .iter()
            .any(|(name, _)| name == field || place_under(name, field).is_some())
            .then_some("true")
    }

    pub fn add(&mut self, field: &str, message: impl Into<String>) {
        match self.fields.iter_mut().find(|(name, _)| name == field) {
            Some((_, messages)) => messages.push(message.into()),
            None => self.fields.push((field.to_owned(), vec![message.into()])),
        }
    }

    /// The errors of an operation's refusal: its field errors (its `errors`
    /// member, nested for a nested object's fields) when it has them, else
    /// its detail, so a form shows what the operation refused as it shows
    /// what `parse` refused.
    pub fn from_api(err: &ApiError) -> Self {
        let mut errors = Self::default();
        if let Some(fields) = err.errors.as_deref() {
            errors.read("", fields);
        }
        if errors.is_empty() {
            errors.form.push(err.message.clone());
        }
        errors
    }

    /// Reads field errors keyed by path, nested for a nested object's
    /// fields (`{"rooms[0]": {"adults": [...]}}`), each a list of
    /// `{validator, message}`.
    fn read(&mut self, prefix: &str, fields: &Value) {
        for (key, value) in fields.as_object().into_iter().flatten() {
            let field = if prefix.is_empty() { key.clone() } else { format!("{prefix}.{key}") };
            match value {
                Value::Array(messages) => {
                    for message in messages {
                        if let Some(text) = message.get("message").and_then(Value::as_str) {
                            self.add(&field, text);
                        }
                    }
                }
                nested => self.read(&field, nested),
            }
        }
    }

    /// The form's own messages, and those of a place the component shows
    /// no control for (an `@uiHidden` field, a key the input does not
    /// declare), each after its name.
    fn unshown(&self, shows: fn(&[Segment]) -> bool) -> Vec<String> {
        let mut out = self.form.clone();
        for (name, messages) in &self.fields {
            if !segments(name).is_some_and(|path| shows(&path)) {
                out.extend(messages.iter().map(|message| format!("{name}: {message}")));
            }
        }
        out
    }
}

/// Where `name` is under `field`: `vip` of `labels.vip`, `[1]` of
/// `tags[1]`.
fn place_under<'a>(name: &'a str, field: &str) -> Option<&'a str> {
    let rest = name.strip_prefix(field)?;
    rest.strip_prefix('.').or_else(|| rest.starts_with('[').then_some(rest))
}

impl From<ParseError> for FormErrors {
    fn from(err: ParseError) -> Self {
        let mut errors = Self::default();
        if let ParseError::Invalid(fields) = &err {
            for (field, messages) in fields.flatten() {
                for message in messages {
                    errors.add(&field, message.message);
                }
            }
        }
        if errors.is_empty() {
            errors.form.push(err.to_string());
        }
        errors
    }
}

/// Options the app supplies for a form's text and number controls, each
/// of which then renders as a `<select>`. An input type does not say which
/// values an id may take (a product's, a room's), so the page that renders
/// the form says, per field.
///
/// A field is named by its path with the rows' indexes left out,
/// `rooms.roomId` for every room's, or by its control's name,
/// `rooms[0].roomId` for one row's, which wins.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Choices {
    fields: Vec<(String, Vec<Choice>)>,
}

/// One option: the value a form sends and the label it shows.
#[derive(Debug, Clone, PartialEq)]
pub struct Choice {
    pub value: String,
    pub label: String,
}

impl Choices {
    pub fn new() -> Self {
        Self::default()
    }

    /// These choices with `field`'s options, each a value and its label,
    /// in order.
    #[must_use]
    pub fn with<V: Into<String>, L: Into<String>>(
        mut self,
        field: impl Into<String>,
        options: impl IntoIterator<Item = (V, L)>,
    ) -> Self {
        let options = options
            .into_iter()
            .map(|(value, label)| Choice { value: value.into(), label: label.into() })
            .collect();
        self.fields.push((field.into(), options));
        self
    }

    /// The options of the control named `name`, else of its `path`.
    pub fn of(&self, name: &str, path: &str) -> Option<&[Choice]> {
        self.find(name).or_else(|| self.find(path))
    }

    fn find(&self, field: &str) -> Option<&[Choice]> {
        self.fields
            .iter()
            .rev()
            .find(|(name, _)| name == field)
            .map(|(_, options)| options.as_slice())
    }
}

/// A select's options: each choice, selected when it is the value held,
/// and the value held when no choice is it, so a form renders as sent.
fn choice_options(options: &[Choice], held: Option<&str>) -> Vec<(String, String, bool)> {
    let mut out: Vec<_> = options
        .iter()
        .map(|option| (option.value.clone(), option.label.clone(), held == Some(option.value.as_str())))
        .collect();
    if let Some(held) = held
        && !options.iter().any(|option| option.value == held)
    {
        out.push((held.to_owned(), held.to_owned(), true));
    }
    out
}

/// A step of a control's name: a field's key, or a row's index.
#[derive(Debug, Clone, PartialEq)]
enum Segment {
    Key(String),
    Index(usize),
}

/// The most steps a name a form reads has.
const MAX_DEPTH: usize = 32;

/// A control's name as its steps, `rooms[0].roomId` as `rooms`, `0` and
/// `roomId`; None for a name no control has.
fn segments(name: &str) -> Option<Vec<Segment>> {
    let mut path = Vec::new();
    let mut rest = name;
    loop {
        let end = rest.find(['.', '[']).unwrap_or(rest.len());
        if end == 0 {
            return None;
        }
        path.push(Segment::Key(rest[..end].to_owned()));
        rest = &rest[end..];
        while let Some(index) = rest.strip_prefix('[') {
            let (digits, after) = index.split_once(']')?;
            path.push(Segment::Index(digits.parse().ok()?));
            rest = after;
        }
        if path.len() > MAX_DEPTH {
            return None;
        }
        if rest.is_empty() {
            return Some(path);
        }
        rest = rest.strip_prefix('.')?;
    }
}

/// The pairs a form posts, as a tree of their names: `rooms[0].roomId` is
/// the value of key `roomId` of row 0 of key `rooms`. A name no control
/// has is left out.
#[derive(Debug, Default)]
struct Posted {
    values: Vec<String>,
    keys: BTreeMap<String, Posted>,
    rows: BTreeMap<usize, Posted>,
}

/// What a name holds when nothing was posted under it.
static NOTHING: Posted = Posted { values: Vec::new(), keys: BTreeMap::new(), rows: BTreeMap::new() };

impl Posted {
    fn from_pairs(pairs: impl IntoIterator<Item = (String, String)>) -> Self {
        let mut root = Self::default();
        for (name, value) in pairs {
            let Some(path) = segments(&name) else {
                continue;
            };
            let mut node = &mut root;
            for segment in path {
                node = match segment {
                    Segment::Key(key) => node.keys.entry(key).or_default(),
                    Segment::Index(index) => node.rows.entry(index).or_default(),
                };
            }
            node.values.push(value);
        }
        root
    }

    /// What was posted under `key`.
    fn get(&self, key: &str) -> &Posted {
        self.keys.get(key).unwrap_or(&NOTHING)
    }

    /// The last value posted at this name, unless it is empty, as a browser
    /// sends a blank control.
    fn text(&self) -> Option<String> {
        self.values.last().filter(|value| !value.is_empty()).cloned()
    }

    /// Each value posted at this name that is not empty: a group's checked
    /// members.
    fn texts(&self) -> Vec<String> {
        self.values.iter().filter(|value| !value.is_empty()).cloned().collect()
    }

    /// Each row posted under this name, in the order of their indexes.
    fn rows(&self) -> impl Iterator<Item = &Posted> {
        self.rows.values()
    }
}

/// What one control sent, read as the input's JSON: nothing, a value, or
/// the message of a value it cannot be.
type Read = Result<Option<Value>, &'static str>;

/// Puts a control's value at `key`, or its message at its control.
fn put(json: &mut Map<String, Value>, errors: &mut FormErrors, key: &str, name: &str, read: Read) {
    match read {
        Ok(Some(value)) => {
            json.insert(key.to_owned(), value);
        }
        Ok(None) => {}
        Err(message) => errors.add(name, message),
    }
}

/// Puts a list at `key`: always when the input requires it, else when it
/// holds an item.
fn put_list(json: &mut Map<String, Value>, key: &str, items: Vec<Value>, required: bool) {
    if required || !items.is_empty() {
        json.insert(key.to_owned(), Value::Array(items));
    }
}

/// A row of a list of values: its value, or null for a row that sent none,
/// which the input's rules refuse at the row, as a list holds no null; a
/// value the row cannot be is its message.
fn row(errors: &mut FormErrors, name: &str, read: Read) -> Value {
    match read {
        Ok(value) => value.unwrap_or(Value::Null),
        Err(message) => {
            errors.add(name, message);
            Value::Null
        }
    }
}

/// A text control's value as sent, when it sent one.
fn text(value: &Option<String>) -> Read {
    Ok(value.as_deref().map(Value::from))
}

/// A checkbox: true when the browser sent it, which it does when checked.
fn boolean(value: &Option<String>) -> Read {
    Ok(Some(Value::from(value.is_some())))
}

/// A whole number, refused when it is not one.
fn integer(value: &Option<String>) -> Read {
    match value {
        None => Ok(None),
        Some(text) => text.trim().parse::<i64>().map(|number| Some(Value::from(number))).map_err(|_| "must be a whole number"),
    }
}

/// A number, refused when it is not one.
fn number(value: &Option<String>) -> Read {
    match value.as_deref().map(|text| text.trim().parse::<f64>()) {
        None => Ok(None),
        Some(Ok(number)) if number.is_finite() => Ok(Some(Value::from(number))),
        Some(_) => Err("must be a number"),
    }
}

/// A date and time from a `datetime-local` control, which carries no
/// offset, read as UTC: `2026-10-09T14:30` is `2026-10-09T14:30:00Z`. A
/// value with an offset, which an app may set, keeps it.
fn date_time(value: &Option<String>) -> Read {
    match value.as_deref().map(str::trim) {
        None => Ok(None),
        Some(text) => utc_date_time(text).map(|text| Some(Value::from(text))).ok_or("must be a date and time"),
    }
}

/// `YYYY-MM-DDTHH:MM`, with seconds and a fraction or not, as the API
/// reads it: in UTC unless it ends in an offset (`Z`, `+01:00`). None for
/// any other text, or a date or a time that does not exist.
fn utc_date_time(text: &str) -> Option<String> {
    let (date, rest) = text.split_once('T')?;
    let (clock, offset) = rest.split_at(rest.find(['Z', '+', '-']).unwrap_or(rest.len()));
    let (d, c, o) = (date.as_bytes(), clock.as_bytes(), offset.as_bytes());
    let year = digits(d, 0..4).filter(|year| *year >= 1000)?;
    let month = digits(d, 5..7).filter(|month| (1..=12).contains(month))?;
    digits(d, 8..10).filter(|day| (1..=days_in_month(year, month)).contains(day))?;
    digits(c, 0..2).filter(|hour| *hour < 24)?;
    digits(c, 3..5).filter(|minute| *minute < 60)?;
    let seconds = match c.len() {
        5 => ":00",
        8.. if c[5] == b':'
            && digits(c, 6..8).is_some_and(|second| second < 60)
            && (c.len() == 8 || (c[8] == b'.' && c.len() > 9 && c[9..].iter().all(u8::is_ascii_digit))) =>
        {
            ""
        }
        _ => return None,
    };
    let offset_ok = match o {
        [] | [b'Z'] => true,
        [b'+' | b'-', ..] => {
            o.len() == 6
                && o[3] == b':'
                && digits(o, 1..3).is_some_and(|hour| hour < 24)
                && digits(o, 4..6).is_some_and(|minute| minute < 60)
        }
        _ => false,
    };
    let zone = if offset.is_empty() { "Z" } else { offset };
    (d.len() == 10 && d[4] == b'-' && d[7] == b'-' && c[2] == b':' && offset_ok)
        .then(|| format!("{date}T{clock}{seconds}{zone}"))
}

/// The number the ASCII digits at `range` spell, when they are all digits.
fn digits(bytes: &[u8], range: std::ops::Range<usize>) -> Option<u32> {
    let digits = bytes.get(range)?;
    digits
        .iter()
        .all(u8::is_ascii_digit)
        .then(|| digits.iter().fold(0, |number, digit| number * 10 + u32::from(digit - b'0')))
}

fn days_in_month(year: u32, month: u32) -> u32 {
    match month {
        2 if year.is_multiple_of(4) && (!year.is_multiple_of(100) || year.is_multiple_of(400)) => 29,
        2 => 28,
        4 | 6 | 9 | 11 => 30,
        _ => 31,
    }
}

/// A date and time as a `datetime-local` control shows it: a UTC value
/// without its `Z`.
fn local_date_time(value: Option<&str>) -> Option<&str> {
    value.map(|value| value.strip_suffix('Z').or_else(|| value.strip_suffix("+00:00")).unwrap_or(value))
}

/// A JSON value, from its text.
fn json_text(value: &Option<String>) -> Read {
    match value {
        None => Ok(None),
        Some(text) => serde_json::from_str(text).map(Some).map_err(|_| "must be JSON"),
    }
}

/// Whether a group's checkbox for `value` is checked.
fn checked(values: &[String], value: &str) -> bool {
    values.iter().any(|sent| sent == value)
}

/// A list's bounds: a row button adds no row past `max`, the list's
/// listMax, and removes none at `min`, its listMin.
#[derive(Clone, Copy)]
struct Bounds {
    min: usize,
    max: Option<usize>,
}

/// Applies a row action to `rows` at `path`: adds a row (`new`) when
/// `path` is the list, or removes the row it names, within `bounds`; a
/// path into a row is the row's (`act`). True when it did.
fn act_on_rows<T>(
    rows: &mut Vec<T>,
    path: &[Segment],
    add: bool,
    bounds: Bounds,
    new: impl FnOnce() -> T,
    act: impl FnOnce(&mut T, &[Segment], bool) -> bool,
) -> bool {
    match path {
        [] if add => {
            let room = bounds.max.is_none_or(|max| rows.len() < max);
            if room {
                rows.push(new());
            }
            room
        }
        [Segment::Index(index)] if !add => {
            let removable = *index < rows.len() && rows.len() > bounds.min;
            if removable {
                rows.remove(*index);
            }
            removable
        }
        [Segment::Index(index), rest @ ..] => rows.get_mut(*index).is_some_and(|row| act(row, rest, add)),
        _ => false,
    }
}

/// The row action of a row that holds no list.
fn no_rows<T>(_row: &mut T, _path: &[Segment], _add: bool) -> bool {
    false
}

/// A JSON value or a group shows the errors at it and under it.
fn shows_all(_path: &[Segment]) -> bool {
    true
}

/// A list of values shows its errors and each row's.
fn shows_row(path: &[Segment]) -> bool {
    matches!(path, [] | [Segment::Index(_)])
}

/// A list of objects shows its errors, each row's, and what each row's
/// struct shows.
fn shows_rows(path: &[Segment], shows: fn(&[Segment]) -> bool) -> bool {
    match path {
        [] => true,
        [Segment::Index(_), rest @ ..] => shows(rest),
        _ => false,
    }
}

/// The form of `BillingAddress`, each field as the browser sends it.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct BillingAddressForm {
    pub line1: Option<String>,
    pub city: Option<String>,
    pub postcode: Option<String>,
}

impl BillingAddressForm {
    /// A new form: each field's `@default`, a required nested object's new
    /// form, and each list's first rows: its listMin, or one when the
    /// input requires the list. An optional nested object starts empty.
    pub fn new() -> Self {
        Self {
            line1: None,
            city: None,
            postcode: None,
        }
    }

    /// The form as posted under `posted`.
    fn from_posted(posted: &Posted) -> Self {
        Self {
            line1: posted.get("line1").text(),
            city: posted.get("city").text(),
            postcode: posted.get("postcode").text(),
        }
    }

    /// Each field as the input type's JSON, its controls named under `at`;
    /// a value a control cannot hold is an error at the control.
    fn write(&self, at: &str, errors: &mut FormErrors) -> Map<String, Value> {
        let mut json = Map::new();
        put(&mut json, errors, "line1", &format!("{at}line1"), text(&self.line1));
        put(&mut json, errors, "city", &format!("{at}city"), text(&self.city));
        put(&mut json, errors, "postcode", &format!("{at}postcode"), text(&self.postcode));
        json
    }

    /// Whether a field was sent: an optional nested object is part of the
    /// input only then.
    fn is_sent(&self) -> bool {
        self.line1.is_some() || self.city.is_some() || self.postcode.is_some()
    }

    /// Whether the component shows the errors at `path`: at a control, a
    /// nested object's or a list's fieldset, or a row.
    fn shows(path: &[Segment]) -> bool {
        match path {
            [] => true,
            [Segment::Key(key), rest @ ..] => match key.as_str() {
                "line1" => rest.is_empty(),
                "city" => rest.is_empty(),
                "postcode" => rest.is_empty(),
                _ => false,
            },
            _ => false,
        }
    }
}

/// The form of `BookingInput`, each field as the browser sends it.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct BookingInputForm {
    pub guest: GuestForm,
    pub billing: BillingAddressForm,
    pub rooms: Vec<RoomRequestForm>,
    pub amenities: Vec<String>,
    pub arrival: Option<String>,
    pub check_in: Option<String>,
    pub hold_until: Option<String>,
    pub door_code: Option<String>,
    pub currency: Option<String>,
    pub preferences: Option<String>,
    pub labels: Option<String>,
    /// The row button that submitted the form (`_action`), which
    /// `apply_action` applies.
    pub row_action: Option<String>,
}

impl BookingInputForm {
    /// A new form: each field's `@default`, a required nested object's new
    /// form, and each list's first rows: its listMin, or one when the
    /// input requires the list. An optional nested object starts empty.
    pub fn new() -> Self {
        Self {
            guest: GuestForm::new(),
            billing: BillingAddressForm::default(),
            rooms: vec![RoomRequestForm::new(); 1],
            amenities: Vec::new(),
            arrival: None,
            check_in: None,
            hold_until: None,
            door_code: None,
            currency: Some("GBP".to_owned()),
            preferences: None,
            labels: None,
            row_action: None,
        }
    }

    /// The form a browser posted, from its pairs: each control read by its
    /// name, a list's rows in the order of their indexes.
    /// `Form<BookingInputForm>` decodes a post this way.
    pub fn from_pairs(pairs: impl IntoIterator<Item = (String, String)>) -> Self {
        let posted = Posted::from_pairs(pairs);
        Self { row_action: posted.get("_action").text(), ..Self::from_posted(&posted) }
    }

    /// The input: each field read as the input type's JSON, then parsed by
    /// the type's rules with undeclared keys refused; else each control's
    /// errors.
    pub fn parse(&self) -> Result<types::BookingInput, FormErrors> {
        let mut errors = FormErrors::default();
        let json = self.write("", &mut errors);
        if !errors.is_empty() {
            return Err(errors);
        }
        types::validators::parse_booking_input(Value::Object(json), UnknownFields::Refuse).map_err(FormErrors::from)
    }

    /// Applies the row button that submitted the form, `row_action`: `add:`
    /// and a list's name adds a row to it unless it holds its listMax, and
    /// `remove:` and a row's name removes the row unless its list holds no
    /// more than its listMin; the other rows keep their values, numbered
    /// again. True when a row button submitted the form, whether or not
    /// the list's bounds let it act: the page renders the form again and
    /// does not call the operation.
    pub fn apply_action(&mut self) -> bool {
        let Some(action) = self.row_action.take() else {
            return false;
        };
        let (add, name) = match action.split_once(':') {
            Some(("add", name)) => (true, name),
            Some(("remove", name)) => (false, name),
            _ => return true,
        };
        if let Some(path) = segments(name) {
            self.act(&path, add);
        }
        true
    }

    /// The form as posted under `posted`.
    fn from_posted(posted: &Posted) -> Self {
        Self {
            guest: GuestForm::from_posted(posted.get("guest")),
            billing: BillingAddressForm::from_posted(posted.get("billing")),
            rooms: posted.get("rooms").rows().map(RoomRequestForm::from_posted).collect(),
            amenities: posted.get("amenities").texts(),
            arrival: posted.get("arrival").text(),
            check_in: posted.get("checkIn").text(),
            hold_until: posted.get("holdUntil").text(),
            door_code: posted.get("doorCode").text(),
            currency: posted.get("currency").text(),
            preferences: posted.get("preferences").text(),
            labels: posted.get("labels").text(),
            row_action: None,
        }
    }

    /// Each field as the input type's JSON, its controls named under `at`;
    /// a value a control cannot hold is an error at the control.
    fn write(&self, at: &str, errors: &mut FormErrors) -> Map<String, Value> {
        let mut json = Map::new();
        json.insert("guest".to_owned(), Value::Object(self.guest.write(&format!("{at}guest."), errors)));
        if self.billing.is_sent() {
            json.insert("billing".to_owned(), Value::Object(self.billing.write(&format!("{at}billing."), errors)));
        }
        let rows: Vec<Value> = self
            .rooms
            .iter()
            .enumerate()
            .map(|(index, row)| Value::Object(row.write(&format!("{at}rooms[{index}]."), errors)))
            .collect();
        put_list(&mut json, "rooms", rows, true);
        put_list(&mut json, "amenities", self.amenities.iter().map(|value| Value::from(value.as_str())).collect(), false);
        put(&mut json, errors, "arrival", &format!("{at}arrival"), text(&self.arrival));
        put(&mut json, errors, "checkIn", &format!("{at}checkIn"), text(&self.check_in));
        put(&mut json, errors, "holdUntil", &format!("{at}holdUntil"), date_time(&self.hold_until));
        put(&mut json, errors, "doorCode", &format!("{at}doorCode"), text(&self.door_code));
        put(&mut json, errors, "currency", &format!("{at}currency"), text(&self.currency));
        put(&mut json, errors, "preferences", &format!("{at}preferences"), json_text(&self.preferences));
        put(&mut json, errors, "labels", &format!("{at}labels"), json_text(&self.labels));
        json
    }

    /// Whether the component shows the errors at `path`: at a control, a
    /// nested object's or a list's fieldset, or a row.
    fn shows(path: &[Segment]) -> bool {
        match path {
            [] => true,
            [Segment::Key(key), rest @ ..] => match key.as_str() {
                "guest" => GuestForm::shows(rest),
                "billing" => BillingAddressForm::shows(rest),
                "rooms" => shows_rows(rest, RoomRequestForm::shows),
                "amenities" => shows_all(rest),
                "arrival" => rest.is_empty(),
                "checkIn" => rest.is_empty(),
                "holdUntil" => rest.is_empty(),
                "doorCode" => rest.is_empty(),
                "currency" => rest.is_empty(),
                "preferences" => shows_all(rest),
                "labels" => shows_all(rest),
                _ => false,
            },
            _ => false,
        }
    }

    /// Applies a row action at `path`: adds a row to the list there, or
    /// removes the row there, within the list's bounds. True when it did.
    fn act(&mut self, path: &[Segment], add: bool) -> bool {
        let [Segment::Key(key), rest @ ..] = path else {
            return false;
        };
        match key.as_str() {
            "rooms" => act_on_rows(&mut self.rooms, rest, add, Bounds { min: 1, max: Some(3) }, RoomRequestForm::new, no_rows),
            _ => false,
        }
    }
}

impl<'de> Deserialize<'de> for BookingInputForm {
    /// Reads the pairs of a post, as Topcoat's `Form` hands them, by
    /// `from_pairs`.
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Vec::<(String, String)>::deserialize(deserializer).map(Self::from_pairs)
    }
}

/// The form of `Guest`, each field as the browser sends it.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct GuestForm {
    pub name: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
}

impl GuestForm {
    /// A new form: each field's `@default`, a required nested object's new
    /// form, and each list's first rows: its listMin, or one when the
    /// input requires the list. An optional nested object starts empty.
    pub fn new() -> Self {
        Self {
            name: None,
            email: None,
            phone: None,
        }
    }

    /// The form as posted under `posted`.
    fn from_posted(posted: &Posted) -> Self {
        Self {
            name: posted.get("name").text(),
            email: posted.get("email").text(),
            phone: posted.get("phone").text(),
        }
    }

    /// Each field as the input type's JSON, its controls named under `at`;
    /// a value a control cannot hold is an error at the control.
    fn write(&self, at: &str, errors: &mut FormErrors) -> Map<String, Value> {
        let mut json = Map::new();
        put(&mut json, errors, "name", &format!("{at}name"), text(&self.name));
        put(&mut json, errors, "email", &format!("{at}email"), text(&self.email));
        put(&mut json, errors, "phone", &format!("{at}phone"), text(&self.phone));
        json
    }

    /// Whether the component shows the errors at `path`: at a control, a
    /// nested object's or a list's fieldset, or a row.
    fn shows(path: &[Segment]) -> bool {
        match path {
            [] => true,
            [Segment::Key(key), rest @ ..] => match key.as_str() {
                "name" => rest.is_empty(),
                "email" => rest.is_empty(),
                "phone" => rest.is_empty(),
                _ => false,
            },
            _ => false,
        }
    }
}

/// The form of `NoteInput`, each field as the browser sends it.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct NoteInputForm {
    pub text: Option<String>,
    pub tags: Vec<Option<String>>,
    /// The row button that submitted the form (`_action`), which
    /// `apply_action` applies.
    pub row_action: Option<String>,
}

impl NoteInputForm {
    /// A new form: each field's `@default`, a required nested object's new
    /// form, and each list's first rows: its listMin, or one when the
    /// input requires the list. An optional nested object starts empty.
    pub fn new() -> Self {
        Self {
            text: None,
            tags: Vec::new(),
            row_action: None,
        }
    }

    /// The form a browser posted, from its pairs: each control read by its
    /// name, a list's rows in the order of their indexes.
    /// `Form<NoteInputForm>` decodes a post this way.
    pub fn from_pairs(pairs: impl IntoIterator<Item = (String, String)>) -> Self {
        let posted = Posted::from_pairs(pairs);
        Self { row_action: posted.get("_action").text(), ..Self::from_posted(&posted) }
    }

    /// The input: each field read as the input type's JSON, then parsed by
    /// the type's rules with undeclared keys refused; else each control's
    /// errors.
    pub fn parse(&self) -> Result<types::NoteInput, FormErrors> {
        let mut errors = FormErrors::default();
        let json = self.write("", &mut errors);
        if !errors.is_empty() {
            return Err(errors);
        }
        types::validators::parse_note_input(Value::Object(json), UnknownFields::Refuse).map_err(FormErrors::from)
    }

    /// Applies the row button that submitted the form, `row_action`: `add:`
    /// and a list's name adds a row to it unless it holds its listMax, and
    /// `remove:` and a row's name removes the row unless its list holds no
    /// more than its listMin; the other rows keep their values, numbered
    /// again. True when a row button submitted the form, whether or not
    /// the list's bounds let it act: the page renders the form again and
    /// does not call the operation.
    pub fn apply_action(&mut self) -> bool {
        let Some(action) = self.row_action.take() else {
            return false;
        };
        let (add, name) = match action.split_once(':') {
            Some(("add", name)) => (true, name),
            Some(("remove", name)) => (false, name),
            _ => return true,
        };
        if let Some(path) = segments(name) {
            self.act(&path, add);
        }
        true
    }

    /// The form as posted under `posted`.
    fn from_posted(posted: &Posted) -> Self {
        Self {
            text: posted.get("text").text(),
            tags: posted.get("tags").rows().map(Posted::text).collect(),
            row_action: None,
        }
    }

    /// Each field as the input type's JSON, its controls named under `at`;
    /// a value a control cannot hold is an error at the control.
    fn write(&self, at: &str, errors: &mut FormErrors) -> Map<String, Value> {
        let mut json = Map::new();
        put(&mut json, errors, "text", &format!("{at}text"), text(&self.text));
        let rows: Vec<Value> = self
            .tags
            .iter()
            .enumerate()
            .map(|(index, value)| row(errors, &format!("{at}tags[{index}]"), text(value)))
            .collect();
        put_list(&mut json, "tags", rows, false);
        json
    }

    /// Whether the component shows the errors at `path`: at a control, a
    /// nested object's or a list's fieldset, or a row.
    fn shows(path: &[Segment]) -> bool {
        match path {
            [] => true,
            [Segment::Key(key), rest @ ..] => match key.as_str() {
                "text" => rest.is_empty(),
                "tags" => shows_row(rest),
                _ => false,
            },
            _ => false,
        }
    }

    /// Applies a row action at `path`: adds a row to the list there, or
    /// removes the row there, within the list's bounds. True when it did.
    fn act(&mut self, path: &[Segment], add: bool) -> bool {
        let [Segment::Key(key), rest @ ..] = path else {
            return false;
        };
        match key.as_str() {
            "tags" => act_on_rows(&mut self.tags, rest, add, Bounds { min: 0, max: Some(3) }, || None, no_rows),
            _ => false,
        }
    }
}

impl<'de> Deserialize<'de> for NoteInputForm {
    /// Reads the pairs of a post, as Topcoat's `Form` hands them, by
    /// `from_pairs`.
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Vec::<(String, String)>::deserialize(deserializer).map(Self::from_pairs)
    }
}

/// The form of `RoomRequest`, each field as the browser sends it.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct RoomRequestForm {
    pub room_id: Option<String>,
    pub adults: Option<String>,
    pub extras: Vec<String>,
}

impl RoomRequestForm {
    /// A new form: each field's `@default`, a required nested object's new
    /// form, and each list's first rows: its listMin, or one when the
    /// input requires the list. An optional nested object starts empty.
    pub fn new() -> Self {
        Self {
            room_id: None,
            adults: None,
            extras: Vec::new(),
        }
    }

    /// The form as posted under `posted`.
    fn from_posted(posted: &Posted) -> Self {
        Self {
            room_id: posted.get("roomId").text(),
            adults: posted.get("adults").text(),
            extras: posted.get("extras").texts(),
        }
    }

    /// Each field as the input type's JSON, its controls named under `at`;
    /// a value a control cannot hold is an error at the control.
    fn write(&self, at: &str, errors: &mut FormErrors) -> Map<String, Value> {
        let mut json = Map::new();
        put(&mut json, errors, "roomId", &format!("{at}roomId"), text(&self.room_id));
        put(&mut json, errors, "adults", &format!("{at}adults"), integer(&self.adults));
        put_list(&mut json, "extras", self.extras.iter().map(|value| Value::from(value.as_str())).collect(), false);
        json
    }

    /// Whether the component shows the errors at `path`: at a control, a
    /// nested object's or a list's fieldset, or a row.
    fn shows(path: &[Segment]) -> bool {
        match path {
            [] => true,
            [Segment::Key(key), rest @ ..] => match key.as_str() {
                "roomId" => rest.is_empty(),
                "adults" => rest.is_empty(),
                "extras" => shows_all(rest),
                _ => false,
            },
            _ => false,
        }
    }
}

/// The form of `SignupInput`, each field as the browser sends it.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SignupInputForm {
    pub email: Option<String>,
    pub display_name: Option<String>,
    pub handle: Option<String>,
    pub website: Option<String>,
    pub plan: Option<String>,
    pub seats: Option<String>,
    pub budget: Option<String>,
    pub newsletter: Option<String>,
}

impl SignupInputForm {
    /// A new form: each field's `@default`, a required nested object's new
    /// form, and each list's first rows: its listMin, or one when the
    /// input requires the list. An optional nested object starts empty.
    pub fn new() -> Self {
        Self {
            email: None,
            display_name: None,
            handle: None,
            website: None,
            plan: None,
            seats: None,
            budget: None,
            newsletter: None,
        }
    }

    /// The form a browser posted, from its pairs: each control read by its
    /// name, a list's rows in the order of their indexes.
    /// `Form<SignupInputForm>` decodes a post this way.
    pub fn from_pairs(pairs: impl IntoIterator<Item = (String, String)>) -> Self {
        let posted = Posted::from_pairs(pairs);
        Self::from_posted(&posted)
    }

    /// The input: each field read as the input type's JSON, then parsed by
    /// the type's rules with undeclared keys refused; else each control's
    /// errors.
    pub fn parse(&self) -> Result<types::SignupInput, FormErrors> {
        let mut errors = FormErrors::default();
        let json = self.write("", &mut errors);
        if !errors.is_empty() {
            return Err(errors);
        }
        types::validators::parse_signup_input(Value::Object(json), UnknownFields::Refuse).map_err(FormErrors::from)
    }

    /// The form as posted under `posted`.
    fn from_posted(posted: &Posted) -> Self {
        Self {
            email: posted.get("email").text(),
            display_name: posted.get("displayName").text(),
            handle: posted.get("handle").text(),
            website: posted.get("website").text(),
            plan: posted.get("plan").text(),
            seats: posted.get("seats").text(),
            budget: posted.get("budget").text(),
            newsletter: posted.get("newsletter").text(),
        }
    }

    /// Each field as the input type's JSON, its controls named under `at`;
    /// a value a control cannot hold is an error at the control.
    fn write(&self, at: &str, errors: &mut FormErrors) -> Map<String, Value> {
        let mut json = Map::new();
        put(&mut json, errors, "email", &format!("{at}email"), text(&self.email));
        put(&mut json, errors, "displayName", &format!("{at}displayName"), text(&self.display_name));
        put(&mut json, errors, "handle", &format!("{at}handle"), text(&self.handle));
        put(&mut json, errors, "website", &format!("{at}website"), text(&self.website));
        put(&mut json, errors, "plan", &format!("{at}plan"), text(&self.plan));
        put(&mut json, errors, "seats", &format!("{at}seats"), integer(&self.seats));
        put(&mut json, errors, "budget", &format!("{at}budget"), number(&self.budget));
        put(&mut json, errors, "newsletter", &format!("{at}newsletter"), boolean(&self.newsletter));
        json
    }

    /// Whether the component shows the errors at `path`: at a control, a
    /// nested object's or a list's fieldset, or a row.
    fn shows(path: &[Segment]) -> bool {
        match path {
            [] => true,
            [Segment::Key(key), rest @ ..] => match key.as_str() {
                "email" => rest.is_empty(),
                "displayName" => rest.is_empty(),
                "handle" => rest.is_empty(),
                "website" => rest.is_empty(),
                "plan" => rest.is_empty(),
                "seats" => rest.is_empty(),
                "budget" => rest.is_empty(),
                "newsletter" => rest.is_empty(),
                _ => false,
            },
            _ => false,
        }
    }
}

impl<'de> Deserialize<'de> for SignupInputForm {
    /// Reads the pairs of a post, as Topcoat's `Form` hands them, by
    /// `from_pairs`.
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Vec::<(String, String)>::deserialize(deserializer).map(Self::from_pairs)
    }
}

/// The fields of `BookingInputForm`, each with its label, its value as sent,
/// the attributes the input type's rules give it and its errors; a nested
/// object's in a fieldset, and a list's rows with their buttons. `form` is
/// a new form when the page passes none, and `choices` turns a text or
/// number field the app names into a select.
#[component]
pub async fn booking_input_fields(
    #[default(BookingInputForm::new())] form: BookingInputForm,
    #[default] errors: FormErrors,
    #[default] choices: Choices,
) -> topcoat::Result<impl View> {
    let form_errors = errors.unshown(BookingInputForm::shows);
    Ok(view! {
        // The button Enter presses, ahead of every row button: it submits
        // the form without an `_action`.
        <button type="submit" class="ss-submit" hidden=(true)></button>
        for message in form_errors {
            <p class="form-error">(message)</p>
        }
        <fieldset class="ss-object" data-field="guest">
            <legend>"Guest"</legend>
            for message in errors.of("guest") {
                <p class="field-error">(message)</p>
            }
            <div class="field">
                <label for="booking-input-guest-name">"Name"</label>
                match choices.of("guest.name", "guest.name") {
                    Some(options) => {
                        <select id="booking-input-guest-name" name="guest.name" required=(true) aria-invalid=(errors.invalid("guest.name"))>
                            <option value="" selected=(form.guest.name.is_none())>""</option>
                            for (value, label, selected) in choice_options(options, form.guest.name.as_deref()) {
                                <option value=(value) selected=(selected)>(label)</option>
                            }
                        </select>
                    }
                    None => <input id="booking-input-guest-name" name="guest.name" type="text" required=(true) minlength="2" value=(form.guest.name.clone()) aria-invalid=(errors.invalid("guest.name"))>,
                }
                for message in errors.of("guest.name") {
                    <p class="field-error">(message)</p>
                }
            </div>
            <div class="field">
                <label for="booking-input-guest-email">"Email"</label>
                match choices.of("guest.email", "guest.email") {
                    Some(options) => {
                        <select id="booking-input-guest-email" name="guest.email" required=(true) aria-invalid=(errors.invalid("guest.email"))>
                            <option value="" selected=(form.guest.email.is_none())>""</option>
                            for (value, label, selected) in choice_options(options, form.guest.email.as_deref()) {
                                <option value=(value) selected=(selected)>(label)</option>
                            }
                        </select>
                    }
                    None => <input id="booking-input-guest-email" name="guest.email" type="email" required=(true) maxlength="255" value=(form.guest.email.clone()) aria-invalid=(errors.invalid("guest.email"))>,
                }
                for message in errors.of("guest.email") {
                    <p class="field-error">(message)</p>
                }
            </div>
            <div class="field">
                <label for="booking-input-guest-phone">"Phone"</label>
                match choices.of("guest.phone", "guest.phone") {
                    Some(options) => {
                        <select id="booking-input-guest-phone" name="guest.phone" aria-invalid=(errors.invalid("guest.phone"))>
                            <option value="" selected=(form.guest.phone.is_none())>""</option>
                            for (value, label, selected) in choice_options(options, form.guest.phone.as_deref()) {
                                <option value=(value) selected=(selected)>(label)</option>
                            }
                        </select>
                    }
                    None => <input id="booking-input-guest-phone" name="guest.phone" type="text" value=(form.guest.phone.clone()) aria-invalid=(errors.invalid("guest.phone"))>,
                }
                for message in errors.of("guest.phone") {
                    <p class="field-error">(message)</p>
                }
            </div>
        </fieldset>
        <fieldset class="ss-object" data-field="billing">
            <legend>"Billing address"</legend>
            for message in errors.of("billing") {
                <p class="field-error">(message)</p>
            }
            <div class="field">
                <label for="booking-input-billing-line1">"Address line 1"</label>
                match choices.of("billing.line1", "billing.line1") {
                    Some(options) => {
                        <select id="booking-input-billing-line1" name="billing.line1" aria-invalid=(errors.invalid("billing.line1"))>
                            <option value="" selected=(form.billing.line1.is_none())>""</option>
                            for (value, label, selected) in choice_options(options, form.billing.line1.as_deref()) {
                                <option value=(value) selected=(selected)>(label)</option>
                            }
                        </select>
                    }
                    None => <input id="booking-input-billing-line1" name="billing.line1" type="text" value=(form.billing.line1.clone()) aria-invalid=(errors.invalid("billing.line1"))>,
                }
                for message in errors.of("billing.line1") {
                    <p class="field-error">(message)</p>
                }
            </div>
            <div class="field">
                <label for="booking-input-billing-city">"City"</label>
                match choices.of("billing.city", "billing.city") {
                    Some(options) => {
                        <select id="booking-input-billing-city" name="billing.city" aria-invalid=(errors.invalid("billing.city"))>
                            <option value="" selected=(form.billing.city.is_none())>""</option>
                            for (value, label, selected) in choice_options(options, form.billing.city.as_deref()) {
                                <option value=(value) selected=(selected)>(label)</option>
                            }
                        </select>
                    }
                    None => <input id="booking-input-billing-city" name="billing.city" type="text" value=(form.billing.city.clone()) aria-invalid=(errors.invalid("billing.city"))>,
                }
                for message in errors.of("billing.city") {
                    <p class="field-error">(message)</p>
                }
            </div>
            <div class="field">
                <label for="booking-input-billing-postcode">"Postcode"</label>
                match choices.of("billing.postcode", "billing.postcode") {
                    Some(options) => {
                        <select id="booking-input-billing-postcode" name="billing.postcode" aria-invalid=(errors.invalid("billing.postcode"))>
                            <option value="" selected=(form.billing.postcode.is_none())>""</option>
                            for (value, label, selected) in choice_options(options, form.billing.postcode.as_deref()) {
                                <option value=(value) selected=(selected)>(label)</option>
                            }
                        </select>
                    }
                    None => <input id="booking-input-billing-postcode" name="billing.postcode" type="text" value=(form.billing.postcode.clone()) aria-invalid=(errors.invalid("billing.postcode"))>,
                }
                for message in errors.of("billing.postcode") {
                    <p class="field-error">(message)</p>
                }
            </div>
        </fieldset>
        <fieldset class="ss-list" data-field="rooms">
            <legend>"Rooms"</legend>
            for message in errors.of("rooms") {
                <p class="field-error">(message)</p>
            }
            for (i0, row0) in form.rooms.iter().enumerate() {
                <fieldset class="ss-row">
                    let row = format!("rooms[{i0}]");
                    let label = format!("Room {}", i0 + 1);
                    <legend>(&label)</legend>
                    <input type="hidden" name=(&row) value="">
                    for message in errors.of(&row) {
                        <p class="field-error">(message)</p>
                    }
                    <div class="field">
                        let name = format!("rooms[{i0}].roomId");
                        let id = format!("booking-input-rooms-{i0}-room-id");
                        <label for=(&id)>"Room"</label>
                        match choices.of(&name, "rooms.roomId") {
                            Some(options) => {
                                <select id=(&id) name=(&name) required=(true) aria-invalid=(errors.invalid(&name))>
                                    <option value="" selected=(row0.room_id.is_none())>""</option>
                                    for (value, label, selected) in choice_options(options, row0.room_id.as_deref()) {
                                        <option value=(value) selected=(selected)>(label)</option>
                                    }
                                </select>
                            }
                            None => <input id=(&id) name=(&name) type="text" required=(true) pattern="^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$" value=(row0.room_id.clone()) aria-invalid=(errors.invalid(&name))>,
                        }
                        for message in errors.of(&name) {
                            <p class="field-error">(message)</p>
                        }
                    </div>
                    <div class="field">
                        let name = format!("rooms[{i0}].adults");
                        let id = format!("booking-input-rooms-{i0}-adults");
                        <label for=(&id)>"Adults"</label>
                        match choices.of(&name, "rooms.adults") {
                            Some(options) => {
                                <select id=(&id) name=(&name) required=(true) aria-invalid=(errors.invalid(&name))>
                                    <option value="" selected=(row0.adults.is_none())>""</option>
                                    for (value, label, selected) in choice_options(options, row0.adults.as_deref()) {
                                        <option value=(value) selected=(selected)>(label)</option>
                                    }
                                </select>
                            }
                            None => <input id=(&id) name=(&name) type="number" required=(true) step="1" min="1" max="4" value=(row0.adults.clone()) aria-invalid=(errors.invalid(&name))>,
                        }
                        for message in errors.of(&name) {
                            <p class="field-error">(message)</p>
                        }
                    </div>
                    <fieldset class="ss-choices" data-field="extras">
                        let name = format!("rooms[{i0}].extras");
                        <legend>"Extras"</legend>
                        for message in errors.under(&name) {
                            <p class="field-error">(message)</p>
                        }
                        <label class="ss-choice"><input type="checkbox" name=(&name) value="wifi" checked=(checked(&row0.extras, "wifi"))>"Wifi"</label>
                        <label class="ss-choice"><input type="checkbox" name=(&name) value="breakfast" checked=(checked(&row0.extras, "breakfast"))>"Breakfast"</label>
                        <label class="ss-choice"><input type="checkbox" name=(&name) value="late_checkout" checked=(checked(&row0.extras, "late_checkout"))>"Late checkout"</label>
                    </fieldset>
                    if form.rooms.len() > 1 {
                        <button type="submit" class="ss-remove" name="_action" value=(format!("remove:{row}")) formnovalidate=(true) aria-label=(format!("Remove {label}"))>"Remove"</button>
                    }
                </fieldset>
            }
            if form.rooms.len() < 3 {
                <button type="submit" class="ss-add" name="_action" value="add:rooms" formnovalidate=(true)>"Add a room"</button>
            }
        </fieldset>
        <fieldset class="ss-choices" data-field="amenities">
            <legend>"Amenities"</legend>
            for message in errors.under("amenities") {
                <p class="field-error">(message)</p>
            }
            <label class="ss-choice"><input type="checkbox" name="amenities" value="wifi" checked=(checked(&form.amenities, "wifi"))>"Wifi"</label>
            <label class="ss-choice"><input type="checkbox" name="amenities" value="breakfast" checked=(checked(&form.amenities, "breakfast"))>"Breakfast"</label>
            <label class="ss-choice"><input type="checkbox" name="amenities" value="late_checkout" checked=(checked(&form.amenities, "late_checkout"))>"Late checkout"</label>
        </fieldset>
        <div class="field">
            <label for="booking-input-arrival">"Arrival"</label>
            <input id="booking-input-arrival" name="arrival" type="date" required=(true) value=(form.arrival.clone()) aria-invalid=(errors.invalid("arrival"))>
            for message in errors.of("arrival") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="booking-input-check-in">"Check-in time"</label>
            <input id="booking-input-check-in" name="checkIn" type="time" value=(form.check_in.clone()) aria-invalid=(errors.invalid("checkIn"))>
            for message in errors.of("checkIn") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="booking-input-hold-until">"Hold until (UTC)"</label>
            <input id="booking-input-hold-until" name="holdUntil" type="datetime-local" value=(local_date_time(form.hold_until.as_deref())) aria-invalid=(errors.invalid("holdUntil"))>
            for message in errors.of("holdUntil") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="booking-input-door-code">"Door code"</label>
            <input id="booking-input-door-code" name="doorCode" type="password" minlength="4" autocomplete="off" aria-invalid=(errors.invalid("doorCode"))>
            for message in errors.of("doorCode") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="booking-input-currency">"Currency"</label>
            match choices.of("currency", "currency") {
                Some(options) => {
                    <select id="booking-input-currency" name="currency" aria-invalid=(errors.invalid("currency"))>
                        <option value="" selected=(form.currency.is_none())>""</option>
                        for (value, label, selected) in choice_options(options, form.currency.as_deref()) {
                            <option value=(value) selected=(selected)>(label)</option>
                        }
                    </select>
                }
                None => <input id="booking-input-currency" name="currency" type="text" pattern="^[A-Z]{3}$" value=(form.currency.clone()) aria-invalid=(errors.invalid("currency"))>,
            }
            for message in errors.of("currency") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="booking-input-preferences">"Preferences (JSON)"</label>
            <textarea id="booking-input-preferences" name="preferences" rows="4" spellcheck="false" aria-invalid=(errors.invalid("preferences"))>(form.preferences.clone())</textarea>
            for message in errors.under("preferences") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="booking-input-labels">"Labels (JSON)"</label>
            <textarea id="booking-input-labels" name="labels" rows="4" spellcheck="false" aria-invalid=(errors.invalid("labels"))>(form.labels.clone())</textarea>
            for message in errors.under("labels") {
                <p class="field-error">(message)</p>
            }
        </div>
    })
}

/// The fields of `NoteInputForm`, each with its label, its value as sent,
/// the attributes the input type's rules give it and its errors; a nested
/// object's in a fieldset, and a list's rows with their buttons. `form` is
/// a new form when the page passes none, and `choices` turns a text or
/// number field the app names into a select.
#[component]
pub async fn note_input_fields(
    #[default(NoteInputForm::new())] form: NoteInputForm,
    #[default] errors: FormErrors,
    #[default] choices: Choices,
) -> topcoat::Result<impl View> {
    let form_errors = errors.unshown(NoteInputForm::shows);
    Ok(view! {
        // The button Enter presses, ahead of every row button: it submits
        // the form without an `_action`.
        <button type="submit" class="ss-submit" hidden=(true)></button>
        for message in form_errors {
            <p class="form-error">(message)</p>
        }
        <div class="field">
            <label for="note-input-text">"Text"</label>
            match choices.of("text", "text") {
                Some(options) => {
                    <select id="note-input-text" name="text" required=(true) aria-invalid=(errors.invalid("text"))>
                        <option value="" selected=(form.text.is_none())>""</option>
                        for (value, label, selected) in choice_options(options, form.text.as_deref()) {
                            <option value=(value) selected=(selected)>(label)</option>
                        }
                    </select>
                }
                None => <input id="note-input-text" name="text" type="text" required=(true) value=(form.text.clone()) aria-invalid=(errors.invalid("text"))>,
            }
            for message in errors.of("text") {
                <p class="field-error">(message)</p>
            }
        </div>
        <fieldset class="ss-list" data-field="tags">
            <legend>"Tags"</legend>
            for message in errors.of("tags") {
                <p class="field-error">(message)</p>
            }
            for (i0, row0) in form.tags.iter().enumerate() {
                <div class="field ss-row">
                    let name = format!("tags[{i0}]");
                    let id = format!("note-input-tags-{i0}");
                    let label = format!("Tags {}", i0 + 1);
                    <label for=(&id)>(&label)</label>
                    match choices.of(&name, "tags") {
                        Some(options) => {
                            <select id=(&id) name=(&name) required=(true) aria-invalid=(errors.invalid(&name))>
                                <option value="" selected=(row0.is_none())>""</option>
                                for (value, label, selected) in choice_options(options, row0.as_deref()) {
                                    <option value=(value) selected=(selected)>(label)</option>
                                }
                            </select>
                        }
                        None => <input id=(&id) name=(&name) type="text" required=(true) value=(row0.clone()) aria-invalid=(errors.invalid(&name))>,
                    }
                    <button type="submit" class="ss-remove" name="_action" value=(format!("remove:{name}")) formnovalidate=(true) aria-label=(format!("Remove {label}"))>"Remove"</button>
                    for message in errors.of(&name) {
                        <p class="field-error">(message)</p>
                    }
                </div>
            }
            if form.tags.len() < 3 {
                <button type="submit" class="ss-add" name="_action" value="add:tags" formnovalidate=(true)>"Add"</button>
            }
        </fieldset>
    })
}

/// The fields of `SignupInputForm`, each with its label, its value as sent,
/// the attributes the input type's rules give it and its errors; a nested
/// object's in a fieldset, and a list's rows with their buttons. `form` is
/// a new form when the page passes none, and `choices` turns a text or
/// number field the app names into a select.
#[component]
pub async fn signup_input_fields(
    #[default(SignupInputForm::new())] form: SignupInputForm,
    #[default] errors: FormErrors,
    #[default] choices: Choices,
) -> topcoat::Result<impl View> {
    let form_errors = errors.unshown(SignupInputForm::shows);
    Ok(view! {
        for message in form_errors {
            <p class="form-error">(message)</p>
        }
        <div class="field">
            <label for="signup-input-email">"Email"</label>
            match choices.of("email", "email") {
                Some(options) => {
                    <select id="signup-input-email" name="email" required=(true) aria-invalid=(errors.invalid("email"))>
                        <option value="" selected=(form.email.is_none())>""</option>
                        for (value, label, selected) in choice_options(options, form.email.as_deref()) {
                            <option value=(value) selected=(selected)>(label)</option>
                        }
                    </select>
                }
                None => <input id="signup-input-email" name="email" type="email" required=(true) maxlength="255" value=(form.email.clone()) aria-invalid=(errors.invalid("email"))>,
            }
            for message in errors.of("email") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="signup-input-display-name">"Display name"</label>
            match choices.of("displayName", "displayName") {
                Some(options) => {
                    <select id="signup-input-display-name" name="displayName" required=(true) aria-invalid=(errors.invalid("displayName"))>
                        <option value="" selected=(form.display_name.is_none())>""</option>
                        for (value, label, selected) in choice_options(options, form.display_name.as_deref()) {
                            <option value=(value) selected=(selected)>(label)</option>
                        }
                    </select>
                }
                None => <input id="signup-input-display-name" name="displayName" type="text" required=(true) minlength="2" maxlength="40" placeholder="Ada Lovelace" value=(form.display_name.clone()) aria-invalid=(errors.invalid("displayName"))>,
            }
            for message in errors.of("displayName") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="signup-input-handle">"Handle"</label>
            match choices.of("handle", "handle") {
                Some(options) => {
                    <select id="signup-input-handle" name="handle" aria-invalid=(errors.invalid("handle"))>
                        <option value="" selected=(form.handle.is_none())>""</option>
                        for (value, label, selected) in choice_options(options, form.handle.as_deref()) {
                            <option value=(value) selected=(selected)>(label)</option>
                        }
                    </select>
                }
                None => <input id="signup-input-handle" name="handle" type="text" pattern="^[a-z0-9]+$" value=(form.handle.clone()) aria-invalid=(errors.invalid("handle"))>,
            }
            for message in errors.of("handle") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="signup-input-website">"Website"</label>
            match choices.of("website", "website") {
                Some(options) => {
                    <select id="signup-input-website" name="website" aria-invalid=(errors.invalid("website"))>
                        <option value="" selected=(form.website.is_none())>""</option>
                        for (value, label, selected) in choice_options(options, form.website.as_deref()) {
                            <option value=(value) selected=(selected)>(label)</option>
                        }
                    </select>
                }
                None => <input id="signup-input-website" name="website" type="url" maxlength="2048" value=(form.website.clone()) aria-invalid=(errors.invalid("website"))>,
            }
            for message in errors.of("website") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="signup-input-plan">"Plan"</label>
            <select id="signup-input-plan" name="plan" required=(true) aria-invalid=(errors.invalid("plan"))>
                <option value="free" selected=(form.plan.as_deref() == Some("free"))>"Free"</option>
                <option value="pro" selected=(form.plan.as_deref() == Some("pro"))>"Pro"</option>
            </select>
            for message in errors.of("plan") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="signup-input-seats">"Seats"</label>
            match choices.of("seats", "seats") {
                Some(options) => {
                    <select id="signup-input-seats" name="seats" aria-invalid=(errors.invalid("seats"))>
                        <option value="" selected=(form.seats.is_none())>""</option>
                        for (value, label, selected) in choice_options(options, form.seats.as_deref()) {
                            <option value=(value) selected=(selected)>(label)</option>
                        }
                    </select>
                }
                None => <input id="signup-input-seats" name="seats" type="number" step="1" min="1" max="50" value=(form.seats.clone()) aria-invalid=(errors.invalid("seats"))>,
            }
            for message in errors.of("seats") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="signup-input-budget">"Budget"</label>
            match choices.of("budget", "budget") {
                Some(options) => {
                    <select id="signup-input-budget" name="budget" aria-invalid=(errors.invalid("budget"))>
                        <option value="" selected=(form.budget.is_none())>""</option>
                        for (value, label, selected) in choice_options(options, form.budget.as_deref()) {
                            <option value=(value) selected=(selected)>(label)</option>
                        }
                    </select>
                }
                None => <input id="signup-input-budget" name="budget" type="number" step="any" value=(form.budget.clone()) aria-invalid=(errors.invalid("budget"))>,
            }
            for message in errors.of("budget") {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="signup-input-newsletter">"Newsletter"</label>
            <input id="signup-input-newsletter" name="newsletter" type="checkbox" checked=(form.newsletter.is_some()) aria-invalid=(errors.invalid("newsletter"))>
            for message in errors.of("newsletter") {
                <p class="field-error">(message)</p>
            }
        </div>
    })
}
