//! Code generated by superschematic topcoat. DO NOT EDIT.
//!
//! A procedure per operation of fixture-forms-api, which browser code calls by
//! importing it: its arguments a record the browser builds, its result a
//! record, and a refusal a `ProblemRecord` the browser reads (an `Err` of a
//! procedure reaches it as a bare 500). Each procedure is on a stable path,
//! `/_superschematic/fixture-forms-api/<namespace>/<operation>`, and the app's
//! `.discover()` registers it; registering one again with `.route` panics.
//! `call_<operation>` is the procedure's body as a plain function: the
//! record decoded into the operation's arguments, then the operation called
//! in-process by its route's rules.

#![allow(unused_imports)]

use crate::api::runtime::ApiError;
use crate::operations;
use crate::records::*;
use crate::wire;
use serde::de::DeserializeOwned;
use serde_json::Value;
use topcoat::context::Cx;
use topcoat::runtime::{procedure, record};

/// A refusal as the browser reads it: the route's status, code and detail,
/// and each refused field's error.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct ProblemRecord {
    pub status: i64,
    pub code: String,
    pub detail: String,
    pub errors: Vec<FieldErrorRecord>,
}

/// One refused field: its path (`name`, `lines[0].quantity`), the rule it
/// broke and the message.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct FieldErrorRecord {
    pub path: String,
    pub validator: String,
    pub message: String,
}

impl From<ApiError> for ProblemRecord {
    /// The refusal's field errors: an input's, by path, and a parameter's,
    /// at the parameter.
    fn from(err: ApiError) -> Self {
        let mut errors = Vec::new();
        if let Some(fields) = err.errors.as_deref() {
            field_errors("", fields, &mut errors);
        }
        if let Some(details) = err.details.as_deref()
            && let Some(parameter) = details.get("parameter").and_then(Value::as_str)
        {
            let validator = details["errors"][0]["validator"].as_str().unwrap_or("type");
            errors.push(FieldErrorRecord {
                path: details.get("path").and_then(Value::as_str).unwrap_or(parameter).to_owned(),
                validator: validator.to_owned(),
                message: details.get("reason").and_then(Value::as_str).unwrap_or_default().to_owned(),
            });
        }
        Self { status: i64::from(err.status.as_u16()), code: err.code, detail: err.message, errors }
    }
}

/// Field errors keyed by path, nested for a nested object's fields, each a
/// list of `{validator, message}`.
fn field_errors(prefix: &str, fields: &Value, out: &mut Vec<FieldErrorRecord>) {
    for (key, value) in fields.as_object().into_iter().flatten() {
        let path = if prefix.is_empty() { key.clone() } else { format!("{prefix}.{key}") };
        match value {
            Value::Array(errors) => {
                for error in errors {
                    out.push(FieldErrorRecord {
                        path: path.clone(),
                        validator: error["validator"].as_str().unwrap_or_default().to_owned(),
                        message: error["message"].as_str().unwrap_or_default().to_owned(),
                    });
                }
            }
            nested => field_errors(&path, nested, out),
        }
    }
}

/// An argument's JSON decoded into its Rust type; a value that does not
/// decode (a UUID or a timestamp that does not parse, a value an enum does
/// not have) is the 400 the router answers.
fn decode<T: DeserializeOwned>(argument: &str, value: Value) -> Result<T, ProblemRecord> {
    serde_json::from_value(value).map_err(|_| {
        ProblemRecord::from(
            ApiError::bad_request(format!("Invalid argument {argument}: does not match the declared type"))
                .with_errors(serde_json::json!({ argument: [{"validator": "type", "message": "does not match the declared type"}] })),
        )
    })
}

/// The arguments of account.signUp, as browser code builds them.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct AccountSignUpArgsRecord {
    pub input: SignupInputRecord,
}

impl AccountSignUpArgsRecord {
    /// The operation's arguments: each field's JSON, as a request carries
    /// it, decoded into its Rust type.
    pub fn to_args(&self) -> Result<crate::api::AccountSignUpArgs, ProblemRecord> {
        Ok(crate::api::AccountSignUpArgs {
            input: decode("input", SignupInputRecord::to_wire(&self.input))?,
        })
    }
}

/// account.signUp, called from the browser.
#[procedure("/_superschematic/fixture-forms-api/account/sign-up")]
pub async fn account_sign_up(cx: &Cx, args: AccountSignUpArgsRecord) -> topcoat::Result<Result<AccountViewRecord, ProblemRecord>> {
    Ok(call_account_sign_up(cx, args).await)
}

/// The body of the account_sign_up procedure.
pub async fn call_account_sign_up(cx: &Cx, args: AccountSignUpArgsRecord) -> Result<AccountViewRecord, ProblemRecord> {
    let args = args.to_args()?;
    let value = operations::account_sign_up(cx, args).await?;
    let json = serde_json::to_value(&value).unwrap_or_default();
    Ok(AccountViewRecord::from_wire(&json))
}

/// The arguments of account.annotate, as browser code builds them.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct AccountAnnotateArgsRecord {
    pub input: NoteInputRecord,
    pub id: String,
}

impl AccountAnnotateArgsRecord {
    /// The operation's arguments: each field's JSON, as a request carries
    /// it, decoded into its Rust type.
    pub fn to_args(&self) -> Result<crate::api::AccountAnnotateArgs, ProblemRecord> {
        Ok(crate::api::AccountAnnotateArgs {
            input: decode("input", NoteInputRecord::to_wire(&self.input))?,
            id: decode("id", wire::put_string(&self.id))?,
        })
    }
}

/// account.annotate, called from the browser.
#[procedure("/_superschematic/fixture-forms-api/account/annotate")]
pub async fn account_annotate(cx: &Cx, args: AccountAnnotateArgsRecord) -> topcoat::Result<Result<AccountViewRecord, ProblemRecord>> {
    Ok(call_account_annotate(cx, args).await)
}

/// The body of the account_annotate procedure.
pub async fn call_account_annotate(cx: &Cx, args: AccountAnnotateArgsRecord) -> Result<AccountViewRecord, ProblemRecord> {
    let args = args.to_args()?;
    let value = operations::account_annotate(cx, args).await?;
    let json = serde_json::to_value(&value).unwrap_or_default();
    Ok(AccountViewRecord::from_wire(&json))
}
