//! Code generated by superschematic topcoat. DO NOT EDIT.
//!
//! A Topcoat record per type an in-process call of fixture-forms-api returns,
//! per type a procedure's arguments name, and per type such a type nests:
//! the type's JSON as the API sends it, in types a record holds. A UUID, a
//! timestamp, an enum and any other string scalar are their JSON strings; a
//! map is its entries; a union or any JSON value is its JSON text. A field
//! marked @uiHidden, and a secret field, is left out: everything in a record
//! reaches the browser.

use crate::api::types;
use crate::wire;
use topcoat::runtime::record;

/// The record of `types::AccountView`.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct AccountViewRecord {
    pub id: String,
    pub email: String,
    pub display_name: String,
    pub plan: String,
    pub seats: Option<i64>,
    pub newsletter: bool,
}

impl AccountViewRecord {
    /// The record of the type's JSON, as the API sends it.
    pub fn from_wire(json: &serde_json::Value) -> Self {
        Self {
            id: wire::string(&json["id"]),
            email: wire::string(&json["email"]),
            display_name: wire::string(&json["displayName"]),
            plan: wire::string(&json["plan"]),
            seats: wire::optional(&json["seats"], wire::integer),
            newsletter: wire::boolean(&json["newsletter"]),
        }
    }

    /// The type's JSON, as a request carries it.
    pub fn to_wire(&self) -> serde_json::Value {
        let mut json = serde_json::Map::new();
        json.insert("id".to_owned(), wire::put_string(&self.id));
        json.insert("email".to_owned(), wire::put_string(&self.email));
        json.insert("displayName".to_owned(), wire::put_string(&self.display_name));
        json.insert("plan".to_owned(), wire::put_string(&self.plan));
        if let Some(value) = &self.seats {
            json.insert("seats".to_owned(), wire::put_integer(value));
        }
        json.insert("newsletter".to_owned(), wire::put_boolean(&self.newsletter));
        serde_json::Value::Object(json)
    }
}

impl From<&types::AccountView> for AccountViewRecord {
    fn from(value: &types::AccountView) -> Self {
        Self::from_wire(&serde_json::to_value(value).unwrap_or_default())
    }
}

impl From<types::AccountView> for AccountViewRecord {
    fn from(value: types::AccountView) -> Self {
        Self::from(&value)
    }
}

/// The record of `types::BillingAddress`.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct BillingAddressRecord {
    pub line1: String,
    pub city: String,
    pub postcode: Option<String>,
}

impl BillingAddressRecord {
    /// The record of the type's JSON, as the API sends it.
    pub fn from_wire(json: &serde_json::Value) -> Self {
        Self {
            line1: wire::string(&json["line1"]),
            city: wire::string(&json["city"]),
            postcode: wire::optional(&json["postcode"], wire::string),
        }
    }

    /// The type's JSON, as a request carries it.
    pub fn to_wire(&self) -> serde_json::Value {
        let mut json = serde_json::Map::new();
        json.insert("line1".to_owned(), wire::put_string(&self.line1));
        json.insert("city".to_owned(), wire::put_string(&self.city));
        if let Some(value) = &self.postcode {
            json.insert("postcode".to_owned(), wire::put_string(value));
        }
        serde_json::Value::Object(json)
    }
}

impl From<&types::BillingAddress> for BillingAddressRecord {
    fn from(value: &types::BillingAddress) -> Self {
        Self::from_wire(&serde_json::to_value(value).unwrap_or_default())
    }
}

impl From<types::BillingAddress> for BillingAddressRecord {
    fn from(value: types::BillingAddress) -> Self {
        Self::from(&value)
    }
}

/// The record of `types::BookingInput`.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct BookingInputRecord {
    pub guest: GuestRecord,
    pub billing: Option<BillingAddressRecord>,
    pub rooms: Vec<RoomRequestRecord>,
    pub amenities: Option<Vec<String>>,
    pub arrival: String,
    pub check_in: Option<String>,
    pub hold_until: Option<String>,
    pub currency: Option<String>,
    pub preferences: Option<String>,
    pub labels: Option<Vec<(String, String)>>,
}

impl BookingInputRecord {
    /// The record of the type's JSON, as the API sends it.
    pub fn from_wire(json: &serde_json::Value) -> Self {
        Self {
            guest: GuestRecord::from_wire(&json["guest"]),
            billing: wire::optional(&json["billing"], BillingAddressRecord::from_wire),
            rooms: wire::list(&json["rooms"], RoomRequestRecord::from_wire),
            amenities: wire::optional(&json["amenities"], |v| wire::list(v, wire::string)),
            arrival: wire::string(&json["arrival"]),
            check_in: wire::optional(&json["checkIn"], wire::string),
            hold_until: wire::optional(&json["holdUntil"], wire::string),
            currency: wire::optional(&json["currency"], wire::string),
            preferences: wire::optional(&json["preferences"], wire::json_text),
            labels: wire::optional(&json["labels"], |v| wire::entries(v, wire::string)),
        }
    }

    /// The type's JSON, as a request carries it.
    pub fn to_wire(&self) -> serde_json::Value {
        let mut json = serde_json::Map::new();
        json.insert("guest".to_owned(), GuestRecord::to_wire(&self.guest));
        if let Some(value) = &self.billing {
            json.insert("billing".to_owned(), BillingAddressRecord::to_wire(value));
        }
        json.insert("rooms".to_owned(), wire::put_list(&self.rooms, RoomRequestRecord::to_wire));
        if let Some(value) = &self.amenities {
            json.insert("amenities".to_owned(), wire::put_list(value, wire::put_string));
        }
        json.insert("arrival".to_owned(), wire::put_string(&self.arrival));
        if let Some(value) = &self.check_in {
            json.insert("checkIn".to_owned(), wire::put_string(value));
        }
        if let Some(value) = &self.hold_until {
            json.insert("holdUntil".to_owned(), wire::put_string(value));
        }
        if let Some(value) = &self.currency {
            json.insert("currency".to_owned(), wire::put_string(value));
        }
        if let Some(value) = &self.preferences {
            json.insert("preferences".to_owned(), wire::put_json_text(value));
        }
        if let Some(value) = &self.labels {
            json.insert("labels".to_owned(), wire::put_entries(value, wire::put_string));
        }
        serde_json::Value::Object(json)
    }
}

impl From<&types::BookingInput> for BookingInputRecord {
    fn from(value: &types::BookingInput) -> Self {
        Self::from_wire(&serde_json::to_value(value).unwrap_or_default())
    }
}

impl From<types::BookingInput> for BookingInputRecord {
    fn from(value: types::BookingInput) -> Self {
        Self::from(&value)
    }
}

/// The record of `types::BookingView`.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct BookingViewRecord {
    pub id: String,
    pub rooms: f64,
}

impl BookingViewRecord {
    /// The record of the type's JSON, as the API sends it.
    pub fn from_wire(json: &serde_json::Value) -> Self {
        Self {
            id: wire::string(&json["id"]),
            rooms: wire::number(&json["rooms"]),
        }
    }

    /// The type's JSON, as a request carries it.
    pub fn to_wire(&self) -> serde_json::Value {
        let mut json = serde_json::Map::new();
        json.insert("id".to_owned(), wire::put_string(&self.id));
        json.insert("rooms".to_owned(), wire::put_number(&self.rooms));
        serde_json::Value::Object(json)
    }
}

impl From<&types::BookingView> for BookingViewRecord {
    fn from(value: &types::BookingView) -> Self {
        Self::from_wire(&serde_json::to_value(value).unwrap_or_default())
    }
}

impl From<types::BookingView> for BookingViewRecord {
    fn from(value: types::BookingView) -> Self {
        Self::from(&value)
    }
}

/// The record of `types::Guest`.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct GuestRecord {
    pub name: String,
    pub email: String,
    pub phone: Option<String>,
}

impl GuestRecord {
    /// The record of the type's JSON, as the API sends it.
    pub fn from_wire(json: &serde_json::Value) -> Self {
        Self {
            name: wire::string(&json["name"]),
            email: wire::string(&json["email"]),
            phone: wire::optional(&json["phone"], wire::string),
        }
    }

    /// The type's JSON, as a request carries it.
    pub fn to_wire(&self) -> serde_json::Value {
        let mut json = serde_json::Map::new();
        json.insert("name".to_owned(), wire::put_string(&self.name));
        json.insert("email".to_owned(), wire::put_string(&self.email));
        if let Some(value) = &self.phone {
            json.insert("phone".to_owned(), wire::put_string(value));
        }
        serde_json::Value::Object(json)
    }
}

impl From<&types::Guest> for GuestRecord {
    fn from(value: &types::Guest) -> Self {
        Self::from_wire(&serde_json::to_value(value).unwrap_or_default())
    }
}

impl From<types::Guest> for GuestRecord {
    fn from(value: types::Guest) -> Self {
        Self::from(&value)
    }
}

/// The record of `types::NoteInput`.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct NoteInputRecord {
    pub text: String,
    pub tags: Option<Vec<String>>,
}

impl NoteInputRecord {
    /// The record of the type's JSON, as the API sends it.
    pub fn from_wire(json: &serde_json::Value) -> Self {
        Self {
            text: wire::string(&json["text"]),
            tags: wire::optional(&json["tags"], |v| wire::list(v, wire::string)),
        }
    }

    /// The type's JSON, as a request carries it.
    pub fn to_wire(&self) -> serde_json::Value {
        let mut json = serde_json::Map::new();
        json.insert("text".to_owned(), wire::put_string(&self.text));
        if let Some(value) = &self.tags {
            json.insert("tags".to_owned(), wire::put_list(value, wire::put_string));
        }
        serde_json::Value::Object(json)
    }
}

impl From<&types::NoteInput> for NoteInputRecord {
    fn from(value: &types::NoteInput) -> Self {
        Self::from_wire(&serde_json::to_value(value).unwrap_or_default())
    }
}

impl From<types::NoteInput> for NoteInputRecord {
    fn from(value: types::NoteInput) -> Self {
        Self::from(&value)
    }
}

/// The record of `types::RoomRequest`.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct RoomRequestRecord {
    pub room_id: String,
    pub adults: i64,
    pub extras: Option<Vec<String>>,
}

impl RoomRequestRecord {
    /// The record of the type's JSON, as the API sends it.
    pub fn from_wire(json: &serde_json::Value) -> Self {
        Self {
            room_id: wire::string(&json["roomId"]),
            adults: wire::integer(&json["adults"]),
            extras: wire::optional(&json["extras"], |v| wire::list(v, wire::string)),
        }
    }

    /// The type's JSON, as a request carries it.
    pub fn to_wire(&self) -> serde_json::Value {
        let mut json = serde_json::Map::new();
        json.insert("roomId".to_owned(), wire::put_string(&self.room_id));
        json.insert("adults".to_owned(), wire::put_integer(&self.adults));
        if let Some(value) = &self.extras {
            json.insert("extras".to_owned(), wire::put_list(value, wire::put_string));
        }
        serde_json::Value::Object(json)
    }
}

impl From<&types::RoomRequest> for RoomRequestRecord {
    fn from(value: &types::RoomRequest) -> Self {
        Self::from_wire(&serde_json::to_value(value).unwrap_or_default())
    }
}

impl From<types::RoomRequest> for RoomRequestRecord {
    fn from(value: types::RoomRequest) -> Self {
        Self::from(&value)
    }
}

/// The record of `types::SignupInput`.
#[record]
#[derive(Debug, Clone, PartialEq)]
pub struct SignupInputRecord {
    pub email: String,
    pub display_name: String,
    pub handle: Option<String>,
    pub website: Option<String>,
    pub plan: String,
    pub seats: Option<i64>,
    pub budget: Option<f64>,
    pub newsletter: Option<bool>,
}

impl SignupInputRecord {
    /// The record of the type's JSON, as the API sends it.
    pub fn from_wire(json: &serde_json::Value) -> Self {
        Self {
            email: wire::string(&json["email"]),
            display_name: wire::string(&json["displayName"]),
            handle: wire::optional(&json["handle"], wire::string),
            website: wire::optional(&json["website"], wire::string),
            plan: wire::string(&json["plan"]),
            seats: wire::optional(&json["seats"], wire::integer),
            budget: wire::optional(&json["budget"], wire::number),
            newsletter: wire::optional(&json["newsletter"], wire::boolean),
        }
    }

    /// The type's JSON, as a request carries it.
    pub fn to_wire(&self) -> serde_json::Value {
        let mut json = serde_json::Map::new();
        json.insert("email".to_owned(), wire::put_string(&self.email));
        json.insert("displayName".to_owned(), wire::put_string(&self.display_name));
        if let Some(value) = &self.handle {
            json.insert("handle".to_owned(), wire::put_string(value));
        }
        if let Some(value) = &self.website {
            json.insert("website".to_owned(), wire::put_string(value));
        }
        json.insert("plan".to_owned(), wire::put_string(&self.plan));
        if let Some(value) = &self.seats {
            json.insert("seats".to_owned(), wire::put_integer(value));
        }
        if let Some(value) = &self.budget {
            json.insert("budget".to_owned(), wire::put_number(value));
        }
        if let Some(value) = &self.newsletter {
            json.insert("newsletter".to_owned(), wire::put_boolean(value));
        }
        serde_json::Value::Object(json)
    }
}

impl From<&types::SignupInput> for SignupInputRecord {
    fn from(value: &types::SignupInput) -> Self {
        Self::from_wire(&serde_json::to_value(value).unwrap_or_default())
    }
}

impl From<types::SignupInput> for SignupInputRecord {
    fn from(value: types::SignupInput) -> Self {
        Self::from(&value)
    }
}
