// Code generated by tsgen. DO NOT EDIT.

import {
  newValidationErrors,
  addFieldError,
  setFieldErrors,
  addNestedErrors,
} from 'superscalar/validation';
import type { ScalarValidationResult, ValidationResult } from 'superscalar/validation';
import { expectNumber } from '../primitives';
import { load as loadYaml } from 'js-yaml';
import { ParseError } from '../errors';
import type { RecipeRelease, JSDate, Recipe, RecipeCommit } from '../../types';

import { validateIdentityUUIDRequired, validateIdentityUUID } from '../scalars/identity_uuid';

import { validateTemporalDateTimeRequired, validateTemporalDateTime } from '../scalars/temporal_date_time';

import { parseTemporalDateTime as parseTemporalDateTimeFromLib } from 'superscalar/scalars';

import { parseRecipeFromJSON, validateRecipe } from './recipe';

import { parseRecipeCommitFromJSON, validateRecipeCommit } from './recipecommit';

/**
 * Validates a RecipeRelease object
 */
export function validateRecipeRelease(value: RecipeRelease | null | undefined): ValidationResult {
  const errors = newValidationErrors();

  if (value === null || value === undefined) {
    return true;
  }

  if (value.id !== null && value.id !== undefined) {
    const [valid, fieldErrors] = validateIdentityUUID(value.id);
    if (!valid && fieldErrors) {
      setFieldErrors(errors, "id", fieldErrors);
    }
  }

  {
    // A nested object is validated as its own type, its errors under the
    // field's path. Any other JSON value is "type"; null is left to the
    // field's presence checks.
    const validateNested = (nested: unknown, path: string) => {
      if (nested === null || nested === undefined) {
        return;
      }
      if (typeof nested !== 'object' || Array.isArray(nested)) {
        addFieldError(errors, path, "type", "expected an object");
        return;
      }
      const nestedErrors = validateRecipe(nested as Recipe);
      if (nestedErrors !== true) {
        addNestedErrors(errors, path, nestedErrors);
      }
    };

    validateNested(value.root, "root");

  }

  if (value.root === null || value.root === undefined) {
    addFieldError(errors, "root", "required", "required field");
  }

  {
    // A nested object is validated as its own type, its errors under the
    // field's path. Any other JSON value is "type"; null is left to the
    // field's presence checks.
    const validateNested = (nested: unknown, path: string) => {
      if (nested === null || nested === undefined) {
        return;
      }
      if (typeof nested !== 'object' || Array.isArray(nested)) {
        addFieldError(errors, path, "type", "expected an object");
        return;
      }
      const nestedErrors = validateRecipeCommit(nested as RecipeCommit);
      if (nestedErrors !== true) {
        addNestedErrors(errors, path, nestedErrors);
      }
    };

    validateNested(value.commit, "commit");

  }

  if (value.commit === null || value.commit === undefined) {
    addFieldError(errors, "commit", "required", "required field");
  }

  {
    const [valid, fieldErrors] = validateTemporalDateTimeRequired(value.createdAt);
    if (!valid && fieldErrors) {
      setFieldErrors(errors, "createdAt", fieldErrors);
    }
  }

  {
    const [valid, fieldErrors] = validateIdentityUUIDRequired(value.createdBy);
    if (!valid && fieldErrors) {
      setFieldErrors(errors, "createdBy", fieldErrors);
    }
  }

  {
    const [valid, fieldErrors] = validateTemporalDateTimeRequired(value.updatedAt);
    if (!valid && fieldErrors) {
      setFieldErrors(errors, "updatedAt", fieldErrors);
    }
  }

  {
    const [valid, fieldErrors] = validateIdentityUUIDRequired(value.updatedBy);
    if (!valid && fieldErrors) {
      setFieldErrors(errors, "updatedBy", fieldErrors);
    }
  }

  expectNumber(errors, "_version", value._version);

  return Object.keys(errors).length > 0 ? errors : true;
}

export function validateRecipeReleaseRequired(value: RecipeRelease | null | undefined): ScalarValidationResult {
  if (value === null || value === undefined) {
    return [false, [{ validator: 'required', message: 'required field' }]];
  }

  const validationResult = validateRecipeRelease(value);
  if (validationResult !== true) {
    return [false, [{ validator: 'object', message: JSON.stringify(validationResult) }]];
  }

  return [true, null];
}

const RecipeReleaseKnownFields = new Set<string>([
  'id',
  'root',
  'commit',
  'createdAt',
  'createdBy',
  'updatedAt',
  'updatedBy',
  '_version',
]);

type RecipeReleaseTextParser = (value: string) => unknown;

function parseRecipeReleaseInput(
  input: string | unknown,
  strict: boolean,
  sourceFormat: 'json' | 'yaml',
  parseText: RecipeReleaseTextParser
): RecipeRelease {
  let parsed: unknown = input;

  if (typeof input === 'string') {
    try {
      parsed = parseText(input);
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      throw new ParseError(
        `parseRecipeRelease ${sourceFormat} parse failed: ${reason}`,
        `not valid ${sourceFormat === 'json' ? 'JSON' : 'YAML'}`
      );
    }
  }

  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new ParseError(`parseRecipeRelease ${sourceFormat} expects an object input`, 'expected an object');
  }

  const candidate = parsed as Record<string, unknown>;

  // Apply @default values from the schema for keys absent from the payload.

  if (strict) {
    const unknownFields = Object.keys(candidate).filter(
      (fieldName) => !RecipeReleaseKnownFields.has(fieldName)
    );
    if (unknownFields.length > 0) {
      const unknownErrors = newValidationErrors();
      for (const fieldName of unknownFields) {
        addFieldError(unknownErrors, fieldName, "unknown", "unknown field");
      }
      throw new ParseError(
        `parseRecipeRelease ${sourceFormat} contains unknown fields: ${unknownFields.join(', ')}`,
        `unknown fields: ${unknownFields.join(', ')}`,
        unknownErrors
      );
    }
  }

  const typedCandidate = candidate as unknown as RecipeRelease;
  const validationResult = validateRecipeRelease(typedCandidate);
  if (validationResult !== true) {
    throw new ParseError(
      `parseRecipeRelease ${sourceFormat} validation failed: ${JSON.stringify(validationResult)}`,
      'validation failed',
      validationResult
    );
  }

  return typedCandidate;
}

export function parseRecipeReleaseJson(input: string | unknown): RecipeRelease {
  return parseRecipeReleaseInput(input, true, 'json', (value) => JSON.parse(value) as unknown);
}

export function parseRecipeReleaseJsonNonStrict(input: string | unknown): RecipeRelease {
  return parseRecipeReleaseInput(input, false, 'json', (value) => JSON.parse(value) as unknown);
}

export function parseRecipeReleaseYaml(input: string | unknown): RecipeRelease {
  return parseRecipeReleaseInput(input, true, 'yaml', (value) => loadYaml(value));
}

export function parseRecipeReleaseYamlNonStrict(input: string | unknown): RecipeRelease {
  return parseRecipeReleaseInput(input, false, 'yaml', (value) => loadYaml(value));
}

/**
 * Parses a RecipeRelease from JSON wire format into runtime types
 */

export function parseRecipeReleaseFromJSON(input: unknown): RecipeRelease {
  if (input == null || typeof input !== 'object') {
    return input as RecipeRelease;
  }
  const obj = input as Record<string, unknown>;
  return {
    ...(obj as unknown as RecipeRelease),

    root: obj.root != null
      ? parseRecipeFromJSON(obj.root)
      : (obj.root as unknown as Recipe),

    commit: obj.commit != null
      ? parseRecipeCommitFromJSON(obj.commit)
      : (obj.commit as unknown as RecipeCommit),

    createdAt: obj.createdAt != null
      ? (parseTemporalDateTimeFromLib(obj.createdAt as string) as JSDate)
      : (obj.createdAt as unknown as JSDate),

    updatedAt: obj.updatedAt != null
      ? (parseTemporalDateTimeFromLib(obj.updatedAt as string) as JSDate)
      : (obj.updatedAt as unknown as JSDate),

  };
}
