// Code generated by sdkgen. DO NOT EDIT.

import type { FixtureToolInvokeApiSDK } from '../index';
import type {
  AttachmentUpload,
  NoteInput,
} from '@schemas/fixture-tool-invoke-api-types';

/**
 * Tool parameter types for type-safe invocation
 */

export interface NoteCreateNoteParams {
  createdBy: string;
  dueAt?: NoteInput['due_at'];
  title: string;
}

export interface NoteAttachParams {
  caption: string;
  file: AttachmentUpload['file'];
}

export interface NoteConfigureNotesParams {
  reason: string;
  settings: unknown;
}

export interface NoteMoveNoteParams {
  dryRun?: boolean;
  folder: string;
  title: string;
}

export interface NoteSealNoteParams {
  body: string;
  dryRun?: boolean;
  publicEncryptionKey?: { algorithm: string; keyId: string; publicKey: string };
  title: string;
}

export interface NoteTagNoteParams {
  comment?: string;
  id: string;
  label: string;
  weight: number;
}

/**
 * Tool definition interface
 */
export interface ToolDefinition {
  name: string;
  operationId: string;
  title: string;
  mcp: {
    hidden: boolean;
    hiddenReason?: string;
    name?: string;
    handle?: string;
    description?: string;
    invocationPolicy?: 'auto' | 'ask';
    _meta?: Record<string, unknown>;
    icon?: {
      name: string;
      family?: string;
      style?: string;
    };
  } | null;
  capability: string;
  lifecycle: string;
  visibility: string;
  audience: string;
  guidance: {
    useWhen: string;
    doNotUseWhen: string;
    success: string;
    errors: Array<{ code: string; description: string; commonCorrection: string }>;
  };
  requiredPermissions: string[];
  replay: {
    mode: string;
    idempotencyKeyPointers: string[];
    expectedRevisionPointers: string[];
  } | null;
  description: string;
  namespace: string;
  methodName: string;
  requiresAuth: boolean;
  isScoped: boolean;
  bindingStatus: 'ready' | 'unsupported_multipart';
  inputSchemaDigest: string;
  parameters: {
    type: 'object';
    additionalProperties: false;
    properties: Record<string, JSONSchemaProperty>;
    required?: string[];
  };
  returns: {
    type: string;
    description?: string;
    items?: { type: string; description?: string };
  };
}

/**
 * JSON Schema property interface
 */
export interface JSONSchemaProperty {
  'x-superschematic-scalar'?: string;
  additionalProperties?: boolean | JSONSchemaProperty;
  type: string | string[];
  format?: string;
  description?: string;
  pattern?: string;
  enum?: Array<string | null>;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  items?: JSONSchemaProperty;
  properties?: Record<string, JSONSchemaProperty>;
  required?: string[];
  oneOf?: JSONSchemaProperty[];
}

/**
 * OpenAI function definition interface
 */
export interface OpenAIFunction {
  name: string;
  description: string;
  parameters: {
    type: 'object';
    additionalProperties: false;
    properties: Record<string, JSONSchemaProperty>;
    required?: string[];
  };
}

/**
 * Anthropic tool definition interface
 */
export interface AnthropicTool {
  name: string;
  description: string;
  input_schema: {
    type: 'object';
    additionalProperties: false;
    properties: Record<string, JSONSchemaProperty>;
    required?: string[];
  };
}

/**
 * Tool name constants
 */
export const NOTE_CREATE_NOTE = 'note.createNote' as const;
export const NOTE_ATTACH = 'note.attach' as const;
export const NOTE_CONFIGURE_NOTES = 'note.configureNotes' as const;
export const NOTE_MOVE_NOTE = 'note.moveNote' as const;
export const NOTE_SEAL_NOTE = 'note.sealNote' as const;
export const NOTE_TAG_NOTE = 'note.tagNote' as const;

/**
 * Union type of all tool names
 */
export type ToolName =
  | typeof NOTE_CREATE_NOTE
  | typeof NOTE_ATTACH
  | typeof NOTE_CONFIGURE_NOTES
  | typeof NOTE_MOVE_NOTE
  | typeof NOTE_SEAL_NOTE
  | typeof NOTE_TAG_NOTE;

/**
 * All available tools as an array of names
 */
export const TOOL_NAMES: ToolName[] = [
  NOTE_CREATE_NOTE,
  NOTE_ATTACH,
  NOTE_CONFIGURE_NOTES,
  NOTE_MOVE_NOTE,
  NOTE_SEAL_NOTE,
  NOTE_TAG_NOTE,
];

/**
 * Complete tool definitions with metadata
 */
export const toolDefinitions: Record<ToolName, ToolDefinition> = {
  [NOTE_CREATE_NOTE]: {
    name: 'note.createNote',
    operationId: 'NoteCreateNoteHandler',
    title: ``,
    mcp: null,
    capability: '',
    lifecycle: '',
    visibility: '',
    audience: '',
    guidance: {"useWhen":"","doNotUseWhen":"","success":"","errors":[]},
    requiredPermissions: [],
    replay: null,
    description: `An input type with snake_case fields.`,
    namespace: 'note',
    methodName: 'createNote',
    requiresAuth: false,
    isScoped: false,
    bindingStatus: 'ready',
    inputSchemaDigest: 'sha256:32f14921c3f4e7c0ac4cb8a11fc3a3fe2badb34b268f3270d94c5556525b7027',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        createdBy: {"description":"A string value","type":"string"},
        dueAt: {"description":"ISO8601 datetime string. Epoch wire values keep this scalar and declare x-temporal-format (unix, unix_millis, unix_micros, unix_nanos) on the property; the unit is never guessed from digit count.","format":"date-time","type":["string","null"],"x-superschematic-scalar":"Temporal.DateTime"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['createdBy', 'title']
    },
    returns: {
      type: 'object',
      description: `NoteView object`
    }
  },
  [NOTE_ATTACH]: {
    name: 'note.attach',
    operationId: 'NoteAttachHandler',
    title: ``,
    mcp: null,
    capability: '',
    lifecycle: '',
    visibility: '',
    audience: '',
    guidance: {"useWhen":"","doNotUseWhen":"","success":"","errors":[]},
    requiredPermissions: [],
    replay: null,
    description: `A file upload.`,
    namespace: 'note',
    methodName: 'attach',
    requiresAuth: false,
    isScoped: false,
    bindingStatus: 'unsupported_multipart',
    inputSchemaDigest: 'sha256:849c0f45b027786b8d18c4a7abc11a9637cb805d1e91b0c455f4d44da522ef37',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        caption: {"description":"A string value","type":"string"},
        file: {"description":"Valid HTTP/HTTPS URL","format":"uri","maxLength":2048,"pattern":"^https?://[\\w\\-\\{\\}]+(\\.[\\w\\-\\{\\}]+)+([:/?#][\\w\\-\\._~:/?#\\[\\]@!\\$\u0026'\\(\\)\\*\\+,;=\\{\\}%]*)?$","type":"string","x-superschematic-scalar":"Network.Url"},
      },
      required: ['caption', 'file']
    },
    returns: {
      type: 'object',
      description: `NoteView object`
    }
  },
  [NOTE_CONFIGURE_NOTES]: {
    name: 'note.configureNotes',
    operationId: 'NoteConfigureNotesHandler',
    title: ``,
    mcp: null,
    capability: '',
    lifecycle: '',
    visibility: '',
    audience: '',
    guidance: {"useWhen":"","doNotUseWhen":"","success":"","errors":[]},
    requiredPermissions: [],
    replay: null,
    description: `Two required body arguments, the first an object value.`,
    namespace: 'note',
    methodName: 'configureNotes',
    requiresAuth: false,
    isScoped: false,
    bindingStatus: 'ready',
    inputSchemaDigest: 'sha256:88e6e3df83ae32d0fe93ecc983db1a0e2e3c26b70b94c9ec84b01e9288bdb19f',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        reason: {"description":"A string value","type":"string"},
        settings: {"description":"Any valid JSON value: object, array, primitive, or null","type":["object","array","string","number","boolean","null"],"x-superschematic-scalar":"Generic.JSON"},
      },
      required: ['reason', 'settings']
    },
    returns: {
      type: 'object',
      description: `NoteView object`
    }
  },
  [NOTE_MOVE_NOTE]: {
    name: 'note.moveNote',
    operationId: 'NoteMoveNoteHandler',
    title: ``,
    mcp: null,
    capability: '',
    lifecycle: '',
    visibility: '',
    audience: '',
    guidance: {"useWhen":"","doNotUseWhen":"","success":"","errors":[]},
    requiredPermissions: [],
    replay: null,
    description: `Two required body arguments and a query parameter.`,
    namespace: 'note',
    methodName: 'moveNote',
    requiresAuth: false,
    isScoped: false,
    bindingStatus: 'ready',
    inputSchemaDigest: 'sha256:2d3f3ebd7544b6b3adf3b68d1186011966b905b09caa5a898915acfa4e8eb324',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        dryRun: {"description":"A boolean value (true or false)","type":"boolean"},
        folder: {"description":"A string value","type":"string"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['folder', 'title']
    },
    returns: {
      type: 'object',
      description: `NoteView object`
    }
  },
  [NOTE_SEAL_NOTE]: {
    name: 'note.sealNote',
    operationId: 'NoteSealNoteHandler',
    title: ``,
    mcp: null,
    capability: '',
    lifecycle: '',
    visibility: '',
    audience: '',
    guidance: {"useWhen":"","doNotUseWhen":"","success":"","errors":[]},
    requiredPermissions: [],
    replay: null,
    description: `Two required body arguments and a query parameter, encrypted.`,
    namespace: 'note',
    methodName: 'sealNote',
    requiresAuth: false,
    isScoped: false,
    bindingStatus: 'ready',
    inputSchemaDigest: 'sha256:1ca7d01e681c8560dae2b4d0c24ac0ea06c9c5616a57484d4cfd63d9e8170d30',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        body: {"description":"A string value","type":"string"},
        dryRun: {"description":"A boolean value (true or false)","type":"boolean"},
        publicEncryptionKey: {"additionalProperties":false,"description":"Public key details used to encrypt this request payload","properties":{"algorithm":{"description":"Encryption algorithm identifier from the server","type":"string"},"keyId":{"description":"Server key identifier for the public key","type":"string"},"publicKey":{"description":"PEM-encoded RSA public key","type":"string"}},"required":["publicKey","algorithm","keyId"],"type":"object"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['body', 'title']
    },
    returns: {
      type: 'object',
      description: `NoteView object`
    }
  },
  [NOTE_TAG_NOTE]: {
    name: 'note.tagNote',
    operationId: 'NoteTagNoteHandler',
    title: ``,
    mcp: null,
    capability: '',
    lifecycle: '',
    visibility: '',
    audience: '',
    guidance: {"useWhen":"","doNotUseWhen":"","success":"","errors":[]},
    requiredPermissions: [],
    replay: null,
    description: `Two required body arguments and an optional one, after a path parameter.`,
    namespace: 'note',
    methodName: 'tagNote',
    requiresAuth: false,
    isScoped: false,
    bindingStatus: 'ready',
    inputSchemaDigest: 'sha256:6c61a564b827fceace5f26d55209344f8683ea8df6a79be8a4080dd605e67a52',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        comment: {"description":"A string value","type":["string","null"]},
        id: {"description":"id parameter","pattern":"^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$","type":"string","x-superschematic-scalar":"Identity.UUID"},
        label: {"description":"A string value","type":"string"},
        weight: {"description":"A numeric value","type":"number"},
      },
      required: ['id', 'label', 'weight']
    },
    returns: {
      type: 'object',
      description: `NoteView object`
    }
  }
};

/**
 * OpenAI-formatted function definitions
 * Use with OpenAI's function calling: { functions: openAIFunctions }
 */
export const openAIFunctions: OpenAIFunction[] = [
  {
    name: 'note.createNote',
    description: `An input type with snake_case fields.`,
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        createdBy: {"description":"A string value","type":"string"},
        dueAt: {"description":"ISO8601 datetime string. Epoch wire values keep this scalar and declare x-temporal-format (unix, unix_millis, unix_micros, unix_nanos) on the property; the unit is never guessed from digit count.","format":"date-time","type":["string","null"],"x-superschematic-scalar":"Temporal.DateTime"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['createdBy', 'title']
    }
  },
  {
    name: 'note.attach',
    description: `A file upload.`,
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        caption: {"description":"A string value","type":"string"},
        file: {"description":"Valid HTTP/HTTPS URL","format":"uri","maxLength":2048,"pattern":"^https?://[\\w\\-\\{\\}]+(\\.[\\w\\-\\{\\}]+)+([:/?#][\\w\\-\\._~:/?#\\[\\]@!\\$\u0026'\\(\\)\\*\\+,;=\\{\\}%]*)?$","type":"string","x-superschematic-scalar":"Network.Url"},
      },
      required: ['caption', 'file']
    }
  },
  {
    name: 'note.configureNotes',
    description: `Two required body arguments, the first an object value.`,
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        reason: {"description":"A string value","type":"string"},
        settings: {"description":"Any valid JSON value: object, array, primitive, or null","type":["object","array","string","number","boolean","null"],"x-superschematic-scalar":"Generic.JSON"},
      },
      required: ['reason', 'settings']
    }
  },
  {
    name: 'note.moveNote',
    description: `Two required body arguments and a query parameter.`,
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        dryRun: {"description":"A boolean value (true or false)","type":"boolean"},
        folder: {"description":"A string value","type":"string"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['folder', 'title']
    }
  },
  {
    name: 'note.sealNote',
    description: `Two required body arguments and a query parameter, encrypted.`,
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        body: {"description":"A string value","type":"string"},
        dryRun: {"description":"A boolean value (true or false)","type":"boolean"},
        publicEncryptionKey: {"additionalProperties":false,"description":"Public key details used to encrypt this request payload","properties":{"algorithm":{"description":"Encryption algorithm identifier from the server","type":"string"},"keyId":{"description":"Server key identifier for the public key","type":"string"},"publicKey":{"description":"PEM-encoded RSA public key","type":"string"}},"required":["publicKey","algorithm","keyId"],"type":"object"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['body', 'title']
    }
  },
  {
    name: 'note.tagNote',
    description: `Two required body arguments and an optional one, after a path parameter.`,
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        comment: {"description":"A string value","type":["string","null"]},
        id: {"description":"id parameter","pattern":"^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$","type":"string","x-superschematic-scalar":"Identity.UUID"},
        label: {"description":"A string value","type":"string"},
        weight: {"description":"A numeric value","type":"number"},
      },
      required: ['id', 'label', 'weight']
    }
  }
];

/**
 * Anthropic-formatted tool definitions
 * Use with Anthropic's tool use: { tools: anthropicTools }
 */
export const anthropicTools: AnthropicTool[] = [
  {
    name: 'note.createNote',
    description: `An input type with snake_case fields.`,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        createdBy: {"description":"A string value","type":"string"},
        dueAt: {"description":"ISO8601 datetime string. Epoch wire values keep this scalar and declare x-temporal-format (unix, unix_millis, unix_micros, unix_nanos) on the property; the unit is never guessed from digit count.","format":"date-time","type":["string","null"],"x-superschematic-scalar":"Temporal.DateTime"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['createdBy', 'title']
    }
  },
  {
    name: 'note.attach',
    description: `A file upload.`,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        caption: {"description":"A string value","type":"string"},
        file: {"description":"Valid HTTP/HTTPS URL","format":"uri","maxLength":2048,"pattern":"^https?://[\\w\\-\\{\\}]+(\\.[\\w\\-\\{\\}]+)+([:/?#][\\w\\-\\._~:/?#\\[\\]@!\\$\u0026'\\(\\)\\*\\+,;=\\{\\}%]*)?$","type":"string","x-superschematic-scalar":"Network.Url"},
      },
      required: ['caption', 'file']
    }
  },
  {
    name: 'note.configureNotes',
    description: `Two required body arguments, the first an object value.`,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        reason: {"description":"A string value","type":"string"},
        settings: {"description":"Any valid JSON value: object, array, primitive, or null","type":["object","array","string","number","boolean","null"],"x-superschematic-scalar":"Generic.JSON"},
      },
      required: ['reason', 'settings']
    }
  },
  {
    name: 'note.moveNote',
    description: `Two required body arguments and a query parameter.`,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        dryRun: {"description":"A boolean value (true or false)","type":"boolean"},
        folder: {"description":"A string value","type":"string"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['folder', 'title']
    }
  },
  {
    name: 'note.sealNote',
    description: `Two required body arguments and a query parameter, encrypted.`,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        body: {"description":"A string value","type":"string"},
        dryRun: {"description":"A boolean value (true or false)","type":"boolean"},
        publicEncryptionKey: {"additionalProperties":false,"description":"Public key details used to encrypt this request payload","properties":{"algorithm":{"description":"Encryption algorithm identifier from the server","type":"string"},"keyId":{"description":"Server key identifier for the public key","type":"string"},"publicKey":{"description":"PEM-encoded RSA public key","type":"string"}},"required":["publicKey","algorithm","keyId"],"type":"object"},
        title: {"description":"A string value","type":"string"},
      },
      required: ['body', 'title']
    }
  },
  {
    name: 'note.tagNote',
    description: `Two required body arguments and an optional one, after a path parameter.`,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        comment: {"description":"A string value","type":["string","null"]},
        id: {"description":"id parameter","pattern":"^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$","type":"string","x-superschematic-scalar":"Identity.UUID"},
        label: {"description":"A string value","type":"string"},
        weight: {"description":"A numeric value","type":"number"},
      },
      required: ['id', 'label', 'weight']
    }
  }
];

/**
 * Parameter types for each tool, mapped by tool name
 */
export type ToolParams = {
  [NOTE_CREATE_NOTE]: NoteCreateNoteParams;
  [NOTE_ATTACH]: NoteAttachParams;
  [NOTE_CONFIGURE_NOTES]: NoteConfigureNotesParams;
  [NOTE_MOVE_NOTE]: NoteMoveNoteParams;
  [NOTE_SEAL_NOTE]: NoteSealNoteParams;
  [NOTE_TAG_NOTE]: NoteTagNoteParams;
};

/**
 * Invokes a tool by name using the SDK. A tool whose bindingStatus is
 * unsupported_multipart uploads a file, which tool parameters cannot carry;
 * invokeTool throws for it without sending a request.
 *
 * @param sdk - The initialized SDK instance
 * @param toolName - The namespaced tool name (e.g., "auth.sendMagicLink")
 * @param params - The parameters for the tool
 * @returns The result of the tool invocation
 * @throws Error if the tool name is not recognized
 *
 * @example
 * ```typescript
 * const sdk = new FixtureToolInvokeApiSDK({ baseUrl: 'https://api.example.com' });
 * const result = await invokeTool(sdk, 'auth.sendMagicLink', { email: 'user@example.com' });
 * ```
 */
export async function invokeTool<T extends ToolName>(
  sdk: FixtureToolInvokeApiSDK,
  toolName: T,
  params: ToolParams[T]
): Promise<unknown> {
  switch (toolName) {
    case NOTE_CREATE_NOTE:
      return sdk.note.createNote({ title: (params as NoteCreateNoteParams).title, created_by: (params as NoteCreateNoteParams).createdBy, due_at: (params as NoteCreateNoteParams).dueAt });
    case NOTE_ATTACH:
      throw new Error("note.attach uploads a file, which tool parameters cannot carry (bindingStatus unsupported_multipart); call sdk.note.attach with the files");
    case NOTE_CONFIGURE_NOTES:
      return sdk.note.configureNotes({ settings: (params as NoteConfigureNotesParams).settings, reason: (params as NoteConfigureNotesParams).reason }, undefined);
    case NOTE_MOVE_NOTE:
      return sdk.note.moveNote({ title: (params as NoteMoveNoteParams).title, folder: (params as NoteMoveNoteParams).folder }, { dryRun: (params as NoteMoveNoteParams).dryRun });
    case NOTE_SEAL_NOTE:
      return sdk.note.sealNote({ title: (params as NoteSealNoteParams).title, body: (params as NoteSealNoteParams).body }, { dryRun: (params as NoteSealNoteParams).dryRun }, undefined, (params as NoteSealNoteParams).publicEncryptionKey ? { publicEncryptionKey: (params as NoteSealNoteParams).publicEncryptionKey as { publicKey: string; algorithm: string; keyId: string } } : undefined);
    case NOTE_TAG_NOTE:
      return sdk.note.tagNote((params as NoteTagNoteParams).id, { label: (params as NoteTagNoteParams).label, weight: (params as NoteTagNoteParams).weight, comment: (params as NoteTagNoteParams).comment }, undefined);
    default:
      throw new Error(`Unknown tool: ${toolName}`);
  }
}

/**
 * Gets the tool definition for a given tool name
 */
export function getToolDefinition(toolName: ToolName): ToolDefinition {
  return toolDefinitions[toolName];
}

/**
 * Gets all tools that require authentication
 */
export function getAuthRequiredTools(): ToolDefinition[] {
  return Object.values(toolDefinitions).filter(t => t.requiresAuth);
}

/**
 * Gets all tools that don't require authentication
 */
export function getPublicTools(): ToolDefinition[] {
  return Object.values(toolDefinitions).filter(t => !t.requiresAuth);
}

/**
 * Gets all tools for a specific namespace
 */
export function getToolsForNamespace(namespace: string): ToolDefinition[] {
  return Object.values(toolDefinitions).filter(t => t.namespace === namespace);
}

/**
 * Validates that params contain all required fields for a tool
 */
export function validateToolParams(toolName: ToolName, params: Record<string, unknown>): { valid: boolean; missing: string[] } {
  const tool = toolDefinitions[toolName];
  const required = tool.parameters.required || [];
  const missing = required.filter(field => !(field in params) || params[field] === undefined);
  return { valid: missing.length === 0, missing };
}
