# Code generated by pygen. DO NOT EDIT.

from setuptools import setup, find_packages

setup(
    name="schemas_types_fixture_api",
    version="1.0.0",
    description="Generated Python types for fixture-api schema",
    author="superschematic",
    packages=find_packages(),
    package_data={
        "schemas_types_fixture_api": ["py.typed"],
    },
    install_requires=[
        "pydantic>=2.12.0,<3.0.0",
        "PyYAML>=6.0.0",
        "superscalar>=1.0.0",
    ],
    python_requires=">=3.12",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.12",
        "Typing :: Typed",
    ],
    zip_safe=False,
)
