// Code generated by superschematic typegen. DO NOT EDIT.

package types

// CellState - The state of one board cell.
type CellState string

const (

	// CellStateEmpty
	CellState_Empty CellState = "empty"

	// CellStateFilled
	CellState_Filled CellState = "filled"
)

// String returns the string representation of CellState
func (e CellState) String() string {
	return string(e)
}

// IsValid returns true if the CellState value is valid
func (e CellState) IsValid() bool {
	switch e {

	case CellState_Empty:
		return true

	case CellState_Filled:
		return true

	}
	return false
}

// Values returns every CellState member in schema declaration order.
// Each call returns a new slice.
func (CellState) Values() []CellState {
	return []CellState{
		CellState_Empty,
		CellState_Filled,
	}
}

// Validate and returns whether validation passed along with any errors.
func (e CellState) Validate() (bool, []ValidationError) {
	var errs []ValidationError

	if !e.IsValid() {
		errs = append(errs, ValidationError{Validator: "enum", Message: "invalid enum value"})
	}

	return len(errs) == 0, errs
}

// ValidateRequired with required check and returns whether validation passed along with any errors.
func (e CellState) ValidateRequired() (bool, []ValidationError) {
	var errs []ValidationError

	if e == "" {
		errs = append(errs, ValidationError{Validator: "required", Message: "required field"})
		return false, errs
	}

	if !e.IsValid() {
		errs = append(errs, ValidationError{Validator: "enum", Message: "invalid enum value"})
	}

	return len(errs) == 0, errs
}
