import type {
  ArgumentDef,
  FieldDef,
  OperationSet,
  ScalarDef,
  Schema,
  TypeRef,
} from '../validation/types';

type JsonValue = string | number | boolean | null | JsonObject | JsonValue[];
interface JsonObject {
  [key: string]: JsonValue;
}

function sortObject(value: JsonValue): JsonValue {
  if (Array.isArray(value)) {
    return value.map(item => sortObject(item));
  }
  if (value === null || typeof value !== 'object') {
    return value;
  }

  const sorted: JsonObject = {};
  for (const key of Object.keys(value).sort((a, b) => a.localeCompare(b))) {
    sorted[key] = sortObject(value[key] as JsonValue);
  }
  return sorted;
}

function primitiveToJsonType(primitive: string): string {
  switch (primitive) {
    case 'String':
      return 'string';
    case 'Int':
      return 'integer';
    case 'Float':
      return 'number';
    case 'Boolean':
      return 'boolean';
    case 'Type':
    case 'JSON':
      return 'object';
    default:
      return '';
  }
}

function isJsonPrimitiveType(typeName: string): boolean {
  return (
    typeName === 'String' ||
    typeName === 'Int' ||
    typeName === 'Float' ||
    typeName === 'Boolean' ||
    typeName === 'Type' ||
    typeName === 'JSON'
  );
}

function withMiddleware(
  target: JsonObject,
  middleware: OperationSet['middleware'] | FieldDef['middleware'],
  encryptedFallback = false
): void {
  if (!middleware && !encryptedFallback) {
    return;
  }
  if (middleware?.rateLimit !== null && middleware?.rateLimit !== undefined) {
    target['x-rateLimit'] = { requestsPerMinute: middleware.rateLimit };
  }
  if (middleware?.bodyLimit !== null && middleware?.bodyLimit !== undefined) {
    target['x-bodyLimit'] = { megabytes: middleware.bodyLimit };
  }
  if (middleware?.timeout !== null && middleware?.timeout !== undefined) {
    target['x-timeout'] = { seconds: middleware.timeout };
  }
  if (middleware?.encrypted || encryptedFallback) {
    target['x-encrypted'] = true;
  }
}

function serializeTypeRef(typeRef: TypeRef, scalarNames: Set<string>): JsonObject {
  if (typeRef.isArray) {
    return {
      type: 'array',
      items: serializeTypeRef(
        {
          name: typeRef.name,
          isArray: false,
          elemNonNull: typeRef.elemNonNull,
        },
        scalarNames
      ),
    };
  }

  if (isJsonPrimitiveType(typeRef.name)) {
    return {
      type: primitiveToJsonType(typeRef.name),
    };
  }

  const refPrefix = scalarNames.has(typeRef.name) ? '#/definitions/scalars/' : '#/definitions/';
  return {
    $ref: `${refPrefix}${typeRef.name}`,
  };
}

function parseDefaultValue(defaultValue: string, typeRef: TypeRef): JsonValue {
  if (typeRef.name === 'Boolean') {
    if (defaultValue === 'true') {
      return true;
    }
    if (defaultValue === 'false') {
      return false;
    }
  }

  if (typeRef.name === 'Int') {
    const parsed = Number.parseInt(defaultValue, 10);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }

  if (typeRef.name === 'Float') {
    const parsed = Number.parseFloat(defaultValue);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }

  return defaultValue;
}

function serializeArgument(argument: ArgumentDef, scalarNames: Set<string>): JsonObject {
  const output: JsonObject = serializeTypeRef(argument.typeRef, scalarNames);
  if (argument.description) {
    output.description = argument.description;
  }
  if (argument.required) {
    output['x-required'] = true;
  }
  if (argument.defaultValue !== null) {
    output.default = parseDefaultValue(argument.defaultValue, argument.typeRef);
  }
  if (argument.isQuery) {
    output['x-paramType'] = 'query';
  }
  return output;
}

function serializeField(field: FieldDef, scalarNames: Set<string>): JsonObject {
  const output: JsonObject = serializeTypeRef(field.typeRef, scalarNames);
  if (field.description) {
    output.description = field.description;
  }
  if (field.title) {
    output.title = field.title;
  }
  if (field.purpose) {
    output['x-purpose'] = field.purpose;
  }
  if (field.icon) {
    output['x-icon'] = field.icon;
  }
  if (field.placeholder) {
    output['x-placeholder'] = field.placeholder;
  }
  if (field.defaultValue !== null) {
    output.default = parseDefaultValue(field.defaultValue, field.typeRef);
  }
  if (field.jsonKey !== field.name) {
    output['x-jsonTag'] = field.jsonKey;
  }
  if (field.autoGenerated) {
    output['x-autoGenerated'] = true;
  }
  if (field.key) {
    output['x-key'] = true;
  }
  if (field.unique) {
    output['x-unique'] = true;
  }
  if (field.searchField) {
    output['x-searchField'] = true;
  }
  if (field.relation) {
    output['x-relation'] = {
      type: field.relation.type,
      field: field.relation.field,
    };
  }
  if (field.hasMany) {
    output['x-hasMany'] = true;
  }
  if (field.manyToMany) {
    output['x-manyToMany'] = true;
  }
  if (field.jsonField) {
    output['x-jsonField'] = true;
  }
  if (field.secret) {
    output['x-secret'] = true;
  }
  if (field.uiHidden) {
    output['x-uiHidden'] = true;
  }
  if (field.semanticRole) {
    output['x-semantic-role'] = field.semanticRole;
  }
  if (field.temporalFormat) {
    output['x-temporal-format'] = field.temporalFormat;
  }
  if (field.transformDedupKey) {
    output['x-transformDedupKey'] = true;
  }
  if (field.transformOrdering) {
    output['x-transformOrdering'] = true;
  }
  if (field.transformFingerprintInput) {
    output['x-transformFingerprintInput'] = true;
  }
  if (field.transformPartitionDate) {
    output['x-transformPartitionDate'] = true;
  }
  if (field.transformStructural) {
    output['x-transformStructural'] = true;
  }
  if (field.transformPersonEmail) {
    output['x-transformPersonEmail'] = true;
  }
  if (field.transformPersonName) {
    output['x-transformPersonName'] = true;
  }
  if (field.transformAccountId) {
    output['x-transformAccountId'] = true;
  }
  if (field.transformExternalUserId) {
    output['x-transformExternalUserId'] = true;
  }
  if (field.exclude) {
    output['x-exclude'] = true;
  }
  if (field.internalMetadata) {
    output['x-internal-metadata'] = true;
  }
  if (field.auth) {
    output['x-auth'] = true;
  }
  if (field.requireOwnership) {
    output['x-requireOwnership'] = true;
  }
  if (field.permissions.length > 0) {
    output['x-permissions'] = [...field.permissions];
  }
  if (field.restMethod) {
    output['x-restMethod'] = field.restMethod;
  }
  if (field.paramType) {
    output['x-paramType'] = field.paramType;
  }
  if (field.validateMin !== null) {
    output['x-validateMin'] = field.validateMin;
  }
  if (field.validateMax !== null) {
    output['x-validateMax'] = field.validateMax;
  }
  if (field.validateMinLength !== null) {
    output['x-validateMinLength'] = field.validateMinLength;
  }
  if (field.validateMaxLength !== null) {
    output['x-validateMaxLength'] = field.validateMaxLength;
  }
  if (field.validateListMin !== null) {
    output['x-validateListMin'] = field.validateListMin;
  }
  if (field.validateListMax !== null) {
    output['x-validateListMax'] = field.validateListMax;
  }
  if (field.validatePattern) {
    output['x-validatePattern'] = field.validatePattern;
  }
  withMiddleware(output, field.middleware, field.encrypted);

  if (field.arguments.length > 0) {
    const args: JsonObject = {};
    for (const argument of [...field.arguments].sort((a, b) => a.name.localeCompare(b.name))) {
      args[argument.name] = serializeArgument(argument, scalarNames);
    }
    output['x-arguments'] = args;
  }

  return output;
}

function serializeOperationSet(
  operationSet: OperationSet | undefined,
  scalarNames: Set<string>
): JsonObject | undefined {
  if (!operationSet || operationSet.operations.length === 0) {
    return undefined;
  }

  const required: string[] = [];
  const properties: JsonObject = {};
  for (const operation of [...operationSet.operations].sort((a, b) =>
    a.name.localeCompare(b.name)
  )) {
    properties[operation.name] = serializeField(operation, scalarNames);
    if (operation.required || operation.autoGenerated) {
      required.push(operation.name);
    }
  }

  const output: JsonObject = {
    type: 'object',
    properties,
  };
  if (required.length > 0) {
    output.required = required;
  }
  withMiddleware(output, operationSet.middleware, operationSet.encrypted);

  return output;
}

function serializeSchemaDefinitions(schema: Schema): JsonObject {
  const output: JsonObject = {};
  const schemaScalars = schema.scalars || {};
  const schemaEnums = schema.enums || {};
  const schemaTypes = schema.types || {};
  const schemaInputs = schema.inputs || {};
  const scalarNames = new Set(Object.keys(schemaScalars));

  for (const scalarName of Object.keys(schemaScalars).sort((a, b) => a.localeCompare(b))) {
    output[scalarName] = serializeScalar(schemaScalars[scalarName]);
  }

  for (const enumName of Object.keys(schemaEnums).sort((a, b) => a.localeCompare(b))) {
    const enumDef = schemaEnums[enumName];
    const enumValues = enumDef.values.map(value => value.name);
    const enumValueMeta: JsonObject = {};
    let hasEnumMetadata = false;
    for (const value of enumDef.values) {
      const valueMeta: JsonObject = {};
      if (value.description) {
        valueMeta.description = value.description;
      }
      if (value.serializedAs) {
        valueMeta.serializedAs = value.serializedAs;
      }
      if (Object.keys(valueMeta).length > 0) {
        hasEnumMetadata = true;
      }
      enumValueMeta[value.name] = valueMeta;
    }

    const enumOut: JsonObject = {
      'x-kind': 'enum',
      type: 'string',
      enum: enumValues,
    };
    if (enumDef.description) {
      enumOut.description = enumDef.description;
    }
    if (enumDef.owner) {
      enumOut['x-owner'] = enumDef.owner;
    }
    if (hasEnumMetadata) {
      enumOut['x-enumValues'] = enumValueMeta;
    }
    output[enumName] = enumOut;
  }

  for (const typeName of Object.keys(schemaTypes).sort((a, b) => a.localeCompare(b))) {
    const typeDef = schemaTypes[typeName];
    const properties: JsonObject = {};
    const required: string[] = [];
    for (const field of typeDef.fields) {
      properties[field.name] = serializeField(field, scalarNames);
      if (field.required || field.autoGenerated) {
        required.push(field.name);
      }
    }
    const typeOut: JsonObject = {
      'x-kind': 'type',
      type: 'object',
      properties,
    };
    if (typeDef.description) {
      typeOut.description = typeDef.description;
    }
    if (required.length > 0) {
      typeOut.required = required;
    }
    if (typeDef.indexes.length > 0) {
      typeOut['x-indexes'] = typeDef.indexes.map(index => ({
        keys: [...index.keys],
        unique: index.unique,
      }));
    }
    if (typeDef.envVars) {
      typeOut['x-envVars'] = true;
    }
    output[typeName] = typeOut;
  }

  for (const inputName of Object.keys(schemaInputs).sort((a, b) => a.localeCompare(b))) {
    const inputDef = schemaInputs[inputName];
    const properties: JsonObject = {};
    const required: string[] = [];
    for (const field of inputDef.fields) {
      properties[field.name] = serializeField(field, scalarNames);
      if (field.required || field.autoGenerated) {
        required.push(field.name);
      }
    }
    const inputOut: JsonObject = {
      'x-kind': 'input',
      type: 'object',
      properties,
    };
    if (inputDef.description) {
      inputOut.description = inputDef.description;
    }
    if (required.length > 0) {
      inputOut.required = required;
    }
    if (inputDef.indexes.length > 0) {
      inputOut['x-indexes'] = inputDef.indexes.map(index => ({
        keys: [...index.keys],
        unique: index.unique,
      }));
    }
    if (inputDef.envVars) {
      inputOut['x-envVars'] = true;
    }
    output[inputName] = inputOut;
  }

  return output;
}

function serializeScalar(scalar: ScalarDef): JsonObject {
  const output: JsonObject = {
    type: primitiveToJsonType(scalar.primitive) || 'string',
    'x-scalar': scalar.name,
  };

  if (scalar.description) {
    output.description = scalar.description;
  }
  if (scalar.minLength > 0) {
    output.minLength = scalar.minLength;
  }
  if (scalar.maxLength > 0) {
    output.maxLength = scalar.maxLength;
  }
  if (scalar.pattern) {
    output.pattern = scalar.pattern;
  }
  if (scalar.format) {
    output.format = scalar.format;
  }
  if (scalar.reservedWords.length > 0) {
    output['x-reservedWords'] = [...scalar.reservedWords];
  }
  if (scalar.caseInsensitive) {
    output['x-caseInsensitive'] = true;
  }
  if (scalar.reservedWordsCaseInsensitive) {
    output['x-reservedWordsCaseInsensitive'] = true;
  }
  if (scalar.reservedWordsMatchPartial) {
    output['x-reservedWordsMatchPartial'] = true;
  }
  if (scalar.minimum !== null) {
    output.minimum = scalar.minimum;
  }
  if (scalar.maximum !== null) {
    output.maximum = scalar.maximum;
  }
  if (scalar.example) {
    output['x-example'] = scalar.example;
  }
  if (scalar.fileUpload) {
    output['x-fileUpload'] = {
      maxSize: scalar.fileUpload.maxSize,
      allowedTypes: [...scalar.fileUpload.allowedTypes],
      category: scalar.fileUpload.category,
    };
  }
  if (scalar.imageConstraints) {
    output['x-imageConstraints'] = {
      maxWidth: scalar.imageConstraints.maxWidth,
      maxHeight: scalar.imageConstraints.maxHeight,
      ...(scalar.imageConstraints.minAspectRatio !== null
        ? { minAspectRatio: scalar.imageConstraints.minAspectRatio }
        : {}),
      ...(scalar.imageConstraints.maxAspectRatio !== null
        ? { maxAspectRatio: scalar.imageConstraints.maxAspectRatio }
        : {}),
      requireTransparency: scalar.imageConstraints.requireTransparency,
    };
  }
  if (scalar.hasCustomNormalize) {
    output['x-hasCustomNormalize'] = true;
  }
  if (scalar.hasCustomValidate) {
    output['x-hasCustomValidate'] = true;
  }
  if (scalar.hasCustomParse) {
    output['x-hasCustomParse'] = true;
  }

  const typeMappingKeys = Object.keys(scalar.typeMappings).sort((a, b) => a.localeCompare(b));
  if (typeMappingKeys.length > 0) {
    const typeMappings: JsonObject = {};
    for (const key of typeMappingKeys) {
      typeMappings[key] = scalar.typeMappings[key];
    }
    output['x-typeMapping'] = typeMappings;
  }

  return output;
}

export function writeScalarsJson(scalars: Record<string, ScalarDef>): string {
  const definitions: JsonObject = {};
  for (const scalarName of Object.keys(scalars).sort((a, b) => a.localeCompare(b))) {
    definitions[scalarName] = serializeScalar(scalars[scalarName]);
  }

  const root: JsonObject = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    definitions,
  };

  return `${JSON.stringify(sortObject(root), null, 2)}\n`;
}

// DEFAULT_META_SCHEMA_URL is the $id the compiler gives its schema-file
// meta-schema under default naming (Naming.MetaSchemaURL("schema-file.json")).
// A deployment that renames the prefix in its naming file passes its own URL
// through WriteSchemaJsonOptions.
export const DEFAULT_META_SCHEMA_URL = 'superschematic://schema-file.json';

export interface WriteSchemaJsonOptions {
  metaSchemaUrl?: string;
}

export function writeSchemaJson(schema: Schema, options: WriteSchemaJsonOptions = {}): string {
  const scalarNames = new Set(Object.keys(schema.scalars || {}));
  const metaSchemaUrl = options.metaSchemaUrl || DEFAULT_META_SCHEMA_URL;
  const root: JsonObject = {
    $schema: metaSchemaUrl,
    ...(schema.name ? { title: schema.name } : {}),
    ...(schema.kind ? { 'x-kind': schema.kind } : {}),
    ...(schema.description ? { description: schema.description } : {}),
    ...(schema.rootType ? { 'x-rootType': schema.rootType } : {}),
    definitions: serializeSchemaDefinitions(schema),
  };

  const imports = [...schema.imports]
    .filter(runtimeImport => runtimeImport.from)
    .sort((a, b) => a.from.localeCompare(b.from))
    .map(runtimeImport => ({
      from: runtimeImport.from,
      types:
        runtimeImport.types.length === 1 && runtimeImport.types[0] === '*'
          ? '*'
          : [...runtimeImport.types],
    }));
  if (imports.length > 0) {
    root['x-imports'] = imports;
  }

  const unions: JsonObject = {};
  const schemaUnions = schema.unions || {};
  for (const unionName of Object.keys(schemaUnions).sort((a, b) => a.localeCompare(b))) {
    const unionDef = schemaUnions[unionName];
    unions[unionName] = {
      ...(unionDef.description ? { description: unionDef.description } : {}),
      anyOf: [...unionDef.types]
        .sort((a, b) => a.localeCompare(b))
        .map(typeName => ({
          $ref: `#/definitions/${typeName}`,
        })),
    };
  }
  if (Object.keys(unions).length > 0) {
    root['x-unions'] = unions;
  }

  const queries = serializeOperationSet(schema.queries, scalarNames);
  if (queries) {
    root['x-queries'] = queries;
  }

  const mutations = serializeOperationSet(schema.mutations, scalarNames);
  if (mutations) {
    root['x-mutations'] = mutations;
  }

  return `${JSON.stringify(sortObject(root), null, 2)}\n`;
}
