// Code generated by tsgen. DO NOT EDIT.

import type { ScalarValidationResult, ValidationError } from '@psgen/scalar-lib/validation';

const IdentitySlugPattern = new RegExp("^[a-z0-9]+(?:[-_][a-z0-9]+)*$");

/**
 * Validates a Identity.Slug value
 */
export function validateIdentitySlug(
  value: string | null | undefined
): ScalarValidationResult {
  const errors: ValidationError[] = [];

  if (value === null || value === undefined) {
    return [true, null];
  }

  const s = String(value);

  if (s.length < 1) {
    errors.push({ validator: "minLength", message: "must be at least 1 characters" });
  }

  if (s.length > 255) {
    errors.push({ validator: "maxLength", message: "must be at most 255 characters" });
  }

  if (!IdentitySlugPattern.test(s)) {
    errors.push({ validator: "pattern", message: "invalid format" });
  }

  return errors.length > 0 ? [false, errors] : [true, null];
}

/**
 * Validates a Identity.Slug value with required check
 */
export function validateIdentitySlugRequired(
  value: string | null | undefined
): ScalarValidationResult {

  if (value === null || value === undefined || value === "") {
    return [false, [{ validator: "required", message: "required field" }]];
  }

  return validateIdentitySlug(value);
}
