// Code generated by superschematic sentinel. DO NOT EDIT.
import { service, SchemaKind } from "@superschematic/schema-config";
import type { OrdersConfig } from "./config.schema";
export const ShopOrders = service<"API", OrdersConfig>({ name: "shop-orders", kind: SchemaKind.API });
