// Code generated by tsgen. DO NOT EDIT.

import type { ScalarValidationResult, ValidationError } from 'superscalar/validation';

import { validateContactEmail as validateContactEmailFromLib, normalizeContactEmail as normalizeContactEmailFromLib } from 'superscalar/scalars';

const ContactEmailPattern = new RegExp("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", "u");

/**
 * Validates a Contact.Email value
 */
export function validateContactEmail(
  value: string | null | undefined
): ScalarValidationResult {
  const errors: ValidationError[] = [];

  if (value === null || value === undefined) {
    return [true, null];
  }

  // A value of another JSON type is "type", and its length and format are
  // not checked.
  const candidate: unknown = value;

  if (typeof candidate !== "string") {
    return [false, [{ validator: "type", message: "expected string value" }]];
  }
  const s = candidate;

  // Lengths count code points, not UTF-16 units.
  const length = [...s].length;

  if (length > 255) {
    errors.push({ validator: "maxLength", message: "must be at most 255 characters" });
  }

  if (!ContactEmailPattern.test(s)) {
    errors.push({ validator: "pattern", message: "invalid format" });
  }

  // The scalar core checks the rules above again, so it runs only when they
  // pass: one failing value, one error.
  if (errors.length === 0) {
    const [isValid, customErrors] = validateContactEmailFromLib(value as string);
    if (!isValid && customErrors) {
      errors.push(...customErrors);
    }
  }

  return errors.length > 0 ? [false, errors] : [true, null];
}

/**
 * Validates a Contact.Email value with required check
 */
export function validateContactEmailRequired(
  value: string | null | undefined
): ScalarValidationResult {

  if (value === null || value === undefined || value === "") {
    return [false, [{ validator: "required", message: "required field" }]];
  }

  return validateContactEmail(value);
}

/**
 * Normalizes a Contact.Email value using custom normalization
 */
export function normalizeContactEmail(value: string): string | null {
  return normalizeContactEmailFromLib(value);
}
