// Code generated by superschematic sentinel. DO NOT EDIT.
import { service, SchemaKind } from "@superschematic/schema-config";
export const FixtureChainBase = service({ name: "fixture-chain-base", kind: SchemaKind.General });
