# Code generated by pygen. DO NOT EDIT.

"""
schemas_types_fixture_version_graph_db - Generated Python types for fixture-version-graph-db schema.

This package provides type-safe Python models generated from Superschematic
definitions. All models use Pydantic v2 for validation and serialization.

Modules:
    - scalars: Custom scalar types with validation
    - enums: Enumeration types
    - types: Complex object types
    - validation_errors: Validation error classes

Usage:
    from schemas_types_fixture_version_graph_db import *

    # Use the generated types
    obj = SomeType.model_validate(data)
"""

__version__ = "1.0.0"

from .validation_errors import (
    ValidationError,
    FieldValidationError,
    RequiredFieldError,
    ValidationErrors,
)

from .scalars import (
    GenericInt64,
    GenericJSON,
    IdentityUUID,
    IdentityUserID,
    TemporalDate,
    TemporalDateTime,
    TemporalDuration,
    TemporalTime
)

from .enums import (
    RecipeEntityKind,
    RecipePatchOperation,
    Verdict
)

from .types import (
    Cover,
    HistoryRecord,
    Ingredient,
    Note,
    Recipe,
    RecipeCommit,
    RecipePatch,
    RecipeRef,
    RecipeRelease,
    RecipeSnapshotEntry,
    Step,
    Tasting,
    Utensil
)

__all__ = [
    "__version__",
    "ValidationError",
    "FieldValidationError",
    "RequiredFieldError",
    "ValidationErrors",
    # Scalars
    "GenericInt64",
    "GenericJSON",
    "IdentityUUID",
    "IdentityUserID",
    "TemporalDate",
    "TemporalDateTime",
    "TemporalDuration",
    "TemporalTime",

    # Enums
    "RecipeEntityKind",
    "RecipePatchOperation",
    "Verdict",

    # Types
    "Cover",
    "HistoryRecord",
    "Ingredient",
    "Note",
    "Recipe",
    "RecipeCommit",
    "RecipePatch",
    "RecipeRef",
    "RecipeRelease",
    "RecipeSnapshotEntry",
    "Step",
    "Tasting",
    "Utensil",

]
