// @generated; do not edit
// Builtin scalar catalog generated from the parable-scalars-core registry
// (utils/parable-scalars/ext/src/lib.rs registry(): the Parable scalars
// assembled over the superscalar built-in catalog).
// Regenerate with: cd utils/parable-scalars && make codegen
import type { ScalarDef } from './validation/types';

export const BUILTIN_SCALARS: Record<string, ScalarDef> = {
  "Artifact_File": {
    "name": "Artifact_File",
    "description": "Artifact file metadata with GCS storage path",
    "primitive": "Type",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "{\"gcsPath\":\"gs://bucket/artifacts/tenant/file.csv\",\"mimeType\":\"text/csv\",\"size\":204800,\"filename\":\"export.csv\"}",
    "fileUpload": {
      "maxSize": 1073741824,
      "allowedTypes": [
        "text/csv",
        "application/octet-stream",
        "application/zip",
        "application/x-zip-compressed",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-excel",
        "application/vnd.apple.numbers",
        "application/vnd.oasis.opendocument.spreadsheet"
      ],
      "category": "artifact"
    },
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "ArtifactFileMetadata",
      "python": "ArtifactFileMetadata",
      "go": "ArtifactFileMetadata",
      "rust": "serde_json::Value",
      "sql": "JSONB",
      "json_schema": "object"
    }
  },
  "Asset_File": {
    "name": "Asset_File",
    "description": "Generic file metadata",
    "primitive": "Type",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "{\"url\":\"https://cdn.example.com/file.pdf\",\"mimeType\":\"application/pdf\",\"size\":204800,\"filename\":\"document.pdf\",\"assetId\":\"abc123\"}",
    "fileUpload": {
      "maxSize": 52428800,
      "allowedTypes": [],
      "category": "file"
    },
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "FileMetadata",
      "python": "FileMetadata",
      "go": "FileMetadata",
      "rust": "serde_json::Value",
      "sql": "JSONB",
      "json_schema": "object"
    }
  },
  "Asset_FilePath": {
    "name": "Asset_FilePath",
    "description": "A file system path",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "../dist/api/web-api",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "json_schema": "string"
    }
  },
  "Asset_Image": {
    "name": "Asset_Image",
    "description": "Image metadata",
    "primitive": "Type",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "{\"url\":\"https://cdn.example.com/img.jpg\",\"mimeType\":\"image/jpeg\",\"size\":102400,\"width\":800,\"height\":600,\"filename\":\"photo.jpg\"}",
    "fileUpload": {
      "maxSize": 2000000,
      "allowedTypes": [
        "image/jpeg",
        "image/png",
        "image/gif",
        "image/webp"
      ],
      "category": "image"
    },
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "ImageMetadata",
      "python": "ImageMetadata",
      "go": "ImageMetadata",
      "rust": "serde_json::Value",
      "sql": "JSONB",
      "json_schema": "object"
    }
  },
  "Asset_LogoImage": {
    "name": "Asset_LogoImage",
    "description": "Transparent PNG logo image",
    "primitive": "Type",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "{\"url\":\"https://cdn.example.com/logo.png\",\"mimeType\":\"image/png\",\"size\":51200,\"width\":512,\"height\":512,\"filename\":\"logo.png\",\"hasTransparency\":true}",
    "fileUpload": {
      "maxSize": 1000000,
      "allowedTypes": [
        "image/png"
      ],
      "category": "image"
    },
    "imageConstraints": {
      "maxWidth": 0,
      "maxHeight": 0,
      "minAspectRatio": null,
      "maxAspectRatio": null,
      "requireTransparency": true
    },
    "hasCustomNormalize": false,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "LogoImageMetadata",
      "python": "LogoImageMetadata",
      "go": "LogoImageMetadata",
      "rust": "serde_json::Value",
      "sql": "JSONB",
      "json_schema": "object"
    }
  },
  "Auth_JWT": {
    "name": "Auth_JWT",
    "description": "JSON Web Token string",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "TEXT",
      "json_schema": "string"
    }
  },
  "Auth_Password": {
    "name": "Auth_Password",
    "description": "User password (minimum 8 characters)",
    "primitive": "String",
    "minLength": 8,
    "maxLength": 128,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(128)",
      "json_schema": "string"
    }
  },
  "Connector_Slug": {
    "name": "Connector_Slug",
    "description": "An opaque identifier for a connector definition",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 32,
    "pattern": "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$",
    "format": "",
    "reservedWords": [
      "identity",
      "artifacts"
    ],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "anaplan",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "CITEXT",
      "json_schema": "string"
    }
  },
  "Contact_Email": {
    "name": "Contact_Email",
    "description": "An email address",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 255,
    "pattern": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "test@example.com",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": true,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "CITEXT",
      "json_schema": "string"
    }
  },
  "Contact_PhoneNumber": {
    "name": "Contact_PhoneNumber",
    "description": "Phone number in E.164 format",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 16,
    "pattern": "^\\+[1-9]\\d{1,14}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "+1234567890",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": true,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(16)",
      "json_schema": "string"
    }
  },
  "Crypto_RSAPrivateKey": {
    "name": "Crypto_RSAPrivateKey",
    "description": "RSA private key in PEM format",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^-----BEGIN (RSA )?PRIVATE KEY-----[\\s\\S]*-----END (RSA )?PRIVATE KEY-----\\s*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "-----BEGIN RSA PRIVATE KEY----------END RSA PRIVATE KEY-----",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "TEXT",
      "json_schema": "string"
    }
  },
  "Crypto_RSAPublicKey": {
    "name": "Crypto_RSAPublicKey",
    "description": "RSA public key in PEM format",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^-----BEGIN PUBLIC KEY-----[\\s\\S]*-----END PUBLIC KEY-----\\s*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "-----BEGIN PUBLIC KEY----------END PUBLIC KEY-----",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "TEXT",
      "json_schema": "string"
    }
  },
  "Design_Color": {
    "name": "Design_Color",
    "description": "CSS color value normalized to 8-digit RGBA hex format (#RRGGBBAA)",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 9,
    "pattern": "^#[0-9A-Fa-f]{8}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "#FF5733FF",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": true,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(9)",
      "json_schema": "string"
    }
  },
  "Embedding_Vector": {
    "name": "Embedding_Vector",
    "description": "Fixed-dimensional float32 vector",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "number[]",
      "python": "list[float]",
      "go": "[]float32",
      "rust": "Vec<f32>",
      "json_schema": "array"
    }
  },
  "File_SizeBytes": {
    "name": "File_SizeBytes",
    "description": "File size in bytes (non-negative, BIGINT-backed)",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": 0,
    "maximum": 9007199254740991,
    "example": "204800",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "number",
      "python": "int",
      "go": "int64",
      "rust": "i64",
      "sql": "BIGINT",
      "json_schema": "integer"
    }
  },
  "Finance_Money": {
    "name": "Finance_Money",
    "description": "Monetary amount in smallest currency unit (e.g., cents for USD)",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": 0,
    "maximum": 9007199254740991,
    "example": "1000",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "number",
      "python": "int",
      "go": "int64",
      "rust": "i64",
      "sql": "BIGINT",
      "json_schema": "integer"
    }
  },
  "Generic_Int64": {
    "name": "Generic_Int64",
    "description": "Signed 64-bit integer; range bounded by JavaScript's safe-integer ceiling.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "1000",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "number",
      "python": "int",
      "go": "int64",
      "rust": "i64",
      "sql": "BIGINT",
      "json_schema": "integer"
    }
  },
  "Generic_JSON": {
    "name": "Generic_JSON",
    "description": "A JSON object represented as a string",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "Record<string, any>",
      "python": "dict",
      "go": "json.RawMessage",
      "rust": "serde_json::Value",
      "sql": "JSONB",
      "json_schema": "object"
    }
  },
  "Generic_Probability": {
    "name": "Generic_Probability",
    "description": "Probability value from 0.0 to 1.0 inclusive",
    "primitive": "Float",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": 0,
    "maximum": 1,
    "example": "0.75",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "number",
      "python": "float",
      "go": "float64",
      "rust": "f64",
      "sql": "DOUBLE PRECISION",
      "json_schema": "number"
    }
  },
  "Generic_StringMap": {
    "name": "Generic_StringMap",
    "description": "A string-to-string map stored as JSON",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "Record<string, string>",
      "python": "Dict[str, str]",
      "go": "map[string]string",
      "rust": "std::collections::HashMap<String, String>",
      "sql": "JSONB",
      "json_schema": "object"
    }
  },
  "Geo_Location": {
    "name": "Geo_Location",
    "description": "Geographic location with latitude and longitude",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^-?\\d+(\\.\\d+)?,-?\\d+(\\.\\d+)?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "37.7749,-122.4194",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "{ lat: number; lon: number }",
      "python": "dict",
      "go": "struct{ Lat float64; Lon float64 }",
      "rust": "struct Location { lat: f64, lon: f64 }",
      "sql": "POINT",
      "json_schema": "object"
    }
  },
  "Identity_Name": {
    "name": "Identity_Name",
    "description": "An objects name",
    "primitive": "String",
    "minLength": 2,
    "maxLength": 80,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "A Name",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(80)",
      "json_schema": "string"
    }
  },
  "Identity_Slug": {
    "name": "Identity_Slug",
    "description": "A URL friendly version of a string",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 255,
    "pattern": "^[a-z0-9]+(?:[-_][a-z0-9]+)*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "acme-corp",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "CITEXT",
      "json_schema": "string"
    }
  },
  "Identity_UUID": {
    "name": "Identity_UUID",
    "description": "UUID v4 with automatic base62 encoding for client-facing APIs",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "YQJpYwUwvbaLOwTUr4thA",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "string",
      "python": "uuid.UUID",
      "go": "uuid.UUID",
      "rust": "uuid::Uuid",
      "sql": "UUID",
      "json_schema": "string"
    }
  },
  "Identity_UserID": {
    "name": "Identity_UserID",
    "description": "UUID v4 string as base62",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^[0-9A-Za-z]{1,22}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "YQJpYwUwvbaLOwTUr4thA",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "string",
      "python": "uuid.UUID",
      "go": "uuid.UUID",
      "rust": "uuid::Uuid",
      "sql": "UUID",
      "json_schema": "string"
    }
  },
  "Localization_Locale": {
    "name": "Localization_Locale",
    "description": "BCP 47 language tag (e.g., en-US, fr-FR)",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 35,
    "pattern": "^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "en-US",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(35)",
      "json_schema": "string"
    }
  },
  "Network_DomainName": {
    "name": "Network_DomainName",
    "description": "Valid domain name (RFC 1035 compliant)",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 255,
    "pattern": "^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "example.com",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "CITEXT",
      "json_schema": "string"
    }
  },
  "Network_IpAddress": {
    "name": "Network_IpAddress",
    "description": "IPv4 or IPv6 address",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 45,
    "pattern": "^(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "192.168.1.1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "INET",
      "json_schema": "string"
    }
  },
  "Network_Uri": {
    "name": "Network_Uri",
    "description": "RFC 3986 URI for connection strings and non-HTTP resources",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 4096,
    "pattern": "^[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s]+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "postgres://user:pass@localhost:5432/dbname",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "TEXT",
      "json_schema": "string"
    }
  },
  "Network_Url": {
    "name": "Network_Url",
    "description": "Valid HTTP/HTTPS URL",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 2048,
    "pattern": "^https?://[\\w\\-\\{\\}]+(\\.[\\w\\-\\{\\}]+)+([:/?#][\\w\\-\\._~:/?#\\[\\]@!\\$&'\\(\\)\\*\\+,;=\\{\\}%]*)?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "https://www.example.com/example/path",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "varchar(4096)",
      "json_schema": "string"
    }
  },
  "Parable_ErrorCode": {
    "name": "Parable_ErrorCode",
    "description": "Application error code",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 50,
    "pattern": "^[A-Z_][A-Z0-9_]*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(50)",
      "json_schema": "string"
    }
  },
  "Parable_LtreePath": {
    "name": "Parable_LtreePath",
    "description": "Hierarchical path expressed as a dot-separated ltree (e.g., 'reports.q1.draft').",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 2048,
    "pattern": "^[A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "reports.q1.draft",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "ltree",
      "json_schema": "string"
    }
  },
  "Parable_Permission": {
    "name": "Parable_Permission",
    "description": "Hierarchical permission string (e.g., 'admin.users.read')",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 255,
    "pattern": "^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "admin.users.read",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "ltree",
      "json_schema": "string"
    }
  },
  "Parable_Scalar": {
    "name": "Parable_Scalar",
    "description": "Canonical name of a Parable scalar (e.g., Identity.UUID, Generic.Int64)",
    "primitive": "String",
    "minLength": 3,
    "maxLength": 128,
    "pattern": "^[A-Z][A-Za-z0-9]*\\.[A-Z][A-Za-z0-9]*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "Identity.UUID",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(128)",
      "json_schema": "string"
    }
  },
  "Parable_Schema": {
    "name": "Parable_Schema",
    "description": "A Parable Schema in JSON",
    "primitive": "Type",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "{\"$schema\":\"https://parable.work/schemas/parable-schema.json\",\"definitions\":{\"ExampleType\":{\"properties\":{\"accountId\":{\"$ref\":\"#/definitions/scalars/Identity.UUID\"},\"clientSecret\":{\"type\":\"string\",\"x-secret\":true},\"url\":{\"$ref\":\"#/definitions/scalars/Network.Url\"}},\"required\":[\"accountId\",\"clientSecret\",\"url\"],\"type\":\"object\",\"x-kind\":\"type\"}}}",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "ParableSchemaType",
      "python": "ParableSchemaType",
      "go": "ParableSchemaType",
      "rust": "serde_json::Value",
      "sql": "JSONB",
      "json_schema": "object"
    }
  },
  "Parable_SchemaData": {
    "name": "Parable_SchemaData",
    "description": "A Parable Schema in JSON",
    "primitive": "Type",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "{\"__typename\": \"ExampleType\", \"accountId\": \"YQJpYwUwvbaLOwTUr4thA\", \"clientSecret\": \"secret123\", \"url\": \"https://example.com\"}",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "ParableSchemaDataType",
      "python": "ParableSchemaDataType",
      "go": "ParableSchemaDataType",
      "rust": "serde_json::Value",
      "sql": "JSONB",
      "json_schema": "object"
    }
  },
  "Parable_Slug": {
    "name": "Parable_Slug",
    "description": "A URL friendly version of a string",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 17,
    "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
    "format": "",
    "reservedWords": [
      "parable",
      "admin",
      "trust",
      "cdn",
      "app"
    ],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "acme-corp",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "CITEXT",
      "json_schema": "string"
    }
  },
  "Tap_Identifier": {
    "name": "Tap_Identifier",
    "description": "A machine identifier for a data tap (lowercase alphanumeric, underscores, and hyphens)",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 200,
    "pattern": "^[a-z][a-z0-9_-]*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "group_members",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(80)",
      "json_schema": "string"
    }
  },
  "Temporal_CronExpression": {
    "name": "Temporal_CronExpression",
    "description": "Standard 5-field cron expression for scheduling",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 100,
    "pattern": "^[0-9*,\\-\\/]+\\s+[0-9*,\\-\\/]+\\s+[0-9*,\\-\\/?]+\\s+[0-9*,\\-\\/A-Za-z]+\\s+[0-9*,\\-\\/A-Za-z]+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "0 9 * * MON-FRI",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(100)",
      "json_schema": "string"
    }
  },
  "Temporal_Date": {
    "name": "Temporal_Date",
    "description": "Calendar date, normalized to ISO 'YYYY-MM-DD'. Accepts ISO ('2025-01-01'), slash-separated ('2025/01/15', '01/15/2025'), named-month ('January 15, 2025', 'Jan 15, 2025'), and full RFC3339 datetime (the time portion is dropped).",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 40,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "2025-01-01",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "DATE",
      "json_schema": "string"
    }
  },
  "Temporal_DateTime": {
    "name": "Temporal_DateTime",
    "description": "ISO8601 datetime string. Epoch wire values keep this scalar and declare x-temporal-format (unix, unix_millis, unix_micros, unix_nanos) on the property; the unit is never guessed from digit count.",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "2025-01-01T12:00:00Z",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "Date",
      "python": "datetime.datetime",
      "go": "time.Time",
      "rust": "chrono::DateTime<chrono::Utc>",
      "sql": "TIMESTAMPTZ",
      "json_schema": "string"
    }
  },
  "Temporal_Duration": {
    "name": "Temporal_Duration",
    "description": "Duration for timeouts and intervals",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 32,
    "pattern": "^(\\d+(\\.\\d+)?(ns|us|µs|ms|s|m|h))+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "30s",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": true,
    "hasCustomValidate": true,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "time.Duration",
      "rust": "String",
      "sql": "INTERVAL",
      "json_schema": "string"
    }
  },
  "Temporal_Milliseconds": {
    "name": "Temporal_Milliseconds",
    "description": "Signed integer count of milliseconds: an amount of elapsed time, never a point in time. An epoch timestamp is Temporal.DateTime with x-temporal-format: unix_millis.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "1000",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "number",
      "python": "int",
      "go": "int64",
      "rust": "i64",
      "sql": "BIGINT",
      "json_schema": "integer"
    }
  },
  "Temporal_Month": {
    "name": "Temporal_Month",
    "description": "Calendar month, normalized to two-digit numeric (01-12). Accepts '2', '02', 'Feb', 'February' (case-insensitive).",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 9,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "02",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(2)",
      "json_schema": "string"
    }
  },
  "Temporal_Quarter": {
    "name": "Temporal_Quarter",
    "description": "Calendar quarter (Q1-Q4)",
    "primitive": "String",
    "minLength": 2,
    "maxLength": 2,
    "pattern": "^[Qq][1-4]$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "Q1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(2)",
      "json_schema": "string"
    }
  },
  "Temporal_QuarterYear": {
    "name": "Temporal_QuarterYear",
    "description": "Quarter and year, normalized to 'YYYY-Q#'. Accepts '2025-Q1', 'Q1/2025', 'Q1-2025', 'Q1-25' (2-digit years interpreted as 20XX).",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 8,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "2025-Q1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(7)",
      "json_schema": "string"
    }
  },
  "Temporal_Time": {
    "name": "Temporal_Time",
    "description": "Time of day. 24-hour 'HH:MM' or 'HH:MM:SS' (hours 00-23), or 12-hour 'H:MM'/'HH:MM' with optional ':SS' and required AM/PM suffix (hours 1-12). Seconds and the AM/PM separator space are optional.",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^(?:(?:[01][0-9]|2[0-3]):[0-5][0-9](?::[0-5][0-9])?|(?:0?[1-9]|1[0-2]):[0-5][0-9](?::[0-5][0-9])?\\s?[AaPp][Mm])$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "12:25",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "TIME",
      "json_schema": "string"
    }
  },
  "Temporal_TimeZone": {
    "name": "Temporal_TimeZone",
    "description": "IANA timezone identifier (e.g., America/New_York, UTC, Etc/UTC)",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 100,
    "pattern": "^(?:UTC|[A-Za-z]+/[A-Za-z_/]+)$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "America/New_York",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(100)",
      "json_schema": "string"
    }
  },
  "Temporal_Year": {
    "name": "Temporal_Year",
    "description": "Calendar year as a 4-digit string (e.g., 2025)",
    "primitive": "String",
    "minLength": 4,
    "maxLength": 4,
    "pattern": "^[1-9]\\d{3}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "2025",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(4)",
      "json_schema": "string"
    }
  },
  "Text_Markdown": {
    "name": "Text_Markdown",
    "description": "Markdown text",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 0,
    "pattern": "^[\\s\\S]*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "## Hello, World!",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "TEXT",
      "json_schema": "string"
    }
  },
  "Parable_Handle": {
    "name": "Parable_Handle",
    "description": "A mutable camelCase code, path, and file identifier; URLs use stable UUIDs",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 200,
    "pattern": "^[a-z][A-Za-z0-9]*$",
    "format": "",
    "reservedWords": [
      "con",
      "prn",
      "aux",
      "nul",
      "com1",
      "com2",
      "com3",
      "com4",
      "com5",
      "com6",
      "com7",
      "com8",
      "com9",
      "lpt1",
      "lpt2",
      "lpt3",
      "lpt4",
      "lpt5",
      "lpt6",
      "lpt7",
      "lpt8",
      "lpt9"
    ],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": true,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "revenueForecast",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "CITEXT",
      "json_schema": "string"
    }
  },
  "Temporal_Seconds": {
    "name": "Temporal_Seconds",
    "description": "Signed integer count of seconds: an amount of elapsed time, never a point in time. An epoch timestamp is Temporal.DateTime with x-temporal-format: unix.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "60",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "number",
      "python": "int",
      "go": "int64",
      "rust": "i64",
      "sql": "BIGINT",
      "json_schema": "integer"
    }
  },
  "Temporal_Minutes": {
    "name": "Temporal_Minutes",
    "description": "Signed integer count of minutes: an amount of elapsed time, never a point in time.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "5",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "number",
      "python": "int",
      "go": "int64",
      "rust": "i64",
      "sql": "BIGINT",
      "json_schema": "integer"
    }
  },
  "Temporal_Hours": {
    "name": "Temporal_Hours",
    "description": "Signed integer count of hours: an amount of elapsed time, never a point in time.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "2",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "number",
      "python": "int",
      "go": "int64",
      "rust": "i64",
      "sql": "BIGINT",
      "json_schema": "integer"
    }
  },
  "Temporal_Days": {
    "name": "Temporal_Days",
    "description": "Signed integer count of days: an amount of elapsed time, never a point in time or a calendar date.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "7",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "typescript": "number",
      "python": "int",
      "go": "int64",
      "rust": "i64",
      "sql": "BIGINT",
      "json_schema": "integer"
    }
  },
  "Text_Sql": {
    "name": "Text_Sql",
    "description": "SQL text",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 0,
    "pattern": "^[\\s\\S]*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "SELECT 1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "TEXT",
      "json_schema": "string"
    }
  },
  "Parable_Icon": {
    "name": "Parable_Icon",
    "description": "Serialized icon spec: a Font Awesome pack/weight/fill/name, an emoji, or an asset URL",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 2048,
    "pattern": "^(?:fa:[a-z0-9]+(?:-[a-z0-9]+)*:[a-z0-9]+-[a-z0-9]+(?:-[a-z0-9]+)*:[a-z0-9]+(?:-[a-z0-9]+)*(?:@#[0-9a-f]{6})?|emoji:\\S+|image:\\S+)$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "fa:classic:regular-outline:circle-check",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "TEXT",
      "json_schema": "string"
    }
  },
  "Crypto_SHA256": {
    "name": "Crypto_SHA256",
    "description": "Lowercase hexadecimal SHA-256 digest",
    "primitive": "String",
    "minLength": 64,
    "maxLength": 64,
    "pattern": "^[0-9a-f]{64}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(64)",
      "json_schema": "string"
    }
  },
  "Network_DnsLabel": {
    "name": "Network_DnsLabel",
    "description": "Single DNS label (RFC 1035): one hostname segment, no dots",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 63,
    "pattern": "^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "mycompany",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "CITEXT",
      "json_schema": "string"
    }
  },
  "Temporal_RecurrenceRule": {
    "name": "Temporal_RecurrenceRule",
    "description": "RFC 5545 recurrence rule, without DTSTART",
    "primitive": "String",
    "minLength": 6,
    "maxLength": 512,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "FREQ=WEEKLY;BYMINUTE=0;BYHOUR=9;BYDAY=MO,WE,FR",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "VARCHAR(512)",
      "json_schema": "string"
    }
  },
  "Parable_CatalogSlug": {
    "name": "Parable_CatalogSlug",
    "description": "An immutable data-catalog segment: parables.{parable_slug}.{plot_slug}",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 255,
    "pattern": "^[a-z][a-z0-9]*(_[a-z0-9]+)*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": true,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "q1_sales",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "typescript": "string",
      "python": "str",
      "go": "string",
      "rust": "String",
      "sql": "CITEXT",
      "json_schema": "string"
    }
  }
};
