// @generated; do not edit
// Builtin scalar catalog: one row per scalar in the superscalar Go package
// this repository pins (superscalar.pin). Regenerate with:
//   go run ./internal/tools/scalarcatalog
import type { ScalarDef } from './validation/types';

export const BUILTIN_SCALARS: Record<string, ScalarDef> = {
  "AgentSkill_Name": {
    "name": "AgentSkill_Name",
    "description": "Portable Agent Skills directory and frontmatter name",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 64,
    "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "data-analysis",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "AgentSkillName",
      "json_schema": "string",
      "sql": "CITEXT"
    }
  },
  "Auth_JWT": {
    "name": "Auth_JWT",
    "description": "JSON Web Token string",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "AuthJWT",
      "json_schema": "string",
      "sql": "TEXT"
    }
  },
  "Auth_Password": {
    "name": "Auth_Password",
    "description": "User password (minimum 8 characters)",
    "primitive": "String",
    "minLength": 8,
    "maxLength": 128,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "AuthPassword",
      "json_schema": "string",
      "sql": "VARCHAR(128)"
    }
  },
  "Contact_Email": {
    "name": "Contact_Email",
    "description": "An email address",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 255,
    "pattern": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "test@example.com",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": true,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "ContactEmail",
      "json_schema": "string",
      "sql": "CITEXT"
    }
  },
  "Contact_PhoneNumber": {
    "name": "Contact_PhoneNumber",
    "description": "Phone number in E.164 format",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 16,
    "pattern": "^\\+[1-9]\\d{1,14}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "+1234567890",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": true,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "ContactPhoneNumber",
      "json_schema": "string",
      "sql": "VARCHAR(16)"
    }
  },
  "Crypto_RSAPrivateKey": {
    "name": "Crypto_RSAPrivateKey",
    "description": "RSA private key in PEM format",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^-----BEGIN (RSA )?PRIVATE KEY-----[\\s\\S]*-----END (RSA )?PRIVATE KEY-----\\s*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "-----BEGIN RSA PRIVATE KEY----------END RSA PRIVATE KEY-----",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "CryptoRSAPrivateKey",
      "json_schema": "string",
      "sql": "TEXT"
    }
  },
  "Crypto_RSAPublicKey": {
    "name": "Crypto_RSAPublicKey",
    "description": "RSA public key in PEM format",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^-----BEGIN PUBLIC KEY-----[\\s\\S]*-----END PUBLIC KEY-----\\s*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "-----BEGIN PUBLIC KEY----------END PUBLIC KEY-----",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "CryptoRSAPublicKey",
      "json_schema": "string",
      "sql": "TEXT"
    }
  },
  "Crypto_SHA256": {
    "name": "Crypto_SHA256",
    "description": "Lowercase hexadecimal SHA-256 digest",
    "primitive": "String",
    "minLength": 64,
    "maxLength": 64,
    "pattern": "^[0-9a-f]{64}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "CryptoSHA256",
      "json_schema": "string",
      "sql": "VARCHAR(64)"
    }
  },
  "Design_Color": {
    "name": "Design_Color",
    "description": "CSS color value normalized to 8-digit RGBA hex format (#RRGGBBAA)",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 9,
    "pattern": "^#[0-9A-Fa-f]{8}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "#FF5733FF",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": true,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "DesignColor",
      "json_schema": "string",
      "sql": "VARCHAR(9)"
    }
  },
  "Embedding_Vector": {
    "name": "Embedding_Vector",
    "description": "Fixed-dimensional float32 vector",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "EmbeddingVector",
      "json_schema": "array"
    }
  },
  "File_SizeBytes": {
    "name": "File_SizeBytes",
    "description": "File size in bytes (non-negative, BIGINT-backed)",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": 0,
    "maximum": 9007199254740991,
    "example": "204800",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "FileSizeBytes",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Finance_Money": {
    "name": "Finance_Money",
    "description": "Monetary amount in smallest currency unit (e.g., cents for USD)",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": 0,
    "maximum": 9007199254740991,
    "example": "1000",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "FinanceMoney",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Generic_Int64": {
    "name": "Generic_Int64",
    "description": "Signed 64-bit integer; range bounded by JavaScript's safe-integer ceiling.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "1000",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "GenericInt64",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Generic_JSON": {
    "name": "Generic_JSON",
    "description": "Any valid JSON value: object, array, primitive, or null",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "{\"k\":1}",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "GenericJSON",
      "json_schema": "any",
      "sql": "JSONB"
    }
  },
  "Generic_Probability": {
    "name": "Generic_Probability",
    "description": "Probability value from 0.0 to 1.0 inclusive",
    "primitive": "Float",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": 0,
    "maximum": 1,
    "example": "0.75",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "GenericProbability",
      "json_schema": "number",
      "sql": "DOUBLE PRECISION"
    }
  },
  "Generic_StringMap": {
    "name": "Generic_StringMap",
    "description": "A string-to-string map stored as JSON",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "GenericStringMap",
      "json_schema": "object",
      "sql": "JSONB"
    }
  },
  "Geo_Location": {
    "name": "Geo_Location",
    "description": "Geographic location with latitude and longitude",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^-?\\d+(\\.\\d+)?,-?\\d+(\\.\\d+)?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "37.7749,-122.4194",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "GeoLocation",
      "json_schema": "object",
      "sql": "POINT"
    }
  },
  "Git_PathPattern": {
    "name": "Git_PathPattern",
    "description": "Repository-rooted, case-sensitive gitignore-style path pattern",
    "primitive": "String",
    "minLength": 2,
    "maxLength": 1024,
    "pattern": "^!?/[^\\x00\\r\\n]+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "/skills/**",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": true,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "GitPathPattern",
      "json_schema": "string",
      "sql": "VARCHAR(1024)"
    }
  },
  "Identity_Name": {
    "name": "Identity_Name",
    "description": "An objects name",
    "primitive": "String",
    "minLength": 2,
    "maxLength": 80,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "A Name",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "IdentityName",
      "json_schema": "string",
      "sql": "VARCHAR(80)"
    }
  },
  "Identity_Slug": {
    "name": "Identity_Slug",
    "description": "A URL friendly version of a string",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 255,
    "pattern": "^[a-z0-9]+(?:[-_][a-z0-9]+)*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "acme-corp",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "IdentitySlug",
      "json_schema": "string",
      "sql": "CITEXT"
    }
  },
  "Identity_UUID": {
    "name": "Identity_UUID",
    "description": "UUID v4 with automatic base62 encoding for client-facing APIs",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "YQJpYwUwvbaLOwTUr4thA",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "IdentityUUID",
      "json_schema": "string",
      "sql": "UUID"
    }
  },
  "Identity_UserID": {
    "name": "Identity_UserID",
    "description": "UUID v4 string as base62",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^[0-9A-Za-z]{1,22}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "YQJpYwUwvbaLOwTUr4thA",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "IdentityUserID",
      "json_schema": "string",
      "sql": "UUID"
    }
  },
  "Localization_Locale": {
    "name": "Localization_Locale",
    "description": "BCP 47 language tag (e.g., en-US, fr-FR)",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 35,
    "pattern": "^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "en-US",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "LocalizationLocale",
      "json_schema": "string",
      "sql": "VARCHAR(35)"
    }
  },
  "Network_DnsLabel": {
    "name": "Network_DnsLabel",
    "description": "Single DNS label (RFC 1035): one hostname segment, no dots",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 63,
    "pattern": "^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "mycompany",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "NetworkDnsLabel",
      "json_schema": "string",
      "sql": "CITEXT"
    }
  },
  "Network_DomainName": {
    "name": "Network_DomainName",
    "description": "Valid domain name (RFC 1035 compliant)",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 255,
    "pattern": "^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "example.com",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "NetworkDomainName",
      "json_schema": "string",
      "sql": "CITEXT"
    }
  },
  "Network_IpAddress": {
    "name": "Network_IpAddress",
    "description": "IPv4 or IPv6 address",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 45,
    "pattern": "^(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "192.168.1.1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "NetworkIpAddress",
      "json_schema": "string",
      "sql": "INET"
    }
  },
  "Network_Uri": {
    "name": "Network_Uri",
    "description": "RFC 3986 URI for connection strings and non-HTTP resources",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 4096,
    "pattern": "^[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s]+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "postgres://user:pass@localhost:5432/dbname",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "NetworkUri",
      "json_schema": "string",
      "sql": "TEXT"
    }
  },
  "Network_Url": {
    "name": "Network_Url",
    "description": "Valid HTTP/HTTPS URL",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 2048,
    "pattern": "^https?://[\\w\\-\\{\\}]+(\\.[\\w\\-\\{\\}]+)+([:/?#][\\w\\-\\._~:/?#\\[\\]@!\\$\u0026'\\(\\)\\*\\+,;=\\{\\}%]*)?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "https://www.example.com/example/path",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "NetworkUrl",
      "json_schema": "string",
      "sql": "varchar(4096)"
    }
  },
  "Ordering_Rank": {
    "name": "Ordering_Rank",
    "description": "Positive JavaScript-safe ordering rank",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": 1,
    "maximum": 9007199254740991,
    "example": "1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "OrderingRank",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Temporal_CronExpression": {
    "name": "Temporal_CronExpression",
    "description": "Standard 5-field cron expression for scheduling",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 100,
    "pattern": "^[0-9*,\\-\\/]+\\s+[0-9*,\\-\\/]+\\s+[0-9*,\\-\\/?]+\\s+[0-9*,\\-\\/A-Za-z]+\\s+[0-9*,\\-\\/A-Za-z]+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "0 9 * * MON-FRI",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalCronExpression",
      "json_schema": "string",
      "sql": "VARCHAR(100)"
    }
  },
  "Temporal_Date": {
    "name": "Temporal_Date",
    "description": "Calendar date, normalized to ISO 'YYYY-MM-DD'. Accepts ISO ('2025-01-01'), slash-separated ('2025/01/15', '01/15/2025'), named-month ('January 15, 2025', 'Jan 15, 2025'), and full RFC3339 datetime (the time portion is dropped).",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 40,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "2025-01-01",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalDate",
      "json_schema": "string",
      "sql": "DATE"
    }
  },
  "Temporal_DateTime": {
    "name": "Temporal_DateTime",
    "description": "ISO8601 datetime string. Epoch wire values keep this scalar and declare x-temporal-format (unix, unix_millis, unix_micros, unix_nanos) on the property; the unit is never guessed from digit count.",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "2025-01-01T12:00:00Z",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "TemporalDateTime",
      "json_schema": "string",
      "sql": "TIMESTAMPTZ"
    }
  },
  "Temporal_Days": {
    "name": "Temporal_Days",
    "description": "Signed integer count of days: an amount of elapsed time, never a point in time or a calendar date.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "7",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "TemporalDays",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Temporal_Duration": {
    "name": "Temporal_Duration",
    "description": "Duration for timeouts and intervals",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 32,
    "pattern": "^(\\d+(\\.\\d+)?(ns|us|µs|ms|s|m|h))+$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "30s",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": true,
    "hasCustomValidate": true,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "TemporalDuration",
      "json_schema": "string",
      "sql": "INTERVAL"
    }
  },
  "Temporal_Hours": {
    "name": "Temporal_Hours",
    "description": "Signed integer count of hours: an amount of elapsed time, never a point in time.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "2",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "TemporalHours",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Temporal_Milliseconds": {
    "name": "Temporal_Milliseconds",
    "description": "Signed integer count of milliseconds: an amount of elapsed time, never a point in time. An epoch timestamp is Temporal.DateTime with x-temporal-format: unix_millis.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "1000",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "TemporalMilliseconds",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Temporal_Minutes": {
    "name": "Temporal_Minutes",
    "description": "Signed integer count of minutes: an amount of elapsed time, never a point in time.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "5",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "TemporalMinutes",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Temporal_Month": {
    "name": "Temporal_Month",
    "description": "Calendar month, normalized to two-digit numeric (01-12). Accepts '2', '02', 'Feb', 'February' (case-insensitive).",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 9,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "02",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalMonth",
      "json_schema": "string",
      "sql": "VARCHAR(2)"
    }
  },
  "Temporal_Quarter": {
    "name": "Temporal_Quarter",
    "description": "Calendar quarter (Q1-Q4)",
    "primitive": "String",
    "minLength": 2,
    "maxLength": 2,
    "pattern": "^[Qq][1-4]$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "Q1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalQuarter",
      "json_schema": "string",
      "sql": "VARCHAR(2)"
    }
  },
  "Temporal_QuarterYear": {
    "name": "Temporal_QuarterYear",
    "description": "Quarter and year, normalized to 'YYYY-Q#'. Accepts '2025-Q1', 'Q1/2025', 'Q1-2025', 'Q1-25' (2-digit years interpreted as 20XX).",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 8,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "2025-Q1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalQuarterYear",
      "json_schema": "string",
      "sql": "VARCHAR(7)"
    }
  },
  "Temporal_RecurrenceRule": {
    "name": "Temporal_RecurrenceRule",
    "description": "RFC 5545 recurrence rule, without DTSTART",
    "primitive": "String",
    "minLength": 6,
    "maxLength": 512,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "FREQ=WEEKLY;BYMINUTE=0;BYHOUR=9;BYDAY=MO,WE,FR",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalRecurrenceRule",
      "json_schema": "string",
      "sql": "VARCHAR(512)"
    }
  },
  "Temporal_Seconds": {
    "name": "Temporal_Seconds",
    "description": "Signed integer count of seconds: an amount of elapsed time, never a point in time. An epoch timestamp is Temporal.DateTime with x-temporal-format: unix.",
    "primitive": "Int",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": -9007199254740991,
    "maximum": 9007199254740991,
    "example": "60",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": true,
    "typeMappings": {
      "go": "TemporalSeconds",
      "json_schema": "integer",
      "sql": "BIGINT"
    }
  },
  "Temporal_Time": {
    "name": "Temporal_Time",
    "description": "Time of day. 24-hour 'HH:MM' or 'HH:MM:SS' (hours 00-23), or 12-hour 'H:MM'/'HH:MM' with optional ':SS' and required AM/PM suffix (hours 1-12). Seconds and the AM/PM separator space are optional.",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 0,
    "pattern": "^(?:(?:[01][0-9]|2[0-3]):[0-5][0-9](?::[0-5][0-9])?|(?:0?[1-9]|1[0-2]):[0-5][0-9](?::[0-5][0-9])?\\s?[AaPp][Mm])$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "12:25",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalTime",
      "json_schema": "string",
      "sql": "TIME"
    }
  },
  "Temporal_TimeZone": {
    "name": "Temporal_TimeZone",
    "description": "IANA timezone identifier (e.g., America/New_York, UTC, Etc/UTC)",
    "primitive": "String",
    "minLength": 0,
    "maxLength": 100,
    "pattern": "^(?:UTC|[A-Za-z]+/[A-Za-z_/]+)$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "America/New_York",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalTimeZone",
      "json_schema": "string",
      "sql": "VARCHAR(100)"
    }
  },
  "Temporal_Year": {
    "name": "Temporal_Year",
    "description": "Calendar year as a 4-digit string (e.g., 2025)",
    "primitive": "String",
    "minLength": 4,
    "maxLength": 4,
    "pattern": "^[1-9]\\d{3}$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "2025",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TemporalYear",
      "json_schema": "string",
      "sql": "VARCHAR(4)"
    }
  },
  "Text_Markdown": {
    "name": "Text_Markdown",
    "description": "Markdown text",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 0,
    "pattern": "^[\\s\\S]*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "## Hello, World!",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TextMarkdown",
      "json_schema": "string",
      "sql": "TEXT"
    }
  },
  "Text_Sql": {
    "name": "Text_Sql",
    "description": "SQL text",
    "primitive": "String",
    "minLength": 1,
    "maxLength": 0,
    "pattern": "^[\\s\\S]*$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "SELECT 1",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "TextSql",
      "json_schema": "string",
      "sql": "TEXT"
    }
  },
  "Version_SemVer": {
    "name": "Version_SemVer",
    "description": "Canonical Semantic Versioning 2.0.0 value",
    "primitive": "String",
    "minLength": 5,
    "maxLength": 255,
    "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$",
    "format": "",
    "reservedWords": [],
    "caseInsensitive": false,
    "reservedWordsCaseInsensitive": false,
    "reservedWordsMatchPartial": false,
    "minimum": null,
    "maximum": null,
    "example": "1.0.0",
    "fileUpload": null,
    "imageConstraints": null,
    "hasCustomNormalize": false,
    "hasCustomValidate": false,
    "hasCustomParse": false,
    "typeMappings": {
      "go": "VersionSemVer",
      "json_schema": "string",
      "sql": "VARCHAR(255)"
    }
  }
};
