package parity

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/parable-work/superschematic/internal/loader"
	"github.com/parable-work/superschematic/internal/testpaths"
	ir "github.com/parable-work/superschematic/ir"
)

var update = flag.Bool("update", false, "rewrite runtime/schema/testdata/validation_parity.json")

// runtimeCorpusPath is the corpus the schema runtimes' own suites read:
// runtime/schema/go/validate, runtime/schema/typescript/test and
// runtime/schema/python/tests.
const runtimeCorpusPath = "runtime/schema/testdata/validation_parity.json"

// runtimeCorpus is the matrix schema, as the loader emits its IR, and the
// vector table with its expected column. Pins and decode refusals concern
// the generated validators only: every runtime must return "want".
type runtimeCorpus struct {
	Comment string         `json:"comment"`
	Schema  *ir.Schema     `json:"schema"`
	Vectors []corpusVector `json:"vectors"`
}

type corpusVector struct {
	Name    string              `json:"name"`
	Type    string              `json:"type"`
	Payload json.RawMessage     `json:"payload"`
	Want    map[string][]string `json:"want"`
}

const corpusComment = "Generated by internal/generator/parity (go test ./internal/generator/parity -update). " +
	"Each schema runtime validates every payload as its type and must report exactly the paths and sorted validator names in want; " +
	"nested object errors are dotted paths."

// TestRuntimeParityCorpus keeps runtime/schema/testdata/validation_parity.json
// equal to the matrix schema and vector table the generated validators run.
// It fails when the committed file is stale; -update rewrites it.
func TestRuntimeParityCorpus(t *testing.T) {
	schema, err := loader.LoadService(stageParityService(t))
	if err != nil {
		t.Fatalf("load parity fixture: %v", err)
	}
	corpus := runtimeCorpus{Comment: corpusComment, Schema: schema}
	for _, v := range vectors {
		var payload bytes.Buffer
		if err := json.Compact(&payload, []byte(v.payload)); err != nil {
			t.Fatalf("vector %s: payload is not JSON: %v", v.name, err)
		}
		corpus.Vectors = append(corpus.Vectors, corpusVector{
			Name:    v.name,
			Type:    v.typ(),
			Payload: payload.Bytes(),
			Want:    v.want,
		})
	}
	data, err := json.MarshalIndent(corpus, "", "  ")
	if err != nil {
		t.Fatalf("marshal corpus: %v", err)
	}
	data = append(data, '\n')

	path := filepath.Join(testpaths.RepoRoot(t), filepath.FromSlash(runtimeCorpusPath))
	if *update {
		if err := os.WriteFile(path, data, 0o644); err != nil {
			t.Fatalf("write corpus: %v", err)
		}
		return
	}
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (run go test ./internal/generator/parity -update)", runtimeCorpusPath, err)
	}
	if !bytes.Equal(committed, data) {
		t.Fatalf("%s is stale; run go test ./internal/generator/parity -update", runtimeCorpusPath)
	}
}
