// Code generated by tsgen. DO NOT EDIT.

import type {
  JSDate,
  NetworkUrl,
} from './scalars';
import type {
  FixtureEnvironment,
} from './enums';

export interface FixtureConfig {
  DATABASE_URL: string;
  JWT_SECRET: string;
  PORT: number;
  ENVIRONMENT: FixtureEnvironment;
}

/**
 * FixtureConfigDefaults holds @default values declared in the schema. Defaults
 * are typed as Partial<FixtureConfig> so they can be merged into incoming
 * payloads or used to bootstrap a new instance.
 */
export const FixtureConfigDefaults: Partial<FixtureConfig> = {
  PORT: 8080,
  ENVIRONMENT: "development" as FixtureEnvironment,
};

/**
 * makeFixtureConfig returns a FixtureConfig initialised with @default values from
 * the schema. Caller-provided overrides win over the declared defaults.
 */
export function makeFixtureConfig(overrides?: Partial<FixtureConfig>): FixtureConfig {
  return { ...FixtureConfigDefaults, ...(overrides || {}) } as FixtureConfig;
}

/**
 * FixtureFilter - JSON-persisted filter: exercises optional-list constraint gating.
Absent/null must skip listMin; an explicit [] must fail it (decode must
not normalize an absent optional list into an empty non-nil slice).
 */
export interface FixtureFilter {
  kind: string;
  values?: string[] | null;
}

export interface RetryPolicy {
  maxAttempts: number;
  backoffSeconds?: number | null;
}

/**
 * Returns a fresh FixtureConfig platform default.
 */
export function defaultFixtureConfig(): FixtureConfig {
  return JSON.parse("{\"DATABASE_URL\":\"https://example.com\",\"ENVIRONMENT\":\"production\",\"JWT_SECRET\":\"test-secret\",\"PORT\":8080}") as FixtureConfig;
}
