// Code generated by superschematic sentinel. DO NOT EDIT.
import { service, SchemaKind } from "@superschematic/schema-config";
export const FixtureAuthdbImport = service({ name: "fixture-authdb-import", kind: SchemaKind.API });
