// Code generated by superschematic sentinel. DO NOT EDIT.
import { service, SchemaKind } from "@superschematic/schema-config";
export const BrokenIndexTable = service({ name: "broken-index-table", kind: SchemaKind.DB });
