// Code generated by tsgen. DO NOT EDIT.

import {
  newValidationErrors,
  addFieldError,
  setFieldErrors,
} from 'superscalar/validation';
import type { ScalarValidationResult, ValidationResult } from 'superscalar/validation';
import { load as loadYaml } from 'js-yaml';
import type { Auditable, JSDate } from '../../types';

import { validateTemporalDateTimeRequired, validateTemporalDateTime } from '../scalars/temporal_date_time';

import { parseTemporalDateTime as parseTemporalDateTimeFromLib } from 'superscalar/scalars';

/**
 * Validates a Auditable object
 */
export function validateAuditable(value: Auditable | null | undefined): ValidationResult {
  const errors = newValidationErrors();

  if (value === null || value === undefined) {
    return true;
  }

  {
    const [valid, fieldErrors] = validateTemporalDateTimeRequired(value.createdAt);
    if (!valid && fieldErrors) {
      setFieldErrors(errors, "createdAt", fieldErrors);
    }
  }

  if (value.updatedAt !== null && value.updatedAt !== undefined) {
    const [valid, fieldErrors] = validateTemporalDateTime(value.updatedAt);
    if (!valid && fieldErrors) {
      setFieldErrors(errors, "updatedAt", fieldErrors);
    }
  }

  return Object.keys(errors).length > 0 ? errors : true;
}

export function validateAuditableRequired(value: Auditable | null | undefined): ScalarValidationResult {
  if (value === null || value === undefined) {
    return [false, [{ validator: 'required', message: 'required field' }]];
  }

  const validationResult = validateAuditable(value);
  if (validationResult !== true) {
    return [false, [{ validator: 'object', message: JSON.stringify(validationResult) }]];
  }

  return [true, null];
}

const AuditableKnownFields = new Set<string>([
  'createdAt',
  'updatedAt',
]);

type AuditableTextParser = (value: string) => unknown;

function parseAuditableInput(
  input: string | unknown,
  strict: boolean,
  sourceFormat: 'json' | 'yaml',
  parseText: AuditableTextParser
): Auditable {
  let parsed: unknown = input;

  if (typeof input === 'string') {
    try {
      parsed = parseText(input);
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      throw new Error(`parseAuditable ${sourceFormat} parse failed: ${reason}`);
    }
  }

  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error(`parseAuditable ${sourceFormat} expects an object input`);
  }

  const candidate = parsed as Record<string, unknown>;

  // Apply @default values from the schema for keys absent from the payload.

  if (strict) {
    const unknownFields = Object.keys(candidate).filter(
      (fieldName) => !AuditableKnownFields.has(fieldName)
    );
    if (unknownFields.length > 0) {
      throw new Error(
        `parseAuditable ${sourceFormat} contains unknown fields: ${unknownFields.join(', ')}`
      );
    }
  }

  const typedCandidate = candidate as unknown as Auditable;
  const validationResult = validateAuditable(typedCandidate);
  if (validationResult !== true) {
    throw new Error(
      `parseAuditable ${sourceFormat} validation failed: ${JSON.stringify(validationResult)}`
    );
  }

  return typedCandidate;
}

export function parseAuditableJson(input: string | unknown): Auditable {
  return parseAuditableInput(input, true, 'json', (value) => JSON.parse(value) as unknown);
}

export function parseAuditableJsonNonStrict(input: string | unknown): Auditable {
  return parseAuditableInput(input, false, 'json', (value) => JSON.parse(value) as unknown);
}

export function parseAuditableYaml(input: string | unknown): Auditable {
  return parseAuditableInput(input, true, 'yaml', (value) => loadYaml(value));
}

export function parseAuditableYamlNonStrict(input: string | unknown): Auditable {
  return parseAuditableInput(input, false, 'yaml', (value) => loadYaml(value));
}

/**
 * Parses a Auditable from JSON wire format into runtime types
 */

export function parseAuditableFromJSON(input: unknown): Auditable {
  if (input == null || typeof input !== 'object') {
    return input as Auditable;
  }
  const obj = input as Record<string, unknown>;
  return {
    ...(obj as unknown as Auditable),

    createdAt: obj.createdAt != null
      ? (parseTemporalDateTimeFromLib(obj.createdAt as string) as JSDate)
      : (obj.createdAt as unknown as JSDate),

    updatedAt: obj.updatedAt != null
      ? (parseTemporalDateTimeFromLib(obj.updatedAt as string) as JSDate)
      : (obj.updatedAt as unknown as JSDate | null),

  };
}
