// Code generated by tsgen. DO NOT EDIT.

import type {
  User,
} from '../../types';

/**
 * Returns a copy of User with fields marked @secret cleared.
 */
export function maskSecretsUser(value: User): User {
  return {
    id: value.id,
    email: value.email,
    displayName: value.displayName,
    createdAt: value.createdAt,
  };
}
