// Code generated by superschematic apigen. DO NOT EDIT.
// This is a generated API module - import it into your service project.
//
// Example usage:
//
//   import api "example.com/acme/schemas/api/fixture-api"
//
//   func main() {
//       r := chi.NewRouter()
//       api.RegisterRoutes(r, api.Config{
//           DB:     db,
//           Logger: logger,
//       })
//   }

module example.com/acme/schemas/api/fixture-api

go 1.26.4

require (
	github.com/go-chi/chi/v5 v5.3.2
	github.com/google/uuid v1.6.0
	example.com/acme/schemas/orm/fixture-db v0.0.0-00010101000000-000000000000
	example.com/acme/schemas/types/go/fixture-api v0.0.0-00010101000000-000000000000
	example.com/acme/http-runtime v0.0.0-00010101000000-000000000000
	example.com/acme/scalars v1.0.0
	go.uber.org/zap v1.28.0
)

// Local module paths for development.
// When consuming this module externally, these resolve via go.work or go.sum.
replace example.com/acme/schemas/types/go/fixture-api => ../../types/go/fixture-api
replace example.com/acme/schemas/orm/fixture-db => ../../orm/fixture-db
replace example.com/acme/schemas/types/go/fixture-db => ../../types/go/fixture-db
