//! Code generated by superschematic topcoat. DO NOT EDIT.
//!
//! A form per input type an in-process call of fixture-api takes whose
//! fields a form holds (a string, a number, a boolean or an enum, each
//! alone). Its struct holds each field as the browser sends it, so a form
//! that is refused re-renders as it was sent; `parse` reads it into the
//! input by the input type's rules (D14); and its component renders the
//! fields with the attributes those rules give them. A browser checks those
//! attributes before it sends the form, and `parse` checks every rule again.

use crate::api::runtime::ApiError;
use crate::api::runtime::schema::{ParseError, UnknownFields};
use crate::api::types;
use serde::Deserialize;
use serde_json::{Map, Value};
use topcoat::view::{View, component, view};

/// Why a form was refused: each field's messages, and the form's own.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct FormErrors {
    /// Each field's messages, by the field's name in the form.
    pub fields: Vec<(String, Vec<String>)>,
    /// Messages about the form as a whole.
    pub form: Vec<String>,
}

impl FormErrors {
    pub fn is_empty(&self) -> bool {
        self.fields.is_empty() && self.form.is_empty()
    }

    /// The field's messages.
    pub fn of(&self, field: &str) -> Vec<String> {
        self.fields
            .iter()
            .filter(|(name, _)| name == field)
            .flat_map(|(_, messages)| messages.iter().cloned())
            .collect()
    }

    pub fn add(&mut self, field: &str, message: impl Into<String>) {
        match self.fields.iter_mut().find(|(name, _)| name == field) {
            Some((_, messages)) => messages.push(message.into()),
            None => self.fields.push((field.to_owned(), vec![message.into()])),
        }
    }

    /// The errors of an operation's refusal: its field errors (its `errors`
    /// member) when it has them, else its detail, so a form shows what the
    /// operation refused as it shows what `parse` refused.
    pub fn from_api(err: &ApiError) -> Self {
        let mut errors = Self::default();
        if let Some(fields) = err.errors.as_deref() {
            errors.read(fields);
        }
        if errors.is_empty() {
            errors.form.push(err.message.clone());
        }
        errors
    }

    /// Reads field errors keyed by field, each a list of
    /// `{validator, message}`.
    fn read(&mut self, fields: &Value) {
        for (field, messages) in fields.as_object().into_iter().flatten() {
            for message in messages.as_array().into_iter().flatten() {
                if let Some(text) = message.get("message").and_then(Value::as_str) {
                    self.add(field, text);
                }
            }
        }
    }
}

impl From<ParseError> for FormErrors {
    fn from(err: ParseError) -> Self {
        let mut errors = Self::default();
        if let ParseError::Invalid(fields) = &err {
            errors.read(&serde_json::to_value(fields).unwrap_or_default());
        }
        if errors.is_empty() {
            errors.form.push(err.to_string());
        }
        errors
    }
}

/// A text field: its value as sent, when the browser sent one.
fn put_string(json: &mut Map<String, Value>, key: &str, value: &Option<String>) {
    if let Some(value) = value {
        json.insert(key.to_owned(), Value::from(value.as_str()));
    }
}

/// The form of `types::CreateTenantInput`, each field as the browser sends it.
#[derive(Debug, Clone, Default, PartialEq, Deserialize)]
pub struct CreateTenantInputForm {
    #[serde(rename = "name")]
    pub name: Option<String>,
    #[serde(rename = "slug")]
    pub slug: Option<String>,
}

impl CreateTenantInputForm {
    /// The input: each field read as the input type's JSON, then parsed by
    /// the type's rules with undeclared keys refused; else each field's
    /// errors.
    pub fn parse(&self) -> Result<types::CreateTenantInput, FormErrors> {
        let mut json = Map::new();
        put_string(&mut json, "name", &self.name);
        put_string(&mut json, "slug", &self.slug);
        types::validators::parse_create_tenant_input(Value::Object(json), UnknownFields::Refuse).map_err(FormErrors::from)
    }
}

/// The fields of `CreateTenantInputForm`: each with its label, its value as sent, the
/// attributes the input type's rules give it and its errors.
#[component]
pub async fn create_tenant_input_fields(#[default] form: CreateTenantInputForm, #[default] errors: FormErrors) -> topcoat::Result<impl View> {
    let form_errors = errors.form.clone();
    let name_errors = errors.of("name");
    let name_invalid = (!name_errors.is_empty()).then_some("true");
    let slug_errors = errors.of("slug");
    let slug_invalid = (!slug_errors.is_empty()).then_some("true");
    Ok(view! {
        for message in form_errors {
            <p class="form-error">(message)</p>
        }
        <div class="field">
            <label for="create-tenant-input-name">"Name"</label>
            <input id="create-tenant-input-name" name="name" type="text" required=(true) minlength="2" maxlength="80" value=(form.name.clone()) aria-invalid=(name_invalid)>
            for message in name_errors {
                <p class="field-error">(message)</p>
            }
        </div>
        <div class="field">
            <label for="create-tenant-input-slug">"Slug"</label>
            <input id="create-tenant-input-slug" name="slug" type="text" required=(true) minlength="1" maxlength="255" value=(form.slug.clone()) aria-invalid=(slug_invalid)>
            for message in slug_errors {
                <p class="field-error">(message)</p>
            }
        </div>
    })
}
