//! Code generated by superschematic topcoat. DO NOT EDIT.
//!
//! Components that render each record of fixture-api as HTML:
//! `<type>_detail(record)` as a description list, a `<dt>` label and a
//! `<dd>` value per field, and `<type>_table(rows)` as a table, a column per
//! field (the type's `@display` summaryFields when it declares them) and a
//! row per record. A field is labeled as a form labels it: its `@docs`
//! title, else its name in words. The type's `@display` titleField names a
//! detail (`aria-label`) and heads its row, and its plural captions a table.
//!
//! An enum's value shows its member's name in words, a date or a time is a
//! `<time>`, a boolean "Yes" or "No", a nested record its own detail (in a
//! table, its title when its type declares one), a list of records a table,
//! any other list a `<ul>`, a map a `<dl>` of its entries, and a union or
//! any JSON value its JSON text in a `<pre>`. An absent optional value
//! leaves its `<dd>` or `<td>` empty. Every value is text the view escapes.
//! The markup has `ss-` classes and `data-field` attributes, the field's
//! JSON key, for a stylesheet or a test, and no style of its own.

use crate::records::{CreateTenantInputRecord, TenantViewRecord};
use topcoat::view::{View, component, view};

/// `CreateTenantInputRecord` as a description list: each field's label and value.
#[component]
pub async fn create_tenant_input_detail(record: CreateTenantInputRecord) -> topcoat::Result<impl View> {
    Ok(view! {
        <div class="ss-detail" data-type="CreateTenantInput" role="group">
            <dl>
                <div data-field="name">
                    <dt>"Name"</dt>
                    <dd>(record.name)</dd>
                </div>
                <div data-field="slug">
                    <dt>"Slug"</dt>
                    <dd>(record.slug)</dd>
                </div>
            </dl>
        </div>
    })
}

/// `CreateTenantInputRecord`s as a table: a column per field and a row per record.
#[component]
pub async fn create_tenant_input_table(rows: Vec<CreateTenantInputRecord>) -> topcoat::Result<impl View> {
    Ok(view! {
        <table class="ss-table" data-type="CreateTenantInput">
            <thead>
                <tr>
                    <th scope="col" data-field="name">"Name"</th>
                    <th scope="col" data-field="slug">"Slug"</th>
                </tr>
            </thead>
            <tbody>
                for row in rows {
                    <tr>
                        <td data-field="name">(row.name)</td>
                        <td data-field="slug">(row.slug)</td>
                    </tr>
                }
            </tbody>
        </table>
    })
}

/// `TenantViewRecord` as a description list: each field's label and value.
#[component]
pub async fn tenant_view_detail(record: TenantViewRecord) -> topcoat::Result<impl View> {
    Ok(view! {
        <div class="ss-detail" data-type="TenantView" role="group">
            <dl>
                <div data-field="id">
                    <dt>"Id"</dt>
                    <dd>(record.id)</dd>
                </div>
                <div data-field="name">
                    <dt>"Name"</dt>
                    <dd>(record.name)</dd>
                </div>
                <div data-field="userCount">
                    <dt>"User count"</dt>
                    <dd>(record.user_count)</dd>
                </div>
            </dl>
        </div>
    })
}

/// `TenantViewRecord`s as a table: a column per field and a row per record.
#[component]
pub async fn tenant_view_table(rows: Vec<TenantViewRecord>) -> topcoat::Result<impl View> {
    Ok(view! {
        <table class="ss-table" data-type="TenantView">
            <thead>
                <tr>
                    <th scope="col" data-field="id">"Id"</th>
                    <th scope="col" data-field="name">"Name"</th>
                    <th scope="col" data-field="userCount">"User count"</th>
                </tr>
            </thead>
            <tbody>
                for row in rows {
                    <tr>
                        <td data-field="id">(row.id)</td>
                        <td data-field="name">(row.name)</td>
                        <td data-field="userCount">(row.user_count)</td>
                    </tr>
                }
            </tbody>
        </table>
    })
}
