[package]
name = "parable-fixture-db-types"
version = "0.1.0"
edition = "2021"
rust-version = "1.95.0"
description = "Generated Rust types for fixture-db schema"
license = "UNLICENSED"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
parable-scalars-core = "0.1.0"
serde_json = { version = "1.0" }
