// Code generated by tsgen. DO NOT EDIT.

import type {
  JSDate,
  GenericInt64,
  GenericJSON,
  IdentityUUID,
  TemporalDateTime,
} from './scalars';
import type {
  RecipeEntityKind,
  RecipePatchOperation,
} from './enums';

export interface HistoryRecord<T> {
  version: number;
  operation: string;
  recordedAt: JSDate;
  value: T;
}

/**
 * Cover - The recipe's cover photo: at most one per ref.
 */
export interface Cover {
  id?: string | null;
  recipe: Recipe;
  photoUrl: string;
  /** The entity's logical identity, shared by its rows on every ref. */
  entityKey?: string | null;
  /** The ref this row overrides the entity on. */
  ref: RecipeRef;
  /** True when the row deletes the entity on its ref. */
  deletedOnRef: boolean;
  _version: number;
}

/**
 * CoverDefaults holds @default values declared in the schema. Defaults
 * are typed as Partial<Cover> so they can be merged into incoming
 * payloads or used to bootstrap a new instance.
 */
export const CoverDefaults: Partial<Cover> = {
  deletedOnRef: false,
};

/**
 * makeCover returns a Cover initialised with @default values from
 * the schema. Caller-provided overrides win over the declared defaults.
 */
export function makeCover(overrides?: Partial<Cover>): Cover {
  return { ...CoverDefaults, ...(overrides || {}) } as Cover;
}

/**
 * Ingredient - An ingredient one step uses.
 */
export interface Ingredient {
  id?: string | null;
  recipe: Recipe;
  stepKey: string;
  quantity: string;
  substitutes: GenericJSON;
  /** The entity's logical identity, shared by its rows on every ref. */
  entityKey?: string | null;
  /** The ref this row overrides the entity on. */
  ref: RecipeRef;
  /** True when the row deletes the entity on its ref. */
  deletedOnRef: boolean;
  _version: number;
}

/**
 * IngredientDefaults holds @default values declared in the schema. Defaults
 * are typed as Partial<Ingredient> so they can be merged into incoming
 * payloads or used to bootstrap a new instance.
 */
export const IngredientDefaults: Partial<Ingredient> = {
  deletedOnRef: false,
};

/**
 * makeIngredient returns a Ingredient initialised with @default values from
 * the schema. Caller-provided overrides win over the declared defaults.
 */
export function makeIngredient(overrides?: Partial<Ingredient>): Ingredient {
  return { ...IngredientDefaults, ...(overrides || {}) } as Ingredient;
}

/**
 * Note - A cook's note, threaded under another note.
 */
export interface Note {
  id?: string | null;
  recipe: Recipe;
  replyTo?: string | null;
  body: string;
  /** The entity's logical identity, shared by its rows on every ref. */
  entityKey?: string | null;
  /** The ref this row overrides the entity on. */
  ref: RecipeRef;
  /** True when the row deletes the entity on its ref. */
  deletedOnRef: boolean;
  _version: number;
}

/**
 * NoteDefaults holds @default values declared in the schema. Defaults
 * are typed as Partial<Note> so they can be merged into incoming
 * payloads or used to bootstrap a new instance.
 */
export const NoteDefaults: Partial<Note> = {
  deletedOnRef: false,
};

/**
 * makeNote returns a Note initialised with @default values from
 * the schema. Caller-provided overrides win over the declared defaults.
 */
export function makeNote(overrides?: Partial<Note>): Note {
  return { ...NoteDefaults, ...(overrides || {}) } as Note;
}

/**
 * Recipe - A recipe: the stable identity its steps and ingredients are versioned under.
 */
export interface Recipe {
  id?: string | null;
  title: string;
  createdAt: JSDate;
  createdBy: string;
}

/**
 * RecipeCommit - A commit of the Recipe version graph: the exact row versions one ref sealed.
 */
export interface RecipeCommit {
  id?: string | null;
  root: Recipe;
  ref: RecipeRef;
  parentCommit?: RecipeCommit | null;
  message?: string | null;
  schemaEpoch: number;
  contentHash: string;
  sequence?: number | null;
  createdAt: JSDate;
  createdBy: string;
}

/**
 * RecipePatch - One entity a commit of the Recipe version graph changed, pinned to the row version it sealed.
 */
export interface RecipePatch {
  id?: string | null;
  commit: RecipeCommit;
  entityKind: RecipeEntityKind;
  entityKey: string;
  entityId: string;
  entityVersion: number;
  operation: RecipePatchOperation;
}

/**
 * RecipeRef - A line of the Recipe version graph: a primary line when parentRef is null, else a change set.
 */
export interface RecipeRef {
  id?: string | null;
  root: Recipe;
  parentRef?: RecipeRef | null;
  baseCommit?: RecipeCommit | null;
  headCommit?: RecipeCommit | null;
  name: string;
  sealedAt?: JSDate | null;
  createdAt: JSDate;
  createdBy: string;
  updatedAt: JSDate;
  updatedBy: string;
  deletedAt?: JSDate | null;
  deletedBy?: string | null;
  _version: number;
}

/**
 * Step - One step of a recipe, ordered by position; updatedBy names its row's writer.
 */
export interface Step {
  id?: string | null;
  recipe: Recipe;
  position: number;
  instruction: string;
  timings: GenericJSON;
  scratch?: string | null;
  createdAt: JSDate;
  createdBy: string;
  updatedAt: JSDate;
  updatedBy: string;
  /** The entity's logical identity, shared by its rows on every ref. */
  entityKey?: string | null;
  /** The ref this row overrides the entity on. */
  ref: RecipeRef;
  /** True when the row deletes the entity on its ref. */
  deletedOnRef: boolean;
  _version: number;
}

/**
 * StepDefaults holds @default values declared in the schema. Defaults
 * are typed as Partial<Step> so they can be merged into incoming
 * payloads or used to bootstrap a new instance.
 */
export const StepDefaults: Partial<Step> = {
  deletedOnRef: false,
};

/**
 * makeStep returns a Step initialised with @default values from
 * the schema. Caller-provided overrides win over the declared defaults.
 */
export function makeStep(overrides?: Partial<Step>): Step {
  return { ...StepDefaults, ...(overrides || {}) } as Step;
}
