// Code generated by superschematic. DO NOT EDIT.

// Command users-api-purge-sessions is job PurgeSessions of users-api, in stack users-stack
// (docs/stack-model.md, section 8.7). superschematic writes it on every build
// of the stack.
//
// It reads its whole configuration from the environment, as the API's server
// does: the API's @envVars settings and the fields its edges derive, one
// variable per member (section 3.4). It builds the API's Deps as the server
// does, calls the implementation's NewJobs, and runs the job's method once,
// with a context that SIGTERM or SIGINT cancels. It logs the run's end and,
// when the job fails, exits 1, so the platform records the run as failed and
// runs it again if the job's retries allow.
//
// The API's implementation is the package at the naming file's
// [implementation_paths] go template (section 8.5): example.com/schemas/implementation/users-api
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/parable-work/superschematic/runtime/http/go/stackconfig"
	"go.uber.org/zap"

	usersapi "example.com/schemas/api/users-api"
	usersapiimpl "example.com/schemas/implementation/users-api"
	usersdborm "example.com/schemas/orm/users-db"
)

func main() {
	logger, err := zap.NewProduction()
	if err != nil {
		fmt.Fprintf(os.Stderr, "users-api-purge-sessions: build the logger: %v\n", err)
		os.Exit(1)
	}
	logger = logger.With(zap.String("stack", "users-stack"), zap.String("job", "users-api-purge-sessions"))
	started := time.Now()
	err = run(logger)
	if err != nil {
		logger.Error("job failed", zap.Duration("took", time.Since(started)), zap.Error(err))
	} else {
		logger.Info("job done", zap.Duration("took", time.Since(started)))
	}
	_ = logger.Sync()
	if err != nil {
		os.Exit(1)
	}
}

// run builds the job from the environment and runs it once, until its
// method returns or SIGTERM or SIGINT cancels its context.
func run(logger *zap.Logger) error {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT)
	defer stop()

	usersApiConfig, err := usersapi.LoadEnvConfig()
	if err != nil {
		return fmt.Errorf("configuration of users-api: %w", err)
	}

	// One pool per database, shared by every API on it. A pool connects when
	// it is first used, so the job starts while its database is not up yet.
	usersDbPool, err := connect(ctx, "USERS_DB_DATABASE", usersApiConfig.UsersDbDatabase)
	if err != nil {
		return fmt.Errorf("database users-db: %w", err)
	}
	defer usersDbPool.Close()
	usersDb, err := usersdborm.ConnectWithPool(usersDbPool)
	if err != nil {
		return fmt.Errorf("database users-db: %w", err)
	}

	// users-api: its jobs, built from its Deps.
	usersApiLogger := logger.With(zap.String("api", "users-api"))
	usersApiDeps := usersapi.Deps{
		Config: *usersApiConfig,
		DB:     usersDb,
		Logger: usersApiLogger,
	}
	jobs, err := usersapiimpl.NewJobs(usersApiDeps)
	if err != nil {
		return fmt.Errorf("jobs of users-api: %w", err)
	}
	logger.Info("job started", zap.String("api", "users-api"), zap.String("class", "PurgeSessions"))
	return jobs.PurgeSessions(ctx)
}

// connect builds the pool of the database field named field, which the
// environment sets as field_URL, a connection string. The pool connects
// when it is first used. No environment places a database of the job
// on Cloud SQL, so it does not link the Cloud SQL connector, and a Cloud
// SQL connector configuration is refused.
func connect(ctx context.Context, field string, db stackconfig.Database) (*pgxpool.Pool, error) {
	if db.CloudSQL != nil {
		return nil, fmt.Errorf("%s is a Cloud SQL connector configuration, which job users-api-purge-sessions does not link: no environment of stack users-stack placed its databases on Cloud SQL when it was built; set %s_URL, or build the stack again", field, field)
	}
	pool, err := pgxpool.New(ctx, db.URL)
	if err != nil {
		return nil, fmt.Errorf("%s_URL: %w", field, err)
	}
	return pool, nil
}
