//! Code generated by superschematic rustrestgen. DO NOT EDIT.

/// The service's OpenAPI document as the build wrote it (`openapi.json`),
/// with placeholders for its version and server URL. `build_router_with`
/// serves it at `GET /api/openapi.json` with the values of its
/// `RouterOptions`.
pub const OPENAPI_JSON: &str = include_str!("../openapi.json");
