-- Generated by superschematic from src/app-preference.projection.schema.ts (AppPreference). DO NOT EDIT.
-- Regenerate with: superschematic build <service-dir>
SET lock_timeout = '5s';
SET statement_timeout = '5min';

DROP VIEW IF EXISTS app.preferences;
