//! Code generated by superschematic rustrestgen. DO NOT EDIT.

#![allow(unused_imports)]

use crate::types;
use async_trait::async_trait;
use superschematic_http_runtime::{ApiError, RequestContext};
use std::collections::HashMap;
use std::sync::Arc;

/// The arguments of pool-search.rebuildIndex (`POST /api/pool-search/indexes`),
/// decoded and checked by the router. `check` makes the same checks on
/// arguments a caller builds.
#[derive(Debug, Clone)]
pub struct PoolSearchRebuildIndexArgs {
    /// The request body.
    pub input: types::RebuildPoolSearchIndexInput,
}

/// The arguments of pool-search.getIndex (`GET /api/pool-search/indexes/{id}`),
/// decoded and checked by the router. `check` makes the same checks on
/// arguments a caller builds.
#[derive(Debug, Clone)]
pub struct PoolSearchGetIndexArgs {
    /// The `id` path parameter.
    pub id: types::IdentityUUID,
}

#[async_trait]
pub trait PoolSearchImplementation: Send + Sync + 'static {
    async fn rebuild_index(&self, ctx: RequestContext, args: PoolSearchRebuildIndexArgs) -> Result<types::PoolSearchIndex, ApiError>;
    async fn get_index(&self, ctx: RequestContext, args: PoolSearchGetIndexArgs) -> Result<types::PoolSearchIndex, ApiError>;
}

#[derive(Clone)]
pub struct Implementations {
    pub pool_search: Arc<dyn PoolSearchImplementation>,
}
