// Code generated by rustgen. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::scalars::*;
use crate::enums::*;

/// HistoryRecord wraps one captured historical value and its version metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HistoryRecord<T> {
    pub version: i64,
    pub operation: String,
    #[serde(rename = "recordedAt")]
    pub recorded_at: superscalar::DateTime,
    pub value: T,
}

fn default_cover_deleted_on_ref() -> bool {
    false
}

/// The recipe's cover photo: at most one per ref.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Cover {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe: Option<Recipe>,
    #[serde(rename = "photoUrl")]
    pub photo_url: String,
    /// The entity's logical identity, shared by its rows on every ref.
    #[serde(default, rename = "entityKey", skip_serializing_if = "Option::is_none")]
    pub entity_key: Option<IdentityUUID>,
    /// The ref this row overrides the entity on.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<RecipeRef>,
    /// True when the row deletes the entity on its ref.
    #[serde(default = "default_cover_deleted_on_ref", rename = "deletedOnRef")]
    pub deleted_on_ref: bool,
    #[serde(default, rename = "_version")]
    pub version: i64,
}

impl Default for Cover {
    fn default() -> Self {
        Self {
            id: None,
            recipe: None,
            photo_url: Default::default(),
            entity_key: None,
            r#ref: None,
            deleted_on_ref: default_cover_deleted_on_ref(),
            version: Default::default(),
        }
    }
}

fn default_ingredient_deleted_on_ref() -> bool {
    false
}

/// An ingredient one step uses.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Ingredient {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe: Option<Recipe>,
    #[serde(rename = "stepKey")]
    pub step_key: IdentityUUID,
    pub quantity: String,
    #[serde(deserialize_with = "superscalar::scalars::json_scalar::serde::deserialize")]
    pub substitutes: GenericJSON,
    /// The entity's logical identity, shared by its rows on every ref.
    #[serde(default, rename = "entityKey", skip_serializing_if = "Option::is_none")]
    pub entity_key: Option<IdentityUUID>,
    /// The ref this row overrides the entity on.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<RecipeRef>,
    /// True when the row deletes the entity on its ref.
    #[serde(default = "default_ingredient_deleted_on_ref", rename = "deletedOnRef")]
    pub deleted_on_ref: bool,
    #[serde(default, rename = "_version")]
    pub version: i64,
}

fn default_note_deleted_on_ref() -> bool {
    false
}

/// A cook's note, threaded under another note.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Note {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe: Option<Recipe>,
    #[serde(default, rename = "replyTo", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<IdentityUUID>,
    pub body: String,
    /// The entity's logical identity, shared by its rows on every ref.
    #[serde(default, rename = "entityKey", skip_serializing_if = "Option::is_none")]
    pub entity_key: Option<IdentityUUID>,
    /// The ref this row overrides the entity on.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<RecipeRef>,
    /// True when the row deletes the entity on its ref.
    #[serde(default = "default_note_deleted_on_ref", rename = "deletedOnRef")]
    pub deleted_on_ref: bool,
    #[serde(default, rename = "_version")]
    pub version: i64,
}

impl Default for Note {
    fn default() -> Self {
        Self {
            id: None,
            recipe: None,
            reply_to: None,
            body: Default::default(),
            entity_key: None,
            r#ref: None,
            deleted_on_ref: default_note_deleted_on_ref(),
            version: Default::default(),
        }
    }
}

/// A recipe: the stable identity its steps and ingredients are versioned under.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Recipe {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    pub title: String,
    #[serde(rename = "createdAt")]
    pub created_at: TemporalDateTime,
    #[serde(rename = "createdBy")]
    pub created_by: IdentityUUID,
}

/// A commit of the Recipe version graph: the exact row versions one ref sealed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecipeCommit {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root: Option<Recipe>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<Box<RecipeRef>>,
    #[serde(default, rename = "parentCommit", skip_serializing_if = "Option::is_none")]
    pub parent_commit: Option<Box<RecipeCommit>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "schemaEpoch")]
    pub schema_epoch: GenericInt64,
    #[serde(rename = "contentHash")]
    pub content_hash: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sequence: Option<GenericInt64>,
    #[serde(rename = "createdAt")]
    pub created_at: TemporalDateTime,
    #[serde(rename = "createdBy")]
    pub created_by: IdentityUUID,
}

/// One entity a commit of the Recipe version graph changed, pinned to the row version it sealed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecipePatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit: Option<RecipeCommit>,
    #[serde(rename = "entityKind")]
    pub entity_kind: RecipeEntityKind,
    #[serde(rename = "entityKey")]
    pub entity_key: IdentityUUID,
    #[serde(rename = "entityId")]
    pub entity_id: IdentityUUID,
    #[serde(rename = "entityVersion")]
    pub entity_version: GenericInt64,
    pub operation: RecipePatchOperation,
}

/// A line of the Recipe version graph: a primary line when parentRef is null, else a change set.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecipeRef {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root: Option<Recipe>,
    #[serde(default, rename = "parentRef", skip_serializing_if = "Option::is_none")]
    pub parent_ref: Option<Box<RecipeRef>>,
    #[serde(default, rename = "baseCommit", skip_serializing_if = "Option::is_none")]
    pub base_commit: Option<Box<RecipeCommit>>,
    #[serde(default, rename = "headCommit", skip_serializing_if = "Option::is_none")]
    pub head_commit: Option<Box<RecipeCommit>>,
    pub name: String,
    #[serde(default, rename = "sealedAt", skip_serializing_if = "Option::is_none")]
    pub sealed_at: Option<TemporalDateTime>,
    #[serde(rename = "createdAt")]
    pub created_at: TemporalDateTime,
    #[serde(rename = "createdBy")]
    pub created_by: IdentityUUID,
    #[serde(rename = "updatedAt")]
    pub updated_at: TemporalDateTime,
    #[serde(rename = "updatedBy")]
    pub updated_by: IdentityUUID,
    #[serde(default, rename = "deletedAt", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<TemporalDateTime>,
    #[serde(default, rename = "deletedBy", skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<IdentityUUID>,
    #[serde(default, rename = "_version")]
    pub version: i64,
}

fn default_step_deleted_on_ref() -> bool {
    false
}

/// One step of a recipe, ordered by position; updatedBy names its row's writer.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Step {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<IdentityUUID>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe: Option<Recipe>,
    pub position: GenericInt64,
    pub instruction: String,
    #[serde(deserialize_with = "superscalar::scalars::json_scalar::serde::deserialize")]
    pub timings: GenericJSON,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scratch: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: TemporalDateTime,
    #[serde(rename = "createdBy")]
    pub created_by: IdentityUUID,
    #[serde(rename = "updatedAt")]
    pub updated_at: TemporalDateTime,
    #[serde(rename = "updatedBy")]
    pub updated_by: IdentityUUID,
    /// The entity's logical identity, shared by its rows on every ref.
    #[serde(default, rename = "entityKey", skip_serializing_if = "Option::is_none")]
    pub entity_key: Option<IdentityUUID>,
    /// The ref this row overrides the entity on.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<RecipeRef>,
    /// True when the row deletes the entity on its ref.
    #[serde(default = "default_step_deleted_on_ref", rename = "deletedOnRef")]
    pub deleted_on_ref: bool,
    #[serde(default, rename = "_version")]
    pub version: i64,
}

fn default_utensil_deleted_on_ref() -> bool {
    false
}

/// A utensil the recipe needs, keyed by a plain UUID rather than an
/// AutoGenerate one.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Utensil {
    pub id: IdentityUUID,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe: Option<Recipe>,
    pub name: String,
    /// The entity's logical identity, shared by its rows on every ref.
    #[serde(default, rename = "entityKey", skip_serializing_if = "Option::is_none")]
    pub entity_key: Option<IdentityUUID>,
    /// The ref this row overrides the entity on.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<RecipeRef>,
    /// True when the row deletes the entity on its ref.
    #[serde(default = "default_utensil_deleted_on_ref", rename = "deletedOnRef")]
    pub deleted_on_ref: bool,
    #[serde(default, rename = "_version")]
    pub version: i64,
}
